import "server-only";
import { defaultLocale, isLocale, type Locale } from "../../i18n/config";

type Copy = {
  welcomeSubject: string; welcomeHeading: string; welcomeBody: string; welcomeCta: string;
  verifySubject: string; verifyHeading: string; verifyBody: string; verifyCta: string;
  resetSubject: string; resetHeading: string; resetBody: string; resetCta: string;
  hello: string; fallback: string; security: string; support: string; transactional: string; copyright: string;
};

const copy: Record<Locale, Copy> = {
  en: { welcomeSubject:"Welcome to Todijo — your account is ready",welcomeHeading:"Welcome to Todijo",welcomeBody:"Your account is ready. Discover independent shops and products selected for you.",welcomeCta:"Explore Todijo",verifySubject:"Verify your Todijo email",verifyHeading:"Verify your email",verifyBody:"Confirm this email address to complete your Todijo account verification. This link expires in 24 hours.",verifyCta:"Verify email",resetSubject:"Reset your Todijo password",resetHeading:"Reset your password",resetBody:"We received a request to reset your password. This link expires in one hour.",resetCta:"Reset password",hello:"Hello {name},",fallback:"If the button does not work, copy this URL into your browser:",security:"If you did not request this email, you can safely ignore it. Never share this link.",support:"Need help? Contact",transactional:"This transactional message was sent by Todijo.",copyright:"© 2026 Todijo. All rights reserved." },
  fr: { welcomeSubject:"Bienvenue sur Todijo — votre compte est prêt",welcomeHeading:"Bienvenue sur Todijo",welcomeBody:"Votre compte est prêt. Découvrez des boutiques indépendantes et des produits sélectionnés pour vous.",welcomeCta:"Découvrir Todijo",verifySubject:"Vérifiez votre e-mail Todijo",verifyHeading:"Vérifiez votre e-mail",verifyBody:"Confirmez cette adresse e-mail pour finaliser la vérification de votre compte Todijo. Ce lien expire dans 24 heures.",verifyCta:"Vérifier l’e-mail",resetSubject:"Réinitialisez votre mot de passe Todijo",resetHeading:"Réinitialisez votre mot de passe",resetBody:"Nous avons reçu une demande de réinitialisation de votre mot de passe. Ce lien expire dans une heure.",resetCta:"Réinitialiser le mot de passe",hello:"Bonjour {name},",fallback:"Si le bouton ne fonctionne pas, copiez cette URL dans votre navigateur :",security:"Si vous n’êtes pas à l’origine de cet e-mail, ignorez-le. Ne partagez jamais ce lien.",support:"Besoin d’aide ? Contactez",transactional:"Ce message transactionnel a été envoyé par Todijo.",copyright:"© 2026 Todijo. Tous droits réservés." },
  ar: { welcomeSubject:"مرحبًا بك في Todijo — حسابك جاهز",welcomeHeading:"مرحبًا بك في Todijo",welcomeBody:"حسابك جاهز. اكتشف المتاجر المستقلة والمنتجات المختارة لك.",welcomeCta:"استكشف Todijo",verifySubject:"تحقق من بريد Todijo الإلكتروني",verifyHeading:"تحقق من بريدك الإلكتروني",verifyBody:"أكد عنوان البريد الإلكتروني لإكمال التحقق من حساب Todijo. تنتهي صلاحية الرابط خلال 24 ساعة.",verifyCta:"تحقق من البريد",resetSubject:"إعادة تعيين كلمة مرور Todijo",resetHeading:"إعادة تعيين كلمة المرور",resetBody:"تلقينا طلبًا لإعادة تعيين كلمة المرور. تنتهي صلاحية الرابط خلال ساعة.",resetCta:"إعادة تعيين كلمة المرور",hello:"مرحبًا {name}،",fallback:"إذا لم يعمل الزر، انسخ هذا الرابط إلى المتصفح:",security:"إذا لم تطلب هذه الرسالة، يمكنك تجاهلها. لا تشارك هذا الرابط.",support:"هل تحتاج إلى مساعدة؟ تواصل مع",transactional:"أُرسلت هذه الرسالة الخاصة بالمعاملة من Todijo.",copyright:"© 2026 Todijo. جميع الحقوق محفوظة." },
  ku: { welcomeSubject:"بەخێربێیت بۆ Todijo — هەژمارەکەت ئامادەیە",welcomeHeading:"بەخێربێیت بۆ Todijo",welcomeBody:"هەژمارەکەت ئامادەیە. فرۆشگا سەربەخۆکان و بەرهەمە هەڵبژێردراوەکان بدۆزەوە.",welcomeCta:"گەڕان لە Todijo",verifySubject:"ئیمەیڵی Todijo پشتڕاست بکەرەوە",verifyHeading:"ئیمەیڵەکەت پشتڕاست بکەرەوە",verifyBody:"ئەم ئیمەیڵە پشتڕاست بکەرەوە بۆ تەواوکردنی هەژمارەکەت. لینکەکە دوای ٢٤ کاتژمێر بەسەر دەچێت.",verifyCta:"پشتڕاستکردنەوەی ئیمەیڵ",resetSubject:"وشەی نهێنی Todijo نوێ بکەرەوە",resetHeading:"وشەی نهێنی نوێ بکەرەوە",resetBody:"داواکارییەکمان بۆ نوێکردنەوەی وشەی نهێنی وەرگرت. لینکەکە دوای یەک کاتژمێر بەسەر دەچێت.",resetCta:"نوێکردنەوەی وشەی نهێنی",hello:"سڵاو {name}،",fallback:"ئەگەر دوگمەکە کار نەکرد، ئەم لینکە کۆپی بکە:",security:"ئەگەر تۆ ئەم داواکارییەت نەکردووە، نامەکە پشتگوێ بخە. لینکەکە هاوبەش مەکە.",support:"پێویستت بە یارمەتییە؟ پەیوەندی بکە بە",transactional:"ئەم نامەیە لەلایەن Todijo نێردراوە.",copyright:"© 2026 Todijo. هەموو مافەکان پارێزراون." },
  de: { welcomeSubject:"Willkommen bei Todijo — Ihr Konto ist bereit",welcomeHeading:"Willkommen bei Todijo",welcomeBody:"Ihr Konto ist bereit. Entdecken Sie unabhängige Shops und ausgewählte Produkte.",welcomeCta:"Todijo entdecken",verifySubject:"Todijo-E-Mail bestätigen",verifyHeading:"E-Mail bestätigen",verifyBody:"Bestätigen Sie diese E-Mail-Adresse. Der Link läuft nach 24 Stunden ab.",verifyCta:"E-Mail bestätigen",resetSubject:"Todijo-Passwort zurücksetzen",resetHeading:"Passwort zurücksetzen",resetBody:"Wir haben eine Anfrage zum Zurücksetzen Ihres Passworts erhalten. Der Link läuft nach einer Stunde ab.",resetCta:"Passwort zurücksetzen",hello:"Hallo {name},",fallback:"Falls die Schaltfläche nicht funktioniert, kopieren Sie diese URL:",security:"Wenn Sie diese E-Mail nicht angefordert haben, ignorieren Sie sie. Teilen Sie diesen Link niemals.",support:"Benötigen Sie Hilfe? Kontaktieren Sie",transactional:"Diese Transaktionsnachricht wurde von Todijo gesendet.",copyright:"© 2026 Todijo. Alle Rechte vorbehalten." },
  es: { welcomeSubject:"Te damos la bienvenida a Todijo — tu cuenta está lista",welcomeHeading:"Bienvenido a Todijo",welcomeBody:"Tu cuenta está lista. Descubre tiendas independientes y productos seleccionados.",welcomeCta:"Explorar Todijo",verifySubject:"Verifica tu correo de Todijo",verifyHeading:"Verifica tu correo",verifyBody:"Confirma este correo para completar la verificación. El enlace caduca en 24 horas.",verifyCta:"Verificar correo",resetSubject:"Restablece tu contraseña de Todijo",resetHeading:"Restablece tu contraseña",resetBody:"Recibimos una solicitud para restablecer tu contraseña. El enlace caduca en una hora.",resetCta:"Restablecer contraseña",hello:"Hola {name},",fallback:"Si el botón no funciona, copia esta URL:",security:"Si no solicitaste este correo, puedes ignorarlo. No compartas este enlace.",support:"¿Necesitas ayuda? Contacta con",transactional:"Todijo envió este mensaje transaccional.",copyright:"© 2026 Todijo. Todos los derechos reservados." },
  it: { welcomeSubject:"Benvenuto su Todijo — il tuo account è pronto",welcomeHeading:"Benvenuto su Todijo",welcomeBody:"Il tuo account è pronto. Scopri negozi indipendenti e prodotti selezionati.",welcomeCta:"Esplora Todijo",verifySubject:"Verifica l’e-mail Todijo",verifyHeading:"Verifica la tua e-mail",verifyBody:"Conferma questo indirizzo per completare la verifica. Il link scade tra 24 ore.",verifyCta:"Verifica e-mail",resetSubject:"Reimposta la password Todijo",resetHeading:"Reimposta la password",resetBody:"Abbiamo ricevuto una richiesta di reimpostazione. Il link scade tra un’ora.",resetCta:"Reimposta password",hello:"Ciao {name},",fallback:"Se il pulsante non funziona, copia questo URL:",security:"Se non hai richiesto questa e-mail, ignorala. Non condividere il link.",support:"Hai bisogno di aiuto? Contatta",transactional:"Questo messaggio transazionale è stato inviato da Todijo.",copyright:"© 2026 Todijo. Tutti i diritti riservati." },
  nl: { welcomeSubject:"Welkom bij Todijo — je account is klaar",welcomeHeading:"Welkom bij Todijo",welcomeBody:"Je account is klaar. Ontdek onafhankelijke winkels en geselecteerde producten.",welcomeCta:"Ontdek Todijo",verifySubject:"Verifieer je Todijo-e-mail",verifyHeading:"Verifieer je e-mail",verifyBody:"Bevestig dit e-mailadres om de verificatie te voltooien. De link verloopt over 24 uur.",verifyCta:"E-mail verifiëren",resetSubject:"Stel je Todijo-wachtwoord opnieuw in",resetHeading:"Wachtwoord opnieuw instellen",resetBody:"We ontvingen een verzoek om je wachtwoord opnieuw in te stellen. De link verloopt over één uur.",resetCta:"Wachtwoord instellen",hello:"Hallo {name},",fallback:"Werkt de knop niet, kopieer dan deze URL:",security:"Heb je dit niet aangevraagd, negeer deze e-mail. Deel deze link nooit.",support:"Hulp nodig? Neem contact op met",transactional:"Dit transactionele bericht is verzonden door Todijo.",copyright:"© 2026 Todijo. Alle rechten voorbehouden." },
  tr: { welcomeSubject:"Todijo’ya hoş geldiniz — hesabınız hazır",welcomeHeading:"Todijo’ya hoş geldiniz",welcomeBody:"Hesabınız hazır. Bağımsız mağazaları ve seçilmiş ürünleri keşfedin.",welcomeCta:"Todijo’yu keşfet",verifySubject:"Todijo e-postanızı doğrulayın",verifyHeading:"E-postanızı doğrulayın",verifyBody:"Hesap doğrulamasını tamamlamak için adresi onaylayın. Bağlantı 24 saat içinde sona erer.",verifyCta:"E-postayı doğrula",resetSubject:"Todijo şifrenizi sıfırlayın",resetHeading:"Şifrenizi sıfırlayın",resetBody:"Şifre sıfırlama isteği aldık. Bağlantı bir saat içinde sona erer.",resetCta:"Şifreyi sıfırla",hello:"Merhaba {name},",fallback:"Düğme çalışmazsa bu URL’yi tarayıcınıza kopyalayın:",security:"Bu e-postayı istemediyseniz yok sayabilirsiniz. Bağlantıyı paylaşmayın.",support:"Yardıma mı ihtiyacınız var? İletişime geçin:",transactional:"Bu işlem mesajı Todijo tarafından gönderildi.",copyright:"© 2026 Todijo. Tüm hakları saklıdır." },
};

export function emailCopy(locale: string) {
  const localized = copy[isLocale(locale) ? locale : defaultLocale];
  return { ...localized, copyright: localized.copyright.replace("2026", String(new Date().getUTCFullYear())) };
}

export function emailGreeting(locale: string, name: string) {
  return emailCopy(locale).hello.replace("{name}", name);
}
