import {Prisma} from "@prisma/client";
import {NextResponse} from "next/server";
import {prisma} from "@/lib/prisma";
import {resolveBuyerCurrency,supportedBuyerCurrency} from "@/lib/currency";
import {cartLineKey} from "@/lib/cart-line";
import {embeddedShippingQuote} from "@/lib/payments";
import {cartShippingQuote,effectiveShippingRule,quoteShippingRule,ShippingError} from "@/lib/shipping";
import {resolveDropshippingEligibility,resolveDropshippingPricing,type DropshippingPriceSnapshot} from "@/lib/suppliers/commerce-pricing";
import {readSession} from "@/lib/session";
import {defaultBuyerAddress} from "@/lib/buyer-addresses";
import {convertMarketplacePrice} from "@/lib/marketplace-presentment";

export async function POST(request:Request){
 const session=await readSession();if(!session)return NextResponse.json({code:"AUTH_REQUIRED"},{status:401});
 const address=await defaultBuyerAddress(prisma,session.userId);if(!address)return NextResponse.json({code:"ADDRESS_REQUIRED"},{status:409});
 const body=await request.json().catch(()=>({})) as {items?:Array<{productId?:unknown;variantId?:unknown;quantity?:unknown}>;destinationCountry?:unknown;destinationPostalCode?:unknown;buyerCurrency?:unknown};
 body.destinationCountry=address.country;body.destinationPostalCode=address.postalCode;
 const requested=(Array.isArray(body.items)?body.items:[]).slice(0,100).map(item=>({productId:String(item.productId??""),variantId:typeof item.variantId==="string"?item.variantId:null,quantity:Number(item.quantity)})).filter(item=>item.productId&&Number.isInteger(item.quantity)&&item.quantity>0&&item.quantity<=1000);
 const productIds=[...new Set(requested.map(item=>item.productId))];if(!productIds.length)return NextResponse.json({code:"INVALID_CART"},{status:400});
 const products=await prisma.product.findMany({where:{id:{in:productIds},status:"PUBLISHED"},select:{id:true,storeId:true,price:true,currency:true,shippingOverrideEnabled:true,shippingEnabled:true,shippingMethodName:true,shippingPrice:true,shippingFree:true,shippingFreeThreshold:true,shippingMinDays:true,shippingMaxDays:true,shippingCountries:true,shippingWorldwide:true,shippingPostalCodes:true,shippingCarrier:true,shippingProvider:true,shippingExternalServiceId:true,variants:{select:{id:true,active:true,priceOverride:true}},supplierLink:{select:{provider:true,ownerType:true,sourceMetadata:true,connection:{select:{status:true,store:{select:{dropshippingEnabled:true}}}}}},store:{select:{currency:true,shippingEnabled:true,shippingMethodName:true,shippingPrice:true,shippingFree:true,shippingFreeThreshold:true,shippingMinDays:true,shippingMaxDays:true,shippingCountries:true,shippingWorldwide:true,shippingPostalCodes:true,shippingCarrier:true,shippingProvider:true,shippingExternalServiceId:true}}}});
 if(products.length!==productIds.length)return NextResponse.json({code:"INVALID_CART"},{status:409});
 try{
  const classified=requested.map(item=>{const product=products.find(candidate=>candidate.id===item.productId)!,link=product.supplierLink,eligibility=resolveDropshippingEligibility({hasSupplierLink:Boolean(link),provider:link?.provider,ownerType:link?.ownerType,connectionStatus:link?.connection?.status,sellerDropshippingEnabled:link?.connection?.store?.dropshippingEnabled,sourceMetadata:link?.sourceMetadata});return{...item,product,eligibility};});
  const currency=supportedBuyerCurrency(resolveBuyerCurrency({explicitPreference:body.buyerCurrency,shippingCountry:body.destinationCountry}));if(!currency)throw new ShippingError("SHIPPING_NOT_CONFIGURED");
  const lines:Array<{lineKey:string;product:typeof products[number];subtotal:Prisma.Decimal;sourceSubtotal:Prisma.Decimal;pricingSnapshot:DropshippingPriceSnapshot|null;unitPrice:string;currency:string;freeShipping:boolean;deliveryMinDays:number|null;deliveryMaxDays:number|null}>=[],blocked:Array<{lineKey:string;productId:string;code:string;allowedCountries:string[]}>=[];
  for(const line of classified){const variant=line.variantId?line.product.variants.find(candidate=>candidate.id===line.variantId&&candidate.active):null,lineKey=cartLineKey(line.product.id,null,null,variant?.id??line.variantId);if(line.product.variants.length&&!variant){blocked.push({lineKey,productId:line.product.id,code:"SHIPPING_NOT_CONFIGURED",allowedCountries:[]});continue;}if(line.eligibility.eligible){try{if(!variant)throw new ShippingError("SHIPPING_NOT_CONFIGURED");const resolved=await resolveDropshippingPricing(prisma,{productId:line.product.id,variantId:variant.id,quantity:line.quantity,destinationCountry:body.destinationCountry,buyerCurrency:currency});if(!resolved.buyer||!resolved.snapshot)throw new ShippingError("SHIPPING_NOT_CONFIGURED");const subtotal=new Prisma.Decimal(resolved.buyer.buyerLineTotal);lines.push({lineKey,product:line.product,subtotal,sourceSubtotal:subtotal,pricingSnapshot:resolved.snapshot,unitPrice:resolved.buyer.buyerUnitPrice,currency,freeShipping:resolved.buyer.freeShipping,deliveryMinDays:resolved.buyer.deliveryMinDays,deliveryMaxDays:resolved.buyer.deliveryMaxDays});}catch{blocked.push({lineKey,productId:line.product.id,code:"SHIPPING_NOT_CONFIGURED",allowedCountries:[]});}}else{const unit=variant?.priceOverride??line.product.price,rule=effectiveShippingRule(line.product.store,line.product);try{quoteShippingRule(rule,body.destinationCountry,body.destinationPostalCode,unit.mul(line.quantity));const presentment=await convertMarketplacePrice(unit,line.product.currency,currency),subtotal=new Prisma.Decimal(presentment.buyerAmount).mul(line.quantity);lines.push({lineKey,product:line.product,subtotal,sourceSubtotal:unit.mul(line.quantity),pricingSnapshot:null,unitPrice:presentment.buyerAmount,currency,freeShipping:false,deliveryMinDays:null,deliveryMaxDays:null});}catch(error){blocked.push({lineKey,productId:line.product.id,code:error instanceof ShippingError?error.message:"SHIPPING_NOT_CONFIGURED",allowedCountries:rule.shippingWorldwide?[]:rule.shippingCountries});}}}
  if(blocked.length)return NextResponse.json({code:"SHIPPING_LINES_UNAVAILABLE",lines:[...lines.map(({lineKey,unitPrice,currency,freeShipping,deliveryMinDays,deliveryMaxDays})=>({lineKey,available:true,unitPrice,currency,freeShipping,deliveryMinDays,deliveryMaxDays})),...blocked.map(line=>({...line,available:false}))]},{status:409});
  const buckets=new Map<string,typeof lines>();for(const line of lines){const key=line.pricingSnapshot?.shippingIncluded?"cj:platform":`store:${line.product.storeId}`;buckets.set(key,[...(buckets.get(key)??[]),line])}const quotes=[] as Array<ReturnType<typeof embeddedShippingQuote>|ReturnType<typeof cartShippingQuote>>;for(const [key,group] of buckets){if(key==="cj:platform"){quotes.push(embeddedShippingQuote(group,currency,body.destinationCountry));continue;}const source=cartShippingQuote(group[0].product.store,group.map(line=>({product:line.product,subtotal:line.sourceSubtotal})),body.destinationCountry,body.destinationPostalCode),presentment=await convertMarketplacePrice(source.amount,group[0].product.currency,currency);quotes.push({...source,amount:new Prisma.Decimal(presentment.buyerAmount),currency});}const quote={method:quotes.length===1?quotes[0].method:"Grouped delivery",amount:quotes.reduce((sum,value)=>sum.add(value.amount),new Prisma.Decimal(0)),free:quotes.every(value=>value.free),estimatedMinDays:Math.min(...quotes.map(value=>value.estimatedMinDays)),estimatedMaxDays:Math.max(...quotes.map(value=>value.estimatedMaxDays)),carrier:null};
  return NextResponse.json({method:quote.method,amount:quote.amount.toString(),currency,free:quote.free,estimatedMinDays:quote.estimatedMinDays,estimatedMaxDays:quote.estimatedMaxDays,carrier:quote.carrier,lines:lines.map(({lineKey,unitPrice,currency,freeShipping,deliveryMinDays,deliveryMaxDays})=>({lineKey,unitPrice,currency,freeShipping,deliveryMinDays,deliveryMaxDays}))});
 }catch(error){const code=error instanceof ShippingError?error.message:"SHIPPING_NOT_CONFIGURED";return NextResponse.json({code},{status:409});}
}
