import {NextResponse} from "next/server";
import {revalidatePath} from "next/cache";
import {prisma} from "@/lib/prisma";
import {readSession} from "@/lib/session";
import {AdminAccessError,requireAdmin} from "@/lib/admin-access";
import {assertAdminMutationRequest,MutationOriginError} from "@/lib/request-security";
import {NewsInputError,newsInput,newsTranslationInput} from "@/lib/news";
import {locales} from "@/i18n/config";

function failure(error:unknown){if(error instanceof AdminAccessError||error instanceof NewsInputError)return NextResponse.json({error:error instanceof NewsInputError?error.code:error.code},{status:error.status});if(error instanceof MutationOriginError)return NextResponse.json({error:error.message},{status:403});return NextResponse.json({error:"NEWS_WRITE_FAILED"},{status:500});}
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){try{assertAdminMutationRequest(request);const admin=await requireAdmin(prisma,await readSession()),{id}=await params,body=await request.json().catch(()=>({})) as Record<string,unknown>,value=newsInput(body),translation=newsTranslationInput(body),current=await prisma.newsArticle.findUnique({where:{id},select:{publishedAt:true}});if(!current)return NextResponse.json({error:"NEWS_NOT_FOUND"},{status:404});if(translation?.locale===value.locale)throw new NewsInputError("TRANSLATION_MATCHES_SOURCE");const published=body.published===true,article=await prisma.newsArticle.update({where:{id},data:{...value,published,publishedAt:published?(current.publishedAt??new Date()):null,editorAdminId:admin.id,translations:translation?{upsert:{where:{articleId_locale:{articleId:id,locale:translation.locale}},create:translation,update:{title:translation.title,content:translation.content,automatic:false,sourceFingerprint:null,provider:null,providerVersion:null}}}:undefined},include:{translations:true}});for(const item of locales)revalidatePath(`/${item}/actualites`);return NextResponse.json({article});}catch(error){return failure(error)}}
export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){try{assertAdminMutationRequest(request);await requireAdmin(prisma,await readSession());const{id}=await params;await prisma.newsArticle.delete({where:{id}});for(const item of locales)revalidatePath(`/${item}/actualites`);return NextResponse.json({ok:true});}catch(error){return failure(error)}}
