import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import test from "node:test";
const source=(path:string)=>readFileSync(path,"utf8");

test("seller Account and messages reuse the shared seller shell",()=>{const account=source("app/account/page.tsx"),messages=source("app/messages/page.tsx"),thread=source("app/messages/[id]/page.tsx");assert.match(account,/SellerDashboardLayout/);assert.match(account,/active="account"/);assert.match(messages,/SellerRouteShell/);assert.match(thread,/SellerRouteShell/)});
test("shared seller navigation contains every operational and account destination",()=>{const layout=source("components/SellerDashboardLayout.tsx"),dashboard=source("app/dashboard/page.tsx");for(const destination of["/dashboard","/seller/products","/seller/products/new","/seller/orders","/messages","#analytics","/seller/reviews","/seller/store-settings","/account","/info/privacy-data"])assert.match(layout,new RegExp(destination.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(dashboard,/common\("account"\)/);assert.match(dashboard,/privacy\("privacyData"\)/)});
test("expanded sidebar scrolls independently while logout remains outside navigation",()=>{const ui=source("components/DashboardUI.tsx"),css=source("app/globals.css");assert.ok(ui.indexOf("premiumSidebarDetails")<ui.indexOf('<form action="/api/auth/logout"'));assert.match(css,/\.premiumSidebarDetails nav\{[^}]*overflow-y:auto/);assert.match(css,/\.premiumDashboardSidebar>form\{flex:0 0 auto/);assert.match(css,/overflow-x:hidden/)});
test("customer Account keeps marketplace shell and receives no seller-only shell",()=>{const page=source("app/account/page.tsx");assert.match(page,/if\(user\.role==="SELLER"\)/);assert.match(page,/SiteHeader/);assert.match(page,/MarketplaceFooter/)});
test("French Account and onboarding copy has no known English leakage",()=>{const fr=JSON.parse(source("messages/auth/fr.json"));for(const value of[fr.accountSettings,fr.accountSettingsIntro,fr.saved,fr.profile,fr.security,fr.linkedProviders,fr.notLinked,fr.changePassword,fr.currentPassword,fr.continueWith.google,fr.continueWith.apple,fr.continueWith.facebook])assert.doesNotMatch(value,/Account settings|Manage your|Changes saved|Profile|Security|Linked sign-in|Continue with|Not linked|Change password|Current password/)});
test("password reset security and missing OAuth configuration remain unchanged",()=>{const reset=source("lib/auth-tokens.ts"),social=source("components/SocialLoginButtons.tsx"),config=source("lib/social-auth.ts");assert.match(reset,/usedAt: null, expiresAt: \{ gt: now \}/);assert.match(reset,/authVersion: \{ increment: 1 \}/);assert.match(social,/disabled title=\{t\("providerNotConfigured"\)\}/);for(const name of["GOOGLE_CLIENT_ID","GOOGLE_CLIENT_SECRET","APPLE_CLIENT_ID","APPLE_CLIENT_SECRET","FACEBOOK_APP_ID","FACEBOOK_APP_SECRET"])assert.match(config,new RegExp(name))});
test("email runbook documents authentication alignment without secrets",()=>{const runbook=source("docs/email-deliverability-production-runbook.md"),transport=source("lib/email/transport.ts"),config=source("lib/email/config.ts");for(const term of["SPF","DKIM","DMARC","alignment","https://todijo.com","SMTP_FROM","SMTP_REPLY_TO"])assert.match(runbook,new RegExp(term,"i"));assert.match(transport,/from, replyTo/);assert.match(config,/production[\s\S]*https:/);assert.doesNotMatch(runbook,/SMTP_PASS\s*=|-----BEGIN [A-Z ]*PRIVATE KEY-----|client_secret\s*=/i)});
