import test from"node:test";
import assert from"node:assert/strict";
import fs from"node:fs";
import path from"node:path";
const source=(file:string)=>fs.readFileSync(path.join(process.cwd(),file),"utf8");
test("hard deletion is guarded by protected financial and audit history",()=>{const lib=source("lib/admin-user-deletion.ts");for(const marker of["STRIPE_CONNECTED_ACCOUNT","BUYER_ORDERS","SELLER_ORDER_HISTORY","ADMIN_AUDIT_HISTORY","SUPPLIER_AUDIT_HISTORY","ADMIN_ACCOUNT"])assert.match(lib,new RegExp(marker));assert.match(lib,/confirmation!=="DELETE"/);assert.match(lib,/db\.user\.delete/)});
test("individual admin deletion previews before destructive request",()=>{const component=source("components/AdminUserActions.tsx"),route=source("app/api/admin/users/[userId]/route.ts");assert.match(component,/method:"DELETE"/);assert.match(component,/hardDeleteSafe/);assert.match(component,/productCount/);assert.match(route,/adminUserDeletionPreview/);assert.match(route,/hardDeleteUserAsAdmin/)});
test("bulk test cleanup is explicit and protects administrators",()=>{const route=source("app/api/admin/users/test-cleanup/route.ts"),ui=source("components/AdminTestAccountCleanup.tsx"),page=source("app/adm-barewbar-182203/test-accounts/page.tsx");assert.match(route,/SELF_ACTION_FORBIDDEN/);assert.match(route,/preview\.role==="ADMIN"/);assert.match(route,/ANONYMIZE/);assert.match(route,/DELETED/);assert.match(ui,/selected accounts are test accounts|comptes sélectionnés sont des comptes de test/);assert.match(page,/role:\{not:"ADMIN"\}/);assert.match(page,/deactivatedAt:null/)});
test("test cleanup never guesses test accounts automatically",()=>{const page=source("app/adm-barewbar-182203/test-accounts/page.tsx"),ui=source("components/AdminTestAccountCleanup.tsx");assert.match(page,/findMany\(\{where:\{id:\{not:session\.userId\},role:\{not:"ADMIN"\},deactivatedAt:null\}/);assert.doesNotMatch(page,/where:[\s\S]*(?:email|firstName|lastName):\{(?:contains|startsWith|endsWith):"?test/i);assert.match(ui,/type="checkbox"/);assert.match(ui,/window\.confirm/)});
