import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {join} from "node:path";
import test from "node:test";
import {checkoutExpirationCandidates,expireCheckoutOrder,processExpiredCheckouts} from "../lib/checkout-expiration";
import {adminOrderWhere} from "../lib/admin-marketplace";

const source=(...parts:string[])=>readFileSync(join(process.cwd(),...parts),"utf8"),now=new Date("2026-08-28T12:00:00Z");
function order(overrides:any={}){return{id:"order",status:"PENDING",paidAt:null,stripePaymentIntentId:null,stripeCheckoutSessionId:"cs_test_old",checkoutExpiresAt:new Date("2026-08-28T10:00:00Z"),checkoutExpiredAt:null,createdAt:new Date("2026-08-27T00:00:00Z"),shippedAt:null,deliveredAt:null,...overrides}}
function db(row:any){const events:any[]=[],updates:any[]=[],value:any={order:{findUnique:async()=>row,updateMany:async({where,data}:any)=>{updates.push({where,data});if(row.status!=="PENDING"||row.paidAt||row.stripePaymentIntentId||row.checkoutExpiredAt)return{count:0};Object.assign(row,data);return{count:1}},findMany:async()=>[{id:row.id}]},orderLifecycleEvent:{create:async({data}:any)=>{events.push(data);return data}}};value.$transaction=async(fn:(tx:any)=>unknown)=>fn(value);return{events,updates,db:value}}
const stripe=(status:"open"|"complete"|"expired",payment_status="unpaid")=>async(id:string)=>({id,status,payment_status,payment_intent:null,client_reference_id:"order"});

test("old unpaid expired Stripe checkout is cancelled and audited",async()=>{const row=order(),value=db(row),result=await expireCheckoutOrder(value.db,row.id,now,stripe("expired"));assert.equal(result.outcome,"EXPIRED");assert.equal(row.status,"CANCELLED");assert.equal(row.checkoutExpiredAt,now);assert.equal(value.events[0].type,"CHECKOUT_EXPIRED")});
test("paid, payment-intent, shipped, delivered, and refunded commerce is never downgraded",async()=>{for(const protectedRow of [order({status:"PAID",paidAt:new Date()}),order({stripePaymentIntentId:"pi_paid"}),order({status:"SHIPPED",shippedAt:new Date()}),order({status:"DELIVERED",deliveredAt:new Date()}),order({status:"REFUNDED",paidAt:new Date()})]){const value=db(protectedRow);assert.equal((await expireCheckoutOrder(value.db,"order",now,stripe("expired"))).outcome,"PROTECTED");assert.equal(value.updates.length,0)}});
test("Stripe open, complete, or paid evidence fails closed without local expiry",async()=>{for(const retrieve of [stripe("open"),stripe("complete"),stripe("expired","paid")]){const value=db(order());assert.notEqual((await expireCheckoutOrder(value.db,"order",now,retrieve)).outcome,"EXPIRED");assert.equal(value.updates.length,0)}});
test("expiration is idempotent",async()=>{const value=db(order({status:"CANCELLED",checkoutExpiredAt:new Date()}));assert.equal((await expireCheckoutOrder(value.db,"order",now,stripe("expired"))).outcome,"ALREADY_EXPIRED");assert.equal(value.events.length,0)});
test("bounded runner keeps Stripe failures retryable",async()=>{const value=db(order());const result=await processExpiredCheckouts(value.db,now,async()=>{throw new Error("unavailable")});assert.deepEqual(result,{processed:1,expired:0,results:[{orderId:"order",outcome:"RETRY_LATER"}]})});
test("candidate and admin filters separate paid pending abandoned and refund workflows",()=>{const candidate:any=checkoutExpirationCandidates(now);assert.equal(candidate.status,"PENDING");assert.equal(candidate.paidAt,null);assert.equal(candidate.stripePaymentIntentId,null);const active:any=adminOrderWhere("","active"),refund:any=adminOrderWhere("","refund"),pending:any=adminOrderWhere("","pending"),abandoned:any=adminOrderWhere("","abandoned");assert.ok(active.AND[0].OR);assert.deepEqual(refund.AND[0].refundRequest.is.status.in,["SELLER_APPROVED","SELLER_REJECTED"]);assert.equal(pending.AND[0].status,"PENDING");assert.equal(abandoned.AND[0].status,"CANCELLED");assert.deepEqual(abandoned.AND[0].checkoutExpiredAt,{not:null})});
test("admin notification and operational UI are correctly separated",()=>{const dashboard=source("app/adm-barewbar-182203/page.tsx"),page=source("app/adm-barewbar-182203/orders/page.tsx"),labels=source("i18n/admin-order-filters.ts");assert.match(dashboard,/status:\s*\{\s*in:\s*\["SELLER_APPROVED",\s*"SELLER_REJECTED"\]/);assert.match(dashboard,/orders\?view=refund/);assert.match(page,/adminOrderViews\.map/);assert.match(page,/paid&&order\.supplierFulfillments/);assert.match(labels,/Non payée/);assert.match(labels,/Unpaid/)});
test("cart remains client-only while checkout initiation creates the pending order",()=>{const cart=source("components/CartProvider.tsx"),payments=source("lib/payments.ts");assert.match(cart,/localStorage/);assert.doesNotMatch(cart,/prisma|order\.create/);assert.match(payments,/order = await db\.order\.create/);assert.match(payments,/checkoutExpiresAt/)});
test("Stripe expired webhook and existing financial runner classify abandonment",()=>{const payments=source("lib/payments.ts"),runner=source("app/api/internal/refund-financials/route.ts");assert.match(payments,/checkout\.session\.expired/);assert.match(payments,/paidAt:null,stripePaymentIntentId:null/);assert.match(runner,/processExpiredCheckouts/);assert.match(runner,/REFUND_FINANCIAL_CRON_SECRET/)});
test("money, Stripe mode, transfer, refund, and CJ paid fulfillment invariants are untouched",()=>{const payments=source("lib/payments.ts"),stripeSource=source("lib/stripe.ts"),runner=source("lib/checkout-expiration.ts");assert.match(payments,/unitAmountMinor/);assert.match(stripeSource,/assertStripeCheckoutSessionMode/);assert.doesNotMatch(runner,/SellerTransfer|RefundOperation|SupplierFulfillment|unitAmount|stripeMode/)});
