import test from "node:test";import assert from "node:assert/strict";import{readFileSync}from"node:fs";import{DESKTOP_CATEGORY_TAXONOMY,assertValidDesktopTaxonomy,categorySearchHref}from"../lib/desktop-category-taxonomy";
const labels=["Vêtements pour femmes","Fournitures pour animaux de compagnie","Maison et Jardin, Meubles","Santé et Beauté Cheveux","Bijoux & Montres","Vêtements pour hommes","Sac et Chaussures","Jouets, Enfants et Bébé","Sports et Plein air","Électronique grand public","Amélioration de l'habitat","Automobiles et Motos","Téléphones et Accessoires","Ordinateur et Bureau"];
test("desktop taxonomy has exact deterministic fourteen-category order",()=>{assert.equal(DESKTOP_CATEGORY_TAXONOMY.length,14);assert.deepEqual(DESKTOP_CATEGORY_TAXONOMY.map(category=>category.label),labels);assert.equal(assertValidDesktopTaxonomy(),true)});
test("documented hierarchy and locale-safe live search routes",()=>{assert.equal(DESKTOP_CATEGORY_TAXONOMY[0].groups.find(group=>group.label==="Pantalon")?.items.includes("Leggings"),true);assert.equal(categorySearchHref("fr","Robes de cocktail"),"/fr/search?category=Robes%20de%20cocktail");for(const category of DESKTOP_CATEGORY_TAXONOMY){assert.ok(category.id&&category.slug&&!category.id.startsWith("CJ"));for(const group of category.groups)assert.ok(group.items.length>0)}});
test("duplicate ids and slugs fail closed",()=>assert.throws(()=>assertValidDesktopTaxonomy([...DESKTOP_CATEGORY_TAXONOMY,{...DESKTOP_CATEGORY_TAXONOMY[0]}])));
test("desktop menu preserves actions and accessible interaction",()=>{const header=readFileSync("components/MarketplaceHeader.tsx","utf8");for(const token of ["marketTopSearch","LanguageSwitcher","marketFavoritesAction","marketAccountAction","CartLink","marketSellLink"])assert.match(header,new RegExp(token));assert.match(header,/aria-expanded=\{categoriesOpen\}/);assert.match(header,/event\.key === "Escape"/);assert.match(header,/onFocus=\{\(\) => setActiveCategory/);assert.match(header,/DESKTOP_CATEGORY_TAXONOMY/);assert.doesNotMatch(header,/supplierCategoryId|categoryIdCJ/)});
test("men and bags-shoes contain the approved complete taxonomy",()=>{const men=DESKTOP_CATEGORY_TAXONOMY.find(category=>category.id==="men")!;const bags=DESKTOP_CATEGORY_TAXONOMY.find(category=>category.id==="bags-shoes")!;assert.equal(men.groups.length,6);assert.equal(men.groups.reduce((count,group)=>count+group.items.length,0),41);assert.deepEqual(men.groups.map(group=>group.label),["Accessories","Pantalon","Sous-vêtements et Vêtements de détente","T-shirts","Vêtements d'extérieur et Vestes","Chapeaux et Casquettes"]);assert.ok(men.groups.some(group=>group.items.includes("Sweats à capuche et Sweat-shirts pour hommes")));assert.equal(bags.groups.length,4);assert.equal(bags.groups.reduce((count,group)=>count+group.items.length,0),30);assert.deepEqual(bags.groups.map(group=>group.label),["Chaussures de femme","Chaussures pour hommes","Bagages et sacs pour hommes","Bagages et Sacs pour Femmes"]);assert.ok(bags.groups.some(group=>group.items.includes("Sacs à dos à la mode")))});
test("all populated desktop categories render reachable groups without fallback",()=>{assert.equal(DESKTOP_CATEGORY_TAXONOMY.every(category=>category.groups.length>0),true);const header=readFileSync("components/MarketplaceHeader.tsx","utf8");assert.match(header,/category\.groups\.length\?/);assert.match(header,/className="marketCategoryDetail"/);assert.match(header,/className="marketCategoryColumns"/);const css=readFileSync("app/globals.css","utf8");assert.match(css,/\.marketCategoryDetail\{[^}]*overflow:auto[^}]*background:#fff/);assert.match(css,/\.marketCategoryColumns\{[^}]*columns:3 220px/)});
test("subcategory links use readable transparent defaults and accessible subtle interaction",()=>{const css=readFileSync("app/globals.css","utf8");assert.match(css,/\.marketCategoryDetail \.marketCategoryColumns a\{[^}]*background:transparent!important[^}]*color:#314b43!important/);assert.match(css,/\.marketCategoryDetail \.marketCategoryColumns a:hover,\.marketCategoryDetail \.marketCategoryColumns a:focus-visible\{[^}]*background:#edf8f4!important[^}]*color:#075f43!important[^}]*outline:2px solid #83cdb3/);assert.doesNotMatch(css,/\.marketCategoryDetail \.marketCategoryColumns a\{[^}]*background:#0[0-9a-f]{5}/i)});
