import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { DESKTOP_CATEGORY_TAXONOMY, assertValidDesktopTaxonomy, categoryFilterValues, categorySearchHref, subcategoryId, subcategoryImagePath } from "../lib/desktop-category-taxonomy";

const labels=["Vêtements pour femmes","Fournitures pour animaux de compagnie","Maison et Jardin, Meubles","Santé et Beauté Cheveux","Bijoux & Montres","Vêtements pour hommes","Sac et Chaussures","Jouets, Enfants et Bébé","Sports et Plein air","Électronique grand public","Amélioration de l'habitat","Automobiles et Motos","Téléphones et Accessoires","Ordinateur et Bureau"];

test("desktop taxonomy has exact deterministic fourteen-category order",()=>{assert.equal(DESKTOP_CATEGORY_TAXONOMY.length,14);assert.deepEqual(DESKTOP_CATEGORY_TAXONOMY.map(category=>category.label),labels);assert.equal(assertValidDesktopTaxonomy(),true)});
test("documented hierarchy and locale-safe live search routes",()=>{assert.equal(DESKTOP_CATEGORY_TAXONOMY[0].groups.find(group=>group.label==="Pantalon")?.items.includes("Leggings"),true);assert.equal(categorySearchHref("fr","Robes de cocktail"),"/fr/search?category=Robes%20de%20cocktail");for(const category of DESKTOP_CATEGORY_TAXONOMY){assert.ok(category.id&&category.slug&&!category.id.startsWith("CJ"));for(const group of category.groups)assert.ok(group.items.length>0)}});
test("duplicate ids and slugs fail closed",()=>assert.throws(()=>assertValidDesktopTaxonomy([...DESKTOP_CATEGORY_TAXONOMY,{...DESKTOP_CATEGORY_TAXONOMY[0]}])));
test("shared header keeps wide search and shared category navigation",()=>{const header=readFileSync("components/MarketplaceHeader.tsx","utf8");for(const token of ["marketTopSearch","LanguageSwitcher","marketHeaderIconAction","marketAccountAction","CartLink","MarketplaceCategoryNavigation"])assert.match(header,new RegExp(token));assert.doesNotMatch(header,/supplierCategoryId|categoryIdCJ/)});
test("click and keyboard category navigation expose real taxonomy descendants",()=>{const menu=readFileSync("components/MarketplaceCategoryNavigation.tsx","utf8");for(const token of ["DESKTOP_CATEGORY_TAXONOMY","marketQuickCategory","marketQuickMegaMenu","marketQuickMegaSidebar","marketQuickMegaColumns","onClick","aria-expanded","aria-controls","ChevronDown"])assert.match(menu,new RegExp(token));assert.doesNotMatch(menu,/onMouseEnter|onMouseLeave/);assert.match(menu,/event\.key === "Escape"/);assert.match(menu,/active\.groups\.map/);assert.match(menu,/group\.items\.map/);assert.doesNotMatch(menu,/supplierCategoryId|categoryIdCJ/)});
test("men and bags-shoes contain the approved complete taxonomy",()=>{const men=DESKTOP_CATEGORY_TAXONOMY.find(category=>category.id==="men")!;const bags=DESKTOP_CATEGORY_TAXONOMY.find(category=>category.id==="bags-shoes")!;assert.equal(men.groups.length,6);assert.equal(men.groups.reduce((count,group)=>count+group.items.length,0),41);assert.ok(men.groups.some(group=>group.items.includes("Sweats à capuche et Sweat-shirts pour hommes")));assert.equal(bags.groups.length,4);assert.equal(bags.groups.reduce((count,group)=>count+group.items.length,0),30);assert.ok(bags.groups.some(group=>group.items.includes("Sacs à dos à la mode")))});
test("all populated desktop categories render without manufactured fallback",()=>{assert.equal(DESKTOP_CATEGORY_TAXONOMY.every(category=>category.groups.length>0),true);const menu=readFileSync("components/MarketplaceCategoryNavigation.tsx","utf8");assert.match(menu,/marketQuickMegaContent/);assert.match(menu,/marketQuickMegaColumns/);const css=readFileSync("app/globals.css","utf8");assert.match(css,/\.marketQuickMegaMenu\{/);assert.match(css,/\.marketQuickMegaColumns\{/)});
test("category scroller resets before paint when hover target changes",()=>{const menu=readFileSync("components/MarketplaceCategoryNavigation.tsx","utf8");assert.match(menu,/useLayoutEffect/);assert.match(menu,/contentRef\.current\?\.scrollTo/);assert.match(menu,/\[activeCategory\]/)});
test("view-all remains locale-safe and includes every descendant category value",()=>{for(const category of DESKTOP_CATEGORY_TAXONOMY){assert.equal(categorySearchHref("fr",category.label),`/fr/search?category=${encodeURIComponent(category.label)}`);const values=categoryFilterValues(category.label);assert.ok(values.includes(category.label));for(const group of category.groups){assert.ok(values.includes(group.label));for(const item of group.items)assert.ok(values.includes(item))}}const page=readFileSync("app/page.tsx","utf8");assert.match(page,/category: \{ in: categoryFilterValues\(category\) \}/)});
test("every leaf subcategory has a unique contextual thumbnail",()=>{const ids:string[]=[];const paths:string[]=[];for(const category of DESKTOP_CATEGORY_TAXONOMY)for(const group of category.groups)for(const item of group.items){ids.push(subcategoryId(category.id,group.id,item));const imagePath=subcategoryImagePath(category.id,group.id,item);paths.push(imagePath);assert.equal(existsSync(`public${imagePath}`),true,`Missing thumbnail for ${category.id}/${group.id}/${item}`)}assert.equal(ids.length,447);assert.equal(new Set(ids).size,447);assert.equal(new Set(paths).size,447)});
