import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {dynamicContentTargets} from "../lib/dynamic-content-translations";
import {resolveBuyerProductContent} from "../lib/product-content";
import {resolveNewsContent} from "../lib/news-localization";

test("every supported source locale queues exactly the other thirteen locales",()=>{for(const source of ["fr","en","ar","ku","tr","de","es","it","nl","zh","fa","hi","pt","ru"]){const targets=dynamicContentTargets(source);assert.equal(targets.length,13);assert.ok(!targets.includes(source as never));for(const required of ["en","ar","ku"].filter(item=>item!==source))assert.ok(targets.includes(required as never));}});

test("product display falls back current locale then English then canonical source",()=>{const base={name:"Titre source",description:"Description source",sourceLocale:"fr",sourceMetadata:undefined};const translations=[{locale:"en",title:"English title",description:"English description",automatic:true},{locale:"ar",title:"عنوان عربي",description:"وصف عربي",automatic:true}];assert.equal(resolveBuyerProductContent({...base,locale:"ar",translations}).title,"عنوان عربي");assert.equal(resolveBuyerProductContent({...base,locale:"fr",translations}).title,"Titre source");assert.equal(resolveBuyerProductContent({...base,locale:"ku",translations}).title,"English title");assert.equal(resolveBuyerProductContent({...base,locale:"ku",translations:[]}).title,"Titre source");});

test("manual product translation wins and Actualités uses the same fallback order",()=>{const product=resolveBuyerProductContent({name:"Source",description:"Source description",sourceLocale:"fr",locale:"ar",translations:[{locale:"ar",title:"Automatic",description:"Automatic",automatic:true},{locale:"ar",title:"Manual",description:"Manual",automatic:false}]});assert.equal(product.title,"Manual");const article={locale:"fr",title:"Titre",content:"Contenu",translations:[{locale:"en",title:"News",content:"English"},{locale:"ar",title:"خبر",content:"عربي"}]};assert.equal(resolveNewsContent(article,"ar").title,"خبر");assert.equal(resolveNewsContent(article,"ku").title,"News");assert.equal(resolveNewsContent({...article,translations:[]},"ku").title,"Titre");});

test("queue remains bounded, background-only, retry-safe, and manual records are protected",()=>{const worker=readFileSync("lib/dynamic-content-translations.ts","utf8"),route=readFileSync("app/api/internal/catalog-translations/route.ts","utf8"),schema=readFileSync("prisma/schema.prisma","utf8"),migration=readFileSync("prisma/migrations/20260907190000_add_dynamic_content_translation/migration.sql","utf8");assert.match(worker,/runBoundedTranslationWork/);assert.match(worker,/config\.perRunItems/);assert.match(worker,/config\.perRunCharacters/);assert.match(worker,/config\.concurrency/);assert.match(worker,/maxAttempts/);assert.match(worker,/STALE_TRANSLATION_CLAIM_RECOVERED/);assert.match(worker,/SKIPPED_MANUAL/);assert.match(route,/hasValidBearerSecret/);assert.doesNotMatch(route,/export async function GET/);assert.match(schema,/automatic\s+Boolean\s+@default\(false\)/);assert.doesNotMatch(migration,/\b(?:DROP|TRUNCATE|DELETE FROM)\b/i);});
