import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {dynamicContentTargets,dynamicTranslationFailure,dynamicTranslationFieldsMatchTarget,fairDynamicTranslationTasks,reconcileInvalidAutomaticNewsTranslations,recordDynamicTranslationFailure,translateDynamicContentFields} from "../lib/dynamic-content-translations";
import {resolveBuyerProductContent} from "../lib/product-content";
import {resolveNewsContent} from "../lib/news-localization";
import {createSelfHostedTranslationProvider} from "../lib/self-hosted-translation";

test("automatic dynamic translations target only the five priority locales",()=>{for(const source of ["fr","en","ar","ku","tr","de","es","it","nl","zh","fa","hi","pt","ru"]){const targets=dynamicContentTargets(source);assert.deepEqual(targets,["fr","en","es","ar","zh"].filter(item=>item!==source));if(!["fr","en","es","ar","zh"].includes(source))assert.equal(targets[1],"en");}});

test("product display falls back current locale then English then canonical source",()=>{const base={name:"Titre source",description:"Description source",sourceLocale:"fr",sourceMetadata:undefined};const translations=[{locale:"en",title:"English title",description:"English description",automatic:true},{locale:"ar",title:"عنوان عربي",description:"وصف عربي",automatic:true}];assert.equal(resolveBuyerProductContent({...base,locale:"ar",translations}).title,"عنوان عربي");assert.equal(resolveBuyerProductContent({...base,locale:"fr",translations}).title,"Titre source");assert.equal(resolveBuyerProductContent({...base,locale:"ku",translations}).title,"English title");assert.equal(resolveBuyerProductContent({...base,locale:"ku",translations:[]}).title,"Titre source");});

test("manual translations win and non-priority locales ignore obsolete automatic records",()=>{const product=resolveBuyerProductContent({name:"Source",description:"Source description",sourceLocale:"fr",locale:"ku",translations:[{locale:"en",title:"English",description:"English",automatic:true},{locale:"ku",title:"Old automatic",description:"Old automatic",automatic:true},{locale:"ku",title:"Manual Kurdish",description:"Manual Kurdish",automatic:false}]});assert.equal(product.title,"Manual Kurdish");assert.equal(resolveBuyerProductContent({...product,name:"Source",description:"Source description",sourceLocale:"fr",locale:"ku",translations:[{locale:"en",title:"English",description:"English",automatic:true},{locale:"ku",title:"Old automatic",description:"Old automatic",automatic:true}]}).title,"English");const article={locale:"fr",title:"Titre",content:"Contenu",translations:[{locale:"en",title:"News",content:"English",automatic:true},{locale:"ku",title:"Old automatic",content:"Old",automatic:true}]};assert.equal(resolveNewsContent(article,"ku").title,"News");assert.equal(resolveNewsContent({...article,translations:[...article.translations,{locale:"ku",title:"Manual Kurdish",content:"Manual",automatic:false}]} ,"ku").title,"Manual Kurdish");});

test("queue remains bounded, free, retry-safe, and manual records are protected",()=>{const worker=readFileSync("lib/dynamic-content-translations.ts","utf8"),config=readFileSync("lib/dynamic-translation-config.ts","utf8"),provider=readFileSync("lib/self-hosted-translation.ts","utf8"),route=readFileSync("app/api/internal/catalog-translations/route.ts","utf8"),schema=readFileSync("prisma/schema.prisma","utf8"),migration=readFileSync("prisma/migrations/20260907190000_add_dynamic_content_translation/migration.sql","utf8");assert.match(worker,/runBoundedTranslationWork/);assert.match(worker,/config\.perRunItems/);assert.match(worker,/config\.perRunCharacters/);assert.match(worker,/config\.concurrency/);assert.match(worker,/maxAttempts/);assert.match(worker,/STALE_TRANSLATION_CLAIM_RECOVERED/);assert.match(worker,/SKIPPED_MANUAL/);assert.match(worker,/WAITING_FOR_ENGLISH/);assert.match(worker,/DISABLED_LOCALE/);assert.match(config,/createSelfHostedTranslationProvider/);assert.match(provider,/SELF_HOSTED_LIBRETRANSLATE/);assert.match(provider,/billable:false/);assert.doesNotMatch(config+provider,/Azure|MicrosoftTranslator|DeepL|OpenAI|Google Translate/i);assert.match(route,/hasValidBearerSecret/);assert.doesNotMatch(route,/export async function GET/);assert.match(schema,/automatic\s+Boolean\s+@default\(false\)/);assert.doesNotMatch(migration,/\b(?:DROP|TRUNCATE|DELETE FROM)\b/i);});

test("oversized worker diagnostics are safely bounded for the VARCHAR(100) task field",()=>{const failure=dynamicTranslationFailure(new Error(`provider failed ${"x".repeat(500)}`));assert.equal(failure.status,"FAILED");assert.equal(failure.lastErrorCode.length,100);assert.doesNotMatch(failure.lastErrorCode,/[\r\n\t]/);});

test("PostgreSQL concurrent updates become visible retryable task failures",()=>{for(const error of [{code:"P2034"},{code:"P2010",meta:{code:"40001",message:"could not serialize access due to concurrent update"}},new Error("PostgreSQL 40001 could not serialize access due to concurrent update")]){const failure=dynamicTranslationFailure(error);assert.deepEqual(failure,{lastErrorCode:"DATABASE_SERIALIZATION_CONFLICT",retryable:true,status:"RETRYABLE"});}});

test("legacy Arabic repair uses conflict-free atomic budget reservations before persistence",()=>{const worker=readFileSync("lib/dynamic-content-translations.ts","utf8"),reservation=worker.slice(worker.indexOf("async function reserveDynamicBudget"),worker.indexOf("async function completeDynamicBudget"));assert.match(reservation,/ON CONFLICT \("provider","periodType","periodStart"\) DO UPDATE/);assert.match(reservation,/TransactionIsolationLevel\.ReadCommitted/);assert.doesNotMatch(reservation,/TransactionIsolationLevel\.Serializable/);assert.match(worker,/reconcileInvalidAutomaticNewsTranslations\(db\)[\s\S]*discoverDynamicContentTranslationTasks\(db\)[\s\S]*runBoundedTranslationWork/);assert.match(worker,/newsArticleTranslation\.upsert[\s\S]*status:"COMPLETED"/);});

test("worker records oversized failures without overflowing or crashing",async()=>{const writes:unknown[]=[];const db={dynamicContentTranslationTask:{updateMany:async(args:unknown)=>{writes.push(args);return{count:1};}}};const failure=await recordDynamicTranslationFailure(db as any,{id:"task-1",entityType:"PRODUCT",targetLocale:"fr"},"claim-1",new Error("x".repeat(1000)),new Date("2026-09-07T00:00:00Z"));assert.equal(failure.lastErrorCode.length,100);assert.equal(writes.length,1);assert.equal((writes[0] as any).data.lastErrorCode.length,100);});

test("Actualités resolves completed priority translations for listing and detail content",()=>{const article={locale:"fr",title:"Titre français",content:"Contenu français",translations:[{locale:"en",title:"English title",content:"English body",automatic:true},{locale:"ar",title:"عنوان عربي",content:"محتوى عربي",automatic:true},{locale:"es",title:"Título español",content:"Contenido español",automatic:true},{locale:"zh",title:"中文标题",content:"中文内容",automatic:true}]};for(const [locale,title,content] of [["en","English title","English body"],["ar","عنوان عربي","محتوى عربي"],["es","Título español","Contenido español"],["zh","中文标题","中文内容"]]){const resolved=resolveNewsContent(article,locale);assert.equal(resolved.title,title);assert.equal(resolved.content,content);}});

test("Actualités fallback is manual requested locale then automatic requested locale then English then source",()=>{const article={locale:"fr",title:"Source",content:"Source body",translations:[{locale:"en",title:"English",content:"English body",automatic:true},{locale:"ar",title:"Automatic Arabic",content:"Automatic body",automatic:true},{locale:"ar",title:"Manual Arabic",content:"Manual body",automatic:false},{locale:"ku",title:"Obsolete automatic Kurdish",content:"Old",automatic:true}]};assert.equal(resolveNewsContent(article,"ar").title,"Manual Arabic");assert.equal(resolveNewsContent(article,"ku").title,"English");assert.equal(resolveNewsContent({...article,translations:[]},"ku").title,"Source");});

test("Todijo zh maps to the self-hosted provider zh-Hans code",async()=>{let payload:any;const fetcher=(async(_url:unknown,init?:RequestInit)=>{payload=JSON.parse(String(init?.body));return new Response(JSON.stringify({translatedText:["中文","正文"]}),{status:200,headers:{"content-type":"application/json"}});}) as typeof fetch,provider=createSelfHostedTranslationProvider({DYNAMIC_TRANSLATION_URL:"http://translate.local"} as unknown as NodeJS.ProcessEnv,fetcher);await provider.translate({sourceLocale:"fr",targetLocale:"zh",texts:["Titre","Contenu"]});assert.equal(payload.source,"fr");assert.equal(payload.target,"zh-Hans");});

test("French Actualités translates title and body independently into the same target locale",async()=>{const calls:any[]=[],providerResult=(text:string)=>({texts:[text],requestId:null,providerVersion:"test",usage:{characters:text.length,billable:false,confirmed:true}});const translate=async(input:any)=>{calls.push(input);const values:Record<string,string>={Titre:"عنوان عربي",Contenu:"محتوى عربي"};return providerResult(values[input.texts[0]]);};const result=await translateDynamicContentFields({sourceLocale:"fr",targetLocale:"ar",sourceTitle:"Titre",sourceContent:"Contenu"},translate);assert.deepEqual(result.texts,["عنوان عربي","محتوى عربي"]);assert.equal(calls.length,2);assert.deepEqual(calls.map(call=>call.targetLocale),["ar","ar"]);assert.deepEqual(calls.map(call=>call.texts),[["Titre"],["Contenu"]]);});

test("short French news title gets one contextual Arabic fallback without persisting its wrapper",async()=>{const calls:string[]=[];const result=await translateDynamicContentFields({sourceLocale:"fr",targetLocale:"ar",sourceTitle:"Todijo : une marketplace française tournée vers l’avenir",sourceContent:"Contenu source"},async input=>{const value=input.texts[0];calls.push(value);const translated=value==="Todijo : une marketplace française tournée vers l’avenir"?"Todijo: a future-oriented French marketplace":value==="Contenu source"?"محتوى عربي":"يقدم هذا المقال العنوان التالي: [[[Todijo: سوق فرنسي موجه نحو المستقبل]]].";return{texts:[translated],requestId:null,providerVersion:"test",usage:{characters:value.length,billable:false,confirmed:true}};});assert.equal(calls.length,3);assert.match(calls[1],/^Cet article présente le titre suivant:/);assert.deepEqual(result.texts,["Todijo: سوق فرنسي موجه نحو المستقبل","محتوى عربي"]);assert.doesNotMatch(result.texts[0],/Cet article|يقدم هذا المقال|\[\[\[/);});

test("English, Spanish, and Chinese Actualités keep title and body associated with one target",async()=>{for(const[targetLocale,title,content]of[["en","English title","English body"],["es","Título español","Contenido español"],["zh","中文标题","中文内容"]]){const calls:any[]=[];const result=await translateDynamicContentFields({sourceLocale:"fr",targetLocale,sourceTitle:"Titre",sourceContent:"Contenu"},async input=>{calls.push(input);const text=input.texts[0]==="Titre"?title:content;return{texts:[text],requestId:null,providerVersion:"test",usage:{characters:text.length,billable:false,confirmed:true}};});assert.deepEqual(result.texts,[title,content]);assert.deepEqual(calls.map(call=>call.targetLocale),[targetLocale,targetLocale]);}});

test("mixed-language automatic fields cannot be persisted as a completed Arabic or Chinese translation",async()=>{assert.equal(dynamicTranslationFieldsMatchTarget("ar","Todijo: a future-oriented French marketplace","محتوى عربي"),false);assert.equal(dynamicTranslationFieldsMatchTarget("ar","عنوان عربي","محتوى عربي"),true);assert.equal(dynamicTranslationFieldsMatchTarget("zh","English title","中文内容"),false);assert.equal(dynamicTranslationFieldsMatchTarget("zh","中文标题","中文内容"),true);for(const targetLocale of["en","es"]){assert.equal(dynamicTranslationFieldsMatchTarget(targetLocale,"Translated title","Translated body"),true);}await assert.rejects(()=>translateDynamicContentFields({sourceLocale:"fr",targetLocale:"ar",sourceTitle:"Titre",sourceContent:"Contenu"},async input=>({texts:[input.texts[0]==="Titre"?"English title":"محتوى عربي"],requestId:null,providerVersion:"test",usage:{characters:10,billable:false,confirmed:true}})),(error:any)=>error.safeCode==="TRANSLATION_TARGET_LANGUAGE_MISMATCH"&&error.retryable===true);});

test("only invalid automatic NewsArticle translations are requeued for safe repair",()=>{const worker=readFileSync("lib/dynamic-content-translations.ts","utf8");assert.match(worker,/!translation\.automatic/);assert.match(worker,/dynamicTranslationFieldsMatchTarget\(translation\.locale,translation\.title,translation\.content\)/);assert.match(worker,/entityType:"NEWS_ARTICLE",entityId:article\.id,targetLocale:translation\.locale,sourceFingerprint,status:"COMPLETED"/);assert.match(worker,/status:"RETRYABLE",attemptCount:0/);assert.match(worker,/AUTOMATIC_TRANSLATION_LANGUAGE_MISMATCH/);});

test("bounded reconciliation requeues the completed legacy Arabic task without touching manual Arabic or valid EN/ES",async()=>{const writes:any[]=[],rows=[{articleId:"article-1",locale:"ar",title:"Todijo: a future-oriented French marketplace",content:"محتوى عربي",automatic:true,sourceFingerprint:"f".repeat(64)},{articleId:"article-2",locale:"ar",title:"عنوان يدوي",content:"محتوى يدوي",automatic:false,sourceFingerprint:"m".repeat(64)},{articleId:"article-1",locale:"en",title:"English title",content:"English body",automatic:true,sourceFingerprint:"f".repeat(64)},{articleId:"article-1",locale:"es",title:"Título español",content:"Contenido español",automatic:true,sourceFingerprint:"f".repeat(64)}],db={newsArticleTranslation:{findMany:async(args:any)=>{assert.deepEqual(args.where,{automatic:true,locale:"ar"});assert.equal(args.take,25);return rows.filter(row=>row.automatic&&row.locale==="ar");}},dynamicContentTranslationTask:{updateMany:async(args:any)=>{writes.push(args);return{count:1};}}};const result=await reconcileInvalidAutomaticNewsTranslations(db as any);assert.deepEqual(result,{inspected:1,requeued:1});assert.equal(writes.length,1);assert.deepEqual(writes[0].where,{entityType:"NEWS_ARTICLE",entityId:"article-1",targetLocale:"ar",sourceFingerprint:"f".repeat(64),status:"COMPLETED"});assert.equal(writes[0].data.status,"RETRYABLE");assert.equal(writes[0].data.attemptCount,0);});

test("queued Actualités receives bounded opportunities behind a large Product backlog",()=>{const products=Array.from({length:100},(_,index)=>({id:`product-${index}`,entityType:"PRODUCT"})),news=Array.from({length:4},(_,index)=>({id:`news-${index}`,entityType:"NEWS_ARTICLE"})),selected=fairDynamicTranslationTasks(products,news,20);assert.equal(selected.length,20);assert.deepEqual(selected.filter(item=>item.entityType==="NEWS_ARTICLE").map(item=>item.id),["news-0","news-1","news-2","news-3"]);assert.equal(selected.filter(item=>item.entityType==="PRODUCT").length,16);});
