import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {dynamicContentTargets} from "../lib/dynamic-content-translations";
import {resolveBuyerProductContent} from "../lib/product-content";
import {resolveNewsContent} from "../lib/news-localization";

test("automatic dynamic translations target only the five priority locales",()=>{for(const source of ["fr","en","ar","ku","tr","de","es","it","nl","zh","fa","hi","pt","ru"]){const targets=dynamicContentTargets(source);assert.deepEqual(targets,["fr","en","es","ar","zh"].filter(item=>item!==source));if(!["fr","en","es","ar","zh"].includes(source))assert.equal(targets[1],"en");}});

test("product display falls back current locale then English then canonical source",()=>{const base={name:"Titre source",description:"Description source",sourceLocale:"fr",sourceMetadata:undefined};const translations=[{locale:"en",title:"English title",description:"English description",automatic:true},{locale:"ar",title:"عنوان عربي",description:"وصف عربي",automatic:true}];assert.equal(resolveBuyerProductContent({...base,locale:"ar",translations}).title,"عنوان عربي");assert.equal(resolveBuyerProductContent({...base,locale:"fr",translations}).title,"Titre source");assert.equal(resolveBuyerProductContent({...base,locale:"ku",translations}).title,"English title");assert.equal(resolveBuyerProductContent({...base,locale:"ku",translations:[]}).title,"Titre source");});

test("manual translations win and non-priority locales ignore obsolete automatic records",()=>{const product=resolveBuyerProductContent({name:"Source",description:"Source description",sourceLocale:"fr",locale:"ku",translations:[{locale:"en",title:"English",description:"English",automatic:true},{locale:"ku",title:"Old automatic",description:"Old automatic",automatic:true},{locale:"ku",title:"Manual Kurdish",description:"Manual Kurdish",automatic:false}]});assert.equal(product.title,"Manual Kurdish");assert.equal(resolveBuyerProductContent({...product,name:"Source",description:"Source description",sourceLocale:"fr",locale:"ku",translations:[{locale:"en",title:"English",description:"English",automatic:true},{locale:"ku",title:"Old automatic",description:"Old automatic",automatic:true}]}).title,"English");const article={locale:"fr",title:"Titre",content:"Contenu",translations:[{locale:"en",title:"News",content:"English",automatic:true},{locale:"ku",title:"Old automatic",content:"Old",automatic:true}]};assert.equal(resolveNewsContent(article,"ku").title,"News");assert.equal(resolveNewsContent({...article,translations:[...article.translations,{locale:"ku",title:"Manual Kurdish",content:"Manual",automatic:false}]} ,"ku").title,"Manual Kurdish");});

test("queue remains bounded, free, retry-safe, and manual records are protected",()=>{const worker=readFileSync("lib/dynamic-content-translations.ts","utf8"),config=readFileSync("lib/dynamic-translation-config.ts","utf8"),provider=readFileSync("lib/self-hosted-translation.ts","utf8"),route=readFileSync("app/api/internal/catalog-translations/route.ts","utf8"),schema=readFileSync("prisma/schema.prisma","utf8"),migration=readFileSync("prisma/migrations/20260907190000_add_dynamic_content_translation/migration.sql","utf8");assert.match(worker,/runBoundedTranslationWork/);assert.match(worker,/config\.perRunItems/);assert.match(worker,/config\.perRunCharacters/);assert.match(worker,/config\.concurrency/);assert.match(worker,/maxAttempts/);assert.match(worker,/STALE_TRANSLATION_CLAIM_RECOVERED/);assert.match(worker,/SKIPPED_MANUAL/);assert.match(worker,/WAITING_FOR_ENGLISH/);assert.match(worker,/DISABLED_LOCALE/);assert.match(config,/createSelfHostedTranslationProvider/);assert.match(provider,/SELF_HOSTED_LIBRETRANSLATE/);assert.match(provider,/billable:false/);assert.doesNotMatch(config+provider,/Azure|MicrosoftTranslator|DeepL|OpenAI|Google Translate/i);assert.match(route,/hasValidBearerSecret/);assert.doesNotMatch(route,/export async function GET/);assert.match(schema,/automatic\s+Boolean\s+@default\(false\)/);assert.doesNotMatch(migration,/\b(?:DROP|TRUNCATE|DELETE FROM)\b/i);});
