import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import type { PrismaClient } from "@prisma/client";
import { catalogTranslationConfig } from "../lib/catalog-translation-config";
import { processCatalogTranslationQueue } from "../lib/catalog-translation-jobs";
import { createMicrosoftTranslationProvider, microsoftLocale, microsoftTranslationConfig, microsoftTranslatorLocales, translateWithMicrosoft } from "../lib/microsoft-translator";
import { parseTranslationProviderId, TranslationProviderError, type TranslationProviderUsage } from "../lib/translation-provider";
import { locales } from "../i18n/config";

const validEnv:NodeJS.ProcessEnv={NODE_ENV:"test",CATALOG_TRANSLATION_ENABLED:"true",CATALOG_TRANSLATION_PROVIDER:"MICROSOFT",AZURE_TRANSLATOR_KEY:"secret",AZURE_TRANSLATOR_REGION:"westeurope",AZURE_TRANSLATOR_ENDPOINT:"https://api.cognitive.microsofttranslator.com",CATALOG_TRANSLATION_CRON_SECRET:"x".repeat(32),CATALOG_TRANSLATION_PER_RUN_CHARACTER_LIMIT:"10000",CATALOG_TRANSLATION_DAILY_CHARACTER_LIMIT:"100000",CATALOG_TRANSLATION_MONTHLY_CHARACTER_LIMIT:"1000000",CATALOG_TRANSLATION_PER_JOB_CHARACTER_LIMIT:"250000",CATALOG_TRANSLATION_PER_RUN_ITEM_LIMIT:"20",CATALOG_TRANSLATION_MAX_ATTEMPTS:"4",CATALOG_TRANSLATION_WORKER_CONCURRENCY:"2"};

test("provider is disabled by default and performs no outbound work",async()=>{let calls=0;const result=await processCatalogTranslationQueue({} as PrismaClient,{NODE_ENV:"test"},async()=>{calls++;throw new Error("unexpected")});assert.equal(result.enabled,false);assert.equal(calls,0);});
test("known providers parse and unknown providers fail closed",()=>{assert.equal(parseTranslationProviderId("microsoft"),"MICROSOFT");assert.equal(parseTranslationProviderId("self_hosted_libretranslate"),"SELF_HOSTED_LIBRETRANSLATE");assert.throws(()=>parseTranslationProviderId("arbitrary"),/TRANSLATION_CONFIG_PROVIDER_INVALID/);assert.throws(()=>catalogTranslationConfig({...validEnv,CATALOG_TRANSLATION_PROVIDER:"SELF_HOSTED_LIBRETRANSLATE"}),/TRANSLATION_CONFIG_PROVIDER_NOT_IMPLEMENTED/);});
test("provider-specific Microsoft configuration remains isolated",()=>{for(const name of ["AZURE_TRANSLATOR_KEY","AZURE_TRANSLATOR_REGION","AZURE_TRANSLATOR_ENDPOINT"]){assert.throws(()=>microsoftTranslationConfig({...validEnv,[name]:""}),/TRANSLATION_CONFIG_/);}const core=readFileSync("lib/catalog-translation-config.ts","utf8");assert.doesNotMatch(core,/AZURE_TRANSLATOR_KEY|AZURE_TRANSLATOR_REGION|AZURE_TRANSLATOR_ENDPOINT/);assert.doesNotMatch(core,/LIBRETRANSLATE_URL|LIBRETRANSLATE_KEY/);});
test("Microsoft adapter satisfies the common provider contract",()=>{const provider=createMicrosoftTranslationProvider(validEnv);assert.equal(provider.id,"MICROSOFT");assert.equal(provider.version,"text-v3.0");assert.equal(provider.accountingMode,"BILLABLE_CHARACTERS");assert.equal(provider.health().ready,true);assert.deepEqual(provider.supportedLocales,[...locales]);assert.equal(typeof provider.translate,"function");});
test("all Todijo locales have one closed Microsoft mapping",()=>{assert.deepEqual(Object.keys(microsoftTranslatorLocales).sort(),[...locales].sort());for(const item of locales)assert.ok(microsoftLocale(item));assert.throws(()=>microsoftLocale("arbitrary"),/TRANSLATION_LOCALE_UNSUPPORTED/);});
test("Central Sorani Kurdish and critical pilot locales use verified codes",()=>{assert.equal(microsoftLocale("ku"),"ku");assert.equal(microsoftLocale("ar"),"ar");assert.equal(microsoftLocale("fr"),"fr");assert.equal(microsoftLocale("de"),"de");assert.equal(microsoftLocale("en"),"en");assert.equal(microsoftLocale("zh"),"zh-Hans");});
test("Microsoft request is bounded, non-redirecting and reports billable usage",async()=>{const fetcher=(async(input:URL|RequestInfo,init?:RequestInit)=>{assert.match(String(input),/^https:\/\/api\.cognitive\.microsofttranslator\.com\/translate\?/);assert.equal(init?.redirect,"error");const headers=init?.headers as Record<string,string>;assert.equal(headers["Ocp-Apim-Subscription-Key"],"secret");assert.equal(headers["Ocp-Apim-Subscription-Region"],"westeurope");return new Response(JSON.stringify([{translations:[{text:"Bouteille",to:"fr"}]}]),{status:200,headers:{"x-metered-usage":"6","x-requestid":"request-1"}});}) as typeof fetch;const result=await translateWithMicrosoft(microsoftTranslationConfig(validEnv),{sourceLocale:"en",targetLocale:"fr",texts:["Bottle"]},fetcher);assert.deepEqual(result.texts,["Bouteille"]);assert.deepEqual(result.usage,{characters:6,billable:true,confirmed:true});});
test("billable and capacity-only usage are represented distinctly",()=>{const billable:TranslationProviderUsage={characters:6,billable:true,confirmed:true},selfHosted:TranslationProviderUsage={characters:6,billable:false,confirmed:true};assert.equal(billable.billable,true);assert.equal(selfHosted.billable,false);});
test("common retry categories safely classify rate limits and unavailable providers",async()=>{for(const [status,category] of [[429,"RATE_LIMITED"],[503,"PROVIDER_UNAVAILABLE"]] as const){const fetcher=(async()=>new Response("{}",{status,headers:status===429?{"retry-after":"120"}:{}})) as typeof fetch;await assert.rejects(()=>translateWithMicrosoft(microsoftTranslationConfig(validEnv),{sourceLocale:"en",targetLocale:"fr",texts:["Bottle"]},fetcher),(error:unknown)=>error instanceof TranslationProviderError&&error.category===category&&error.retryable&&(status!==429||error.retryAfterMs===120000));}});
test("ambiguous Microsoft submission uses the common non-retryable category",async()=>{const fetcher=(async()=>{throw new Error("socket");}) as typeof fetch;await assert.rejects(()=>translateWithMicrosoft(microsoftTranslationConfig(validEnv),{sourceLocale:"en",targetLocale:"fr",texts:["Bottle"]},fetcher),(error:unknown)=>error instanceof TranslationProviderError&&error.category==="AMBIGUOUS_SUBMISSION"&&!error.retryable&&error.safeCode==="TRANSLATION_SUBMISSION_AMBIGUOUS");});
test("malformed provider responses are definite and safe",async()=>{const fetcher=(async()=>new Response("{}",{status:200})) as typeof fetch;await assert.rejects(()=>translateWithMicrosoft(microsoftTranslationConfig(validEnv),{sourceLocale:"en",targetLocale:"fr",texts:["Bottle"]},fetcher),(error:unknown)=>error instanceof TranslationProviderError&&error.category==="MALFORMED_RESPONSE"&&!error.retryable);});
test("queue depends only on common provider errors and preserves safety invariants",()=>{const source=readFileSync("lib/catalog-translation-jobs.ts","utf8");assert.doesNotMatch(source,/MicrosoftTranslatorError|MicrosoftTranslationResult|translateWithMicrosoft/);assert.match(source,/TranslationProviderError/);assert.match(source,/category==="AMBIGUOUS_SUBMISSION"/);assert.match(source,/claimToken:token/);assert.match(source,/attemptCount:\{lt:config\.maxAttempts\}/);assert.match(source,/TransactionIsolationLevel\.Serializable/);assert.match(source,/submittedCharacters"\+"CatalogTranslationBudget"\."reservedCharacters/);assert.match(source,/TRANSLATION_JOB_CHARACTER_LIMIT_EXHAUSTED/);assert.match(source,/config\.provider\.id/);assert.match(source,/config\.provider\.version/);assert.match(source,/result\.usage\.billable/);});
test("Admin and worker routes are isolated from arbitrary public translation",()=>{for(const path of ["app/api/admin/catalog-translations/route.ts","app/api/admin/catalog-translations/preview/route.ts","app/api/admin/catalog-translations/[jobId]/pause/route.ts","app/api/admin/catalog-translations/[jobId]/retry/route.ts"])assert.match(readFileSync(path,"utf8"),/requireAdmin/);const worker=readFileSync("app/api/internal/catalog-translations/route.ts","utf8");assert.match(worker,/timingSafeEqual/);assert.match(worker,/export async function POST/);assert.doesNotMatch(worker,/export async function GET/);for(const path of ["app/page.tsx","app/product/[id]/page.tsx","app/api/marketplace/products/route.ts"]){const source=readFileSync(path,"utf8");assert.doesNotMatch(source,/microsoft-translator|translation-provider|catalog-translation-jobs/);}});
test("provider diagnostics never log text or credentials",()=>{const provider=readFileSync("lib/microsoft-translator.ts","utf8"),worker=readFileSync("app/api/internal/catalog-translations/route.ts","utf8");assert.doesNotMatch(provider,/console\./);assert.doesNotMatch(worker,/AZURE_TRANSLATOR_KEY|sourceMetadata|texts/);});
