import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import type { PrismaClient } from "@prisma/client";
import { catalogTranslationConfig, microsoftLocale, microsoftTranslatorLocales } from "../lib/catalog-translation-config";
import { processCatalogTranslationQueue } from "../lib/catalog-translation-jobs";
import { MicrosoftTranslatorError, translateWithMicrosoft } from "../lib/microsoft-translator";
import { locales } from "../i18n/config";

const validEnv:NodeJS.ProcessEnv={NODE_ENV:"test",CATALOG_TRANSLATION_ENABLED:"true",CATALOG_TRANSLATION_PROVIDER:"MICROSOFT",AZURE_TRANSLATOR_KEY:"secret",AZURE_TRANSLATOR_REGION:"westeurope",AZURE_TRANSLATOR_ENDPOINT:"https://api.cognitive.microsofttranslator.com",CATALOG_TRANSLATION_CRON_SECRET:"x".repeat(32),CATALOG_TRANSLATION_PER_RUN_CHARACTER_LIMIT:"10000",CATALOG_TRANSLATION_DAILY_CHARACTER_LIMIT:"100000",CATALOG_TRANSLATION_MONTHLY_CHARACTER_LIMIT:"1000000",CATALOG_TRANSLATION_PER_JOB_CHARACTER_LIMIT:"250000",CATALOG_TRANSLATION_PER_RUN_ITEM_LIMIT:"20",CATALOG_TRANSLATION_MAX_ATTEMPTS:"4",CATALOG_TRANSLATION_WORKER_CONCURRENCY:"2"};

test("provider is disabled by default and performs no outbound work",async()=>{let calls=0;const result=await processCatalogTranslationQueue({} as PrismaClient,{NODE_ENV:"test"},async()=>{calls++;throw new Error("unexpected")});assert.equal(result.enabled,false);assert.equal(calls,0);});
test("enabled provider fails closed for missing key region and endpoint",()=>{for(const name of ["AZURE_TRANSLATOR_KEY","AZURE_TRANSLATOR_REGION","AZURE_TRANSLATOR_ENDPOINT"]){const env={...validEnv,[name]:""};assert.throws(()=>catalogTranslationConfig(env),/TRANSLATION_CONFIG_/);}});
test("all Todijo locales have one closed Microsoft mapping",()=>{assert.deepEqual(Object.keys(microsoftTranslatorLocales).sort(),[...locales].sort());for(const item of locales)assert.ok(microsoftLocale(item));assert.throws(()=>microsoftLocale("arbitrary"),/TRANSLATION_LOCALE_UNSUPPORTED/);});
test("Central Sorani Kurdish and critical pilot locales use verified codes",()=>{assert.equal(microsoftLocale("ku"),"ku");assert.equal(microsoftLocale("ar"),"ar");assert.equal(microsoftLocale("fr"),"fr");assert.equal(microsoftLocale("de"),"de");assert.equal(microsoftLocale("en"),"en");assert.equal(microsoftLocale("zh"),"zh-Hans");});
test("Microsoft request is HTTPS, non-redirecting, authenticated by headers, and returns metered usage",async()=>{const fetcher=(async(input:URL|RequestInfo,init?:RequestInit)=>{assert.match(String(input),/^https:\/\/api\.cognitive\.microsofttranslator\.com\/translate\?/);assert.equal(init?.redirect,"error");const headers=init?.headers as Record<string,string>;assert.equal(headers["Ocp-Apim-Subscription-Key"],"secret");assert.equal(headers["Ocp-Apim-Subscription-Region"],"westeurope");return new Response(JSON.stringify([{translations:[{text:"Bouteille",to:"fr"}]}]),{status:200,headers:{"x-metered-usage":"6","x-requestid":"request-1"}});}) as typeof fetch;const result=await translateWithMicrosoft(catalogTranslationConfig(validEnv)!,{sourceLocale:"en",targetLocale:"fr",texts:["Bottle"]},fetcher);assert.deepEqual(result.texts,["Bouteille"]);assert.equal(result.meteredCharacters,6);});
test("429 preserves bounded Retry-After and definite 5xx is retryable",async()=>{for(const [status,retry] of [[429,"120"],[503,null]] as const){const fetcher=(async()=>new Response("{}",{status,headers:retry?{"retry-after":retry}:{}})) as typeof fetch;await assert.rejects(()=>translateWithMicrosoft(catalogTranslationConfig(validEnv)!,{sourceLocale:"en",targetLocale:"fr",texts:["Bottle"]},fetcher),(error:unknown)=>error instanceof MicrosoftTranslatorError&&error.retryable&&(status!==429||error.retryAfterMs===120000));}});
test("network ambiguity is never marked blindly retryable",async()=>{const fetcher=(async()=>{throw new Error("socket");}) as typeof fetch;await assert.rejects(()=>translateWithMicrosoft(catalogTranslationConfig(validEnv)!,{sourceLocale:"en",targetLocale:"fr",texts:["Bottle"]},fetcher),(error:unknown)=>error instanceof MicrosoftTranslatorError&&error.ambiguous&&!error.retryable&&error.code==="TRANSLATION_SUBMISSION_AMBIGUOUS");});
test("queue source encodes claims leases finite attempts budgets and per-run bounds",()=>{const source=readFileSync("lib/catalog-translation-jobs.ts","utf8");assert.match(source,/CATALOG_TRANSLATION_LEASE_MS/);assert.match(source,/claimToken:token/);assert.match(source,/attemptCount:\{lt:config\.maxAttempts\}/);assert.match(source,/TRANSLATION_SUBMISSION_AMBIGUOUS/);assert.match(source,/TransactionIsolationLevel\.Serializable/);assert.match(source,/submittedCharacters"\+"CatalogTranslationBudget"\."reservedCharacters"/);assert.match(source,/TRANSLATION_JOB_CHARACTER_LIMIT_EXHAUSTED/);assert.match(source,/characters\+item\.estimatedCharacters>config\.perRunCharacters/);assert.match(source,/take:config\.perRunItems/);});
test("Admin and worker routes are isolated from arbitrary public translation",()=>{for(const path of ["app/api/admin/catalog-translations/route.ts","app/api/admin/catalog-translations/preview/route.ts","app/api/admin/catalog-translations/[jobId]/pause/route.ts","app/api/admin/catalog-translations/[jobId]/retry/route.ts"])assert.match(readFileSync(path,"utf8"),/requireAdmin/);const worker=readFileSync("app/api/internal/catalog-translations/route.ts","utf8");assert.match(worker,/timingSafeEqual/);assert.match(worker,/export async function POST/);assert.doesNotMatch(worker,/export async function GET/);for(const path of ["app/page.tsx","app/product/[id]/page.tsx","app/api/marketplace/products/route.ts"])assert.doesNotMatch(readFileSync(path,"utf8"),/microsoft-translator|catalog-translation-jobs/);});
test("provider diagnostics never log source text or credentials",()=>{const provider=readFileSync("lib/microsoft-translator.ts","utf8"),worker=readFileSync("app/api/internal/catalog-translations/route.ts","utf8");assert.doesNotMatch(provider,/console\./);assert.doesNotMatch(worker,/AZURE_TRANSLATOR_KEY|sourceMetadata|texts/);});
