import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { locales } from "../i18n/config";

const read=(...parts:string[])=>fs.readFileSync(path.join(process.cwd(),...parts),"utf8");
function leaves(value:unknown,prefix="",result=new Map<string,string>()){if(value&&typeof value==="object"&&!Array.isArray(value))for(const[key,child]of Object.entries(value))leaves(child,prefix?`${prefix}.${key}`:key,result);else result.set(prefix,String(value));return result}
const placeholders=(value:string)=>[...value.matchAll(/\{([a-zA-Z][\w]*)/g)].map(match=>match[1]).sort();

test("notification center is bounded, owned, server-read and locale-safe",()=>{const page=read("app","notifications","page.tsx"),route=read("app","api","notifications","read","route.ts"),actions=read("components","NotificationActions.tsx");assert.match(page,/PAGE_SIZE\s*=\s*20/);assert.match(page,/where:\{userId:session\.userId\}/);assert.match(page,/take:PAGE_SIZE/);assert.match(page,/safeHref/);assert.match(route,/userId: session\.userId/);assert.match(route,/updateMany/);assert.match(actions,/\/api\/notifications\/read/);assert.match(actions,/router\.refresh\(\)/)});
test("notification translations have exact key and placeholder parity in all locales",()=>{const expected=leaves(JSON.parse(read("messages","notifications","en.json")));for(const locale of locales){const actual=leaves(JSON.parse(read("messages","notifications",`${locale}.json`)));assert.deepEqual([...actual.keys()].sort(),[...expected.keys()].sort(),locale);for(const[key,value]of expected)assert.deepEqual(placeholders(actual.get(key)!),placeholders(value),`${locale}:${key}`)}});
test("notification event copy has exact parity in all locales",()=>{const expected=leaves(JSON.parse(read("messages","notification-events","en.json")));for(const locale of locales){const actual=leaves(JSON.parse(read("messages","notification-events",`${locale}.json`)));assert.deepEqual([...actual.keys()].sort(),[...expected.keys()].sort(),locale);for(const[key,value]of expected)assert.deepEqual(placeholders(actual.get(key)!),placeholders(value),`${locale}:${key}`)}});
test("dashboard bells point to the notification center and moderation privacy remains intact",()=>{const dashboard=read("app","dashboard","page.tsx"),seller=read("components","SellerDashboardLayout.tsx"),moderation=read("app","api","admin","moderation","product-reports","[reportId]","route.ts");assert.match(dashboard,/notificationHref=\{`\/\$\{locale\}\/notifications`\}/);assert.match(seller,/notificationHref=\{`\/\$\{locale\}\/notifications`\}/);assert.doesNotMatch(moderation,/reporterId|reporter\.email/)});
test("paid orders notify both parties idempotently and message alerts are coalesced",()=>{const payments=read("lib","payments.ts"),newConversation=read("app","api","conversations","route.ts"),message=read("app","api","conversations","[id]","messages","route.ts");assert.match(payments,/if \(order\.status === "PAID"\) return \{ duplicate: true \}/);assert.match(payments,/type: "ORDER_PAID"/);assert.match(payments,/type: "NEW_ORDER"/);for(const source of [newConversation,message]){assert.match(source,/notification\.deleteMany/);assert.match(source,/type: "NEW_MESSAGE"/);assert.match(source,/readAt: null/)}});
