import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";
import webpush from "web-push";
import { activatePushSubscription } from "../lib/push-activation";
import { endpointHash, PushSubscriptionError, savePushSubscription, validatePushSubscription } from "../lib/push-subscriptions";
import { stripeMinorAmount } from "../lib/currency";

const source=(path:string)=>fs.readFileSync(path,"utf8");
const subscription={endpoint:"https://push.example.test/device/a",keys:{p256dh:"A".repeat(65),auth:"B".repeat(16)}};
function configured(){process.env.WEB_PUSH_VAPID_PUBLIC_KEY="A".repeat(87);process.env.WEB_PUSH_VAPID_PRIVATE_KEY="B".repeat(43);process.env.WEB_PUSH_VAPID_SUBJECT="mailto:push@todijo.com";process.env.WEB_PUSH_ENCRYPTION_KEY=Buffer.alloc(32,7).toString("base64")}

test("subscription validation is bounded and HTTPS only",()=>{assert.equal(validatePushSubscription(subscription).endpoint,subscription.endpoint);for(const value of [{}, {...subscription,endpoint:"http://push.test/a"},{...subscription,keys:{p256dh:"short",auth:"short"}},{...subscription,endpoint:"https://user:pass@push.test/a"},{...subscription,expirationTime:Number.NaN}])assert.throws(()=>validatePushSubscription(value),PushSubscriptionError)});
test("endpoint identity is stable without storing the endpoint in lookup columns",()=>{assert.equal(endpointHash(subscription.endpoint).length,64);assert.equal(endpointHash(subscription.endpoint),endpointHash(subscription.endpoint));assert.notEqual(endpointHash(subscription.endpoint),subscription.endpoint)});
test("duplicate endpoint is idempotent while cross-user ownership fails closed",async()=>{configured();let owner:string|null=null,upserts=0;const db={pushSubscription:{findUnique:async()=>owner?{userId:owner}:null,upsert:async()=>{upserts++}}} as any;await savePushSubscription(db,"buyer-a",subscription);owner="buyer-a";await savePushSubscription(db,"buyer-a",subscription);await assert.rejects(()=>savePushSubscription(db,"buyer-b",subscription),(error:any)=>error instanceof PushSubscriptionError&&error.status===409);assert.equal(upserts,2)});
test("subscription APIs require session ownership and never accept userId",()=>{const route=source("app/api/push/subscriptions/route.ts");assert.match(route,/if\(!session\)/);assert.match(route,/session\.userId/);assert.doesNotMatch(route,/body\?\.userId|body\.userId/);assert.doesNotMatch(route,/endpointEncrypted|p256dhEncrypted|authEncrypted/)});
test("private VAPID and encryption keys are never exposed by the browser config API",()=>{const route=source("app/api/push/config/route.ts");assert.match(route,/publicKey:config\.publicKey/);assert.doesNotMatch(route,/privateKey:|encryptionKey:/)});
test("permission is contextual, respects denial, and is never requested on mount",()=>{const ui=source("components/PushNotificationSettings.tsx"),before=ui.slice(0,ui.indexOf("async function enable"));assert.doesNotMatch(before,/requestPermission/);assert.match(ui,/Notification\.permission\s*===\s*"denied"/);assert.match(ui,/Notification\.requestPermission\(\)/);assert.match(source("app/notifications/page.tsx"),/PushNotificationSettings/)});
test("activation reconciles an existing browser subscription before subscribe and persists it",async()=>{const originalFetch=globalThis.fetch,existing={toJSON:()=>subscription};let subscribeCalls=0,postedBody="";(globalThis as any).fetch=async(_input:string,init:any)=>{postedBody=init.body;return{ok:true}};try{await activatePushSubscription(webpush.generateVAPIDKeys().publicKey,{pushManager:{getSubscription:async()=>existing,subscribe:async()=>{subscribeCalls++;throw new Error("should not subscribe")}}} as any);assert.equal(subscribeCalls,0);assert.deepEqual(JSON.parse(postedBody),subscription);}finally{globalThis.fetch=originalFetch}});
test("activation reconciles a concurrent subscribe race and reports only safe error categories",async()=>{const originalFetch=globalThis.fetch,existing={toJSON:()=>subscription};let reads=0,posts=0;(globalThis as any).fetch=async()=>{posts++;return{ok:true}};try{await activatePushSubscription(webpush.generateVAPIDKeys().publicKey,{pushManager:{getSubscription:async()=>++reads===1?null:existing,subscribe:async()=>{throw new DOMException("provider detail","InvalidStateError")}}} as any);assert.equal(reads,2);assert.equal(posts,1);const activation=source("lib/push-activation.ts"),ui=source("components/PushNotificationSettings.tsx");assert.match(activation,/PUSH_SUBSCRIBE/);assert.match(activation,/SUBSCRIPTION_API/);assert.doesNotMatch(ui,/console\.(?:warn|error)\([^\n]*(?:endpoint|p256dh|auth|publicKey)/);}finally{globalThis.fetch=originalFetch}});
test("delivery is user-owned, bounded, idempotent and revokes dead endpoints",()=>{const delivery=source("lib/web-push-delivery.ts");assert.match(delivery,/userId:notification\.userId/);assert.match(delivery,/index\+=5/);assert.match(delivery,/pushDispatchedAt:null/);assert.match(delivery,/status===404\|\|status===410/);assert.match(delivery,/revokedAt:new Date\(\)/);assert.doesNotMatch(delivery,/endpoint.*console|console.*endpoint/)});
test("push payload and service-worker clicks reject arbitrary content and routes",()=>{const worker=source("public/sw.js"),delivery=source("lib/web-push-delivery.ts");assert.match(worker,/PUSH_PATH\.test/);assert.match(worker,/PUSH_COPY\[data\.category\]/);assert.doesNotMatch(worker,/value\?\.(?:title|body)/);assert.match(delivery,/safePath\.test/);assert.doesNotMatch(delivery,/title|body/)});
test("authoritative transitions dispatch only after persistence and remain best effort",()=>{for(const file of["app/api/stripe/webhook/route.ts","app/api/seller/orders/[orderId]/fulfillment/route.ts","app/api/conversations/route.ts","app/api/conversations/[id]/messages/route.ts"]){const value=source(file);assert.match(value,/dispatchNotificationPushBestEffort/)}const helper=source("lib/web-push-delivery.ts");assert.match(helper,/void dispatchNotificationPush/);assert.match(helper,/\.catch\(/)});
test("migration is additive, indexed, unique and cascade-cleaned without backfill",()=>{const sql=source("prisma/migrations/20260831233000_add_web_push_subscriptions/migration.sql");assert.match(sql,/CREATE TABLE "PushSubscription"/);assert.match(sql,/"expirationTime" TIMESTAMP\(3\)/);assert.match(sql,/CREATE UNIQUE INDEX "PushSubscription_endpointHash_key"/);assert.match(sql,/ON DELETE CASCADE/);assert.doesNotMatch(sql,/DROP |DELETE FROM|UPDATE "(?:User|Order|Notification)"/)});
test("protected commerce and Stage 1-6 invariants remain unchanged",()=>{assert.equal(stripeMinorAmount("9.69","EUR"),969);const worker=source("public/sw.js");for(const path of["api","checkout","cart","account","messages","notifications"])assert.match(worker,new RegExp(path));assert.match(source("lib/payments.ts"),/Stripe total does not match the order/);assert.match(source("lib/fulfillment.ts"),/Custom tracking URLs are not accepted/)});
