import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {join} from "node:path";
import test from "node:test";
import {ProductRemovalError,removeProductListing} from "../lib/product-removal";

const root=process.cwd(),source=(...parts:string[])=>readFileSync(join(root,...parts),"utf8");
type Counts={orderItems:number;conversations:number;reviews:number;reports:number};
function mockDb(input:{actor?:any;product?:any}){const calls={deleted:0,updated:[] as any[],variants:[] as any[]};const tx={user:{findUnique:async()=>input.actor??null},product:{findUnique:async()=>input.product??null,delete:async(value:any)=>{calls.deleted++;return value},update:async(value:any)=>{calls.updated.push(value);return value}},productVariant:{updateMany:async(value:any)=>{calls.variants.push(value);return value}}};return{db:{$transaction:async(fn:(value:any)=>unknown)=>fn(tx)} as any,calls}}
const counts=(partial:Partial<Counts>={}):Counts=>({orderItems:0,conversations:0,reviews:0,reports:0,...partial});
const actor=(id="seller",role="SELLER")=>({id,role,deactivatedAt:null,sellerSuspendedAt:null});
const product=(ownerId="seller",history=counts(),removedAt:null|Date=null)=>({id:"product",removedAt,store:{ownerId},_count:history});

test("seller hard deletes only their own unreferenced local listing and disposable catalog cascades",async()=>{const{db,calls}=mockDb({actor:actor(),product:product()});assert.deepEqual(await removeProductListing(db,{userId:"seller"},"product"),{productId:"product",outcome:"HARD_DELETED",protectedHistory:false});assert.equal(calls.deleted,1);assert.equal(calls.updated.length,0);assert.equal(calls.variants.length,0)});
test("seller cannot remove another seller product",async()=>{const{db,calls}=mockDb({actor:actor(),product:product("other")});await assert.rejects(removeProductListing(db,{userId:"seller"},"product"),(error:any)=>error instanceof ProductRemovalError&&error.code==="PRODUCT_REMOVE_FORBIDDEN"&&error.status===403);assert.equal(calls.deleted,0)});
test("admin can remove any seller product",async()=>{const{db,calls}=mockDb({actor:actor("admin","ADMIN"),product:product("other")});const result=await removeProductListing(db,{userId:"admin"},"product");assert.equal(result.outcome,"HARD_DELETED");assert.equal(calls.deleted,1)});
test("unauthenticated removal is rejected",async()=>{const{db}=mockDb({});await assert.rejects(removeProductListing(db,null,"product"),(error:any)=>error.code==="AUTH_REQUIRED"&&error.status===401)});
test("commerce history archives listing and variants without deleting evidence",async()=>{const{db,calls}=mockDb({actor:actor(),product:product("seller",counts({orderItems:1,reviews:1,reports:1,conversations:1}))});const result=await removeProductListing(db,{userId:"seller"},"product",new Date("2026-08-28T00:00:00Z"));assert.equal(result.outcome,"ARCHIVED");assert.equal(calls.deleted,0);assert.deepEqual(calls.updated[0].data,{status:"DRAFT",stock:0,deactivationReason:"SELLER",removedAt:new Date("2026-08-28T00:00:00Z"),removedById:"seller",removalActorRole:"SELLER"});assert.deepEqual(calls.variants[0].data,{active:false,stock:0})});
test("repeated archived removal is deterministic and does not mutate history",async()=>{const{db,calls}=mockDb({actor:actor(),product:product("seller",counts({orderItems:1}),new Date())});assert.equal((await removeProductListing(db,{userId:"seller"},"product")).outcome,"ALREADY_REMOVED");assert.equal(calls.deleted,0);assert.equal(calls.updated.length,0)});
test("missing hard-deleted listing returns deterministic not found",async()=>{const{db}=mockDb({actor:actor()});await assert.rejects(removeProductListing(db,{userId:"seller"},"product"),(error:any)=>error.code==="PRODUCT_NOT_FOUND"&&error.status===404)});
test("removed listings are fail-closed across public access and seller editing",()=>{assert.match(source("lib/admin-access.ts"),/publicProductAccessWhere[\s\S]*removedAt:null/);assert.match(source("app/api/products/[id]/route.ts"),/removedAt:null/);assert.match(source("app/seller/products/[id]/edit/page.tsx"),/removedAt:null/)});
test("seller and admin UI share authoritative service without native confirm or CJ destruction",()=>{const seller=source("app/seller/products/[id]/edit/EditProductForm.tsx"),sellerRoute=source("app/api/products/[id]/route.ts"),adminRoute=source("app/api/admin/products/[id]/route.ts"),service=source("lib/product-removal.ts");assert.match(seller,/showModal\(\)/);assert.doesNotMatch(seller,/window\.confirm/);assert.match(seller,/removed=1/);assert.match(sellerRoute,/removeProductListing/);assert.match(adminRoute,/requireAdmin/);assert.match(adminRoute,/removeProductListing/);assert.doesNotMatch(service,/fetch\(|cjApi|deleteSupplier|deleteCj/i)});
test("protected refund return fulfillment transfer evidence remains reachable through archived OrderItem",()=>{const schema=source("prisma/schema.prisma");assert.match(schema,/model OrderItem[\s\S]*product\s+Product\s+@relation\([^\n]*onDelete: Restrict/);assert.match(schema,/model RefundRequest/);assert.match(schema,/model InventoryRestockEvent/);assert.match(schema,/transferStatus SellerTransferStatus/);assert.match(schema,/model SupplierFulfillment/)});
