import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";
import { assertRefundPaymentMode, orderPaymentMode, processRefundOperation, RefundPaymentModeError } from "../lib/refund-lifecycle";
import { refundPaymentModeMessage } from "../i18n/refund-admin-errors";
import { locales } from "../i18n/config";

const source=(path:string)=>readFileSync(join(process.cwd(),path),"utf8");

test("legacy Checkout identifiers derive payment mode only when unambiguous",()=>{assert.equal(orderPaymentMode({stripeCheckoutSessionId:"cs_test_old"}),"test");assert.equal(orderPaymentMode({stripeCheckoutSessionId:"cs_live_old"}),"live");assert.equal(orderPaymentMode({stripeCheckoutSessionId:null}),null);assert.equal(orderPaymentMode({stripeCheckoutSessionId:"cs_unknown"}),null)});
test("historical test and live payments fail closed in the opposite runtime",()=>{for(const [order,runtime] of [[{stripePaymentMode:"TEST"},"live"],[{stripePaymentMode:"LIVE"},"test"]] as const)assert.throws(()=>assertRefundPaymentMode(order,runtime),(error:any)=>error instanceof RefundPaymentModeError&&error.code==="REFUND_PAYMENT_MODE_MISMATCH")});
test("unresolved legacy payment mode fails closed",()=>{assert.throws(()=>assertRefundPaymentMode({stripeCheckoutSessionId:null},"live"),(error:any)=>error.code==="REFUND_PAYMENT_MODE_UNRESOLVED")});
test("mode mismatch never claims or submits a Stripe refund",async()=>{let claims=0,submits=0,blocked="";const db:any={refundOperation:{findUniqueOrThrow:async()=>({paymentMode:"TEST",order:{stripePaymentMode:"TEST",stripeCheckoutSessionId:"cs_test_old"}}),updateMany:async({data}:any)=>{if(data.status==="PROCESSING")claims++;if(data.status==="MANUAL_ACTION_REQUIRED")blocked=data.errorCode;return{count:1}}}};const previous=process.env.STRIPE_MODE;process.env.STRIPE_MODE="live";try{await assert.rejects(()=>processRefundOperation(db,"operation",new Date(),async()=>{submits++;return{id:"re"}}),(error:any)=>error.code==="REFUND_PAYMENT_MODE_MISMATCH")}finally{if(previous==null)delete process.env.STRIPE_MODE;else process.env.STRIPE_MODE=previous}assert.equal(claims,0);assert.equal(submits,0);assert.equal(blocked,"REFUND_PAYMENT_MODE_MISMATCH")});
test("same-mode processing still reaches the existing idempotent Stripe path",async()=>{let submits=0;const operation:any={id:"operation",status:"PROCESSING",attemptCount:1,orderId:"order",reviewedById:"admin",currency:"EUR",totalAmountMinor:969,refundIdempotencyKey:"buyer-refund:req",paymentMode:"TEST",order:{stripePaymentMode:"TEST",stripeCheckoutSessionId:"cs_test_old",stripePaymentIntentId:"pi_old"},groupAllocations:[]};const db:any={refundOperation:{findUniqueOrThrow:async({select}:any)=>select?{paymentMode:"TEST",order:{stripePaymentMode:"TEST",stripeCheckoutSessionId:"cs_test_old"}}:operation,updateMany:async()=>({count:1})},refundGroupAllocation:{updateMany:async()=>({})},refundItemAllocation:{findMany:async()=>[]},orderLifecycleEvent:{create:async()=>({})},$transaction:async(fn:any)=>fn(db)};const previous=process.env.STRIPE_MODE;process.env.STRIPE_MODE="test";try{const result:any=await processRefundOperation(db,"operation",new Date(),async(input)=>{submits++;assert.equal(input.amount,969);return{id:"re_test"}});assert.equal(result.refunded,true)}finally{if(previous==null)delete process.env.STRIPE_MODE;else process.env.STRIPE_MODE=previous}assert.equal(submits,1)});
test("admin API exposes safe mode codes before changing the decision",()=>{const route=source("app/api/admin/refund-requests/[requestId]/route.ts");assert.match(route,/assertRefundRequestPaymentMode[\s\S]+decideAdminRefundRequest/);assert.match(route,/REFUND_FINANCIAL_PROCESSING_FAILED/);assert.match(route,/refundRequestId/);assert.doesNotMatch(route,/STRIPE_SECRET_KEY/)});
test("localized mismatch feedback and order filter fallback cover every locale",()=>{for(const locale of locales)assert.ok(refundPaymentModeMessage(locale).length>20);const page=source("app/adm-barewbar-182203/orders/page.tsx");assert.doesNotMatch(page,/history\.filtersLabel/);assert.match(page,/labels\.all/)});
test("migration backfills only authoritative Checkout prefixes and snapshots operations",()=>{const sql=source("prisma/migrations/20260829100000_add_refund_payment_mode/migration.sql");assert.match(sql,/cs_test_%/);assert.match(sql,/cs_live_%/);assert.match(sql,/RefundOperation/);assert.doesNotMatch(sql,/pi_test|pi_live/)});
test("money and Checkout mode protections remain intact",()=>{assert.match(source("lib/payments.ts"),/unitAmountMinor/);assert.match(source("lib/stripe.ts"),/assertStripeCheckoutSessionMode/);assert.match(source("tests/payments.test.ts"),/969/)});
