import test from "node:test";
import assert from "node:assert/strict";
import { PrismaClient } from "@prisma/client";
import { publicProductAccessWhere } from "../lib/admin-access";
import { lockSellerProductQuota, requireStorePublishingAccess } from "../lib/seller-subscription";
import { enforceSellerPublicationCapacity } from "../lib/seller-publication-capacity";
import { proHomepageDiscovery } from "../lib/pro-homepage-discovery";
const databaseUrl=process.env.FREE_SELLER_TEST_DATABASE_URL;
test("PostgreSQL FREE visibility, quota concurrency and expiry retain data without auto-republishing",{skip:!databaseUrl},async()=>{
  const url=new URL(databaseUrl!);
  assert.equal(process.env.TODIJO_FREE_EPHEMERAL,"1");assert.equal(url.hostname,"127.0.0.1");assert.equal(url.port,"65431");assert.equal(url.pathname,"/todijo_free_test");assert.equal(url.username,"validation");
  const db=new PrismaClient({datasources:{db:{url:databaseUrl}}});
  try{
    const owner=await db.user.create({data:{firstName:"Free",lastName:"Seller",email:"free@example.invalid",role:"SELLER",emailVerified:true,stripeAccountId:"acct_mock",stripeOnboardingComplete:true,stripeChargesEnabled:true,stripePayoutsEnabled:true}});
    const store=await db.store.create({data:{name:"FREE fixture",slug:"free-fixture",country:"FR",city:"Paris",contactEmail:owner.email,ownerId:owner.id,status:"ACTIVE",sellerType:"PRIVATE",vatStatus:"NOT_REGISTERED_OR_NOT_APPLICABLE"}});
    const business=await db.sellerBusiness.create({data:{ownerId:owner.id,billingStoreId:store.id}});
    await db.store.update({where:{id:store.id},data:{businessId:business.id}});
    const create=(index:number)=>db.product.create({data:{storeId:store.id,name:"Fixture "+index,slug:"fixture-"+index,description:"Disposable fixture",price:10,category:"test",condition:"NEUF",images:["/fixture.png"],complianceDeclaredAt:new Date(),createdAt:new Date(Date.UTC(2026,0,index))}});
    for(let i=1;i<=7;i++)await create(i);
    const published=()=>db.product.findMany({where:{storeId:store.id,status:"PUBLISHED",...publicProductAccessWhere()},orderBy:{createdAt:"asc"}});
    assert.equal((await published()).length,5);
    assert.deepEqual((await published()).map(p=>p.slug),["fixture-1","fixture-2","fixture-3","fixture-4","fixture-5"]);
    const sub=await db.sellerSubscription.create({data:{storeId:store.id,plan:"pro",stripePriceId:"price_mock",status:"ACTIVE",currentPeriodEnd:new Date("2099-01-01")}});
    assert.equal((await published()).length,7);
    await db.sellerSubscription.update({where:{id:sub.id},data:{currentPeriodEnd:new Date(0)}});
    assert.equal((await published()).length,5,"expiry is enforced before worker cleanup");
    assert.equal((await enforceSellerPublicationCapacity(db,store.id,business.id)).count,2);
    assert.equal(await db.product.count({where:{storeId:store.id}}),7);
    assert.equal(await db.product.count({where:{storeId:store.id,status:"DRAFT",deactivationReason:"SUBSCRIPTION_INACTIVE"}}),2);
    await db.sellerSubscription.update({where:{id:sub.id},data:{currentPeriodEnd:new Date("2099-01-01")}});
    assert.equal((await published()).length,5,"renewal never blindly republishes demoted products");
    await db.product.updateMany({where:{storeId:store.id},data:{status:"DRAFT"}});
    await db.sellerSubscription.update({where:{id:sub.id},data:{status:"CANCELED"}});
    const rows=await db.product.findMany({where:{storeId:store.id},orderBy:{createdAt:"asc"}});
    for(const p of rows.slice(0,4))await db.product.update({where:{id:p.id},data:{status:"PUBLISHED",deactivationReason:"NONE"}});
    const publish=(productId:string)=>db.$transaction(async tx=>{
      await lockSellerProductQuota(tx,store.id);
      await requireStorePublishingAccess(tx,owner.id,store.id,"PRODUCT_PUBLISH",productId);
      return tx.product.update({where:{id:productId},data:{status:"PUBLISHED",deactivationReason:"NONE"}});
    });
    const results=await Promise.allSettled([publish(rows[4].id),publish(rows[5].id)]);
    assert.equal(results.filter(r=>r.status==="fulfilled").length,1);
    assert.equal((await published()).length,5);
    await assert.rejects(()=>requireStorePublishingAccess(db,owner.id,store.id,"PRODUCT_CREATE"),(e:any)=>e.code==="SELLER_PRODUCT_LIMIT_REACHED");
    await db.product.update({where:{id:rows[0].id},data:{status:"DRAFT"}});
    await publish(rows[6].id);assert.equal((await published()).length,5);
    const ranks=await db.product.findMany({where:{storeId:store.id,status:"PUBLISHED"},orderBy:{createdAt:"asc"}});
    assert.deepEqual(ranks.map(p=>p.freeVisibilityPosition),[1,2,3,4,5]);
    // Existing publication can be edited at capacity; excluding its own ID is authoritative.
    await requireStorePublishingAccess(db,owner.id,store.id,"PRODUCT_PUBLISH",ranks[0].id);
    await db.store.update({where:{id:store.id},data:{status:"SUSPENDED"}});
    assert.equal((await published()).length,0);
    await db.store.update({where:{id:store.id},data:{status:"ACTIVE"}});
    await db.user.update({where:{id:owner.id},data:{sellerSuspendedAt:new Date()}});
    assert.equal((await published()).length,0);
    assert.equal(await db.product.count({where:{storeId:store.id}}),7);
    assert.equal(await db.order.count(),0);assert.equal(await db.sellerSubscriptionChange.count(),0);
    // Exercise the actual PostgreSQL feed predicates, not merely a mocked source shape.
    await db.user.update({where:{id:owner.id},data:{sellerSuspendedAt:null}});
    await db.product.updateMany({where:{storeId:store.id},data:{status:"PUBLISHED",deactivationReason:"NONE",stock:1}});
    const discovery=()=>proHomepageDiscovery(db,{id:true,storeId:true});
    assert.equal((await discovery()).length,0,"FREE never receives PRO discovery");
    await db.sellerSubscription.update({where:{id:sub.id},data:{status:"ACTIVE",plan:"plus",currentPeriodEnd:new Date("2099-01-01")}});
    assert.equal((await discovery()).length,0,"PLUS never receives PRO discovery");
    await db.sellerSubscription.update({where:{id:sub.id},data:{plan:"pro"}});
    assert.equal((await discovery()).length,5,"PRO is capped at five per store");
    await db.product.update({where:{id:rows[0].id},data:{stock:0}});
    await db.product.update({where:{id:rows[1].id},data:{deactivationReason:"ADMIN"}});
    await db.product.update({where:{id:rows[2].id},data:{removedAt:new Date()}});
    const eligible=await discovery();
    assert.equal(eligible.length,4);
    for(const excluded of rows.slice(0,3))assert.ok(!eligible.some(p=>p.id===excluded.id));
    await db.sellerSubscription.update({where:{id:sub.id},data:{status:"CANCELED"}});
    await db.storeAccessGrant.create({data:{storeId:store.id,source:"ADMIN_GRANTED",plan:"pro",startsAt:new Date(0),endsAt:new Date("2099-01-01"),grantedById:owner.id}});
    assert.equal((await discovery()).length,4,"Admin-granted PRO retains discovery");
    await db.storeAccessGrant.deleteMany({where:{storeId:store.id}});
    await db.user.update({where:{id:owner.id},data:{role:"ADMIN"}});
    assert.equal((await discovery()).length,4,"Admin exemption retains PRO capability without billing");
    await db.store.update({where:{id:store.id},data:{status:"SUSPENDED"}});
    assert.equal((await discovery()).length,0,"suspended stores are never promoted");
  }finally{await db.$disconnect();}
});
