import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { locales } from "../i18n/config";
import { sellerReviewMessages } from "../i18n/seller-review";
import { reviewSellerOnboarding, SellerReviewError } from "../lib/seller-onboarding-review";

const validStore={id:"store",businessId:"business",status:"PENDING",onboardingStatus:"PENDING_REVIEW",onboardingStep:4,country:"FR",sellerType:"PRIVATE",sellerLegalForm:"PRIVATE",companySubtype:null,businessRegistrationId:null,legalBusinessName:null,businessAddress:"1 rue",businessPostalCode:"75001",vatStatus:"NOT_REGISTERED_OR_NOT_APPLICABLE",vatNumber:null,owner:{id:"seller",role:"SELLER",emailVerified:true}};
function database(store={...validStore}){const updates:any[]=[],audits:any[]=[],events:any[]=[];return{db:{store:{findUnique:async()=>store,update:async(input:any)=>{updates.push(input);return{};}},sellerBusinessAuditEvent:{create:async(input:any)=>{audits.push(input);return{};}},accountSecurityEvent:{create:async(input:any)=>{events.push(input);return{};}}}as never,updates,audits,events};}

test("Admin verification validates, activates, and audits without fabricating entitlement",async()=>{const state=database();const result=await reviewSellerOnboarding(state.db,{storeId:"store",adminId:"admin",decision:"VERIFIED",reason:"Identity reviewed"});assert.deepEqual(result,{changed:true,status:"VERIFIED"});assert.equal(state.updates[0].data.status,"ACTIVE");assert.equal(state.updates[0].data.onboardingStatus,"VERIFIED");assert.equal(state.audits[0].data.action,"SELLER_VERIFIED");assert.equal(state.events.length,1);assert.equal("subscription" in state.updates[0].data,false);});
test("invalid or incomplete seller verification fails closed",async()=>{const state=database({...validStore,onboardingStep:3});await assert.rejects(()=>reviewSellerOnboarding(state.db,{storeId:"store",adminId:"admin",decision:"VERIFIED",reason:"review"}),(error:unknown)=>error instanceof SellerReviewError&&error.code==="SELLER_PREREQUISITES_INCOMPLETE");assert.equal(state.updates.length,0);});
test("repeated completed approval is idempotent and creates no duplicate audit",async()=>{const state=database({...validStore,status:"ACTIVE",onboardingStatus:"VERIFIED"});assert.deepEqual(await reviewSellerOnboarding(state.db,{storeId:"store",adminId:"admin",decision:"VERIFIED",reason:"repeat"}),{changed:false,status:"VERIFIED"});assert.equal(state.updates.length,0);assert.equal(state.audits.length,0);});
test("Admin review remains discoverable, localized, and RTL-aware",()=>{for(const locale of locales){const copy=sellerReviewMessages[locale];for(const value of Object.values(copy))assert.ok(value.trim(),`${locale} review copy`);}const admin=readFileSync(join(process.cwd(),"app/adm-barewbar-182203/page.tsx"),"utf8"),page=readFileSync(join(process.cwd(),"app/adm-barewbar-182203/seller-review/page.tsx"),"utf8"),actions=readFileSync(join(process.cwd(),"app/adm-barewbar-182203/seller-review/SellerReviewActions.tsx"),"utf8");assert.match(admin,/seller-review/);assert.match(page,/rtlLocales\.has\(locale\)/);assert.match(actions,/role="status"/);assert.doesNotMatch(actions,/>Verify<|>Reject<|placeholder="Review reason"/);});
