"use client";
import {FormEvent,useState} from "react";
import {useLocale,useTranslations} from "next-intl";
import LocalizedCountrySelect from "@/components/LocalizedCountrySelect";
import SocialLoginButtons from "@/components/SocialLoginButtons";
type Profile={firstName:string;lastName:string;email:string;phone:string|null;profileAddress:string|null;profilePostalCode:string|null;profileCity:string|null;profileCountry:string|null;emailVerified:boolean;hasPassword:boolean;providers:string[]};
const providers=["google","apple","facebook"] as const;
export default function AccountSettings({profile}:{profile:Profile}){
 const t=useTranslations("Auth"),locale=useLocale(),[message,setMessage]=useState(""),[country,setCountry]=useState(profile.profileCountry??"");
 const providerLabel=(provider:typeof providers[number])=>t(`continueWith.${provider}`);
 async function submit(event:FormEvent<HTMLFormElement>,url:string){event.preventDefault();const form=new FormData(event.currentTarget);return fetch(url,{method:url==="/api/account/profile"?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...Object.fromEntries(form),...(url.includes("email")?{locale}:{})})})}
 async function profileSubmit(event:FormEvent<HTMLFormElement>){const response=await submit(event,"/api/account/profile");setMessage(response.ok?t("saved"):t("error"))}
 async function passwordSubmit(event:FormEvent<HTMLFormElement>){const response=await submit(event,"/api/account/password");if(response.ok)location.assign(`/${locale}/login`);else setMessage(t("error"))}
 async function emailSubmit(event:FormEvent<HTMLFormElement>){const response=await submit(event,"/api/account/email/request");setMessage(response.ok?t("emailChangeSent"):t("error"))}
 async function unlinkProvider(provider:string){const response=await fetch(`/api/account/providers/${provider}`,{method:"DELETE"});if(response.ok)location.reload();else setMessage(t("error"))}
 return <main className="accountSettingsPage"><div className="accountSettingsShell"><header><h1>{t("accountSettings")}</h1><p>{t("accountSettingsIntro")}</p></header>{message&&<p className="authMessage" role="status">{message}</p>}
 <section className="accountSettingsCard"><h2>{t("profile")}</h2><form className="authForm" onSubmit={profileSubmit}><div className="formRow"><div className="formField"><label htmlFor="firstName">{t("firstName")}</label><input id="firstName" name="firstName" defaultValue={profile.firstName} autoComplete="given-name" required/></div><div className="formField"><label htmlFor="lastName">{t("lastName")}</label><input id="lastName" name="lastName" defaultValue={profile.lastName} autoComplete="family-name" required/></div></div><div className="formField"><label htmlFor="phone">{t("phone")}</label><input id="phone" name="phone" defaultValue={profile.phone??""} autoComplete="tel"/></div><div className="formField"><label htmlFor="profileAddress">{t("address")}</label><input id="profileAddress" name="profileAddress" defaultValue={profile.profileAddress??""} autoComplete="street-address"/></div><div className="formRow"><div className="formField"><label htmlFor="profilePostalCode">{t("postalCode")}</label><input id="profilePostalCode" name="profilePostalCode" defaultValue={profile.profilePostalCode??""} autoComplete="postal-code"/></div><div className="formField"><label htmlFor="profileCity">{t("city")}</label><input id="profileCity" name="profileCity" defaultValue={profile.profileCity??""} autoComplete="address-level2"/></div></div><LocalizedCountrySelect id="profileCountry" value={country} onChange={setCountry} label={t("country")} placeholder={t("selectCountry")}/><button className="authSubmit">{t("save")}</button></form></section>
 <section className="accountSettingsCard"><h2>{t("security")}</h2><p>{profile.email} · {profile.emailVerified?t("verified"):t("notVerified")}</p><h3>{t("linkedProviders")}</h3><div className="linkedProviders">{providers.map(provider=>{const linked=profile.providers.includes(provider.toUpperCase());return <div key={provider}><span>{providerLabel(provider)}</span>{linked?<button type="button" onClick={()=>unlinkProvider(provider)}>{t("unlink")}</button>:<b>{t("notLinked")}</b>}</div>})}</div><SocialLoginButtons/>
 {profile.hasPassword&&<><h3>{t("changePassword")}</h3><form className="authForm" onSubmit={passwordSubmit}><div className="formField"><label htmlFor="currentPassword">{t("currentPassword")}</label><input id="currentPassword" name="currentPassword" type="password" autoComplete="current-password" required/></div><div className="formField"><label htmlFor="newPassword">{t("newPassword")}</label><input id="newPassword" name="newPassword" type="password" minLength={10} autoComplete="new-password" required/></div><div className="formField"><label htmlFor="passwordConfirm">{t("confirmPassword")}</label><input id="passwordConfirm" name="confirmPassword" type="password" minLength={10} autoComplete="new-password" required/></div><button className="authSubmit">{t("changePassword")}</button></form><h3>{t("changeEmail")}</h3><form className="authForm" onSubmit={emailSubmit}><div className="formField"><label htmlFor="newEmail">{t("newEmail")}</label><input id="newEmail" name="newEmail" type="email" autoComplete="email" required/></div><div className="formField"><label htmlFor="emailPassword">{t("currentPassword")}</label><input id="emailPassword" name="currentPassword" type="password" autoComplete="current-password" required/></div><button className="authSubmit">{t("changeEmail")}</button></form></>}</section></div></main>;
}
