"use client";
import {FormEvent,useState} from "react";
import {useLocale,useTranslations} from "next-intl";
import Link from "next/link";
import {Bell} from "lucide-react";
import LocalizedCountrySelect from "@/components/LocalizedCountrySelect";
import {isLocale} from "@/i18n/config";
import {emailVerificationCopy} from "@/i18n/email-verification";
import EmailVerificationNotice from "@/components/EmailVerificationNotice";
type Profile={firstName:string;lastName:string;email:string;phone:string|null;profileAddress:string|null;profilePostalCode:string|null;profileCity:string|null;profileCountry:string|null;emailVerified:boolean;hasPassword:boolean;providers:string[]};
type BuyerAddress={recipientName:string;addressLine1:string;addressLine2:string|null;postalCode:string;city:string;country:string;state:string|null;phone:string|null;isDefault:boolean};
const providers=["google","apple","facebook"] as const;
export default function AccountSettings({profile,isBuyer,defaultAddress}:{profile:Profile;isBuyer:boolean;defaultAddress:BuyerAddress|null}){
 const t=useTranslations("Auth"),dashboard=useTranslations("DashboardPremium"),locale=useLocale(),safeLocale=isLocale(locale)?locale:"en",verification=emailVerificationCopy[safeLocale],[message,setMessage]=useState(""),[country,setCountry]=useState(profile.profileCountry??"");
 const providerLabel=(provider:typeof providers[number])=>t(`continueWith.${provider}`);
 async function submit(event:FormEvent<HTMLFormElement>,url:string){event.preventDefault();const form=new FormData(event.currentTarget),values=Object.fromEntries(form);return fetch(url,{method:url==="/api/account/profile"?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(url.includes("email")?{newEmail:form.get("requestedEmailChange"),currentPassword:form.get("currentPassword"),locale}:values)})}
 async function profileSubmit(event:FormEvent<HTMLFormElement>){const response=await submit(event,"/api/account/profile");setMessage(response.ok?t("saved"):t("error"))}
 async function passwordSubmit(event:FormEvent<HTMLFormElement>){const response=await submit(event,"/api/account/password");if(response.ok)location.assign(`/${locale}/login`);else setMessage(t("error"))}
 async function emailSubmit(event:FormEvent<HTMLFormElement>){const response=await submit(event,"/api/account/email/request");setMessage(response.ok?t("emailChangeSent"):t("error"))}
 async function unlinkProvider(provider:string){const response=await fetch(`/api/account/providers/${provider}`,{method:"DELETE"});if(response.ok)location.reload();else setMessage(t("error"))}
 return <section className="accountSettingsPage"><div className="accountSettingsShell"><header><h1>{t("accountSettings")}</h1><p>{t("accountSettingsIntro")}</p><nav className="accountSettingsNavigation" aria-label={t("accountSettings")}><Link href={`/${locale}/notifications`}><Bell size={19} aria-hidden="true"/><span>{dashboard("notifications")}</span></Link></nav></header>{message&&<p className="authMessage" role="status">{message}</p>}
 <section className="accountSettingsCard"><h2>{t("profile")}</h2><form className="authForm" onSubmit={profileSubmit}><div className="formRow"><div className="formField"><label htmlFor="firstName">{t("firstName")}</label><input id="firstName" name="firstName" defaultValue={profile.firstName} autoComplete="given-name" required/></div><div className="formField"><label htmlFor="lastName">{t("lastName")}</label><input id="lastName" name="lastName" defaultValue={profile.lastName} autoComplete="family-name" required/></div></div>{!isBuyer&&<><div className="formField"><label htmlFor="phone">{t("phone")}</label><input id="phone" name="phone" defaultValue={profile.phone??""} autoComplete="tel"/></div><div className="formField"><label htmlFor="profileAddress">{t("address")}</label><input id="profileAddress" name="profileAddress" defaultValue={profile.profileAddress??""} autoComplete="street-address"/></div><div className="formRow"><div className="formField"><label htmlFor="profilePostalCode">{t("postalCode")}</label><input id="profilePostalCode" name="profilePostalCode" defaultValue={profile.profilePostalCode??""} autoComplete="postal-code"/></div><div className="formField"><label htmlFor="profileCity">{t("city")}</label><input id="profileCity" name="profileCity" defaultValue={profile.profileCity??""} autoComplete="address-level2"/></div></div><LocalizedCountrySelect id="profileCountry" value={country} onChange={setCountry} label={t("country")} placeholder={t("selectCountry")}/></>}<button className="authSubmit">{t("save")}</button></form>{isBuyer&&<div className="accountDefaultAddress"><h3>{t("address")}</h3>{defaultAddress?<address><strong>{defaultAddress.recipientName}</strong><span>{defaultAddress.addressLine1}{defaultAddress.addressLine2?`, ${defaultAddress.addressLine2}`:""}</span><span>{defaultAddress.postalCode} {defaultAddress.city}</span>{defaultAddress.state&&<span>{defaultAddress.state}</span>}<span>{new Intl.DisplayNames(locale,{type:"region"}).of(defaultAddress.country)??defaultAddress.country}</span>{defaultAddress.phone&&<span>{t("phone")}: {defaultAddress.phone}</span>}</address>:<p>{t("noSavedAddresses")}</p>}<Link href={`/${locale}/account/addresses`}>{t("addresses")}</Link></div>}</section>
 <section className="accountSettingsCard"><h2>{t("security")}</h2><p className="accountCurrentEmail"><strong>{verification.emailAddress}</strong><span>{profile.email}</span><small>{profile.emailVerified?verification.verified:verification.unverified}</small></p>{!profile.emailVerified&&<EmailVerificationNotice email={profile.email} locale={safeLocale}/>}<h3>{t("linkedProviders")}</h3><div className="linkedProviders">{providers.map(provider=>{const linked=profile.providers.includes(provider.toUpperCase());return <div key={provider}><span>{providerLabel(provider)}</span>{linked?<button type="button" onClick={()=>unlinkProvider(provider)}>{t("unlink")}</button>:<b>{t("notLinked")}</b>}</div>})}</div>
 {profile.hasPassword&&<><h3>{t("changePassword")}</h3><form className="authForm" onSubmit={passwordSubmit}><div className="formField"><label htmlFor="currentPassword">{t("currentPassword")}</label><input id="currentPassword" name="currentPassword" type="password" autoComplete="current-password" required/></div><div className="formField"><label htmlFor="newPassword">{t("newPassword")}</label><input id="newPassword" name="newPassword" type="password" minLength={10} autoComplete="new-password" required/></div><div className="formField"><label htmlFor="passwordConfirm">{t("confirmPassword")}</label><input id="passwordConfirm" name="confirmPassword" type="password" minLength={10} autoComplete="new-password" required/></div><button className="authSubmit">{t("changePassword")}</button></form><h3>{t("changeEmail")}</h3><form className="authForm" onSubmit={emailSubmit} autoComplete="off"><div className="formField"><label htmlFor="requestedEmailChange">{t("newEmail")}</label><input id="requestedEmailChange" name="requestedEmailChange" type="email" autoComplete="off" defaultValue="" autoCapitalize="none" spellCheck={false} required/></div><div className="formField"><label htmlFor="emailPassword">{t("currentPassword")}</label><input id="emailPassword" name="currentPassword" type="password" autoComplete="current-password" required/></div><button className="authSubmit">{t("changeEmail")}</button></form></>}</section></div></section>;
}
