"use client";

import { useRef, useState } from "react";
import { useLocale } from "next-intl";
import { useRouter } from "next/navigation";
import { adminUserManagementMessages } from "@/i18n/admin-user-management";
import { isLocale } from "@/i18n/config";

type Action="BLOCK"|"UNBLOCK"|"SELLER_SUSPEND"|"SELLER_RESTORE"|"ANONYMIZE"|"DELETE";
type Props={userId:string;isProtected:boolean;isBlocked:boolean;isSeller:boolean;isSellerSuspended:boolean;isAnonymized:boolean};
type Preview={hardDeleteSafe:boolean;productCount:number;orderCount:number;blockers:string[]};
const errorKeys:Record<string,"reasonRequired"|"invalidExpiry"|"forbidden"|"failed">={REASON_REQUIRED:"reasonRequired",INVALID_BLOCK_EXPIRY:"invalidExpiry",SELF_ACTION_FORBIDDEN:"forbidden",LAST_ADMIN_PROTECTED:"forbidden",ADMIN_REQUIRED:"forbidden",ACCOUNT_DEACTIVATED:"forbidden",HARD_DELETE_UNSAFE:"forbidden"};
const deleteCopy=(locale:string)=>locale==="fr"?{button:"Supprimer définitivement",title:"Suppression définitive",safe:"Ce compte peut être supprimé définitivement. La boutique et ses produits seront supprimés avec lui.",unsafe:"Ce compte contient des données protégées. Utilisez plutôt Désactiver / anonymiser.",confirm:"Je comprends que cette suppression est irréversible."}:locale==="ku"?{button:"سڕینەوەی هەمیشەیی",title:"سڕینەوەی هەمیشەیی",safe:"ئەم هەژمارە دەتوانرێت بە تەواوی بسڕدرێتەوە؛ دوکان و کاڵاکانیشی لەگەڵیدا دەسڕدرێنەوە.",unsafe:"ئەم هەژمارە تۆماری پارێزراوی هەیە؛ ناسنامەسڕینەوە بەکاربهێنە.",confirm:"تێگەیشتم کە ئەم سڕینەوەیە ناگەڕێتەوە."}:{button:"Delete permanently",title:"Permanent deletion",safe:"This account can be permanently deleted. Its store and products will be removed too.",unsafe:"Protected records prevent permanent deletion. Use deactivate/anonymize instead.",confirm:"I understand this deletion cannot be undone."};

export default function AdminUserActions({userId,isProtected,isBlocked,isSeller,isSellerSuspended,isAnonymized}:Props){
  const locale=useLocale(),labels=adminUserManagementMessages[isLocale(locale)?locale:"en"],del=deleteCopy(locale),router=useRouter(),dialog=useRef<HTMLDialogElement>(null);
  const[action,setAction]=useState<Action>("BLOCK"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[feedback,setFeedback]=useState(""),[preview,setPreview]=useState<Preview|null>(null);
  if(isProtected)return <p className="adminUserProtectedAction" title={labels.protectedAction}>{labels.protectedAction}</p>;
  const open=async(next:Action)=>{setAction(next);setError("");setFeedback("");setPreview(null);dialog.current?.showModal();if(next==="DELETE")try{const response=await fetch(`/api/admin/users/${userId}`,{cache:"no-store"}),data=await response.json();if(response.ok)setPreview(data);else setError(labels.failed)}catch{setError(labels.failed)}};
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;setBusy(true);setError("");try{const form=new FormData(event.currentTarget),response=action==="DELETE"?await fetch(`/api/admin/users/${userId}`,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({confirmation:"DELETE"})}):await fetch(`/api/admin/users/${userId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,reason:form.get("reason"),blockExpiresAt:form.get("blockExpiresAt")})}),data=await response.json();if(!response.ok){setError(labels[errorKeys[data.error]??"failed"]);return}dialog.current?.close();setFeedback(action==="DELETE"?del.button:labels.success);router.refresh()}catch{setError(labels.failed)}finally{setBusy(false)}}
  return <div className="adminUserActionRegion"><div className="adminUserActions" aria-label={labels.actionLabel}>{!isAnonymized&&<><button type="button" onClick={()=>open(isBlocked?"UNBLOCK":"BLOCK")}>{labels[isBlocked?"UNBLOCK":"BLOCK"]}</button>{isSeller&&<button type="button" onClick={()=>open(isSellerSuspended?"SELLER_RESTORE":"SELLER_SUSPEND")}>{labels[isSellerSuspended?"SELLER_RESTORE":"SELLER_SUSPEND"]}</button>}<button type="button" className="isDanger" onClick={()=>open("ANONYMIZE")}>{labels.ANONYMIZE}</button></>}<button type="button" className="isDanger" onClick={()=>open("DELETE")}>{del.button}</button></div>{feedback&&<p className="adminUserActionFeedback" role="status">{feedback}</p>}<dialog ref={dialog} className="adminUserDialog" onCancel={()=>setError("")}><form onSubmit={submit}><h2>{action==="DELETE"?del.title:labels[action as Exclude<Action,"DELETE">]}</h2>{action==="DELETE"?<><p>{preview?(preview.hardDeleteSafe?del.safe:del.unsafe):labels.working}</p>{preview&&<p>{preview.productCount} products · {preview.orderCount} orders</p>}{preview?.hardDeleteSafe&&<label className="adminConfirmCheck"><input type="checkbox" required/>{del.confirm}</label>}</>:<><p>{labels.auditNotice}</p><label>{labels.reason}<textarea name="reason" minLength={10} maxLength={1000} required autoFocus/></label>{action==="BLOCK"&&<label>{labels.expiry}<input name="blockExpiresAt" type="datetime-local"/></label>}{action==="ANONYMIZE"&&<label className="adminConfirmCheck"><input type="checkbox" required/>{labels.anonymizeConfirm}</label>}</>}{error&&<p role="alert">{error}</p>}<div><button type="button" onClick={()=>dialog.current?.close()} disabled={busy}>{labels.cancel}</button><button type="submit" disabled={busy||action==="DELETE"&&!preview?.hardDeleteSafe}>{busy?labels.working:labels.confirm}</button></div></form></dialog></div>;
}
