"use client";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { adminUserManagementMessages, type AdminUserManagementMessages } from "@/i18n/admin-user-management";
type Action="BLOCK"|"UNBLOCK"|"SELLER_SUSPEND"|"SELLER_RESTORE"|"ANONYMIZE";
type Props={userId:string;isSelf:boolean;isBlocked:boolean;isSeller:boolean;isSellerSuspended:boolean;isAnonymized:boolean;labels?:AdminUserManagementMessages};
export default function AdminUserActions({userId,isSelf,isBlocked,isSeller,isSellerSuspended,isAnonymized,labels=adminUserManagementMessages.en}:Props){
 const router=useRouter(),dialog=useRef<HTMLDialogElement>(null),[action,setAction]=useState<Action>("BLOCK"),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const open=(next:Action)=>{setAction(next);setError("");dialog.current?.showModal()};
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;setBusy(true);setError("");try{const form=new FormData(event.currentTarget),response=await fetch(`/api/admin/users/${userId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,reason:form.get("reason"),blockExpiresAt:form.get("blockExpiresAt")})}),data=await response.json();if(!response.ok){setError(data.error??labels.failed);return}dialog.current?.close();router.refresh()}finally{setBusy(false)}}
 return <div className="adminUserActions" aria-label={labels.actionLabel}><button type="button" disabled={isSelf||isAnonymized} onClick={()=>open(isBlocked?"UNBLOCK":"BLOCK")}>{labels[isBlocked?"UNBLOCK":"BLOCK"]}</button>{isSeller&&<button type="button" disabled={isSelf||isAnonymized} onClick={()=>open(isSellerSuspended?"SELLER_RESTORE":"SELLER_SUSPEND")}>{labels[isSellerSuspended?"SELLER_RESTORE":"SELLER_SUSPEND"]}</button>}<button type="button" className="isDanger" disabled={isSelf||isAnonymized} onClick={()=>open("ANONYMIZE")}>{labels.ANONYMIZE}</button><dialog ref={dialog} className="adminUserDialog" onCancel={()=>setError("")}><form onSubmit={submit}><h2>{labels[action]}</h2><p>{labels.auditNotice}</p><label>{labels.reason}<textarea name="reason" minLength={10} maxLength={1000} required autoFocus/></label>{action==="BLOCK"&&<label>{labels.expiry}<input name="blockExpiresAt" type="datetime-local"/></label>}{action==="ANONYMIZE"&&<label className="adminConfirmCheck"><input type="checkbox" required/>{labels.anonymizeConfirm}</label>}{error&&<p role="alert">{error}</p>}<div><button type="button" onClick={()=>dialog.current?.close()} disabled={busy}>{labels.cancel}</button><button type="submit" disabled={busy}>{busy?labels.working:labels.confirm}</button></div></form></dialog></div>;
}
