"use client";
import { useEffect, useState } from "react";
import { locales, type Locale } from "@/i18n/config";

type Product={id:string;name:string;state:string};
type Job={id:string;status:string;targetLocales:string[];requestedItemCount:number;estimatedCharacters:string;counts:Record<string,number>;lastErrorCode?:string|null;items:Array<{id:string;status:string;attemptCount:number;lastErrorCode:string|null;lastErrorMessage:string|null;product:{name:string}}>};
type Preview={eligibleCount:number;skippedCount:number;estimatedCharacters:number;providerReady:boolean;withinJobLimit:boolean;withinItemLimit:boolean;dailyRemaining:number|null;monthlyRemaining:number|null};
const mutationHeaders={"Content-Type":"application/json","x-todijo-admin-action":"1"};

export default function AdminTranslationCenter({products,initialLocale="fr"}:{products:Product[];initialLocale?:Locale}){
  const[targetLocale,setTargetLocale]=useState<Locale>(initialLocale),[selected,setSelected]=useState<string[]>([]),[preview,setPreview]=useState<Preview|null>(null),[jobs,setJobs]=useState<Job[]>([]),[configuration,setConfiguration]=useState<{enabled:boolean;ready:boolean;errorCode?:string}|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  async function load(){const response=await fetch("/api/admin/catalog-translations",{cache:"no-store"}),body=await response.json();if(response.ok){setJobs(body.jobs);setConfiguration(body.configuration);}}
  useEffect(()=>{void load();},[]);
  function preset(count:number){setSelected(products.filter(product=>["MISSING","STALE"].includes(product.state)).slice(0,count).map(product=>product.id));setPreview(null);}
  function toggle(id:string){setSelected(value=>value.includes(id)?value.filter(item=>item!==id):[...value,id]);setPreview(null);}
  async function action(kind:"preview"|"enqueue"){if(!selected.length)return setMessage("Choose at least one bounded product.");setBusy(true);setMessage("");try{const response=await fetch(kind==="preview"?"/api/admin/catalog-translations/preview":"/api/admin/catalog-translations",{method:"POST",headers:kind==="enqueue"?mutationHeaders:{"Content-Type":"application/json"},body:JSON.stringify({productIds:selected,targetLocale})}),body=await response.json();if(!response.ok)throw new Error(body.error??"TRANSLATION_ACTION_FAILED");if(kind==="preview")setPreview(body.preview);else{setMessage(`Queued ${body.job.requestedItemCount} ${targetLocale.toUpperCase()} proposals.`);setPreview(null);await load();}}catch(error){setMessage(error instanceof Error?error.message:"TRANSLATION_ACTION_FAILED");}finally{setBusy(false);}}
  async function jobAction(jobId:string,action:"pause"|"retry"){setBusy(true);try{const response=await fetch(`/api/admin/catalog-translations/${jobId}/${action}`,{method:"POST",headers:mutationHeaders,body:"{}"}),body=await response.json();if(!response.ok)throw new Error(body.error??"TRANSLATION_JOB_ACTION_FAILED");setMessage(action==="pause"?"Job paused.":`Retry queued for ${body.retried} items.`);await load();}catch(error){setMessage(error instanceof Error?error.message:"TRANSLATION_JOB_ACTION_FAILED");}finally{setBusy(false);}}
  return <section className="adminPanel" aria-labelledby="translation-center-title"><div className="adminPanelHeader"><div><h2 id="translation-center-title">Catalog translation center</h2><p>French pilot: start with 5 products, review every proposal, then expand to 20. Generated content stays private until approval.</p></div><span className={`adminBadge ${configuration?.ready?"success":"warning"}`}>{configuration?.ready?"PROVIDER READY":configuration?.enabled?"CONFIGURATION INCOMPLETE":"DISABLED"}</span></div>
    <div className="adminHeroActions"><label>One target locale <select value={targetLocale} onChange={event=>{setTargetLocale(event.target.value as Locale);setPreview(null);}}>{locales.map(item=><option key={item} value={item}>{item.toUpperCase()}{item==="fr"?" — pilot":""}</option>)}</select></label><button type="button" onClick={()=>preset(5)}>Select first 5</button><button type="button" onClick={()=>preset(20)}>Select first 20</button><button type="button" disabled={busy||!selected.length} onClick={()=>void action("preview")}>Preview estimate</button><button type="button" disabled={busy||!preview?.providerReady||!preview.withinJobLimit||!preview.withinItemLimit||preview.eligibleCount===0} onClick={()=>void action("enqueue")}>Enqueue bounded batch</button></div>
    <p role="status">Selected: {selected.length}. {message||configuration?.errorCode||"No translation runs from this page; the protected worker processes queued items."}</p>
    {preview&&<dl className="adminMetricGrid"><div><dt>Eligible</dt><dd>{preview.eligibleCount}</dd></div><div><dt>Skipped</dt><dd>{preview.skippedCount}</dd></div><div><dt>Estimated characters</dt><dd>{preview.estimatedCharacters.toLocaleString()}</dd></div><div><dt>Daily remaining</dt><dd>{preview.dailyRemaining?.toLocaleString()??"Unavailable"}</dd></div><div><dt>Monthly remaining</dt><dd>{preview.monthlyRemaining?.toLocaleString()??"Unavailable"}</dd></div></dl>}
    <details><summary>Choose products ({products.length} candidates)</summary><div className="adminCheckboxGrid">{products.map(product=><label key={product.id}><input type="checkbox" checked={selected.includes(product.id)} onChange={()=>toggle(product.id)}/><span>{product.name}</span><small>{product.state}</small></label>)}</div></details>
    <div className="adminTableWrap"><table><thead><tr><th>Job</th><th>Locale</th><th>Progress</th><th>Characters</th><th>Action</th></tr></thead><tbody>{jobs.map(job=><tr key={job.id}><td><strong>{job.status}</strong><small>{job.id}</small>{job.lastErrorCode&&<small>{job.lastErrorCode}</small>} {job.items.some(item=>item.lastErrorCode)&&<details><summary>Safe item errors</summary>{job.items.filter(item=>item.lastErrorCode).map(item=><small key={item.id}>{item.product.name}: {item.lastErrorCode} · attempt {item.attemptCount}{item.lastErrorMessage?` · ${item.lastErrorMessage}`:""}</small>)}</details>}</td><td>{job.targetLocales.join(", ").toUpperCase()}</td><td>{Object.entries(job.counts).map(([status,count])=><small key={status}>{status}: {count} </small>)}</td><td>{Number(job.estimatedCharacters).toLocaleString()}</td><td><button type="button" disabled={busy||!["QUEUED","RUNNING"].includes(job.status)} onClick={()=>void jobAction(job.id,"pause")}>Pause</button> <button type="button" disabled={busy} onClick={()=>void jobAction(job.id,"retry")}>Retry eligible</button></td></tr>)}</tbody></table></div>
  </section>;
}
