"use client";
import {FormEvent,useState} from "react";
import {useRouter} from "next/navigation";
import {locales} from "@/i18n/config";

type Article={id:string;locale:string;title:string;content:string;published:boolean;publishedAt:string|null;updatedAt:string};
const empty={id:"",locale:"en",title:"",content:"",published:false};
export default function NewsAdmin({articles,initialLocale}:{articles:Article[];initialLocale:string}){
  const router=useRouter(),[draft,setDraft]=useState({...empty,locale:initialLocale}),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  async function save(event:FormEvent){event.preventDefault();setBusy(true);setMessage("");try{const response=await fetch(draft.id?`/api/admin/news/${draft.id}`:"/api/admin/news",{method:draft.id?"PATCH":"POST",headers:{"Content-Type":"application/json","x-todijo-admin-action":"1"},body:JSON.stringify(draft)});if(!response.ok)throw new Error();setDraft({...empty,locale:initialLocale});setMessage("Enregistré.");router.refresh();}catch{setMessage("L’opération a échoué.")}finally{setBusy(false)}}
  async function remove(id:string){if(!confirm("Supprimer définitivement cette actualité ?"))return;setBusy(true);try{const response=await fetch(`/api/admin/news/${id}`,{method:"DELETE",headers:{"x-todijo-admin-action":"1"}});if(!response.ok)throw new Error();if(draft.id===id)setDraft({...empty,locale:initialLocale});router.refresh();}catch{setMessage("L’opération a échoué.")}finally{setBusy(false)}}
  return <div className="cmsEditorGrid"><form className="adminPanel adminForm cmsEditor" onSubmit={save}><label>Langue<select value={draft.locale} onChange={event=>setDraft({...draft,locale:event.target.value})}>{locales.map(locale=><option key={locale}>{locale}</option>)}</select></label><label>Titre<input required maxLength={180} value={draft.title} onChange={event=>setDraft({...draft,title:event.target.value})}/></label><label>Contenu<textarea required rows={16} maxLength={50000} value={draft.content} onChange={event=>setDraft({...draft,content:event.target.value})}/></label><label><input type="checkbox" checked={draft.published} onChange={event=>setDraft({...draft,published:event.target.checked})}/> Publié</label>{message&&<p role="status">{message}</p>}<div className="cmsEditorActions"><button disabled={busy}>{draft.id?"Mettre à jour":"Créer"}</button>{draft.id&&<button type="button" onClick={()=>setDraft({...empty,locale:initialLocale})}>Annuler</button>}</div></form><section className="adminPanel cmsHistory"><h2>Actualités</h2>{articles.map(article=><article key={article.id}><strong>{article.title}</strong><small>{article.locale} · {article.published?`Publié${article.publishedAt?` ${new Date(article.publishedAt).toLocaleDateString()}`:""}`:"Brouillon"}</small><div className="cmsEditorActions"><button type="button" disabled={busy} onClick={()=>setDraft({id:article.id,locale:article.locale,title:article.title,content:article.content,published:article.published})}>Modifier</button><button type="button" disabled={busy} onClick={()=>remove(article.id)}>Supprimer</button></div></article>)}{!articles.length&&<p>Aucune actualité.</p>}</section></div>;
}
