"use client";
import {useEffect,useRef,useState} from "react";
import {useTranslations} from "next-intl";
import type{ProductVideoInput}from "@/lib/product-media";

export default function ProductVideoManager({initialVideo=null,productId,onChange,onUploadingChange}:{initialVideo?:ProductVideoInput|null;productId?:string;onChange:(value:ProductVideoInput|null)=>void;onUploadingChange?:(value:boolean)=>void}){
 const t=useTranslations("ProductVideo"),input=useRef<HTMLInputElement>(null),[video,setVideo]=useState(initialVideo),[uploading,setUploading]=useState(false),[error,setError]=useState("");
 useEffect(()=>{if(!productId||initialVideo)return;let active=true;void fetch(`/api/products/${productId}/media`).then(response=>response.ok?response.json():null).then((data:{video?:ProductVideoInput|null}|null)=>{if(active&&data?.video){setVideo(data.video);onChange(data.video)}});return()=>{active=false}},[initialVideo,onChange,productId]);
 async function upload(file:File){const cloud=process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME,preset=process.env.NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET;if(!cloud||!preset){setError(t("configError"));return}setUploading(true);onUploadingChange?.(true);setError("");try{const body=new FormData();body.set("file",file);body.set("upload_preset",preset);body.set("folder","todijo/product-videos");const response=await fetch(`https://api.cloudinary.com/v1_1/${cloud}/video/upload`,{method:"POST",body});const data=await response.json()as{secure_url?:string;public_id?:string};if(!response.ok||!data.secure_url||!data.public_id)throw new Error();const next={url:data.secure_url,publicId:data.public_id,posterUrl:null};setVideo(next);onChange(next)}catch{setError(t("failed"))}finally{setUploading(false);onUploadingChange?.(false)}}
 return <div className="productVideoManager"><p>{t("help")}</p>{video?<><video src={video.url} controls preload="metadata"/><button type="button" className="sellerControlButton secondary" onClick={()=>{setVideo(null);onChange(null)}}>{t("remove")}</button></>:<><input ref={input} type="file" accept="video/mp4,video/webm" hidden onChange={event=>{const file=event.target.files?.[0];if(file)void upload(file)}}/><button type="button" className="sellerControlButton secondary" disabled={uploading} onClick={()=>input.current?.click()}>{uploading?t("uploading"):t("upload")}</button></>}{error&&<p role="alert">{error}</p>}</div>;
}
