"use client";
import { useMemo, useState } from "react";
import { useLocale, useTranslations } from "next-intl";
import { SellerFormField } from "@/components/SellerControlPanel";
import { SHIPPING_COUNTRY_CODES } from "@/lib/shipping-countries";

export type ShippingDraft={enabled:boolean;method:string;price:string;free:boolean;freeThreshold:string;minDays:string;maxDays:string;countries:string[];worldwide:boolean;postalCodes:string;carrier:string};
export const emptyShippingDraft:ShippingDraft={enabled:true,method:"",price:"",free:false,freeThreshold:"",minDays:"",maxDays:"",countries:[],worldwide:false,postalCodes:"",carrier:""};
export function shippingDraftPayload(value:ShippingDraft){return {shippingEnabled:value.enabled,shippingMethodName:value.method,shippingPrice:value.price,shippingFree:value.free,shippingFreeThreshold:value.freeThreshold,shippingMinDays:value.minDays,shippingMaxDays:value.maxDays,shippingCountries:value.countries,shippingWorldwide:value.worldwide,shippingPostalCodes:value.postalCodes.split(/[\n,;]+/).map(v=>v.trim()).filter(Boolean),shippingCarrier:value.carrier};}

export default function ShippingRuleFields({value,onChange,currency,allowDisable=true}:{value:ShippingDraft;onChange:(next:ShippingDraft)=>void;currency:string;allowDisable?:boolean}){
 const t=useTranslations("Shipping"),locale=useLocale(),[search,setSearch]=useState("");
 const display=useMemo(()=>new Intl.DisplayNames([locale],{type:"region"}),[locale]);
 const allOptions=useMemo(()=>SHIPPING_COUNTRY_CODES.map(code=>({code,name:display.of(code)??code})).sort((a,b)=>a.name.localeCompare(b.name,locale)),[display,locale]);
 const options=useMemo(()=>{const query=search.trim().toLocaleLowerCase(locale);return query?allOptions.filter(item=>item.name.toLocaleLowerCase(locale).includes(query)):allOptions},[allOptions,locale,search]);
 const selectedOptions=useMemo(()=>value.countries.map(code=>({code,name:display.of(code)??code})).sort((a,b)=>a.name.localeCompare(b.name,locale)),[display,locale,value.countries]);
 const set=<K extends keyof ShippingDraft>(key:K,next:ShippingDraft[K])=>onChange({...value,[key]:next});
 return <div className="shippingRuleFields">
  {allowDisable&&<label className="shippingToggle"><input type="checkbox" checked={value.enabled} onChange={e=>set("enabled",e.target.checked)}/><span><strong>{t("enabled")}</strong><small>{value.enabled?t("enabledHelp"):t("disabledHelp")}</small></span></label>}
  {value.enabled&&<>
   <div className="sellerControlFieldGrid"><SellerFormField label={t("method")} htmlFor="shippingMethodName" required><input id="shippingMethodName" value={value.method} onChange={e=>set("method",e.target.value)} maxLength={80} required/></SellerFormField><SellerFormField label={t("carrier")} htmlFor="shippingCarrier" hint={t("carrierHelp")}><input id="shippingCarrier" value={value.carrier} onChange={e=>set("carrier",e.target.value)} maxLength={80}/></SellerFormField></div>
   <div className="shippingChoiceRow"><label><input type="radio" checked={!value.worldwide} onChange={()=>set("worldwide",false)}/>{t("selectedDestinations")}</label><label><input type="radio" checked={value.worldwide} onChange={()=>set("worldwide",true)}/>{t("worldwide")}</label></div>
   {value.worldwide?<p className="countryWorldwideNotice">{t("worldwideHelp")}</p>:<div className="countryPicker"><label className="countrySearchLabel" htmlFor="shipping-country-search">{t("searchCountries")}<input id="shipping-country-search" type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder={t("searchCountries")} autoComplete="off"/></label><div className="countryPickerToolbar"><strong>{t("selectedDestinationsCount",{count:value.countries.length})}</strong><div><button type="button" onClick={()=>set("countries",SHIPPING_COUNTRY_CODES)}>{t("selectAll")}</button><button type="button" onClick={()=>set("countries",[])} disabled={!value.countries.length}>{t("clearCountries")}</button></div></div>{selectedOptions.length>0&&<div className="countryChips" aria-label={t("selectedDestinationsCount",{count:value.countries.length})}>{selectedOptions.slice(0,6).map(item=><button type="button" key={item.code} onClick={()=>set("countries",value.countries.filter(v=>v!==item.code))} aria-label={`${item.name} ×`}>{item.name} ×</button>)}{selectedOptions.length>6&&<span>+{selectedOptions.length-6}</span>}</div>}<div className="countryPickerOptions" role="group" aria-label={t("searchCountries")}>{options.map(item=><label key={item.code} className={value.countries.includes(item.code)?"isSelected":undefined}><input type="checkbox" checked={value.countries.includes(item.code)} onChange={e=>set("countries",e.target.checked?[...value.countries,item.code]:value.countries.filter(code=>code!==item.code))}/><span>{item.name}</span></label>)}{!options.length&&<p className="countryNoResults">{t("noCountryResults")}</p>}</div></div>}
   <SellerFormField label={t("postalZones")} htmlFor="shippingPostalCodes" hint={t("postalZonesHelp")}><textarea id="shippingPostalCodes" rows={3} value={value.postalCodes} onChange={e=>set("postalCodes",e.target.value)} placeholder="59000, 59100, 59*"/></SellerFormField>
   <div className="shippingChoiceRow"><label><input type="radio" checked={!value.free} onChange={()=>set("free",false)}/>{t("paidShipping")}</label><label><input type="radio" checked={value.free} onChange={()=>set("free",true)}/>{t("alwaysFree")}</label></div>
   <div className="sellerControlFieldGrid">{!value.free&&<SellerFormField label={t("price")} htmlFor="shippingPrice" required><input id="shippingPrice" type="number" min="0" step="0.01" value={value.price} onChange={e=>set("price",e.target.value)} required/></SellerFormField>}<SellerFormField label={t("freeThreshold",{currency})} htmlFor="shippingFreeThreshold" hint={t("freeThresholdHelp")}><input id="shippingFreeThreshold" type="number" min="0" step="0.01" value={value.freeThreshold} onChange={e=>set("freeThreshold",e.target.value)}/></SellerFormField></div>
   <div className="sellerControlFieldGrid"><SellerFormField label={t("minDays")} htmlFor="shippingMinDays" required><input id="shippingMinDays" type="number" min="1" max="365" value={value.minDays} onChange={e=>set("minDays",e.target.value)} required/></SellerFormField><SellerFormField label={t("maxDays")} htmlFor="shippingMaxDays" required><input id="shippingMaxDays" type="number" min="1" max="365" value={value.maxDays} onChange={e=>set("maxDays",e.target.value)} required/></SellerFormField></div>
  </>}
 </div>;
}
