"use client";
import { useMemo, useState } from "react";
import { useLocale, useTranslations } from "next-intl";
import { SellerFormField } from "@/components/SellerControlPanel";

const COUNTRY_CODES = "AD AE AF AG AI AL AM AO AR AT AU AW AZ BA BB BD BE BF BG BH BI BJ BN BO BR BS BT BW BY BZ CA CD CF CG CH CI CL CM CN CO CR CU CV CY CZ DE DJ DK DM DO DZ EC EE EG ER ES ET FI FJ FM FR GA GB GD GE GH GM GN GQ GR GT GW GY HK HN HR HT HU ID IE IL IN IQ IR IS IT JM JO JP KE KG KH KI KM KN KP KR KW KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MG MH MK ML MM MN MO MR MT MU MV MW MX MY MZ NA NE NG NI NL NO NP NR NZ OM PA PE PG PH PK PL PS PT PW PY QA RO RS RU RW SA SB SC SD SE SG SI SK SL SM SN SO SR SS ST SV SY SZ TD TG TH TJ TL TM TN TO TR TT TV TW TZ UA UG US UY UZ VA VC VE VN VU WS YE ZA ZM ZW".split(" ");
export type ShippingDraft={enabled:boolean;method:string;price:string;free:boolean;freeThreshold:string;minDays:string;maxDays:string;countries:string[];worldwide:boolean;postalCodes:string;carrier:string};
export const emptyShippingDraft:ShippingDraft={enabled:true,method:"",price:"",free:false,freeThreshold:"",minDays:"",maxDays:"",countries:[],worldwide:false,postalCodes:"",carrier:""};

export function shippingDraftPayload(value:ShippingDraft){return {shippingEnabled:value.enabled,shippingMethodName:value.method,shippingPrice:value.price,shippingFree:value.free,shippingFreeThreshold:value.freeThreshold,shippingMinDays:value.minDays,shippingMaxDays:value.maxDays,shippingCountries:value.countries,shippingWorldwide:value.worldwide,shippingPostalCodes:value.postalCodes.split(/[\n,;]+/).map(v=>v.trim()).filter(Boolean),shippingCarrier:value.carrier};}

export default function ShippingRuleFields({value,onChange,currency,allowDisable=true}:{value:ShippingDraft;onChange:(next:ShippingDraft)=>void;currency:string;allowDisable?:boolean}){
 const t=useTranslations("Shipping"),locale=useLocale(),[search,setSearch]=useState("");
 const display=useMemo(()=>new Intl.DisplayNames([locale],{type:"region"}),[locale]);
 const options=useMemo(()=>COUNTRY_CODES.map(code=>({code,name:display.of(code)??code})).sort((a,b)=>a.name.localeCompare(b.name,locale)).filter(item=>item.name.toLocaleLowerCase(locale).includes(search.toLocaleLowerCase(locale))),[display,locale,search]);
 const set=<K extends keyof ShippingDraft>(key:K,next:ShippingDraft[K])=>onChange({...value,[key]:next});
 return <div className="shippingRuleFields">
  {allowDisable&&<label className="shippingToggle"><input type="checkbox" checked={value.enabled} onChange={e=>set("enabled",e.target.checked)}/><span><strong>{t("enabled")}</strong><small>{value.enabled?t("enabledHelp"):t("disabledHelp")}</small></span></label>}
  {value.enabled&&<>
   <div className="sellerControlFieldGrid"><SellerFormField label={t("method")} htmlFor="shippingMethodName" required><input id="shippingMethodName" value={value.method} onChange={e=>set("method",e.target.value)} maxLength={80} required/></SellerFormField><SellerFormField label={t("carrier")} htmlFor="shippingCarrier" hint={t("carrierHelp")}><input id="shippingCarrier" value={value.carrier} onChange={e=>set("carrier",e.target.value)} maxLength={80}/></SellerFormField></div>
   <div className="shippingChoiceRow"><label><input type="radio" checked={!value.worldwide} onChange={()=>set("worldwide",false)}/>{t("selectedDestinations")}</label><label><input type="radio" checked={value.worldwide} onChange={()=>set("worldwide",true)}/>{t("worldwide")}</label></div>
   {!value.worldwide&&<div className="countryPicker"><label>{t("searchCountries")}<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder={t("searchCountries")}/></label><div className="countryPickerOptions">{options.slice(0,80).map(item=><label key={item.code}><input type="checkbox" checked={value.countries.includes(item.code)} onChange={e=>set("countries",e.target.checked?[...value.countries,item.code]:value.countries.filter(code=>code!==item.code))}/>{item.name}</label>)}</div><div className="countryChips">{value.countries.map(code=><button type="button" key={code} onClick={()=>set("countries",value.countries.filter(v=>v!==code))}>{display.of(code)??code} ×</button>)}</div><button type="button" className="shippingClear" onClick={()=>set("countries",[])}>{t("clearCountries")}</button></div>}
   <SellerFormField label={t("postalZones")} htmlFor={undefined} hint={t("postalZonesHelp")}><textarea rows={3} value={value.postalCodes} onChange={e=>set("postalCodes",e.target.value)} placeholder="59000, 59100, 59*"/></SellerFormField>
   <div className="shippingChoiceRow"><label><input type="radio" checked={!value.free} onChange={()=>set("free",false)}/>{t("paidShipping")}</label><label><input type="radio" checked={value.free} onChange={()=>set("free",true)}/>{t("alwaysFree")}</label></div>
   <div className="sellerControlFieldGrid">{!value.free&&<SellerFormField label={t("price")} htmlFor={undefined} required><input type="number" min="0" step="0.01" value={value.price} onChange={e=>set("price",e.target.value)} required/></SellerFormField>}<SellerFormField label={t("freeThreshold",{currency})} htmlFor={undefined} hint={t("freeThresholdHelp")}><input type="number" min="0" step="0.01" value={value.freeThreshold} onChange={e=>set("freeThreshold",e.target.value)}/></SellerFormField></div>
   <div className="sellerControlFieldGrid"><SellerFormField label={t("minDays")} htmlFor={undefined} required><input type="number" min="1" max="365" value={value.minDays} onChange={e=>set("minDays",e.target.value)} required/></SellerFormField><SellerFormField label={t("maxDays")} htmlFor={undefined} required><input type="number" min="1" max="365" value={value.maxDays} onChange={e=>set("maxDays",e.target.value)} required/></SellerFormField></div>
  </>}
 </div>;
}
