"use client";
import { FormEvent, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import type { Locale } from "@/i18n/config";
import { siteContentMessages } from "@/i18n/site-content";
type Initial={id:string;title:string;content:string;seoTitle:string;seoDescription:string}|null;
export default function SiteContentEditor({pageKey,locale,version,initial,history}:{pageKey:string;locale:Locale;version:number;initial:Initial;history:Array<{id:string;revision:number;status:string;createdAt:string;editor:string}>}){
 const t=siteContentMessages[locale],router=useRouter(),busyRef=useRef(false),[currentVersion,setCurrentVersion]=useState(version),[revisionId,setRevisionId]=useState(initial?.id??""),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{const listener=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue=""}};window.addEventListener("beforeunload",listener);return()=>window.removeEventListener("beforeunload",listener)},[dirty]);
 async function request(action:string,payload:Record<string,unknown>){if(busyRef.current)return null;busyRef.current=true;setBusy(true);setMessage("");try{const response=await fetch(`/api/admin/site-content/${pageKey}/${locale}`,{method:action==="save"?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...payload,action,expectedVersion:currentVersion})}),data=await response.json()as{error?:string;version?:number;revision?:{id:string}};if(!response.ok){setMessage(data.error==="VERSION_CONFLICT"?t.conflict:t.failed);return null}if(data.version!==undefined)setCurrentVersion(data.version);if(data.revision?.id)setRevisionId(data.revision.id);setDirty(false);setMessage(t.saved);router.refresh();return data}catch{setMessage(t.failed);return null}finally{busyRef.current=false;setBusy(false)}}
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await request("save",Object.fromEntries(form.entries()))}
 const titleLabel=t.seoTitle.replace(/^SEO\s+/i,"");
 return <div className="cmsEditorGrid"><form className="adminPanel adminForm cmsEditor" onSubmit={save} onChange={()=>setDirty(true)}><label>{t.page}<input value={pageKey} disabled/></label><label>{titleLabel}<input name="title" maxLength={180} required defaultValue={initial?.title??""}/></label><label>{t.content}<textarea name="content" rows={18} maxLength={50000} required defaultValue={initial?.content??""}/><small>{t.markdownHelp}</small></label><label>{t.seoTitle}<input name="seoTitle" maxLength={180} defaultValue={initial?.seoTitle??""}/></label><label>{t.seoDescription}<textarea name="seoDescription" rows={3} maxLength={320} defaultValue={initial?.seoDescription??""}/></label>{dirty&&<p className="adminFeedback">{t.unsaved}</p>}{message&&<p role="status" className="adminFeedback">{message}</p>}<div className="cmsEditorActions"><button disabled={busy}>{t.saveDraft}</button><button type="button" disabled={busy||!revisionId} onClick={()=>request("publish",{revisionId})}>{t.publish}</button><button type="button" disabled={busy} onClick={()=>request("archive",{})}>{t.archive}</button><a href={`/adm-barewbar-182203/content/preview/${pageKey}?locale=${locale}`} target="_blank" rel="noreferrer">{t.preview}</a></div></form><aside className="adminPanel cmsHistory"><h2>{t.history}</h2>{history.map(item=><article key={item.id}><strong>v{item.revision} · {item.status}</strong><small>{item.createdAt} · {item.editor}</small><button type="button" disabled={busy} onClick={()=>request("restore",{revisionId:item.id})}>{t.restore}</button></article>)}{!history.length&&<p>{t.noHistory}</p>}</aside></div>
}
