"use client";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";

export type ManagedSupplierProduct={productId:string;name:string;provider:string;supplierCost:string|null;supplierCurrency:string|null;supplierStock:number|null;syncStatus:string;lastSyncedAt:string|null;sellingPrice:string;currency:string};

export default function SupplierProductManager({products}:{products:ManagedSupplierProduct[]}){
 const t=useTranslations("Supplier"),router=useRouter(),[working,setWorking]=useState(false),[message,setMessage]=useState("");
 async function importProduct(event:FormEvent<HTMLFormElement>){event.preventDefault();setWorking(true);setMessage("");const form=new FormData(event.currentTarget);const response=await fetch("/api/supplier/cj/import",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({supplierProductId:form.get("supplierProductId"),sellingPrice:form.get("sellingPrice"),category:form.get("category")})});const data=await response.json() as {error?:string};setWorking(false);setMessage(response.ok?t("imported"):data.error==="SUPPLIER_NOT_CONFIGURED"?t("notConfigured"):data.error??"SUPPLIER_IMPORT_FAILED");if(response.ok){event.currentTarget.reset();router.refresh();}}
 async function sync(productId:string){setWorking(true);setMessage("");const response=await fetch(`/api/supplier/products/${productId}/sync`,{method:"POST"});const data=await response.json() as {error?:string};setWorking(false);setMessage(response.ok?"OK":data.error??"SUPPLIER_SYNC_FAILED");if(response.ok)router.refresh();}
 return <section className="sellerControlSection supplierManager"><div className="sellerControlSectionHeading"><div><h2>{t("title")}</h2><p>{t("help")}</p></div></div><form className="supplierImportForm" onSubmit={importProduct}><label>{t("productId")}<input name="supplierProductId" required maxLength={200}/></label><label>{t("sellingPrice")}<input name="sellingPrice" type="number" min="0.01" step="0.01" required/></label><label>{t("category")}<input name="category" required maxLength={80}/></label><button className="sellerControlButton primary" disabled={working}>{working?t("working"):t("importAction")}</button></form>{message&&<p className="sellerControlFeedback" role="status">{message}</p>}{products.length>0&&<div className="supplierProductList">{products.map(product=><article key={product.productId}><div><strong>{product.name}</strong><span>{t("status")}: {product.syncStatus}</span></div><dl><div><dt>{t("supplierCost")}</dt><dd>{product.supplierCost??"—"} {product.supplierCurrency??""}</dd></div><div><dt>{t("sellingPrice")}</dt><dd>{product.sellingPrice} {product.currency}</dd></div><div><dt>{t("supplierStock")}</dt><dd>{product.supplierStock??"—"}</dd></div><div><dt>{t("lastSynced")}</dt><dd>{product.lastSyncedAt?new Date(product.lastSyncedAt).toLocaleString():"—"}</dd></div></dl><button type="button" className="sellerControlButton secondary" disabled={working} onClick={()=>void sync(product.productId)}>{t("sync")}</button></article>)}</div>}</section>;
}
