"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { useTranslations } from "next-intl";
import { DESKTOP_CATEGORY_TAXONOMY, resolveCanonicalLeafSelection, subcategoryId } from "@/lib/desktop-category-taxonomy";
import SellerCategorySelector from "./SellerCategorySelector";
import { canContinueCatalogJob, catalogJobProgress } from "@/lib/suppliers/catalog-job-progress";

type SearchItem={supplierProductId:string;sku:string|null;title:string;imageUrl:string|null;categoryReference:string|null;cost:number|null;currency:string};
type JobSummary={id:string;status:string;requestedCount:number;processedCount:number;importedCount:number;skippedCount:number;quarantinedCount:number;failedCount:number;batchLimit:number;destinationCountry:string;createdAt:string|Date;startedAt?:string|Date|null;updatedAt:string|Date;completedAt?:string|Date|null;processingCount?:number;remainingCount?:number;isProcessing?:boolean;canContinue?:boolean};
type JobItem={id:string;requestedIdentifier:string;canonicalSupplierId:string|null;status:string;canonicalCategoryId:string|null;classificationStatus:string|null;classificationConfidence:number|null;classificationEvidence:unknown;pricingStatus:string|null;stockStatus:string|null;complianceStatus:string|null;errorCode:string|null;productId:string|null;attemptCount:number};
type JobDetail=JobSummary&{items:JobItem[];nextCursor:string|null};
type PreviewItem={supplierProductId:string;title:string;errorCode:string|null;classificationStatus:string;classificationConfidence:number;suggestedCanonicalCategoryId:string|null;suggestedCanonicalCategoryLabel:string|null;requiresReview:boolean;canonicalCategoryId:string|null};
type CategoryLabels={main:string;group:string;leaf:string;chooseMain:string;chooseGroup:string;chooseLeaf:string};
const mutationHeaders={"Content-Type":"application/json","X-Todijo-Admin-Action":"1"};
const PREVIEW_DEBOUNCE_MS=650;
const PRICING_REFERENCE_COUNTRY="FR";
function elapsedLabel(job:JobSummary,now:number,unavailable:string){const seconds=catalogJobProgress(job,now).elapsedSeconds;if(seconds==null)return unavailable;return seconds<60?`${seconds}s`:`${Math.floor(seconds/60)}m ${seconds%60}s`;}
function jobStatusKey(job:JobSummary){return job.isProcessing?"jobStatusRunning":job.status==="COMPLETED"?"jobStatusCompleted":job.status==="COMPLETED_WITH_ERRORS"?"jobStatusReview":canContinueCatalogJob(job)?"jobStatusReady":"jobStatusPending";}
const itemStatusKeys:Record<string,string>={PENDING:"jobStatusPending",IMPORTING:"jobStatusRunning",IMPORTED:"bulkImported",SKIPPED:"bulkSkipped",QUARANTINED:"quarantined",FAILED:"bulkFailed"};

function PreviewCategoryOverride({identifier,initialValue,disabled,labels}:{identifier:string;initialValue:string;disabled:boolean;labels:CategoryLabels}){
  const initial=resolveCanonicalLeafSelection(initialValue);
  const [categoryId,setCategoryId]=useState(initial?.categoryId??"");
  const [groupId,setGroupId]=useState(initial?.groupId??"");
  const [leafId,setLeafId]=useState(initial?.id??"");
  useEffect(()=>{const next=resolveCanonicalLeafSelection(initialValue);setCategoryId(next?.categoryId??"");setGroupId(next?.groupId??"");setLeafId(next?.id??"");},[initialValue]);
  const category=DESKTOP_CATEGORY_TAXONOMY.find(item=>item.id===categoryId),group=category?.groups.find(item=>item.id===groupId);
  return <div className="sellerCategorySelector supplierPreviewCategorySelector">
    <div className="sellerCategoryLevel"><label>{labels.main}</label><select value={categoryId} disabled={disabled} onChange={event=>{setCategoryId(event.target.value);setGroupId("");setLeafId("")}}><option value="">{labels.chooseMain}</option>{DESKTOP_CATEGORY_TAXONOMY.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></div>
    <div className="sellerCategoryLevel"><label>{labels.group}</label><select value={groupId} disabled={disabled||!category} onChange={event=>{setGroupId(event.target.value);setLeafId("")}}><option value="">{labels.chooseGroup}</option>{category?.groups.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></div>
    <div className="sellerCategoryLevel"><label>{labels.leaf}</label><select name={`preview-category-${identifier}`} value={leafId} disabled={disabled||!group} onChange={event=>setLeafId(event.target.value)}><option value="">{labels.chooseLeaf}</option>{group?.items.map(label=>{const id=subcategoryId(categoryId,groupId,label);return <option key={id} value={id}>{label}</option>})}</select></div>
  </div>;
}

export default function SupplierCatalogWorkspace({initialJobs}:{initialJobs:JobSummary[]}){
  const t=useTranslations("Supplier"),categoryText=useTranslations("SellerControl"),formRef=useRef<HTMLFormElement>(null);
  const [jobs,setJobs]=useState(initialJobs),[active,setActive]=useState<JobDetail|null>(null),[query,setQuery]=useState(""),[page,setPage]=useState(1),[hasMore,setHasMore]=useState(false),[results,setResults]=useState<SearchItem[]>([]),[selected,setSelected]=useState<Set<string>>(new Set()),[busy,setBusy]=useState(false),[importing,setImporting]=useState(false),[importFailed,setImportFailed]=useState(false),[message,setMessage]=useState(""),[now,setNow]=useState(()=>Date.now());
  const [previews,setPreviews]=useState<Record<string,PreviewItem>>({}),[previewBusy,setPreviewBusy]=useState(false),previewRequest=useRef(0),previewAbort=useRef<AbortController|null>(null);
  const selectedResults=results.filter((item)=>selected.has(item.supplierProductId));
  const overrideLabels:CategoryLabels={main:categoryText("mainCategory"),group:categoryText("categoryGroup"),leaf:categoryText("leafCategory"),chooseMain:categoryText("chooseMainCategory"),chooseGroup:categoryText("chooseCategoryGroup"),chooseLeaf:categoryText("chooseLeafCategory")};

  useEffect(()=>{const identifiers=Array.from(selected);if(!identifiers.length){previewAbort.current?.abort();previewAbort.current=null;setPreviews({});setPreviewBusy(false);setMessage("");return;}setPreviewBusy(true);const timer=window.setTimeout(()=>{void updatePreviews(identifiers);},PREVIEW_DEBOUNCE_MS);return()=>window.clearTimeout(timer);},[selected]);
  useEffect(()=>{if(!jobs.some(job=>job.isProcessing))return;const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer);},[jobs]);
  useEffect(()=>{if(!jobs.some(job=>job.isProcessing))return;const timer=window.setInterval(()=>{void fetch("/api/admin/supplier-products/bulk-import",{cache:"no-store"}).then(response=>response.json()).then((data:{jobs?:JobSummary[]})=>{if(data.jobs)setJobs(data.jobs);}).catch(()=>undefined);},2000);return()=>window.clearInterval(timer);},[jobs]);

  async function updatePreviews(identifiers:string[]){
    if(!identifiers.length){setPreviews({});setMessage("");return;}const requestId=++previewRequest.current;previewAbort.current?.abort();const controller=new AbortController();previewAbort.current=controller;setPreviewBusy(true);setMessage("");
    try{const response=await fetch("/api/admin/supplier-products/catalog-preview",{method:"POST",headers:mutationHeaders,body:JSON.stringify({identifiers}),signal:controller.signal}),data=await response.json() as {error?:string;previews?:PreviewItem[]};if(requestId!==previewRequest.current)return;if(!response.ok)throw new Error(data.error??"CJ_CLASSIFICATION_FAILED");const next:Record<string,PreviewItem>={};for(const item of data.previews??[])next[item.supplierProductId]=item;setPreviews(next);}catch(error){if(error instanceof DOMException&&error.name==="AbortError")return;if(requestId===previewRequest.current){setPreviews({});setMessage(error instanceof Error?error.message:"CJ_CLASSIFICATION_FAILED");}}finally{if(requestId===previewRequest.current){setPreviewBusy(false);if(previewAbort.current===controller)previewAbort.current=null;}}
  }

  async function search(nextPage=1){setBusy(true);setMessage("");try{const response=await fetch(`/api/admin/supplier-products/catalog-search?q=${encodeURIComponent(query)}&page=${nextPage}&pageSize=20`,{cache:"no-store"}),data=await response.json() as {error?:string;items?:SearchItem[];hasMore?:boolean};if(!response.ok)throw new Error(data.error);setResults(current=>nextPage===1?(data.items??[]):[...current,...(data.items??[]).filter(item=>!current.some(existing=>existing.supplierProductId===item.supplierProductId))]);setPage(nextPage);setHasMore(Boolean(data.hasMore));}catch(error){setMessage(error instanceof Error?error.message:"SUPPLIER_CATALOG_SEARCH_FAILED");}finally{setBusy(false);}}
  function toggle(identifier:string){setSelected(current=>{const next=new Set(current);if(next.has(identifier))next.delete(identifier);else next.add(identifier);return next;});}
  async function loadJob(jobId:string){const response=await fetch(`/api/admin/supplier-products/bulk-import/${jobId}?take=100`,{cache:"no-store"}),data=await response.json() as {error?:string;job?:JobDetail};if(!response.ok||!data.job)throw new Error(data.error??"SUPPLIER_CATALOG_JOB_FAILED");setActive(data.job);setJobs(current=>[data.job!,...current.filter(job=>job.id!==jobId)]);return data.job;}
  async function resume(jobId:string){
    if(busy)return;setBusy(true);setMessage("");const poll=window.setInterval(()=>{void loadJob(jobId).catch(()=>undefined);},1000);
    try{
      const before=await loadJob(jobId);if(!canContinueCatalogJob(before))throw new Error("SUPPLIER_CATALOG_JOB_BUSY");
      const response=await fetch(`/api/admin/supplier-products/bulk-import/${jobId}/resume`,{method:"POST",headers:mutationHeaders,body:JSON.stringify({})}),data=await response.json() as {error?:string;job?:JobSummary};if(!response.ok)throw new Error(data.error);
      const job=await loadJob(jobId);if(job.processedCount<=before.processedCount&&job.processedCount<job.requestedCount)throw new Error("SUPPLIER_CATALOG_JOB_STALLED");
      setMessage(`${t("bulkComplete")}: ${job.processedCount}/${job.requestedCount} · ${elapsedLabel(job,Date.now(),t("durationUnavailable"))}`);
    }catch(error){setMessage(error instanceof Error&&error.message==="SUPPLIER_CATALOG_JOB_BUSY"?t("resumeBusy"):error instanceof Error?error.message:"SUPPLIER_CATALOG_JOB_FAILED");}finally{window.clearInterval(poll);setBusy(false);}
  }

  async function create(event:FormEvent<HTMLFormElement>){
    event.preventDefault();if(importing||busy)return;const form=new FormData(event.currentTarget),pasted=String(form.get("identifiers")??"").split(/[\s,;]+/).filter(Boolean),identifiers=[...new Set([...selected,...pasted])];if(!identifiers.length)return;
    const canonicalCategoryByIdentifier:Record<string,string>|undefined=Object.fromEntries(identifiers.map((identifier)=>{const override=form.get(`preview-category-${identifier}`);if(typeof override==="string"){const value=override.trim();if(value)return [identifier,value] as const;}return null;}).filter((entry):entry is [string,string]=>Boolean(entry)));
    const payload={identifiers,destinationCountry:PRICING_REFERENCE_COUNTRY,canonicalCategoryId:form.get("category"),canonicalCategoryByIdentifier:Object.keys(canonicalCategoryByIdentifier).length?canonicalCategoryByIdentifier:undefined};setImporting(true);setImportFailed(false);setBusy(true);setMessage("");
    try{const response=await fetch("/api/admin/supplier-products/bulk-import",{method:"POST",headers:mutationHeaders,body:JSON.stringify(payload)}),data=await response.json() as {error?:string;job?:JobSummary};if(!response.ok||!data.job)throw new Error(data.error);setJobs(current=>[data.job!,...current]);setSelected(new Set());setPreviews({});setBusy(false);await resume(data.job.id);}catch{setImportFailed(true);setMessage(t("importFailed"));setBusy(false);}finally{setImporting(false);}
  }

  async function retry(){if(!active)return;const category=new FormData(formRef.current!).get("category");setBusy(true);setMessage("");try{const response=await fetch(`/api/admin/supplier-products/bulk-import/${active.id}/retry`,{method:"POST",headers:mutationHeaders,body:JSON.stringify({canonicalCategoryId:category})}),data=await response.json() as {error?:string;updated?:number};if(!response.ok)throw new Error(data.error);const job=await loadJob(active.id);setMessage(`${t("bulkComplete")}: ${job.processedCount}/${job.requestedCount}`);}catch(error){setMessage(error instanceof Error?error.message:"SUPPLIER_CATALOG_RETRY_FAILED");}finally{setBusy(false);}}
  async function syncAll(){setBusy(true);setMessage("");try{const response=await fetch("/api/admin/supplier-products/sync-stale",{method:"POST",headers:mutationHeaders,body:JSON.stringify({limit:20,staleMinutes:1})}),data=await response.json() as {error?:string;synced?:number;failed?:number};if(!response.ok)throw new Error(data.error);setMessage(`${t("syncComplete")}: ${data.synced??0} ${t("synced")}, ${data.failed??0} ${t("bulkFailed")}`);}catch(error){setMessage(error instanceof Error?error.message:"SUPPLIER_SYNC_FAILED");}finally{setBusy(false);}}

  return <section className="supplierCatalogWorkspace" aria-labelledby="supplier-catalog-title">
    <header className="sellerControlSectionHeading"><div><h2 id="supplier-catalog-title">{t("bulkTitle")}</h2><p>{t("bulkHelp")}</p></div><button type="button" className="sellerControlButton secondary" disabled={busy} onClick={()=>void syncAll()}>{t("syncAll")}</button></header>
    <form className="supplierCatalogSearch" onSubmit={event=>{event.preventDefault();void search(1)}}><label>{t("catalogSearch")}<input value={query} onChange={event=>setQuery(event.target.value)} maxLength={120} placeholder={t("searchPlaceholder")}/></label><button className="sellerControlButton secondary" disabled={busy}>{t("searchAction")}</button></form>
    {results.length>0&&<div className="supplierCatalogResults">{results.map(item=><label key={item.supplierProductId} className="supplierCatalogResult"><input type="checkbox" checked={selected.has(item.supplierProductId)} onChange={()=>toggle(item.supplierProductId)}/>{item.imageUrl&&<Image unoptimized src={item.imageUrl} alt="" width={72} height={72}/>}<span><strong>{item.title}</strong><small>{item.supplierProductId}{item.sku?` · ${item.sku}`:""}</small></span></label>)}{hasMore&&<button type="button" className="sellerControlButton secondary" disabled={busy} onClick={()=>void search(page+1)}>{t("loadMore")}</button>}</div>}
    <form ref={formRef} className="supplierCatalogCreate" onSubmit={create}><p><strong>{t("selectedCount")}: {selected.size}</strong></p>
      <label>{t("bulkProductIds")}<textarea name="identifiers" rows={5} maxLength={50000} placeholder={t("bulkPlaceholder")}/></label>
      <SellerCategorySelector required={false} labels={{...overrideLabels,legacyInvalid:categoryText("legacyCategoryInvalid")}}/>
      <div className="supplierCatalogItems" aria-live="polite">
        <header><h3>{t("classification")}</h3>{previewBusy&&<p>{t("pending")}</p>}</header>
        {selected.size===0&&<p>{t("reviewRequired")}</p>}
        {selectedResults.map((item)=>{const preview=previews[item.supplierProductId],pending=!preview,isReviewRequired=Boolean(preview&&(preview.requiresReview||preview.classificationStatus==="NEEDS_REVIEW"||preview.classificationStatus==="UNRESOLVED"||preview.classificationStatus==="QUARANTINED"||!preview.suggestedCanonicalCategoryId||!preview.suggestedCanonicalCategoryLabel)),isLowConfidence=Boolean(preview&&(isReviewRequired||preview.classificationConfidence<0.62)),classificationText=pending?t("pending"):preview.errorCode?preview.errorCode:isReviewRequired?t("needsReview"):t("bulkStatusGood"),categoryStatus=pending?t("pending"):preview.errorCode?preview.errorCode:isReviewRequired?t("reviewRequired"):preview.suggestedCanonicalCategoryLabel??t("reviewRequired"),reviewText=pending?t("pending"):preview.errorCode?preview.errorCode:isReviewRequired?t("needsReview"):t("bulkStatusGood");return <article key={item.supplierProductId}><div><strong>{item.supplierProductId}</strong><span>{item.title}</span></div><dl><div><dt>{t("classification")}</dt><dd>{classificationText} {!pending&&preview?.classificationConfidence!=null?`(${Math.round(preview.classificationConfidence*100)}%)`:""}</dd></div><div><dt>{t("categoryStatus")}</dt><dd>{categoryStatus}</dd></div><div><dt>{t("needsReview")}</dt><dd>{reviewText}</dd></div><div className="supplierCatalogOverride"><dt>{t("override")}</dt><dd><PreviewCategoryOverride identifier={item.supplierProductId} initialValue={preview?.suggestedCanonicalCategoryId??""} disabled={pending} labels={overrideLabels}/></dd></div><div>{isLowConfidence&&preview&&!preview.errorCode&&<strong>{t("quarantine")}</strong>}</div></dl></article>;})}
      </div>
      <button className="sellerControlButton primary supplierImportAction" disabled={busy||previewBusy||importing} aria-describedby={importing?"supplier-import-progress":undefined}>{importing?t("importInProgress"):t("bulkImportAction")}</button>
      {importing&&<p id="supplier-import-progress" className="supplierImportProgress" role="status" aria-live="assertive"><span aria-hidden="true"/>{t("importInProgress")}</p>}
      <p className="supplierBulkSafety">{t("bulkSafety")}</p>
    </form>
    {message&&<p className={importFailed?"supplierImportError":"supplierBulkSafety"} role={importFailed?"alert":"status"}>{message}</p>}
    {jobs.length>0&&<div className="supplierCatalogJobs">{jobs.map(job=>{const progress=catalogJobProgress(job,now),canContinue=job.canContinue??canContinueCatalogJob(job);return <article key={job.id}><div className="supplierCatalogJobSummary"><strong><span className={`supplierCatalogStatus is-${job.status.toLowerCase()}`}>{t(jobStatusKey(job))}</span></strong><div className="supplierCatalogProgress" role="progressbar" aria-valuemin={0} aria-valuemax={progress.total} aria-valuenow={progress.processed} aria-label={t("processedCount")}><span style={{width:`${progress.percent}%`}}/></div><dl><div><dt>{t("processedCount")}</dt><dd>{progress.processed} / {progress.total}</dd></div><div><dt>{t("bulkImported")}</dt><dd>{progress.imported}</dd></div><div><dt>{t("bulkSkipped")}</dt><dd>{progress.skipped}</dd></div><div><dt>{t("quarantined")}</dt><dd>{progress.quarantined}</dd></div><div><dt>{t("bulkFailed")}</dt><dd>{progress.failed}</dd></div><div><dt>{t("remainingCount")}</dt><dd>{progress.remaining}</dd></div><div><dt>{t("elapsed")}</dt><dd>{elapsedLabel(job,now,t("durationUnavailable"))}</dd></div></dl></div><div><button type="button" className="sellerControlButton secondary" disabled={busy} onClick={()=>void loadJob(job.id)}>{t("reviewRequired")}</button>{progress.remaining>0&&<button type="button" className="sellerControlButton primary" disabled={busy||!canContinue} aria-busy={job.isProcessing||busy} onClick={()=>void resume(job.id)}>{job.isProcessing?t("resumeBusy"):t("resume")}</button>}</div></article>})}</div>}
    {active&&<section className="supplierCatalogItems" aria-live="polite"><header><h3>{t("jobStatus")}: {t(jobStatusKey(active))}</h3>{active.failedCount+active.quarantinedCount>0&&<button type="button" className="sellerControlButton secondary" disabled={busy} onClick={()=>void retry()}>{t("retryReview")}</button>}</header>{active.items.map(item=><article key={item.id}><div><strong>{item.requestedIdentifier}</strong><span className={`supplierCatalogStatus is-${item.status.toLowerCase()}`}>{t(itemStatusKeys[item.status]??"bulkStatus")}</span></div><dl><div><dt>{t("classification")}</dt><dd>{item.classificationStatus??t("reviewRequired")}{item.classificationConfidence!=null?` · ${Math.round(item.classificationConfidence*100)}%`:""}</dd></div><div><dt>{t("categoryStatus")}</dt><dd>{item.canonicalCategoryId??item.errorCode??t("reviewRequired")}</dd></div><div><dt>{t("pricingStatus")}</dt><dd>{item.pricingStatus??"—"}</dd></div><div><dt>{t("stockStatus")}</dt><dd>{item.stockStatus??"—"}</dd></div><div><dt>{t("complianceStatus")}</dt><dd>{item.complianceStatus??"—"}</dd></div></dl>{item.productId&&<nav><Link href={`/seller/products/${item.productId}/edit`}>{t("openDraft")}</Link><Link href={`/product/${item.productId}?adminPreview=1`} target="_blank">{t("previewDraft")}</Link></nav>}</article>)}</section>}
  </section>;
}
