"use client";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";

export type ManagedSupplierProduct={productId:string;name:string;provider:string;supplierCost:string|null;supplierCurrency:string|null;supplierStock:number|null;syncStatus:string;lastSyncedAt:string|null;sellingPrice:string;currency:string};
type PricingPreview={basePrice:string;sellingCurrency:string;supplierCost:string|null;supplierCurrency:string|null};

export default function SupplierProductManager({products}:{products:ManagedSupplierProduct[]}){
 const t=useTranslations("Supplier"),router=useRouter(),[working,setWorking]=useState(false),[message,setMessage]=useState(""),[manual,setManual]=useState(false),[pricing,setPricing]=useState<PricingPreview|null>(null);
 function pricingError(code?:string){return code==="PRICING_CURRENCY_CONVERSION_REQUIRED"?t("currencyConversionRequired"):code??"SUPPLIER_PRICING_FAILED";}
 async function preview(form:HTMLFormElement){const data=new FormData(form),identifier=String(data.get("supplierProductId")??"").trim();if(!identifier)return;setWorking(true);setMessage("");setPricing(null);const response=await fetch("/api/supplier/cj/pricing",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({supplierProductId:identifier})});const result=await response.json() as {error?:string;pricing?:{basePrice:string;product:{supplierCost:string;supplierCurrency:string;sellingCurrency:string}|null;variants:Array<{calculation:{supplierCost:string;supplierCurrency:string;sellingCurrency:string}}>}};setWorking(false);if(!response.ok||!result.pricing)return setMessage(pricingError(result.error));const first=result.pricing.product??result.pricing.variants[0]?.calculation;setPricing({basePrice:result.pricing.basePrice,sellingCurrency:first?.sellingCurrency??"",supplierCost:first?.supplierCost??null,supplierCurrency:first?.supplierCurrency??null});}
 async function importProduct(event:FormEvent<HTMLFormElement>){event.preventDefault();setWorking(true);setMessage("");const form=new FormData(event.currentTarget);const response=await fetch("/api/supplier/cj/import",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({supplierProductId:form.get("supplierProductId"),pricingMode:manual?"MANUAL":"AUTOMATIC",sellingPrice:manual?form.get("sellingPrice"):null,category:form.get("category")})});const data=await response.json() as {error?:string};setWorking(false);setMessage(response.ok?t("imported"):data.error==="SUPPLIER_NOT_CONFIGURED"?t("notConfigured"):pricingError(data.error));if(response.ok){event.currentTarget.reset();setManual(false);setPricing(null);router.refresh();}}
 async function sync(productId:string){setWorking(true);setMessage("");const response=await fetch(`/api/supplier/products/${productId}/sync`,{method:"POST"});const data=await response.json() as {error?:string};setWorking(false);setMessage(response.ok?"OK":data.error??"SUPPLIER_SYNC_FAILED");if(response.ok)router.refresh();}
 return <section className="sellerControlSection supplierManager"><div className="sellerControlSectionHeading"><div><h2>{t("title")}</h2><p>{t("help")}</p></div></div><form className="supplierImportForm supplierPricingForm" onSubmit={importProduct}><label>{t("productId")}<input name="supplierProductId" required maxLength={200}/></label><label>{t("category")}<input name="category" required maxLength={80}/></label><div className="supplierAutomaticPricing"><strong>{t("automaticPricing")}</strong><span>{t("targetMargin")}</span><button type="button" className="sellerControlButton secondary" disabled={working} onClick={(event)=>void preview(event.currentTarget.form!)}>{t("calculatePrice")}</button></div><label className="supplierManualOverride"><span><input type="checkbox" checked={manual} onChange={(event)=>setManual(event.target.checked)}/>{t("manualOverride")}</span>{manual&&<input name="sellingPrice" type="number" min="0.01" step="0.01" required/>}</label><button className="sellerControlButton primary" disabled={working}>{working?t("working"):t("importAction")}</button></form>{pricing&&<div className="supplierPricingEstimate" role="status"><div><span>{t("supplierCost")}</span><strong>{pricing.supplierCost??"—"} {pricing.supplierCurrency??""}</strong></div><div><span>{t("baseEstimate")}</span><strong>{pricing.basePrice} {pricing.sellingCurrency}</strong></div><p>{t("shippingDeferred")}</p></div>}{message&&<p className="sellerControlFeedback" role="status">{message}</p>}{products.length>0&&<div className="supplierProductList">{products.map(product=><article key={product.productId}><div><strong>{product.name}</strong><span>{t("status")}: {product.syncStatus}</span></div><dl><div><dt>{t("supplierCost")}</dt><dd>{product.supplierCost??"—"} {product.supplierCurrency??""}</dd></div><div><dt>{t("sellingPrice")}</dt><dd>{product.sellingPrice} {product.currency}</dd></div><div><dt>{t("supplierStock")}</dt><dd>{product.supplierStock??"—"}</dd></div><div><dt>{t("lastSynced")}</dt><dd>{product.lastSyncedAt?new Date(product.lastSyncedAt).toLocaleString():"—"}</dd></div></dl><button type="button" className="sellerControlButton secondary" disabled={working} onClick={()=>void sync(product.productId)}>{t("sync")}</button></article>)}</div>}</section>;
}
