import "server-only";
import { randomUUID } from "node:crypto";
import { Prisma, type PrismaClient } from "@prisma/client";
import { isLocale, type Locale } from "../i18n/config";
import { catalogTranslationConfig, CATALOG_TRANSLATION_LEASE_MS, CATALOG_TRANSLATION_MAX_JOB_ITEMS, type CatalogTranslationConfig } from "./catalog-translation-config";
import { TranslationProviderError, type TranslationProvider, type TranslationProviderResult } from "./translation-provider";
import { productTranslationSource, productTranslationState, PRODUCT_TRANSLATION_PIPELINE_VERSION, storeGeneratedTranslationProposal } from "./product-translation";

type Db=PrismaClient|Prisma.TransactionClient;
type Translator=(input:Parameters<TranslationProvider["translate"]>[0])=>Promise<TranslationProviderResult>;

export class CatalogTranslationError extends Error{constructor(public readonly code:string,public readonly status=400){super(code);}}
function ids(value:unknown){return Array.isArray(value)?[...new Set(value.filter((id):id is string=>typeof id==="string"&&id.length>=4&&id.length<=100))].slice(0,CATALOG_TRANSLATION_MAX_JOB_ITEMS):[];}
function locale(value:unknown):Locale{if(typeof value!=="string"||!isLocale(value))throw new CatalogTranslationError("TRANSLATION_LOCALE_UNSUPPORTED");return value;}
function charCount(value:string){return value.length;}
function periods(now:Date){return{day:new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate())),month:new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1))};}
function safeMessage(error:unknown){return(error instanceof Error?error.message:"TRANSLATION_FAILED").replace(/[\r\n\t]+/g," ").slice(0,500);}

async function candidates(db:Db,productIds:string[],targetLocale:Locale){
  const products=await db.product.findMany({where:{id:{in:productIds},removedAt:null,supplierLink:{isNot:null}},select:{id:true,name:true,description:true,status:true,supplierLink:{select:{id:true,sourceMetadata:true}}}});
  return products.map(product=>{const link=product.supplierLink!,source=productTranslationSource({name:product.name,description:product.description,sourceMetadata:link.sourceMetadata}),translation=productTranslationState({name:product.name,description:product.description,sourceMetadata:link.sourceMetadata,targetLocale}),estimatedCharacters=charCount(source.title)+charCount(source.description);return{product,link,source,translation,estimatedCharacters,eligible:["MISSING","STALE"].includes(translation.state)&&source.locale!==targetLocale&&estimatedCharacters>0};});
}

export async function previewCatalogTranslationJob(db:Db,input:{productIds:unknown;targetLocale:unknown},env:NodeJS.ProcessEnv=process.env){
  const productIds=ids(input.productIds),targetLocale=locale(input.targetLocale);if(!productIds.length)throw new CatalogTranslationError("TRANSLATION_PRODUCTS_REQUIRED");
  const rows=await candidates(db,productIds,targetLocale),eligible=rows.filter(row=>row.eligible),estimatedCharacters=eligible.reduce((sum,row)=>sum+row.estimatedCharacters,0),config=catalogTranslationConfig(env),now=new Date(),{day,month}=periods(now);
  const budgets=config?await db.catalogTranslationBudget.findMany({where:{provider:config.provider.id,OR:[{periodType:"DAY",periodStart:day},{periodType:"MONTH",periodStart:month}]},select:{periodType:true,limitCharacters:true,reservedCharacters:true,submittedCharacters:true}}):[];
  const remaining=(period:"DAY"|"MONTH",limit:number)=>{const row=budgets.find(item=>item.periodType===period);return Math.max(0,limit-Number((row?.reservedCharacters??BigInt(0))+(row?.submittedCharacters??BigInt(0))));};
  return{targetLocale,requested:productIds.length,eligibleCount:eligible.length,skippedCount:rows.length-eligible.length,estimatedCharacters,providerReady:Boolean(config),withinJobLimit:Boolean(config&&estimatedCharacters<=config.perJobCharacters),withinItemLimit:Boolean(config&&eligible.every(row=>row.estimatedCharacters<=config.perRunCharacters)),dailyRemaining:config?remaining("DAY",config.dailyCharacters):null,monthlyRemaining:config?remaining("MONTH",config.monthlyCharacters):null,items:rows.map(row=>({productId:row.product.id,title:row.source.title,state:row.translation.state,estimatedCharacters:row.estimatedCharacters,eligible:row.eligible}))};
}

export async function enqueueCatalogTranslationJob(db:PrismaClient,input:{adminId:string;productIds:unknown;targetLocale:unknown},env:NodeJS.ProcessEnv=process.env){
  const config=catalogTranslationConfig(env);if(!config)throw new CatalogTranslationError("TRANSLATION_PROVIDER_DISABLED",503);
  const productIds=ids(input.productIds),targetLocale=locale(input.targetLocale);if(!productIds.length)throw new CatalogTranslationError("TRANSLATION_PRODUCTS_REQUIRED");
  const rows=(await candidates(db,productIds,targetLocale)).filter(row=>row.eligible),estimated=rows.reduce((sum,row)=>sum+row.estimatedCharacters,0);if(!rows.length)throw new CatalogTranslationError("TRANSLATION_NO_ELIGIBLE_PRODUCTS");if(rows.some(row=>row.estimatedCharacters>config.perRunCharacters))throw new CatalogTranslationError("TRANSLATION_ITEM_CHARACTER_LIMIT_EXCEEDED");if(estimated>config.perJobCharacters)throw new CatalogTranslationError("TRANSLATION_JOB_CHARACTER_LIMIT_EXCEEDED");
  return db.$transaction(async tx=>{const job=await tx.catalogTranslationJob.create({data:{provider:config.provider.id,providerVersion:config.provider.version,pipelineVersion:PRODUCT_TRANSLATION_PIPELINE_VERSION,sourceLocale:rows.every(row=>row.source.locale===rows[0].source.locale)?rows[0].source.locale:null,targetLocales:[targetLocale],requestedItemCount:0,estimatedCharacters:BigInt(0),batchLimit:Math.min(rows.length,config.perRunItems),createdById:input.adminId}});
    for(const row of rows)await tx.catalogTranslationItem.updateMany({where:{productId:row.product.id,targetLocale,sourceFingerprint:{not:row.translation.sourceFingerprint},approvalStatus:"PENDING"},data:{approvalStatus:"SUPERSEDED"}});
    await tx.catalogTranslationItem.createMany({skipDuplicates:true,data:rows.map(row=>({jobId:job.id,productId:row.product.id,supplierProductLinkId:row.link.id,sourceLocale:row.source.locale,targetLocale,sourceFingerprint:row.translation.sourceFingerprint,provider:config.provider.id,providerVersion:config.provider.version,pipelineVersion:PRODUCT_TRANSLATION_PIPELINE_VERSION,estimatedCharacters:row.estimatedCharacters}))});
    const created=await tx.catalogTranslationItem.findMany({where:{jobId:job.id},select:{estimatedCharacters:true}}),createdEstimate=created.reduce((sum,row)=>sum+row.estimatedCharacters,0);if(!created.length){await tx.catalogTranslationJob.delete({where:{id:job.id}});throw new CatalogTranslationError("TRANSLATION_WORK_ALREADY_EXISTS",409);}return tx.catalogTranslationJob.update({where:{id:job.id},data:{requestedItemCount:created.length,estimatedCharacters:BigInt(createdEstimate)},select:{id:true,status:true,requestedItemCount:true,estimatedCharacters:true,targetLocales:true,createdAt:true}});
  },{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});
}

async function refreshJob(db:Db,jobId:string,now=new Date()){
  const [grouped,job]=await Promise.all([db.catalogTranslationItem.groupBy({by:["status"],where:{jobId},_count:{_all:true}}),db.catalogTranslationJob.findUniqueOrThrow({where:{id:jobId},select:{status:true,startedAt:true}})]),counts=Object.fromEntries(grouped.map(row=>[row.status,row._count._all])),active=(counts.QUEUED??0)+(counts.CLAIMED??0)+(counts.RETRYABLE??0),errors=counts.MANUAL_ACTION_REQUIRED??0;
  return db.catalogTranslationJob.update({where:{id:jobId},data:active?{status:job.status==="PAUSED"?"PAUSED":"RUNNING",startedAt:job.startedAt??now}:{status:errors?"COMPLETED_WITH_ERRORS":"COMPLETED",completedAt:now},select:{id:true,status:true}});
}

async function reserveAttempt(db:PrismaClient,item:{id:string;jobId:string;attemptCount:number;provider:string;estimatedCharacters:number},config:CatalogTranslationConfig,now:Date){const{day,month}=periods(now),amount=BigInt(item.estimatedCharacters);return db.$transaction(async tx=>{
  const jobUsage=await tx.catalogTranslationAttempt.aggregate({where:{item:{jobId:item.jobId}},_sum:{submittedCharacters:true}});if((jobUsage._sum.submittedCharacters??0)+item.estimatedCharacters>config.perJobCharacters)throw new CatalogTranslationError("TRANSLATION_JOB_CHARACTER_LIMIT_EXHAUSTED",409);
  for(const [periodType,periodStart,limit] of [["DAY",day,config.dailyCharacters],["MONTH",month,config.monthlyCharacters]] as const){
    const rows=await tx.$queryRaw<Array<{id:string}>>(Prisma.sql`INSERT INTO "CatalogTranslationBudget" ("id","provider","periodType","periodStart","limitCharacters","reservedCharacters","submittedCharacters","completedCharacters","createdAt","updatedAt") VALUES (${randomUUID()},${item.provider},${periodType}::"CatalogTranslationBudgetPeriod",${periodStart},${BigInt(limit)},${amount},0,0,${now},${now}) ON CONFLICT ("provider","periodType","periodStart") DO UPDATE SET "limitCharacters"=EXCLUDED."limitCharacters","reservedCharacters"="CatalogTranslationBudget"."reservedCharacters"+${amount},"updatedAt"=${now} WHERE "CatalogTranslationBudget"."submittedCharacters"+"CatalogTranslationBudget"."reservedCharacters"+${amount}<=EXCLUDED."limitCharacters" RETURNING "id"`);if(rows.length!==1)throw new CatalogTranslationError(`TRANSLATION_${periodType}_BUDGET_EXHAUSTED`,409);
  }
  return tx.catalogTranslationAttempt.create({data:{itemId:item.id,attemptNumber:item.attemptCount,providerRequestKey:`catalog-translation:${item.id}:attempt:${item.attemptCount}`,reservedCharacters:item.estimatedCharacters,dailyPeriodStart:day,monthlyPeriodStart:month}});
 },{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}

async function markSubmitted(db:PrismaClient,itemId:string,attemptId:string,provider:string,amount:number,now:Date){return db.$transaction(async tx=>{const changed=await tx.catalogTranslationAttempt.updateMany({where:{id:attemptId,itemId,status:"RESERVED"},data:{status:"SUBMITTED",submittedCharacters:amount,submittedAt:now}});if(changed.count!==1)throw new CatalogTranslationError("TRANSLATION_ATTEMPT_STATE_CONFLICT",409);const attempt=await tx.catalogTranslationAttempt.findUniqueOrThrow({where:{id:attemptId}});for(const [periodType,periodStart] of [["DAY",attempt.dailyPeriodStart],["MONTH",attempt.monthlyPeriodStart]] as const){const moved=await tx.catalogTranslationBudget.updateMany({where:{provider,periodType,periodStart,reservedCharacters:{gte:BigInt(amount)}},data:{reservedCharacters:{decrement:BigInt(amount)},submittedCharacters:{increment:BigInt(amount)}}});if(moved.count!==1)throw new CatalogTranslationError("TRANSLATION_BUDGET_STATE_CONFLICT",409);}await tx.catalogTranslationItem.update({where:{id:itemId},data:{submittedCharacters:{increment:amount}}});return attempt;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}

async function releaseReservation(db:PrismaClient,attempt:{id:string;itemId:string;reservedCharacters:number;dailyPeriodStart:Date;monthlyPeriodStart:Date},provider:string,now:Date){return db.$transaction(async tx=>{const changed=await tx.catalogTranslationAttempt.updateMany({where:{id:attempt.id,status:"RESERVED"},data:{status:"DEFINITE_FAILURE",safeErrorCode:"STALE_RESERVED_ATTEMPT_RECOVERED",completedAt:now}});if(changed.count!==1)return;for(const [periodType,periodStart] of [["DAY",attempt.dailyPeriodStart],["MONTH",attempt.monthlyPeriodStart]] as const)await tx.catalogTranslationBudget.updateMany({where:{provider,periodType,periodStart,reservedCharacters:{gte:BigInt(attempt.reservedCharacters)}},data:{reservedCharacters:{decrement:BigInt(attempt.reservedCharacters)}}});},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}

async function processItem(db:PrismaClient,itemId:string,config:CatalogTranslationConfig,translate:Translator,now=new Date()){
  const token=randomUUID(),claim=await db.catalogTranslationItem.updateMany({where:{id:itemId,status:{in:["QUEUED","RETRYABLE"]},OR:[{nextAttemptAt:null},{nextAttemptAt:{lte:now}}],attemptCount:{lt:config.maxAttempts},job:{status:{in:["QUEUED","RUNNING"]}}},data:{status:"CLAIMED",claimToken:token,claimedAt:now,leaseExpiresAt:new Date(now.getTime()+CATALOG_TRANSLATION_LEASE_MS),attemptCount:{increment:1},lastErrorCode:null,lastErrorMessage:null}});if(claim.count!==1)return{itemId,outcome:"NOT_CLAIMED"};
  const item=await db.catalogTranslationItem.findUniqueOrThrow({where:{id:itemId},include:{product:{select:{name:true,description:true}},supplierProductLink:{select:{sourceMetadata:true}}}}),state=productTranslationState({name:item.product.name,description:item.product.description,sourceMetadata:item.supplierProductLink.sourceMetadata,targetLocale:item.targetLocale}),source=productTranslationSource({name:item.product.name,description:item.product.description,sourceMetadata:item.supplierProductLink.sourceMetadata});
  if(state.sourceFingerprint!==item.sourceFingerprint||!["MISSING","STALE"].includes(state.state)){await db.catalogTranslationItem.updateMany({where:{id:item.id,claimToken:token},data:{status:"SKIPPED",skippedAt:now,completedAt:now,claimToken:null,claimedAt:null,leaseExpiresAt:null,lastErrorCode:state.sourceFingerprint!==item.sourceFingerprint?"SOURCE_FINGERPRINT_CHANGED":`TRANSLATION_${state.state}`}});await refreshJob(db,item.jobId,now);return{itemId,outcome:"SKIPPED"};}
  let attempt:Awaited<ReturnType<typeof reserveAttempt>>|undefined;try{attempt=await reserveAttempt(db,item,config,now);await markSubmitted(db,item.id,attempt.id,item.provider,item.estimatedCharacters,now);}catch(error){if(attempt)await releaseReservation(db,attempt,item.provider,now);await db.catalogTranslationItem.updateMany({where:{id:item.id,claimToken:token},data:{status:"MANUAL_ACTION_REQUIRED",claimToken:null,claimedAt:null,leaseExpiresAt:null,lastErrorCode:error instanceof Error?error.message:"TRANSLATION_BUDGET_FAILED",lastErrorMessage:safeMessage(error)}});await refreshJob(db,item.jobId,now);return{itemId,outcome:"MANUAL_ACTION_REQUIRED"};}
  const texts=[source.title,...(source.description?[source.description]:[])];let result:TranslationProviderResult;
  try{result=await translate({sourceLocale:item.sourceLocale as Locale,targetLocale:item.targetLocale as Locale,texts});}catch(error){const provider=error instanceof TranslationProviderError?error:null,ambiguous=provider?.category==="AMBIGUOUS_SUBMISSION",exhausted=item.attemptCount>=config.maxAttempts,status=ambiguous||!provider?.retryable||exhausted?"MANUAL_ACTION_REQUIRED":"RETRYABLE",delay=provider?.retryAfterMs??Math.min(30*60_000,60_000*Math.pow(5,Math.max(0,item.attemptCount-1))),safeCode=provider?.safeCode??"TRANSLATION_PROVIDER_FAILED";await db.$transaction([db.catalogTranslationAttempt.updateMany({where:{id:attempt.id,status:"SUBMITTED"},data:{status:ambiguous?"AMBIGUOUS":"DEFINITE_FAILURE",safeErrorCode:safeCode,safeErrorMessage:safeMessage(error),providerRequestId:provider?.requestId,completedAt:now}}),db.catalogTranslationItem.updateMany({where:{id:item.id,claimToken:token},data:{status,nextAttemptAt:status==="RETRYABLE"?new Date(now.getTime()+delay):null,claimToken:null,claimedAt:null,leaseExpiresAt:null,lastErrorCode:safeCode,lastErrorMessage:safeMessage(error)}})]);await refreshJob(db,item.jobId,now);return{itemId,outcome:status};}
  await db.$transaction(async tx=>{const current=await tx.supplierProductLink.findUniqueOrThrow({where:{id:item.supplierProductLinkId},select:{sourceMetadata:true,product:{select:{name:true,description:true}}}}),currentState=productTranslationState({name:current.product.name,description:current.product.description,sourceMetadata:current.sourceMetadata,targetLocale:item.targetLocale});if(currentState.sourceFingerprint!==item.sourceFingerprint||!["MISSING","STALE"].includes(currentState.state)){await tx.catalogTranslationItem.updateMany({where:{id:item.id,claimToken:token},data:{status:"SKIPPED",skippedAt:now,completedAt:now,claimToken:null,claimedAt:null,leaseExpiresAt:null,lastErrorCode:"SOURCE_CHANGED_AFTER_SUBMISSION"}});}else{const metadata=storeGeneratedTranslationProposal({sourceMetadata:current.sourceMetadata,targetLocale:item.targetLocale,title:result.texts[0],description:result.texts[1]??"",sourceFingerprint:item.sourceFingerprint,provider:item.provider,providerVersion:result.providerVersion,translatedAt:now.toISOString()});await tx.supplierProductLink.update({where:{id:item.supplierProductLinkId},data:{sourceMetadata:metadata as Prisma.InputJsonValue}});await tx.catalogTranslationItem.updateMany({where:{id:item.id,claimToken:token},data:{status:"COMPLETED",approvalStatus:"PENDING",proposalWrittenAt:now,completedAt:now,completedCharacters:item.estimatedCharacters,claimToken:null,claimedAt:null,leaseExpiresAt:null,nextAttemptAt:null}});}const billable=result.usage.billable&&result.usage.confirmed?result.usage.characters:null,attemptDone=await tx.catalogTranslationAttempt.updateMany({where:{id:attempt.id,status:"SUBMITTED"},data:{status:"SUCCEEDED",completedCharacters:item.estimatedCharacters,billedCharacters:billable,billingConfirmed:billable!==null,providerRequestId:result.requestId,completedAt:now}});if(attemptDone.count!==1)throw new CatalogTranslationError("TRANSLATION_ATTEMPT_STATE_CONFLICT",409);for(const [periodType,periodStart] of [["DAY",attempt.dailyPeriodStart],["MONTH",attempt.monthlyPeriodStart]] as const)await tx.catalogTranslationBudget.updateMany({where:{provider:item.provider,periodType,periodStart},data:{completedCharacters:{increment:BigInt(item.estimatedCharacters)}}});},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});await refreshJob(db,item.jobId,now);return{itemId,outcome:"COMPLETED"};
}

export async function recoverStaleTranslationLeases(db:PrismaClient,_config:CatalogTranslationConfig,now=new Date()){const stale=await db.catalogTranslationItem.findMany({where:{status:"CLAIMED",leaseExpiresAt:{lte:now}},include:{attempts:{orderBy:{attemptNumber:"desc"},take:1}}});for(const item of stale){const attempt=item.attempts[0];if(attempt?.status==="RESERVED")await releaseReservation(db,attempt,item.provider,now);const ambiguous=attempt?.status==="SUBMITTED";if(ambiguous)await db.catalogTranslationAttempt.updateMany({where:{id:attempt.id,status:"SUBMITTED"},data:{status:"AMBIGUOUS",safeErrorCode:"AMBIGUOUS_SUBMISSION",completedAt:now}});await db.catalogTranslationItem.updateMany({where:{id:item.id,status:"CLAIMED",leaseExpiresAt:{lte:now}},data:{status:ambiguous?"MANUAL_ACTION_REQUIRED":"RETRYABLE",nextAttemptAt:ambiguous?null:now,claimToken:null,claimedAt:null,leaseExpiresAt:null,lastErrorCode:ambiguous?"AMBIGUOUS_SUBMISSION":"STALE_TRANSLATION_CLAIM_RECOVERED"}});}return stale.length;}

export async function processCatalogTranslationQueue(db:PrismaClient,env:NodeJS.ProcessEnv=process.env,translate?:Translator,now=new Date()){const config=catalogTranslationConfig(env);if(!config)return{enabled:false,processed:0,results:[]};const translator=translate??(request=>config.provider.translate(request));await recoverStaleTranslationLeases(db,config,now);const due=await db.catalogTranslationItem.findMany({where:{status:{in:["QUEUED","RETRYABLE"]},OR:[{nextAttemptAt:null},{nextAttemptAt:{lte:now}}],attemptCount:{lt:config.maxAttempts},job:{status:{in:["QUEUED","RUNNING"]}}},orderBy:[{createdAt:"asc"},{id:"asc"}],take:config.perRunItems,select:{id:true,estimatedCharacters:true}}),selected=[] as typeof due;let characters=0;for(const item of due){if(characters+item.estimatedCharacters>config.perRunCharacters)continue;selected.push(item);characters+=item.estimatedCharacters;}const results=[];for(let offset=0;offset<selected.length;offset+=config.concurrency)results.push(...await Promise.all(selected.slice(offset,offset+config.concurrency).map(item=>processItem(db,item.id,config,translator,now))));return{enabled:true,processed:results.length,characters,results};}

export async function pauseCatalogTranslationJob(db:Db,adminId:string,jobId:string){const changed=await db.catalogTranslationJob.updateMany({where:{id:jobId,createdById:adminId,status:{in:["QUEUED","RUNNING"]}},data:{status:"PAUSED",pausedAt:new Date()}});if(changed.count!==1)throw new CatalogTranslationError("TRANSLATION_JOB_NOT_PAUSABLE",409);return{paused:true};}
export async function retryCatalogTranslationItems(db:Db,adminId:string,jobId:string,itemIds:unknown){const selected=ids(itemIds),job=await db.catalogTranslationJob.findFirst({where:{id:jobId,createdById:adminId},select:{id:true}});if(!job)throw new CatalogTranslationError("TRANSLATION_JOB_NOT_FOUND",404);const changed=await db.catalogTranslationItem.updateMany({where:{jobId,status:{in:["RETRYABLE","MANUAL_ACTION_REQUIRED"]},...(selected.length?{id:{in:selected}}:{})},data:{status:"RETRYABLE",nextAttemptAt:new Date(),claimToken:null,claimedAt:null,leaseExpiresAt:null,lastErrorCode:null,lastErrorMessage:null}});await db.catalogTranslationJob.update({where:{id:jobId},data:{status:"RUNNING",pausedAt:null,completedAt:null}});return{retried:changed.count};}
