import type { Prisma, PrismaClient } from "@prisma/client";
import { requireStoreCapability, SellerCapabilityError } from "./seller-business-access";
import { appendSellerBusinessAudit } from "./seller-business-audit";
type Db=PrismaClient|Prisma.TransactionClient;
const detailSelect={id:true,buyerId:true,sellerId:true,storeId:true,lastMessageAt:true,product:{select:{id:true,name:true,images:true,price:true,currency:true}},store:{select:{name:true,slug:true}},buyer:{select:{firstName:true,lastName:true}},seller:{select:{firstName:true,lastName:true}},messages:{orderBy:{createdAt:"asc" as const},select:{id:true,body:true,senderId:true,readAt:true,createdAt:true}}};

async function authorizeConversation(db:Db,id:string,userId:string,permission:"MESSAGE_VIEW"|"MESSAGE_REPLY"){
 const conversation=await db.conversation.findUnique({where:{id},select:{id:true,buyerId:true,sellerId:true,storeId:true,store:{select:{businessId:true}},product:{select:{name:true}}}});if(!conversation)return null;
 if(conversation.buyerId===userId||conversation.sellerId===userId)return conversation;
 try{await requireStoreCapability(db,userId,conversation.storeId,permission);return conversation}catch(error){if(error instanceof SellerCapabilityError)return null;throw error}
}
export async function conversationForUser(db:Db,id:string,userId:string){if(!await authorizeConversation(db,id,userId,"MESSAGE_VIEW"))return null;return db.conversation.findUnique({where:{id},select:detailSelect})}
export async function sendConversationMessage(db:PrismaClient,id:string,userId:string,body:string){const conversation=await authorizeConversation(db,id,userId,"MESSAGE_REPLY");if(!conversation)return null;const recipientId=conversation.buyerId===userId?conversation.sellerId:conversation.buyerId;const notificationId=await db.$transaction(async tx=>{await tx.message.create({data:{conversationId:id,senderId:userId,body}});await tx.conversation.update({where:{id},data:{lastMessageAt:new Date()}});await tx.notification.deleteMany({where:{userId:recipientId,type:"NEW_MESSAGE",href:`/messages/${id}`,readAt:null}});const notification=(await tx.notification.create({data:{userId:recipientId,type:"NEW_MESSAGE",title:"Nouveau message",body:`Nouveau message concernant ${conversation.product.name}.`,href:`/messages/${id}`},select:{id:true}})).id;if(conversation.buyerId!==userId&&conversation.store.businessId)await appendSellerBusinessAudit(tx,{businessId:conversation.store.businessId,storeId:conversation.storeId,actorId:userId,category:"MESSAGE",action:"MESSAGE_REPLIED",targetType:"Conversation",targetId:id});return notification});return{notificationId}}
export async function markConversationRead(db:PrismaClient,id:string,userId:string){if(!await authorizeConversation(db,id,userId,"MESSAGE_VIEW"))return;await Promise.all([db.message.updateMany({where:{conversationId:id,senderId:{not:userId},readAt:null},data:{readAt:new Date()}}),db.notification.updateMany({where:{userId,href:{endsWith:`/messages/${id}`},readAt:null},data:{readAt:new Date()}})])}
