import "server-only";
import {createHash,randomUUID} from "node:crypto";
import {Prisma,type PrismaClient} from "@prisma/client";
import {isLocale,type Locale} from "../i18n/config";
import type {CatalogTranslationConfig} from "./catalog-translation-config";
import {dynamicTranslationConfig} from "./dynamic-translation-config";
import {DYNAMIC_TRANSLATION_LOCALES} from "./dynamic-translation-locales";
import {readProductContentMetadata} from "./product-content";
import {TranslationProviderError,type TranslationProviderResult} from "./translation-provider";
import {runBoundedTranslationWork} from "./translation-worker";

type EntityType="PRODUCT"|"NEWS_ARTICLE";
type Task={id:string;entityType:string;entityId:string;sourceLocale:string;targetLocale:string;sourceFingerprint:string;sourceTitle:string;sourceContent:string;estimatedCharacters:number};
type Translator=(input:{sourceLocale:Locale;targetLocale:Locale;texts:string[]})=>Promise<TranslationProviderResult>;
const DISCOVERY_LIMIT=50,LEASE_MS=10*60_000;
const LAST_ERROR_CODE_MAX=100;
export {DYNAMIC_TRANSLATION_LOCALES} from "./dynamic-translation-locales";

export function fairDynamicTranslationTasks<T extends {entityType:string}>(products:readonly T[],news:readonly T[],limit:number){const selected:T[]=[];for(let index=0;selected.length<limit&&(index<news.length||index<products.length);index++){if(index<news.length)selected.push(news[index]);if(selected.length<limit&&index<products.length)selected.push(products[index]);}return selected;}

function errorObject(value:unknown):Record<string,unknown>{return typeof value==="object"&&value!==null?value as Record<string,unknown>:{};}
function hasSerializationConflict(error:unknown){const outer=errorObject(error),meta=errorObject(outer.meta),cause=errorObject(outer.cause);return [outer.code,meta.code,cause.code].includes("40001")||outer.code==="P2034"||String(outer.message??"").includes("40001");}
export function dynamicTranslationFailure(error:unknown){const provider=error instanceof TranslationProviderError?error:null,serialization=hasSerializationConflict(error),raw=serialization?"DATABASE_SERIALIZATION_CONFLICT":provider?.safeCode??(error instanceof Error?error.message:"TRANSLATION_FAILED"),lastErrorCode=raw.replace(/[\u0000-\u001f\u007f]+/g," ").replace(/\s+/g," ").trim().slice(0,LAST_ERROR_CODE_MAX)||"TRANSLATION_FAILED",retryable=serialization||Boolean(provider?.retryable),status=provider?.category==="AMBIGUOUS_SUBMISSION"?"MANUAL_ACTION_REQUIRED":retryable?"RETRYABLE":"FAILED";return{lastErrorCode,retryable,status};}
export async function recordDynamicTranslationFailure(db:PrismaClient,task:Pick<Task,"id"|"entityType"|"targetLocale">,claimToken:string,error:unknown,now:Date){const failure=dynamicTranslationFailure(error);console.warn("[dynamic-translation-worker]",JSON.stringify({event:"task_failed",taskId:task.id,entityType:task.entityType,targetLocale:task.targetLocale,errorCode:failure.lastErrorCode,retryable:failure.retryable}));await db.dynamicContentTranslationTask.updateMany({where:{id:task.id,claimToken},data:{status:failure.status,claimToken:null,leaseExpiresAt:null,lastErrorCode:failure.lastErrorCode,nextAttemptAt:failure.retryable?new Date(now.getTime()+30_000):null}});return failure;}

function budgetPeriods(now:Date){return{day:new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate())),month:new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1))};}
async function reserveDynamicBudget(db:PrismaClient,task:Task,config:CatalogTranslationConfig,now:Date){const amount=BigInt(task.estimatedCharacters),{day,month}=budgetPeriods(now);await db.$transaction(async tx=>{for(const[periodType,periodStart,limit]of[["DAY",day,config.dailyCharacters],["MONTH",month,config.monthlyCharacters]]as const){const rows=await tx.$queryRaw<Array<{id:string}>>(Prisma.sql`INSERT INTO "CatalogTranslationBudget" ("id","provider","periodType","periodStart","limitCharacters","reservedCharacters","submittedCharacters","completedCharacters","createdAt","updatedAt") VALUES (${randomUUID()},${config.provider.id},${periodType}::"CatalogTranslationBudgetPeriod",${periodStart},${BigInt(limit)},0,${amount},0,${now},${now}) ON CONFLICT ("provider","periodType","periodStart") DO UPDATE SET "limitCharacters"=EXCLUDED."limitCharacters","submittedCharacters"="CatalogTranslationBudget"."submittedCharacters"+${amount},"updatedAt"=${now} WHERE "CatalogTranslationBudget"."submittedCharacters"+"CatalogTranslationBudget"."reservedCharacters"+${amount}<=EXCLUDED."limitCharacters" RETURNING "id"`);if(rows.length!==1)throw new Error(`TRANSLATION_${periodType}_BUDGET_EXHAUSTED`);}},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});return{day,month};}
async function completeDynamicBudget(db:PrismaClient,config:CatalogTranslationConfig,periods:{day:Date;month:Date},amount:number){await db.$transaction([db.catalogTranslationBudget.updateMany({where:{provider:config.provider.id,periodType:"DAY",periodStart:periods.day},data:{completedCharacters:{increment:BigInt(amount)}}}),db.catalogTranslationBudget.updateMany({where:{provider:config.provider.id,periodType:"MONTH",periodStart:periods.month},data:{completedCharacters:{increment:BigInt(amount)}}})]);}

export function dynamicContentFingerprint(sourceLocale:string,title:string,content:string){return createHash("sha256").update(JSON.stringify({sourceLocale,title,content})).digest("hex");}
function locale(value:string):Locale{return isLocale(value)?value:"en";}
export function dynamicContentTargets(sourceLocale:string){const normalized=locale(sourceLocale);return DYNAMIC_TRANSLATION_LOCALES.filter(target=>target!==normalized);}
function tasks(entityType:EntityType,entityId:string,sourceLocale:string,title:string,content:string){const normalized=locale(sourceLocale),sourceFingerprint=dynamicContentFingerprint(normalized,title,content),estimatedCharacters=[title,content].join("").length;return dynamicContentTargets(normalized).map(targetLocale=>({entityType,entityId,sourceLocale:normalized,targetLocale,sourceFingerprint,sourceTitle:title,sourceContent:content,estimatedCharacters}));}
export function dynamicTranslationFieldsMatchTarget(targetLocale:string,title:string,content:string){const fields=[title,content].filter(value=>value.trim().length>0);if(targetLocale==="ar")return fields.every(value=>/\p{Script=Arabic}/u.test(value));if(targetLocale==="zh")return fields.every(value=>/\p{Script=Han}/u.test(value));return true;}
export async function translateDynamicContentFields(task:Pick<Task,"sourceLocale"|"targetLocale"|"sourceTitle"|"sourceContent">,translate:Translator){const request={sourceLocale:locale(task.sourceLocale),targetLocale:locale(task.targetLocale)},title=await translate({...request,texts:[task.sourceTitle]}),content=await translate({...request,texts:[task.sourceContent]}),texts=[title.texts[0]?.trim(),content.texts[0]?.trim()];if(texts.some(value=>!value)||!dynamicTranslationFieldsMatchTarget(task.targetLocale,texts[0]??"",texts[1]??""))throw new TranslationProviderError("MALFORMED_RESPONSE","TRANSLATION_TARGET_LANGUAGE_MISMATCH",true);const characters=title.usage.characters===null||content.usage.characters===null?null:title.usage.characters+content.usage.characters;return{...title,texts:texts as[string,string],usage:{characters,billable:title.usage.billable||content.usage.billable,confirmed:title.usage.confirmed&&content.usage.confirmed}};}

export async function discoverDynamicContentTranslationTasks(db:PrismaClient){
  const [products,articles]=await Promise.all([
    db.product.findMany({where:{removedAt:null},orderBy:{updatedAt:"desc"},take:DISCOVERY_LIMIT,select:{id:true,sourceLocale:true,name:true,description:true}}),
    db.newsArticle.findMany({where:{published:true},orderBy:{updatedAt:"desc"},take:DISCOVERY_LIMIT,select:{id:true,locale:true,title:true,content:true,translations:{select:{locale:true,title:true,content:true,automatic:true}}}}),
  ]);
  const data=[...products.flatMap(item=>tasks("PRODUCT",item.id,item.sourceLocale,item.name,item.description)),...articles.flatMap(item=>tasks("NEWS_ARTICLE",item.id,item.locale,item.title,item.content))];
  if(data.length)await db.dynamicContentTranslationTask.createMany({data,skipDuplicates:true});
  for(const article of articles){const sourceFingerprint=dynamicContentFingerprint(locale(article.locale),article.title,article.content);for(const translation of article.translations){if(!translation.automatic||!DYNAMIC_TRANSLATION_LOCALES.includes(translation.locale as typeof DYNAMIC_TRANSLATION_LOCALES[number])||dynamicTranslationFieldsMatchTarget(translation.locale,translation.title,translation.content))continue;await db.dynamicContentTranslationTask.updateMany({where:{entityType:"NEWS_ARTICLE",entityId:article.id,targetLocale:translation.locale,sourceFingerprint,status:"COMPLETED"},data:{status:"RETRYABLE",attemptCount:0,nextAttemptAt:null,claimToken:null,leaseExpiresAt:null,completedAt:null,lastErrorCode:"AUTOMATIC_TRANSLATION_LANGUAGE_MISMATCH"}});}}
  return data.length;
}

async function currentSource(db:PrismaClient,task:Task){if(task.entityType==="PRODUCT"){const item=await db.product.findUnique({where:{id:task.entityId},select:{name:true,description:true,sourceLocale:true,supplierLink:{select:{sourceMetadata:true}}}});return item?{title:item.name,content:item.description,sourceLocale:locale(item.sourceLocale),supplierMetadata:item.supplierLink?.sourceMetadata}:null;}if(task.entityType==="NEWS_ARTICLE"){const item=await db.newsArticle.findUnique({where:{id:task.entityId},select:{title:true,content:true,locale:true}});return item?{title:item.title,content:item.content,sourceLocale:locale(item.locale),supplierMetadata:null}:null;}return null;}
async function persist(db:PrismaClient,task:Task,result:TranslationProviderResult,config:CatalogTranslationConfig,claimToken:string,now:Date){return db.$transaction(async tx=>{
  const source=await currentSource(tx as PrismaClient,task);if(!source||dynamicContentFingerprint(source.sourceLocale,source.title,source.content)!==task.sourceFingerprint){await tx.dynamicContentTranslationTask.updateMany({where:{id:task.id,claimToken},data:{status:"SUPERSEDED",claimToken:null,leaseExpiresAt:null,completedAt:now}});return"SUPERSEDED";}
  if(task.entityType==="PRODUCT"){
    const supplierManual=readProductContentMetadata(source.supplierMetadata)?.localized[task.targetLocale];
    const existing=await tx.productTranslation.findUnique({where:{productId_locale:{productId:task.entityId,locale:task.targetLocale}},select:{automatic:true}});
    if((supplierManual&&(supplierManual.source==="MANUAL"||supplierManual.source==="SUPPLIER"||supplierManual.generated===false))||existing?.automatic===false){await tx.dynamicContentTranslationTask.updateMany({where:{id:task.id,claimToken},data:{status:"SKIPPED_MANUAL",claimToken:null,leaseExpiresAt:null,completedAt:now}});return"SKIPPED_MANUAL";}
    await tx.productTranslation.upsert({where:{productId_locale:{productId:task.entityId,locale:task.targetLocale}},create:{productId:task.entityId,locale:task.targetLocale,title:result.texts[0],description:result.texts[1]??"",automatic:true,sourceFingerprint:task.sourceFingerprint,provider:config.provider.id,providerVersion:result.providerVersion},update:{title:result.texts[0],description:result.texts[1]??"",sourceFingerprint:task.sourceFingerprint,provider:config.provider.id,providerVersion:result.providerVersion}});
  }else{
    const existing=await tx.newsArticleTranslation.findUnique({where:{articleId_locale:{articleId:task.entityId,locale:task.targetLocale}},select:{automatic:true}});
    if(existing?.automatic===false){await tx.dynamicContentTranslationTask.updateMany({where:{id:task.id,claimToken},data:{status:"SKIPPED_MANUAL",claimToken:null,leaseExpiresAt:null,completedAt:now}});return"SKIPPED_MANUAL";}
    await tx.newsArticleTranslation.upsert({where:{articleId_locale:{articleId:task.entityId,locale:task.targetLocale}},create:{articleId:task.entityId,locale:task.targetLocale,title:result.texts[0],content:result.texts[1]??"",automatic:true,sourceFingerprint:task.sourceFingerprint,provider:config.provider.id,providerVersion:result.providerVersion},update:{title:result.texts[0],content:result.texts[1]??"",sourceFingerprint:task.sourceFingerprint,provider:config.provider.id,providerVersion:result.providerVersion}});
  }
  await tx.dynamicContentTranslationTask.updateMany({where:{id:task.id,claimToken},data:{status:"COMPLETED",claimToken:null,leaseExpiresAt:null,completedAt:now,lastErrorCode:null}});return"COMPLETED";
 });}

async function englishExists(db:PrismaClient,task:Task){if(task.entityType==="PRODUCT")return Boolean(await db.productTranslation.findUnique({where:{productId_locale:{productId:task.entityId,locale:"en"}},select:{id:true}}));if(task.entityType==="NEWS_ARTICLE")return Boolean(await db.newsArticleTranslation.findUnique({where:{articleId_locale:{articleId:task.entityId,locale:"en"}},select:{id:true}}));return false;}

async function processTask(db:PrismaClient,task:Task,config:CatalogTranslationConfig,translate:Translator,now:Date){
  if(!DYNAMIC_TRANSLATION_LOCALES.includes(task.sourceLocale as typeof DYNAMIC_TRANSLATION_LOCALES[number])&&task.targetLocale!=="en"&&!await englishExists(db,task))return{taskId:task.id,outcome:"WAITING_FOR_ENGLISH"};
  const claimToken=randomUUID(),claimed=await db.dynamicContentTranslationTask.updateMany({where:{id:task.id,status:{in:["QUEUED","RETRYABLE"]},attemptCount:{lt:config.maxAttempts}},data:{status:"PROCESSING",claimToken,leaseExpiresAt:new Date(now.getTime()+LEASE_MS),attemptCount:{increment:1}}});
  if(claimed.count!==1)return{taskId:task.id,outcome:"CLAIM_LOST"};
  try{
    const periods=await reserveDynamicBudget(db,task,config,now),result=task.entityType==="NEWS_ARTICLE"?await translateDynamicContentFields(task,translate):await translate({sourceLocale:locale(task.sourceLocale),targetLocale:locale(task.targetLocale),texts:[task.sourceTitle,task.sourceContent]});
    if(result.texts.length<2||result.texts.some(value=>!value.trim()))throw new TranslationProviderError("MALFORMED_RESPONSE","TRANSLATION_PROVIDER_RESPONSE_INVALID",false);
    const outcome=await persist(db,task,result,config,claimToken,now);await completeDynamicBudget(db,config,periods,task.estimatedCharacters);return{taskId:task.id,outcome};
  }catch(error){const failure=await recordDynamicTranslationFailure(db,task,claimToken,error,now);return{taskId:task.id,outcome:failure.status};}
}

export async function processDynamicContentTranslationQueue(db:PrismaClient,env:NodeJS.ProcessEnv=process.env,translate?:Translator,now=new Date()){const config=dynamicTranslationConfig(env);if(!config)return{enabled:false,processed:0,results:[]};await db.dynamicContentTranslationTask.updateMany({where:{status:"PROCESSING",leaseExpiresAt:{lte:now}},data:{status:"RETRYABLE",claimToken:null,leaseExpiresAt:null,nextAttemptAt:now,lastErrorCode:"STALE_TRANSLATION_CLAIM_RECOVERED"}});await db.dynamicContentTranslationTask.updateMany({where:{status:{in:["QUEUED","RETRYABLE"]},targetLocale:{notIn:[...DYNAMIC_TRANSLATION_LOCALES]}},data:{status:"DISABLED_LOCALE",nextAttemptAt:null,lastErrorCode:"AUTOMATIC_LOCALE_NOT_ENABLED"}});await discoverDynamicContentTranslationTasks(db);const translator=translate??(request=>config.provider.translate(request)),dueWhere:Prisma.DynamicContentTranslationTaskWhereInput={status:{in:["QUEUED","RETRYABLE"]},targetLocale:{in:[...DYNAMIC_TRANSLATION_LOCALES]},OR:[{nextAttemptAt:null},{nextAttemptAt:{lte:now}}],attemptCount:{lt:config.maxAttempts}},select={id:true,entityType:true,entityId:true,sourceLocale:true,targetLocale:true,sourceFingerprint:true,sourceTitle:true,sourceContent:true,estimatedCharacters:true} as const;const result=await runBoundedTranslationWork<Task,{taskId:string;outcome:string}>({loadDue:async limit=>{const[products,news]=await Promise.all([db.dynamicContentTranslationTask.findMany({where:{...dueWhere,entityType:"PRODUCT"},orderBy:[{createdAt:"asc"},{id:"asc"}],take:limit,select}),db.dynamicContentTranslationTask.findMany({where:{...dueWhere,entityType:"NEWS_ARTICLE"},orderBy:[{createdAt:"asc"},{id:"asc"}],take:limit,select})]);return fairDynamicTranslationTasks(products,news,limit);},estimatedCharacters:item=>item.estimatedCharacters,processSafely:item=>processTask(db,item,config,translator,now)},{items:config.perRunItems,characters:config.perRunCharacters,concurrency:config.concurrency});return{enabled:true,...result};}
