const copy = {
  en: { errorTitle: "We couldn’t load this page", errorText: "Your information is safe. Check your connection and try again.", retry: "Try again", home: "Go to Home", notFound: "Page not found", notFoundText: "This page does not exist or is no longer available.", continueShopping: "Continue shopping" },
  fr: { errorTitle: "Impossible de charger cette page", errorText: "Vos informations sont en sécurité. Vérifiez votre connexion et réessayez.", retry: "Réessayer", home: "Retour à l’accueil", notFound: "Page introuvable", notFoundText: "Cette page n’existe pas ou n’est plus disponible.", continueShopping: "Continuer mes achats" },
  de: { errorTitle: "Diese Seite konnte nicht geladen werden", errorText: "Ihre Daten sind sicher. Prüfen Sie die Verbindung und versuchen Sie es erneut.", retry: "Erneut versuchen", home: "Zur Startseite", notFound: "Seite nicht gefunden", notFoundText: "Diese Seite existiert nicht oder ist nicht mehr verfügbar.", continueShopping: "Weiter einkaufen" },
  es: { errorTitle: "No pudimos cargar esta página", errorText: "Tu información está segura. Comprueba la conexión e inténtalo de nuevo.", retry: "Reintentar", home: "Ir al inicio", notFound: "Página no encontrada", notFoundText: "Esta página no existe o ya no está disponible.", continueShopping: "Seguir comprando" },
  it: { errorTitle: "Impossibile caricare questa pagina", errorText: "Le tue informazioni sono al sicuro. Controlla la connessione e riprova.", retry: "Riprova", home: "Vai alla Home", notFound: "Pagina non trovata", notFoundText: "Questa pagina non esiste o non è più disponibile.", continueShopping: "Continua gli acquisti" },
  nl: { errorTitle: "Deze pagina kon niet worden geladen", errorText: "Je gegevens zijn veilig. Controleer je verbinding en probeer opnieuw.", retry: "Opnieuw proberen", home: "Naar Home", notFound: "Pagina niet gevonden", notFoundText: "Deze pagina bestaat niet of is niet meer beschikbaar.", continueShopping: "Verder winkelen" },
  zh: { errorTitle: "无法加载此页面", errorText: "您的信息是安全的。请检查网络连接后重试。", retry: "重试", home: "返回首页", notFound: "找不到页面", notFoundText: "此页面不存在或已不再可用。", continueShopping: "继续购物" },
  tr: { errorTitle: "Bu sayfa yüklenemedi", errorText: "Bilgileriniz güvende. Bağlantınızı kontrol edip tekrar deneyin.", retry: "Tekrar dene", home: "Ana sayfaya git", notFound: "Sayfa bulunamadı", notFoundText: "Bu sayfa mevcut değil veya artık kullanılamıyor.", continueShopping: "Alışverişe devam et" },
  ar: { errorTitle: "تعذّر تحميل هذه الصفحة", errorText: "معلوماتك آمنة. تحقّق من اتصالك وحاول مرة أخرى.", retry: "حاول مرة أخرى", home: "العودة إلى الرئيسية", notFound: "الصفحة غير موجودة", notFoundText: "هذه الصفحة غير موجودة أو لم تعد متاحة.", continueShopping: "متابعة التسوق" },
  ku: { errorTitle: "ئەم پەڕەیە بار نەکرا", errorText: "زانیارییەکانت پارێزراون. پەیوەندییەکەت بپشکنە و دووبارە هەوڵ بدەوە.", retry: "دووبارە هەوڵدانەوە", home: "گەڕانەوە بۆ سەرەکی", notFound: "پەڕەکە نەدۆزرایەوە", notFoundText: "ئەم پەڕەیە بوونی نییە یان چیتر بەردەست نییە.", continueShopping: "بەردەوامبوون لە کڕین" },
  fa: { errorTitle: "این صفحه بارگیری نشد", errorText: "اطلاعات شما امن است. اتصال اینترنت را بررسی کنید و دوباره تلاش کنید.", retry: "تلاش دوباره", home: "رفتن به صفحه اصلی", notFound: "صفحه پیدا نشد", notFoundText: "این صفحه وجود ندارد یا دیگر در دسترس نیست.", continueShopping: "ادامه خرید" },
  hi: { errorTitle: "यह पेज लोड नहीं हो सका", errorText: "आपकी जानकारी सुरक्षित है। अपना कनेक्शन जाँचें और फिर से कोशिश करें।", retry: "फिर से कोशिश करें", home: "होम पेज पर जाएँ", notFound: "पेज नहीं मिला", notFoundText: "यह पेज मौजूद नहीं है या अब उपलब्ध नहीं है।", continueShopping: "खरीदारी जारी रखें" },
  pt: { errorTitle: "Não foi possível carregar esta página", errorText: "As suas informações estão seguras. Verifique a ligação e tente novamente.", retry: "Tentar novamente", home: "Ir para o início", notFound: "Página não encontrada", notFoundText: "Esta página não existe ou já não está disponível.", continueShopping: "Continuar a comprar" },
  ru: { errorTitle: "Не удалось загрузить страницу", errorText: "Ваши данные в безопасности. Проверьте подключение и повторите попытку.", retry: "Повторить", home: "На главную", notFound: "Страница не найдена", notFoundText: "Эта страница не существует или больше недоступна.", continueShopping: "Продолжить покупки" },
} as const;

export function feedbackCopy(locale: string) { return copy[locale as keyof typeof copy] ?? copy.en; }
