import "server-only";
import {isLocale,locales} from "../i18n/config";
import {TranslationProviderError,type TranslationProvider,type TranslationProviderRequest,type TranslationProviderResult} from "./translation-provider";

function endpoint(value:string){let url:URL;try{url=new URL(value);}catch{throw new TranslationProviderError("INVALID_CONFIGURATION","DYNAMIC_TRANSLATION_URL_INVALID",false);}if(!["http:","https:"].includes(url.protocol)||url.username||url.password)throw new TranslationProviderError("INVALID_CONFIGURATION","DYNAMIC_TRANSLATION_URL_INVALID",false);url.pathname=url.pathname.replace(/\/$/,"");if(!url.pathname.endsWith("/translate"))url.pathname+="/translate";url.search="";url.hash="";return url;}

export function createSelfHostedTranslationProvider(env:NodeJS.ProcessEnv=process.env,fetcher:typeof fetch=fetch):TranslationProvider{
  const url=endpoint(env.DYNAMIC_TRANSLATION_URL?.trim()??""),apiKey=env.DYNAMIC_TRANSLATION_API_KEY?.trim()||null;
  return{id:"SELF_HOSTED_LIBRETRANSLATE",version:"libretranslate-v1",accountingMode:"CAPACITY_ONLY",supportedLocales:locales,health:()=>({configured:true,ready:true}),translate:async(request:TranslationProviderRequest):Promise<TranslationProviderResult>=>{
    if(!isLocale(request.sourceLocale)||!isLocale(request.targetLocale))throw new TranslationProviderError("UNSUPPORTED_LOCALE","TRANSLATION_LOCALE_UNSUPPORTED",false);
    const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),15_000);
    try{const response=await fetcher(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({q:request.texts,source:request.sourceLocale,target:request.targetLocale,format:"text",...(apiKey?{api_key:apiKey}:{})}),redirect:"error",signal:controller.signal});if(!response.ok)throw new TranslationProviderError(response.status===429?"RATE_LIMITED":"DEFINITE_PROVIDER_FAILURE",`SELF_HOSTED_TRANSLATION_HTTP_${response.status}`,response.status===429||response.status>=500);const body=await response.json() as {translatedText?:unknown},texts=Array.isArray(body.translatedText)?body.translatedText:request.texts.length===1&&typeof body.translatedText==="string"?[body.translatedText]:[];if(texts.length!==request.texts.length||texts.some(value=>typeof value!=="string"||!value.trim()))throw new TranslationProviderError("MALFORMED_RESPONSE","SELF_HOSTED_TRANSLATION_RESPONSE_INVALID",false);return{texts:texts as string[],requestId:response.headers.get("x-request-id"),providerVersion:"libretranslate-v1",usage:{characters:null,billable:false,confirmed:true}};}catch(error){if(error instanceof TranslationProviderError)throw error;if(error instanceof Error&&error.name==="AbortError")throw new TranslationProviderError("TIMEOUT_PRE_SUBMISSION","SELF_HOSTED_TRANSLATION_TIMEOUT",true);throw new TranslationProviderError("PROVIDER_UNAVAILABLE","SELF_HOSTED_TRANSLATION_UNAVAILABLE",true);}finally{clearTimeout(timeout);}
  }};
}
