import { notFound } from "next/navigation";
import HomeClient from "@/app/HomeClient";
import NewProductForm from "@/app/seller/products/new/NewProductForm";
import StripeConnectSection from "@/components/StripeConnectSection";
import AskSellerButton from "@/components/AskSellerButton";
import ProductReportButton from "@/components/ProductReportButton";
import StoreSettingsForm from "@/app/seller/store-settings/StoreSettingsForm";
import SupplierProductManager from "@/components/SupplierProductManager";
import ProductGallery from "@/app/product/[id]/ProductGallery";
import ProductPurchasePanel from "@/components/ProductPurchasePanel";

const products = [
  { id: "e2e-product-x", name: "Buyer A favorite", price: "29.99", compareAtPrice: null, currency: "EUR", category: "electronics", stock: 4, hasActiveVariants: false, isGenerallyAvailable: true, condition: "NEUF", image: null, storeName: "Todijo Test Store", storeSlug: "todijo-test", city: "Paris", country: "France", createdAt: new Date(0).toISOString() },
  { id: "e2e-product-y", name: "Buyer B favorite", price: "39.99", compareAtPrice: null, currency: "EUR", category: "electronics", stock: 4, hasActiveVariants: false, isGenerallyAvailable: true, condition: "NEUF", image: null, storeName: "Todijo Test Store", storeSlug: "todijo-test", city: "Lyon", country: "France", createdAt: new Date(1).toISOString() },
];
const galleryImage = (label: string, color: string) => `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="900" height="900"><rect width="900" height="900" fill="${color}"/><text x="450" y="470" text-anchor="middle" font-family="Arial" font-size="72" fill="white">${label}</text></svg>`)}`;
const galleryImages = [galleryImage("Image 1", "#087653"), galleryImage("Image 2", "#315f50")];

export default async function UxVerificationPage({ searchParams }: { searchParams: Promise<{ view?: string }> }) {
  if (process.env.NODE_ENV === "production") notFound();
  const { view } = await searchParams;
  if (view === "seller") return <main><NewProductForm currency="EUR" productCount={0} productLimit={null}/></main>;
  if (view === "stripe") return <main className="premiumDashboard"><section className="premiumDashboardMain"><div className="premiumDashboardContent"><StripeConnectSection initialStatus={{ connected: true, onboardingComplete: false, chargesEnabled: false, payoutsEnabled: false }}/></div></section></main>;
  if (view === "contact") return <main className="productDetailPage"><section className="productDetailDescriptionSection"><h1>Product</h1><p className="productDetailDescription">A readable description with a verylongunbrokensequencethatmustwrapsafelywithoutescapingtheproductcardorcreatinghorizontaloverflow.</p></section><div className="productAskSeller"><AskSellerButton productId="e2e-product-x" loggedIn/></div></main>;
  if (view === "product-lower") return <main className="productDetailPage"><section className="productDetailShell"><section className="productCompliancePublic"><h2>Informations sur le produit</h2><dl><div><dt>Identifiant du produit</dt><dd>SKU-TEST-123</dd></div><div><dt>Fabricant / producteur</dt><dd>Fabricant exemple</dd></div></dl><div className="productComplianceLongText"><section><h3>Informations de sécurité</h3><p>Conserver loin de toute source de chaleur. UneLongueValeurSansEspacesQuiDoitSeReplierSansDépasserLaCarteProduit.</p></section><section><h3>Autres informations de conformité</h3><p>Respecter les instructions du fabricant et conserver les références du produit pour toute demande ultérieure.</p></section></div></section><div className="productLowerActions"><div className="productAskSeller"><AskSellerButton productId="e2e-product-x" loggedIn/></div><ProductReportButton productId="e2e-product-x" loggedIn/></div></section></main>;
  if (view === "product-gallery") return <main className="productDetailPage"><section className="productDetailShell"><div className="productGallery"><ProductGallery images={galleryImages} productName="Produit de démonstration" media={[{type:"VIDEO",url:"https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",posterUrl:galleryImages[0]}]}/></div></section></main>;
  if (view === "buyer-path") return <main className="productDetailPage"><h1>Stage 5 variant product</h1><ProductPurchasePanel availabilityLabel="Available" colors={[]} sizes={[]} options={[{id:"color",name:"Color",position:0,values:[{id:"black",value:"Black",position:0},{id:"blue",value:"Blue",position:1}]},{id:"size",name:"Size",position:1,values:[{id:"small",value:"S",position:0},{id:"medium",value:"M",position:1}]}]} variants={[{id:"variant-black-s",stock:2,active:true,priceOverride:21,values:[{optionValue:{id:"black",value:"Black",option:{id:"color",name:"Color",position:0}}},{optionValue:{id:"small",value:"S",option:{id:"size",name:"Size",position:1}}}]},{id:"variant-blue-m",stock:3,active:true,priceOverride:24,values:[{optionValue:{id:"blue",value:"Blue",option:{id:"color",name:"Color",position:0}}},{optionValue:{id:"medium",value:"M",option:{id:"size",name:"Size",position:1}}}]}]} product={{id:"stage5-variant-product",name:"Stage 5 variant product",price:20,currency:"EUR",stock:0,storeName:"Stage 5 Store",storeSlug:"stage5-store"}}/></main>;
  if (view === "shipping") return <main className="premiumDashboard"><section className="premiumDashboardMain"><div className="premiumDashboardContent"><StoreSettingsForm initialValues={{name:"Boutique test",description:"",contactEmail:"seller@example.com",phone:"",logo:"",banner:"",country:"France",city:"Paris",currency:"EUR",language:"fr",sellerType:"PRIVATE",legalBusinessName:"",businessRegistrationId:"",businessAddress:"",businessPostalCode:"",vatNumber:"",vatStatus:"NOT_REGISTERED_OR_NOT_APPLICABLE",shippingEnabled:true,shippingMethodName:"Livraison standard",shippingPrice:"4.90",shippingFree:false,shippingFreeThreshold:"",shippingMinDays:2,shippingMaxDays:5,shippingCountries:["FR","BE","DE"],shippingWorldwide:false,shippingPostalCodes:["59*"],shippingCarrier:"La Poste"}}/></div></section></main>;
  if (view === "supplier") return <main className="premiumDashboard"><section className="premiumDashboardMain"><div className="premiumDashboardContent"><SupplierProductManager products={[{productId:"test",name:"Imported test product",provider:"CJ",supplierCost:"8.00",supplierCurrency:"USD",supplierStock:12,syncStatus:"PRICE_CHANGED",lastSyncedAt:new Date(0).toISOString(),sellingPrice:"24.99",currency:"EUR"}]}/></div></section></main>;
  return <HomeClient products={products} heroProducts={products} newArrivals={[]} bestSellers={[]} stores={[]} categories={["electronics"]} total={2} page={1} pageSize={24} initialFilters={{ q: "", category: "", minPrice: "", maxPrice: "", condition: "", country: "", rating: "", availability: "", sort: "newest", color: "", size: "", season: "" }} facets={{ countries:["France"], colors:[], sizes:[], seasons:[] }} resultsOnly={view !== "home"}/>;
}
