import type {Locale} from "./config";
type Text={deliveryCountry:string;selectDeliveryCountry:string;destinationRequired:string;pricingLoading:string;pricingUnavailable:string};
const en:Text={deliveryCountry:"Delivery country",selectDeliveryCountry:"Select your country",destinationRequired:"Select a delivery country to see the verified price.",pricingLoading:"Checking price and deliveryâ€¦",pricingUnavailable:"Price is temporarily unavailable for this destination."};
export const buyerPricingMessages:Record<Locale,Text>={
 en,fr:{deliveryCountry:"Pays de livraison",selectDeliveryCountry:"SÃ©lectionnez votre pays",destinationRequired:"SÃ©lectionnez un pays de livraison pour voir le prix vÃ©rifiÃ©.",pricingLoading:"VÃ©rification du prix et de la livraisonâ€¦",pricingUnavailable:"Prix temporairement indisponible pour cette destination."},
 ar:{deliveryCountry:"Ø¨Ù„Ø¯ Ø§Ù„ØªÙˆØµÙŠÙ„",selectDeliveryCountry:"Ø§Ø®ØªØ± Ø¨Ù„Ø¯Ùƒ",destinationRequired:"Ø§Ø®ØªØ± Ø¨Ù„Ø¯ Ø§Ù„ØªÙˆØµÙŠÙ„ Ù„Ø¹Ø±Ø¶ Ø§Ù„Ø³Ø¹Ø± Ø§Ù„Ù…ØªØ­Ù‚Ù‚ Ù…Ù†Ù‡.",pricingLoading:"Ø¬Ø§Ø±Ù Ø§Ù„ØªØ­Ù‚Ù‚ Ù…Ù† Ø§Ù„Ø³Ø¹Ø± ÙˆØ§Ù„ØªÙˆØµÙŠÙ„â€¦",pricingUnavailable:"Ø§Ù„Ø³Ø¹Ø± ØºÙŠØ± Ù…ØªØ§Ø­ Ù…Ø¤Ù‚ØªÙ‹Ø§ Ù„Ù‡Ø°Ù‡ Ø§Ù„ÙˆØ¬Ù‡Ø©."},
 de:{deliveryCountry:"Lieferland",selectDeliveryCountry:"Land auswÃ¤hlen",destinationRequired:"WÃ¤hlen Sie ein Lieferland, um den verifizierten Preis zu sehen.",pricingLoading:"Preis und Lieferung werden geprÃ¼ftâ€¦",pricingUnavailable:"Der Preis ist fÃ¼r dieses Ziel vorÃ¼bergehend nicht verfÃ¼gbar."},
 es:{deliveryCountry:"PaÃ­s de entrega",selectDeliveryCountry:"Selecciona tu paÃ­s",destinationRequired:"Selecciona un paÃ­s de entrega para ver el precio verificado.",pricingLoading:"Comprobando precio y entregaâ€¦",pricingUnavailable:"El precio no estÃ¡ disponible temporalmente para este destino."},
 fa:{deliveryCountry:"Ú©Ø´ÙˆØ± ØªØ­ÙˆÛŒÙ„",selectDeliveryCountry:"Ú©Ø´ÙˆØ± Ø®ÙˆØ¯ Ø±Ø§ Ø§Ù†ØªØ®Ø§Ø¨ Ú©Ù†ÛŒØ¯",destinationRequired:"Ø¨Ø±Ø§ÛŒ Ù…Ø´Ø§Ù‡Ø¯Ù‡ Ù‚ÛŒÙ…Øª ØªØ£ÛŒÛŒØ¯Ø´Ø¯Ù‡ØŒ Ú©Ø´ÙˆØ± ØªØ­ÙˆÛŒÙ„ Ø±Ø§ Ø§Ù†ØªØ®Ø§Ø¨ Ú©Ù†ÛŒØ¯.",pricingLoading:"Ø¯Ø± Ø­Ø§Ù„ Ø¨Ø±Ø±Ø³ÛŒ Ù‚ÛŒÙ…Øª Ùˆ ØªØ­ÙˆÛŒÙ„â€¦",pricingUnavailable:"Ù‚ÛŒÙ…Øª Ø¨Ø±Ø§ÛŒ Ø§ÛŒÙ† Ù…Ù‚ØµØ¯ Ù…ÙˆÙ‚ØªØ§Ù‹ Ø¯Ø± Ø¯Ø³ØªØ±Ø³ Ù†ÛŒØ³Øª."},
 hi:{deliveryCountry:"à¤¡à¤¿à¤²à¥€à¤µà¤°à¥€ à¤¦à¥‡à¤¶",selectDeliveryCountry:"à¤…à¤ªà¤¨à¤¾ à¤¦à¥‡à¤¶ à¤šà¥à¤¨à¥‡à¤‚",destinationRequired:"à¤¸à¤¤à¥à¤¯à¤¾à¤ªà¤¿à¤¤ à¤®à¥‚à¤²à¥à¤¯ à¤¦à¥‡à¤–à¤¨à¥‡ à¤•à¥‡ à¤²à¤¿à¤ à¤¡à¤¿à¤²à¥€à¤µà¤°à¥€ à¤¦à¥‡à¤¶ à¤šà¥à¤¨à¥‡à¤‚à¥¤",pricingLoading:"à¤®à¥‚à¤²à¥à¤¯ à¤”à¤° à¤¡à¤¿à¤²à¥€à¤µà¤°à¥€ à¤•à¥€ à¤œà¤¾à¤à¤š à¤¹à¥‹ à¤°à¤¹à¥€ à¤¹à¥ˆâ€¦",pricingUnavailable:"à¤‡à¤¸ à¤—à¤‚à¤¤à¤µà¥à¤¯ à¤•à¥‡ à¤²à¤¿à¤ à¤®à¥‚à¤²à¥à¤¯ à¤…à¤¸à¥à¤¥à¤¾à¤¯à¥€ à¤°à¥‚à¤ª à¤¸à¥‡ à¤‰à¤ªà¤²à¤¬à¥à¤§ à¤¨à¤¹à¥€à¤‚ à¤¹à¥ˆà¥¤"},
 it:{deliveryCountry:"Paese di consegna",selectDeliveryCountry:"Seleziona il tuo paese",destinationRequired:"Seleziona un paese di consegna per vedere il prezzo verificato.",pricingLoading:"Verifica di prezzo e consegnaâ€¦",pricingUnavailable:"Il prezzo non Ã¨ temporaneamente disponibile per questa destinazione."},
 ku:{deliveryCountry:"ÙˆÚµØ§ØªÛŒ Ú¯Û•ÛŒØ§Ù†Ø¯Ù†",selectDeliveryCountry:"ÙˆÚµØ§ØªÛŒ Ø®Û†Øª Ù‡Û•ÚµØ¨Ú˜ÛŽØ±Û•",destinationRequired:"Ø¨Û† Ø¨ÛŒÙ†ÛŒÙ†ÛŒ Ù†Ø±Ø®ÛŒ Ù¾Ø´Ú©Ù†ÛŒÙ†Ú©Ø±Ø§Ùˆ ÙˆÚµØ§ØªÛŒ Ú¯Û•ÛŒØ§Ù†Ø¯Ù† Ù‡Û•ÚµØ¨Ú˜ÛŽØ±Û•.",pricingLoading:"Ù†Ø±Ø® Ùˆ Ú¯Û•ÛŒØ§Ù†Ø¯Ù† Ù¾Ø´Ú©Ù†ÛŒÙ† Ø¯Û•Ú©Ø±ÛŽØªâ€¦",pricingUnavailable:"Ù†Ø±Ø® Ø¨Û† Ø¦Û•Ù… Ø´ÙˆÛŽÙ†Û• Ú©Ø§ØªÛŒ Ø¨Û•Ø±Ø¯Û•Ø³Øª Ù†ÛŒÛŒÛ•."},
 nl:{deliveryCountry:"Bezorgland",selectDeliveryCountry:"Selecteer uw land",destinationRequired:"Selecteer een bezorgland om de geverifieerde prijs te zien.",pricingLoading:"Prijs en bezorging controlerenâ€¦",pricingUnavailable:"De prijs is tijdelijk niet beschikbaar voor deze bestemming."},
 pt:{deliveryCountry:"PaÃ­s de entrega",selectDeliveryCountry:"Selecione o seu paÃ­s",destinationRequired:"Selecione um paÃ­s de entrega para ver o preÃ§o verificado.",pricingLoading:"A verificar preÃ§o e entregaâ€¦",pricingUnavailable:"O preÃ§o estÃ¡ temporariamente indisponÃ­vel para este destino."},
 ru:{deliveryCountry:"Ð¡Ñ‚Ñ€Ð°Ð½Ð° Ð´Ð¾ÑÑ‚Ð°Ð²ÐºÐ¸",selectDeliveryCountry:"Ð’Ñ‹Ð±ÐµÑ€Ð¸Ñ‚Ðµ ÑÑ‚Ñ€Ð°Ð½Ñƒ",destinationRequired:"Ð’Ñ‹Ð±ÐµÑ€Ð¸Ñ‚Ðµ ÑÑ‚Ñ€Ð°Ð½Ñƒ Ð´Ð¾ÑÑ‚Ð°Ð²ÐºÐ¸, Ñ‡Ñ‚Ð¾Ð±Ñ‹ ÑƒÐ²Ð¸Ð´ÐµÑ‚ÑŒ Ð¿Ñ€Ð¾Ð²ÐµÑ€ÐµÐ½Ð½ÑƒÑŽ Ñ†ÐµÐ½Ñƒ.",pricingLoading:"ÐŸÑ€Ð¾Ð²ÐµÑ€ÑÐµÐ¼ Ñ†ÐµÐ½Ñƒ Ð¸ Ð´Ð¾ÑÑ‚Ð°Ð²ÐºÑƒâ€¦",pricingUnavailable:"Ð¦ÐµÐ½Ð° Ð´Ð»Ñ ÑÑ‚Ð¾Ð³Ð¾ Ð½Ð°Ð¿Ñ€Ð°Ð²Ð»ÐµÐ½Ð¸Ñ Ð²Ñ€ÐµÐ¼ÐµÐ½Ð½Ð¾ Ð½ÐµÐ´Ð¾ÑÑ‚ÑƒÐ¿Ð½Ð°."},
 tr:{deliveryCountry:"Teslimat Ã¼lkesi",selectDeliveryCountry:"Ãœlkenizi seÃ§in",destinationRequired:"DoÄŸrulanmÄ±ÅŸ fiyatÄ± gÃ¶rmek iÃ§in teslimat Ã¼lkesini seÃ§in.",pricingLoading:"Fiyat ve teslimat kontrol ediliyorâ€¦",pricingUnavailable:"Bu varÄ±ÅŸ noktasÄ± iÃ§in fiyat geÃ§ici olarak kullanÄ±lamÄ±yor."},
 zh:{deliveryCountry:"é…é€å›½å®¶",selectDeliveryCountry:"é€‰æ‹©æ‚¨çš„å›½å®¶",destinationRequired:"è¯·é€‰æ‹©é…é€å›½å®¶ä»¥æŸ¥çœ‹å·²éªŒè¯ä»·æ ¼ã€‚",pricingLoading:"æ­£åœ¨æ ¸å¯¹ä»·æ ¼å’Œé…é€â€¦",pricingUnavailable:"æ­¤ç›®çš„åœ°çš„ä»·æ ¼æš‚æ—¶ä¸å¯ç”¨ã€‚"}
};
