import type { Locale } from "./config";

type Labels = Record<"women"|"pets"|"home"|"beauty"|"jewelry"|"men"|"bags-shoes"|"kids"|"sports"|"electronics"|"improvement"|"auto"|"phones"|"computers", string>;

export const categoryNavigationMessages: Record<Locale, Labels> = {
  en:{women:"Women's clothing",pets:"Pet supplies",home:"Home, garden & furniture",beauty:"Health, beauty & hair",jewelry:"Jewelry & watches",men:"Men's clothing","bags-shoes":"Bags & shoes",kids:"Toys, kids & baby",sports:"Sports & outdoors",electronics:"Consumer electronics",improvement:"Home improvement",auto:"Automotive & motorcycles",phones:"Phones & accessories",computers:"Computers & office"},
  fr:{women:"Vêtements pour femmes",pets:"Fournitures pour animaux",home:"Maison, jardin et meubles",beauty:"Santé, beauté et cheveux",jewelry:"Bijoux et montres",men:"Vêtements pour hommes","bags-shoes":"Sacs et chaussures",kids:"Jouets, enfants et bébé",sports:"Sports et plein air",electronics:"Électronique grand public",improvement:"Amélioration de l’habitat",auto:"Automobiles et motos",phones:"Téléphones et accessoires",computers:"Ordinateurs et bureau"},
  ar:{women:"ملابس نسائية",pets:"مستلزمات الحيوانات الأليفة",home:"المنزل والحديقة والأثاث",beauty:"الصحة والجمال والشعر",jewelry:"المجوهرات والساعات",men:"ملابس رجالية","bags-shoes":"الحقائب والأحذية",kids:"الألعاب والأطفال والرضّع",sports:"الرياضة والهواء الطلق",electronics:"الإلكترونيات الاستهلاكية",improvement:"تحسين المنزل",auto:"السيارات والدراجات النارية",phones:"الهواتف وملحقاتها",computers:"الكمبيوتر والمكتب"},
  ku:{women:"جلوبەرگی ژنان",pets:"پێداویستییەکانی ئاژەڵی ماڵی",home:"ماڵ و باخچە و کەلوپەل",beauty:"تەندروستی و جوانکاری و قژ",jewelry:"خشڵ و کاتژمێر",men:"جلوبەرگی پیاوان","bags-shoes":"جانتا و پێڵاو",kids:"یاری و منداڵ و ساوا",sports:"وەرزش و دەرەوە",electronics:"ئەلیکترۆنیاتی بەکارهێنەر",improvement:"چاکسازی ماڵ",auto:"ئۆتۆمبێل و ماتۆڕ",phones:"مۆبایل و پێوەکراوەکان",computers:"کۆمپیوتەر و ئۆفیس"},
  tr:{women:"Kadın giyim",pets:"Evcil hayvan ürünleri",home:"Ev, bahçe ve mobilya",beauty:"Sağlık, güzellik ve saç",jewelry:"Takı ve saat",men:"Erkek giyim","bags-shoes":"Çanta ve ayakkabı",kids:"Oyuncak, çocuk ve bebek",sports:"Spor ve açık hava",electronics:"Tüketici elektroniği",improvement:"Ev geliştirme",auto:"Otomobil ve motosiklet",phones:"Telefon ve aksesuar",computers:"Bilgisayar ve ofis"},
  de:{women:"Damenbekleidung",pets:"Tierbedarf",home:"Haus, Garten und Möbel",beauty:"Gesundheit, Beauty und Haar",jewelry:"Schmuck und Uhren",men:"Herrenbekleidung","bags-shoes":"Taschen und Schuhe",kids:"Spielzeug, Kinder und Baby",sports:"Sport und Outdoor",electronics:"Unterhaltungselektronik",improvement:"Heimwerken",auto:"Auto und Motorrad",phones:"Telefone und Zubehör",computers:"Computer und Büro"},
  es:{women:"Ropa de mujer",pets:"Productos para mascotas",home:"Hogar, jardín y muebles",beauty:"Salud, belleza y cabello",jewelry:"Joyas y relojes",men:"Ropa de hombre","bags-shoes":"Bolsos y zapatos",kids:"Juguetes, niños y bebé",sports:"Deportes y aire libre",electronics:"Electrónica de consumo",improvement:"Mejoras del hogar",auto:"Automóviles y motos",phones:"Teléfonos y accesorios",computers:"Informática y oficina"},
  it:{women:"Abbigliamento donna",pets:"Articoli per animali",home:"Casa, giardino e mobili",beauty:"Salute, bellezza e capelli",jewelry:"Gioielli e orologi",men:"Abbigliamento uomo","bags-shoes":"Borse e scarpe",kids:"Giochi, bambini e neonati",sports:"Sport e attività all’aperto",electronics:"Elettronica di consumo",improvement:"Fai da te",auto:"Auto e moto",phones:"Telefoni e accessori",computers:"Computer e ufficio"},
  nl:{women:"Dameskleding",pets:"Dierenbenodigdheden",home:"Huis, tuin en meubels",beauty:"Gezondheid, beauty en haar",jewelry:"Sieraden en horloges",men:"Herenkleding","bags-shoes":"Tassen en schoenen",kids:"Speelgoed, kinderen en baby",sports:"Sport en outdoor",electronics:"Consumentenelektronica",improvement:"Woningverbetering",auto:"Auto en motor",phones:"Telefoons en accessoires",computers:"Computers en kantoor"},
  zh:{women:"女装",pets:"宠物用品",home:"家居、花园与家具",beauty:"健康、美容与美发",jewelry:"珠宝与手表",men:"男装","bags-shoes":"箱包与鞋靴",kids:"玩具、儿童与婴儿",sports:"运动与户外",electronics:"消费电子",improvement:"家装建材",auto:"汽车与摩托车",phones:"手机与配件",computers:"电脑与办公"},
  fa:{women:"پوشاک زنانه",pets:"لوازم حیوانات خانگی",home:"خانه، باغ و مبلمان",beauty:"سلامت، زیبایی و مو",jewelry:"جواهرات و ساعت",men:"پوشاک مردانه","bags-shoes":"کیف و کفش",kids:"اسباب‌بازی، کودک و نوزاد",sports:"ورزش و فضای باز",electronics:"لوازم الکترونیکی مصرفی",improvement:"بهسازی خانه",auto:"خودرو و موتورسیکلت",phones:"تلفن و لوازم جانبی",computers:"کامپیوتر و دفتر"},
  hi:{women:"महिलाओं के कपड़े",pets:"पालतू पशु सामग्री",home:"घर, बगीचा और फर्नीचर",beauty:"स्वास्थ्य, सौंदर्य और बाल",jewelry:"आभूषण और घड़ियाँ",men:"पुरुषों के कपड़े","bags-shoes":"बैग और जूते",kids:"खिलौने, बच्चे और शिशु",sports:"खेल और आउटडोर",electronics:"उपभोक्ता इलेक्ट्रॉनिक्स",improvement:"गृह सुधार",auto:"ऑटोमोबाइल और मोटरसाइकिल",phones:"फ़ोन और एक्सेसरीज़",computers:"कंप्यूटर और कार्यालय"},
  pt:{women:"Moda feminina",pets:"Artigos para animais",home:"Casa, jardim e móveis",beauty:"Saúde, beleza e cabelo",jewelry:"Joias e relógios",men:"Moda masculina","bags-shoes":"Bolsas e calçados",kids:"Brinquedos, crianças e bebés",sports:"Desporto e ar livre",electronics:"Eletrónica de consumo",improvement:"Melhorias para casa",auto:"Automóveis e motos",phones:"Telefones e acessórios",computers:"Computadores e escritório"},
  ru:{women:"Женская одежда",pets:"Товары для животных",home:"Дом, сад и мебель",beauty:"Здоровье, красота и волосы",jewelry:"Украшения и часы",men:"Мужская одежда","bags-shoes":"Сумки и обувь",kids:"Игрушки, дети и малыши",sports:"Спорт и отдых",electronics:"Бытовая электроника",improvement:"Ремонт дома",auto:"Авто и мото",phones:"Телефоны и аксессуары",computers:"Компьютеры и офис"},
};
