const en={accessTitle:"Dropshipping",approvedNotConnected:"Your store is approved for dropshipping, but no seller-owned supplier account is connected.",connectPending:"Seller CJ authorization is not yet connected. Platform credentials will never be used as a fallback.",adminSuppliers:"Suppliers / Dropshipping",permissionEnabled:"Dropshipping approved",permissionDisabled:"Dropshipping disabled",enablePermission:"Approve dropshipping",disablePermission:"Revoke dropshipping"};
export const dropshippingAccessMessages:Record<string,typeof en>={
en,fr:{accessTitle:"Dropshipping",approvedNotConnected:"Votre boutique est approuvée pour le dropshipping, mais aucun compte fournisseur appartenant au vendeur n’est connecté.",connectPending:"L’autorisation CJ du vendeur n’est pas encore connectée. Les identifiants de la plateforme ne seront jamais utilisés comme solution de secours.",adminSuppliers:"Fournisseurs / Dropshipping",permissionEnabled:"Dropshipping approuvé",permissionDisabled:"Dropshipping désactivé",enablePermission:"Approuver le dropshipping",disablePermission:"Révoquer le dropshipping"},
de:{accessTitle:"Dropshipping",approvedNotConnected:"Ihr Shop ist für Dropshipping freigegeben, aber es ist kein eigenes Lieferantenkonto verbunden.",connectPending:"Die CJ-Autorisierung des Verkäufers ist noch nicht verbunden. Plattformzugangsdaten werden niemals ersatzweise verwendet.",adminSuppliers:"Lieferanten / Dropshipping",permissionEnabled:"Dropshipping genehmigt",permissionDisabled:"Dropshipping deaktiviert",enablePermission:"Dropshipping genehmigen",disablePermission:"Dropshipping widerrufen"},
es:{accessTitle:"Dropshipping",approvedNotConnected:"Tu tienda está aprobada para dropshipping, pero no hay una cuenta de proveedor propia conectada.",connectPending:"La autorización CJ del vendedor aún no está conectada. Las credenciales de la plataforma nunca se usarán como alternativa.",adminSuppliers:"Proveedores / Dropshipping",permissionEnabled:"Dropshipping aprobado",permissionDisabled:"Dropshipping desactivado",enablePermission:"Aprobar dropshipping",disablePermission:"Revocar dropshipping"},
it:{accessTitle:"Dropshipping",approvedNotConnected:"Il tuo negozio è approvato per il dropshipping, ma non è collegato alcun account fornitore del venditore.",connectPending:"L’autorizzazione CJ del venditore non è ancora collegata. Le credenziali della piattaforma non verranno mai usate come ripiego.",adminSuppliers:"Fornitori / Dropshipping",permissionEnabled:"Dropshipping approvato",permissionDisabled:"Dropshipping disattivato",enablePermission:"Approva dropshipping",disablePermission:"Revoca dropshipping"},
nl:{accessTitle:"Dropshipping",approvedNotConnected:"Je winkel is goedgekeurd voor dropshipping, maar er is geen eigen leveranciersaccount gekoppeld.",connectPending:"De CJ-autorisatie van de verkoper is nog niet gekoppeld. Platformgegevens worden nooit als terugval gebruikt.",adminSuppliers:"Leveranciers / Dropshipping",permissionEnabled:"Dropshipping goedgekeurd",permissionDisabled:"Dropshipping uitgeschakeld",enablePermission:"Dropshipping goedkeuren",disablePermission:"Dropshipping intrekken"},
pt:{accessTitle:"Dropshipping",approvedNotConnected:"A sua loja está aprovada para dropshipping, mas não existe uma conta de fornecedor própria ligada.",connectPending:"A autorização CJ do vendedor ainda não está ligada. As credenciais da plataforma nunca serão usadas como alternativa.",adminSuppliers:"Fornecedores / Dropshipping",permissionEnabled:"Dropshipping aprovado",permissionDisabled:"Dropshipping desativado",enablePermission:"Aprovar dropshipping",disablePermission:"Revogar dropshipping"},
tr:{accessTitle:"Stoksuz satış",approvedNotConnected:"Mağazanız stoksuz satış için onaylandı ancak satıcıya ait tedarikçi hesabı bağlı değil.",connectPending:"Satıcı CJ yetkilendirmesi henüz bağlı değil. Platform kimlik bilgileri hiçbir zaman yedek olarak kullanılmaz.",adminSuppliers:"Tedarikçiler / Stoksuz satış",permissionEnabled:"Stoksuz satış onaylandı",permissionDisabled:"Stoksuz satış kapalı",enablePermission:"Stoksuz satışı onayla",disablePermission:"Stoksuz satış iznini kaldır"},
ru:{accessTitle:"Дропшиппинг",approvedNotConnected:"Ваш магазин одобрен для дропшиппинга, но собственная учётная запись поставщика не подключена.",connectPending:"Авторизация продавца CJ ещё не подключена. Учётные данные платформы никогда не используются как резервные.",adminSuppliers:"Поставщики / Дропшиппинг",permissionEnabled:"Дропшиппинг одобрен",permissionDisabled:"Дропшиппинг отключён",enablePermission:"Одобрить дропшиппинг",disablePermission:"Отозвать дропшиппинг"},
ar:{accessTitle:"الدروبشيبينغ",approvedNotConnected:"متجرك معتمد للدروبشيبينغ، لكن لم يتم ربط حساب مورد مملوك للبائع.",connectPending:"تفويض CJ الخاص بالبائع غير متصل بعد. لن تُستخدم بيانات اعتماد المنصة كبديل أبداً.",adminSuppliers:"الموردون / الدروبشيبينغ",permissionEnabled:"تم اعتماد الدروبشيبينغ",permissionDisabled:"الدروبشيبينغ معطل",enablePermission:"اعتماد الدروبشيبينغ",disablePermission:"إلغاء الدروبشيبينغ"},
fa:{accessTitle:"دراپ‌شیپینگ",approvedNotConnected:"فروشگاه شما برای دراپ‌شیپینگ تأیید شده است، اما حساب تأمین‌کننده متعلق به فروشنده متصل نیست.",connectPending:"مجوز CJ فروشنده هنوز متصل نشده است. اطلاعات ورود پلتفرم هرگز به‌عنوان جایگزین استفاده نمی‌شود.",adminSuppliers:"تأمین‌کنندگان / دراپ‌شیپینگ",permissionEnabled:"دراپ‌شیپینگ تأیید شد",permissionDisabled:"دراپ‌شیپینگ غیرفعال است",enablePermission:"تأیید دراپ‌شیپینگ",disablePermission:"لغو دراپ‌شیپینگ"},
hi:{accessTitle:"ड्रॉपशिपिंग",approvedNotConnected:"आपका स्टोर ड्रॉपशिपिंग के लिए स्वीकृत है, लेकिन विक्रेता का अपना सप्लायर खाता जुड़ा नहीं है।",connectPending:"विक्रेता CJ प्राधिकरण अभी जुड़ा नहीं है। प्लेटफ़ॉर्म क्रेडेंशियल कभी भी फ़ॉलबैक के रूप में उपयोग नहीं होंगे।",adminSuppliers:"आपूर्तिकर्ता / ड्रॉपशिपिंग",permissionEnabled:"ड्रॉपशिपिंग स्वीकृत",permissionDisabled:"ड्रॉपशिपिंग बंद",enablePermission:"ड्रॉपशिपिंग स्वीकृत करें",disablePermission:"ड्रॉपशिपिंग रद्द करें"},
ku:{accessTitle:"دراپشیپینگ",approvedNotConnected:"فرۆشگاکەت بۆ دراپشیپینگ پەسەند کراوە، بەڵام هیچ هەژماری دابینکەری خاوەندارێتی فرۆشیار پەیوەست نییە.",connectPending:"ڕێپێدانی CJی فرۆشیار هێشتا پەیوەست نییە. زانیاری نهێنی پلاتفۆرم هەرگیز وەک جێگرەوە بەکارناهێنرێت.",adminSuppliers:"دابینکەرەکان / دراپشیپینگ",permissionEnabled:"دراپشیپینگ پەسەند کرا",permissionDisabled:"دراپشیپینگ ناچالاکە",enablePermission:"پەسەندکردنی دراپشیپینگ",disablePermission:"هەڵوەشاندنەوەی دراپشیپینگ"},
zh:{accessTitle:"代发货",approvedNotConnected:"您的店铺已获准使用代发货，但尚未连接卖家自有的供应商账户。",connectPending:"卖家的 CJ 授权尚未连接。平台凭据绝不会作为后备凭据使用。",adminSuppliers:"供应商 / 代发货",permissionEnabled:"代发货已批准",permissionDisabled:"代发货已禁用",enablePermission:"批准代发货",disablePermission:"撤销代发货"}
};
