import type { Locale } from "./config";

type Copy = {
  invalidTitle: string; invalidText: string; successTitle: string; successText: string;
  resend: string; sent: string; rateLimited: string; account: string; login: string;
  unverified: string; secureAccount: string; verified: string; emailAddress: string;
  me: string; guest: string;
};

export const emailVerificationCopy: Record<Locale, Copy> = {
  en:{invalidTitle:"This verification link is no longer valid",invalidText:"The link may have expired or already been used. Request a new link to verify your email address.",successTitle:"Email address verified",successText:"Your email address has been verified successfully.",resend:"Resend verification email",sent:"A new verification email has been sent.",rateLimited:"Please wait before requesting another verification email.",account:"Go to my account",login:"Sign in",unverified:"Email address not verified",secureAccount:"Verify your email address to secure your account.",verified:"Verified",emailAddress:"Email address",me:"Me",guest:"Sign in / Register"},
  fr:{invalidTitle:"Ce lien de vérification n’est plus valide",invalidText:"Le lien a peut-être expiré ou déjà été utilisé. Demandez un nouveau lien pour vérifier votre adresse e-mail.",successTitle:"Adresse e-mail vérifiée",successText:"Votre adresse e-mail a été vérifiée avec succès.",resend:"Renvoyer l’e-mail de vérification",sent:"Un nouvel e-mail de vérification a été envoyé.",rateLimited:"Veuillez patienter avant de demander un autre e-mail de vérification.",account:"Aller à mon compte",login:"Se connecter",unverified:"Adresse e-mail non vérifiée",secureAccount:"Vérifiez votre adresse e-mail pour sécuriser votre compte.",verified:"Vérifiée",emailAddress:"Adresse e-mail",me:"Moi",guest:"Se connecter / S’inscrire"},
  ar:{invalidTitle:"رابط التحقق لم يعد صالحًا",invalidText:"ربما انتهت صلاحية الرابط أو تم استخدامه. اطلب رابطًا جديدًا للتحقق من بريدك الإلكتروني.",successTitle:"تم التحقق من البريد الإلكتروني",successText:"تم التحقق من عنوان بريدك الإلكتروني بنجاح.",resend:"إعادة إرسال رسالة التحقق",sent:"تم إرسال رسالة تحقق جديدة.",rateLimited:"يرجى الانتظار قبل طلب رسالة تحقق أخرى.",account:"الانتقال إلى حسابي",login:"تسجيل الدخول",unverified:"البريد الإلكتروني غير موثق",secureAccount:"تحقق من بريدك الإلكتروني لتأمين حسابك.",verified:"موثق",emailAddress:"البريد الإلكتروني",me:"أنا",guest:"تسجيل الدخول / إنشاء حساب"},
  ku:{invalidTitle:"لینکی پشتڕاستکردنەوە چیتر دروست نییە",invalidText:"لەوانەیە لینکەکە بەسەرچووبێت یان بەکارهاتبێت. لینکێکی نوێ داوا بکە.",successTitle:"ئیمەیڵ پشتڕاست کرایەوە",successText:"ناونیشانی ئیمەیڵەکەت بە سەرکەوتوویی پشتڕاست کرایەوە.",resend:"ناردنەوەی ئیمەیڵی پشتڕاستکردنەوە",sent:"ئیمەیڵێکی نوێی پشتڕاستکردنەوە نێردرا.",rateLimited:"تکایە پێش داواکارییەکی تر چاوەڕێ بکە.",account:"بڕۆ بۆ هەژمارەکەم",login:"چوونەژوورەوە",unverified:"ئیمەیڵ پشتڕاست نەکراوەتەوە",secureAccount:"ئیمەیڵەکەت پشتڕاست بکەرەوە بۆ پاراستنی هەژمارەکەت.",verified:"پشتڕاستکراوە",emailAddress:"ناونیشانی ئیمەیڵ",me:"من",guest:"چوونەژوورەوە / تۆمارکردن"},
  tr:{invalidTitle:"Bu doğrulama bağlantısı artık geçerli değil",invalidText:"Bağlantının süresi dolmuş veya kullanılmış olabilir. Yeni bir bağlantı isteyin.",successTitle:"E-posta adresi doğrulandı",successText:"E-posta adresiniz başarıyla doğrulandı.",resend:"Doğrulama e-postasını yeniden gönder",sent:"Yeni bir doğrulama e-postası gönderildi.",rateLimited:"Yeni bir e-posta istemeden önce lütfen bekleyin.",account:"Hesabıma git",login:"Giriş yap",unverified:"E-posta adresi doğrulanmadı",secureAccount:"Hesabınızı korumak için e-posta adresinizi doğrulayın.",verified:"Doğrulandı",emailAddress:"E-posta adresi",me:"Ben",guest:"Giriş yap / Kayıt ol"},
  de:{invalidTitle:"Dieser Bestätigungslink ist nicht mehr gültig",invalidText:"Der Link ist möglicherweise abgelaufen oder wurde bereits verwendet. Fordern Sie einen neuen Link an.",successTitle:"E-Mail-Adresse bestätigt",successText:"Ihre E-Mail-Adresse wurde erfolgreich bestätigt.",resend:"Bestätigungs-E-Mail erneut senden",sent:"Eine neue Bestätigungs-E-Mail wurde gesendet.",rateLimited:"Bitte warten Sie, bevor Sie eine weitere E-Mail anfordern.",account:"Zu meinem Konto",login:"Anmelden",unverified:"E-Mail-Adresse nicht bestätigt",secureAccount:"Bestätigen Sie Ihre E-Mail-Adresse, um Ihr Konto zu schützen.",verified:"Bestätigt",emailAddress:"E-Mail-Adresse",me:"Ich",guest:"Anmelden / Registrieren"},
  es:{invalidTitle:"Este enlace de verificación ya no es válido",invalidText:"Es posible que haya caducado o ya se haya utilizado. Solicita un enlace nuevo.",successTitle:"Correo electrónico verificado",successText:"Tu correo electrónico se ha verificado correctamente.",resend:"Reenviar correo de verificación",sent:"Se ha enviado un nuevo correo de verificación.",rateLimited:"Espera antes de solicitar otro correo de verificación.",account:"Ir a mi cuenta",login:"Iniciar sesión",unverified:"Correo electrónico no verificado",secureAccount:"Verifica tu correo para proteger tu cuenta.",verified:"Verificado",emailAddress:"Correo electrónico",me:"Yo",guest:"Iniciar sesión / Registrarse"},
  it:{invalidTitle:"Questo link di verifica non è più valido",invalidText:"Il link potrebbe essere scaduto o già utilizzato. Richiedine uno nuovo.",successTitle:"Indirizzo e-mail verificato",successText:"Il tuo indirizzo e-mail è stato verificato.",resend:"Invia di nuovo l’e-mail di verifica",sent:"È stata inviata una nuova e-mail di verifica.",rateLimited:"Attendi prima di richiedere un’altra e-mail.",account:"Vai al mio account",login:"Accedi",unverified:"Indirizzo e-mail non verificato",secureAccount:"Verifica l’e-mail per proteggere il tuo account.",verified:"Verificato",emailAddress:"Indirizzo e-mail",me:"Io",guest:"Accedi / Registrati"},
  nl:{invalidTitle:"Deze verificatielink is niet meer geldig",invalidText:"De link kan verlopen of al gebruikt zijn. Vraag een nieuwe link aan.",successTitle:"E-mailadres geverifieerd",successText:"Je e-mailadres is succesvol geverifieerd.",resend:"Verificatie-e-mail opnieuw verzenden",sent:"Er is een nieuwe verificatie-e-mail verzonden.",rateLimited:"Wacht voordat je nog een e-mail aanvraagt.",account:"Naar mijn account",login:"Inloggen",unverified:"E-mailadres niet geverifieerd",secureAccount:"Verifieer je e-mailadres om je account te beveiligen.",verified:"Geverifieerd",emailAddress:"E-mailadres",me:"Ik",guest:"Inloggen / Registreren"},
  zh:{invalidTitle:"此验证链接已失效",invalidText:"链接可能已过期或已被使用。请申请新的验证链接。",successTitle:"邮箱已验证",successText:"您的邮箱地址已成功验证。",resend:"重新发送验证邮件",sent:"新的验证邮件已发送。",rateLimited:"请稍候再申请验证邮件。",account:"前往我的账户",login:"登录",unverified:"邮箱未验证",secureAccount:"请验证邮箱以保护您的账户。",verified:"已验证",emailAddress:"邮箱地址",me:"我",guest:"登录 / 注册"},
  fa:{invalidTitle:"این پیوند تأیید دیگر معتبر نیست",invalidText:"ممکن است پیوند منقضی یا استفاده شده باشد. پیوند جدیدی درخواست کنید.",successTitle:"ایمیل تأیید شد",successText:"نشانی ایمیل شما با موفقیت تأیید شد.",resend:"ارسال دوباره ایمیل تأیید",sent:"ایمیل تأیید جدیدی ارسال شد.",rateLimited:"لطفاً پیش از درخواست دوباره صبر کنید.",account:"رفتن به حساب من",login:"ورود",unverified:"ایمیل تأیید نشده",secureAccount:"برای امنیت حساب، ایمیل خود را تأیید کنید.",verified:"تأیید شده",emailAddress:"نشانی ایمیل",me:"من",guest:"ورود / ثبت‌نام"},
  hi:{invalidTitle:"यह सत्यापन लिंक अब मान्य नहीं है",invalidText:"लिंक समाप्त हो चुका या उपयोग किया जा चुका है। नया लिंक माँगें।",successTitle:"ईमेल पता सत्यापित",successText:"आपका ईमेल पता सफलतापूर्वक सत्यापित हो गया है।",resend:"सत्यापन ईमेल फिर भेजें",sent:"नया सत्यापन ईमेल भेज दिया गया है।",rateLimited:"दूसरा ईमेल माँगने से पहले प्रतीक्षा करें।",account:"मेरे खाते पर जाएँ",login:"साइन इन करें",unverified:"ईमेल पता सत्यापित नहीं है",secureAccount:"अपने खाते की सुरक्षा के लिए ईमेल सत्यापित करें।",verified:"सत्यापित",emailAddress:"ईमेल पता",me:"मैं",guest:"साइन इन / पंजीकरण"},
  pt:{invalidTitle:"Este link de verificação já não é válido",invalidText:"O link pode ter expirado ou já ter sido usado. Solicite um novo link.",successTitle:"Endereço de e-mail verificado",successText:"O seu endereço de e-mail foi verificado com sucesso.",resend:"Reenviar e-mail de verificação",sent:"Foi enviado um novo e-mail de verificação.",rateLimited:"Aguarde antes de solicitar outro e-mail.",account:"Ir para a minha conta",login:"Entrar",unverified:"Endereço de e-mail não verificado",secureAccount:"Verifique o seu e-mail para proteger a conta.",verified:"Verificado",emailAddress:"Endereço de e-mail",me:"Eu",guest:"Entrar / Registar"},
  ru:{invalidTitle:"Эта ссылка подтверждения больше недействительна",invalidText:"Срок ссылки мог истечь или она уже использована. Запросите новую ссылку.",successTitle:"Адрес электронной почты подтверждён",successText:"Ваш адрес электронной почты успешно подтверждён.",resend:"Отправить письмо подтверждения снова",sent:"Новое письмо подтверждения отправлено.",rateLimited:"Подождите перед повторным запросом письма.",account:"Перейти в мой аккаунт",login:"Войти",unverified:"Адрес электронной почты не подтверждён",secureAccount:"Подтвердите адрес электронной почты для защиты аккаунта.",verified:"Подтверждён",emailAddress:"Адрес электронной почты",me:"Я",guest:"Войти / Регистрация"},
};
