import type { Locale } from "./config";
import { canonicalLeafCategory } from "../lib/desktop-category-taxonomy";

// Display-only translations. Canonical IDs always come from the shared taxonomy.
type FurnitureLabels = readonly [string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string];
export const furnitureTaxonomyLabels: Record<Locale, FurnitureLabels> = {
  fr: ["Mobilier & Aménagement", "Salon & assises", "Bureau & espace de travail", "Tables & repas", "Chaises & sièges", "Chambre & literie", "Armoires & dressing", "Commodes & rangement", "Bibliothèques & étagères", "Meubles TV & multimédia", "Cuisine & aménagement", "Salle de bain & rangement", "Mobilier extérieur", "Assises enfant", "Bureaux enfant", "Tables enfant", "Chaises enfant", "Lits enfant", "Armoires enfant"],
  en: ["Furniture & Interiors", "Living room & seating", "Desks & workspace", "Tables & dining", "Chairs & seats", "Bedroom & bedding", "Wardrobes & dressing", "Chests & storage", "Bookcases & shelving", "TV & media furniture", "Kitchen furnishings", "Bathroom furniture & storage", "Outdoor furniture", "Children’s seating", "Children’s desks", "Children’s tables", "Children’s chairs", "Children’s beds", "Children’s wardrobes"],
  ar: ["الأثاث وتجهيز المنزل", "غرفة المعيشة والجلوس", "المكاتب ومساحات العمل", "الطاولات وتناول الطعام", "الكراسي والمقاعد", "غرفة النوم والمفروشات", "الخزائن وغرف الملابس", "خزائن الأدراج والتخزين", "المكتبات والرفوف", "أثاث التلفزيون والوسائط", "أثاث وتجهيز المطبخ", "أثاث الحمام والتخزين", "الأثاث الخارجي", "مقاعد الأطفال", "مكاتب الأطفال", "طاولات الأطفال", "كراسي الأطفال", "أسرّة الأطفال", "خزائن الأطفال"],
  ku: ["کەلوپەلی ماڵ و ڕێکخستن", "ژووری دانیشتن و دانیشتگە", "مێزی نووسین و شوێنی کار", "مێز و نانخواردن", "کورسی و دانیشتگە", "ژووری نووستن و جێخەو", "دۆڵاب و شوێنی جل", "دۆڵابی کێشەک و هەڵگرتن", "کتێبخانە و ڕەفە", "کەلوپەلی تەلەفزیۆن و میدیا", "کەلوپەل و ڕێکخستنی چێشتخانە", "کەلوپەل و هەڵگرتنی حەمام", "کەلوپەلی دەرەوە", "دانیشتگەی منداڵان", "مێزی نووسینی منداڵان", "مێزی منداڵان", "کورسیی منداڵان", "جێخەوی منداڵان", "دۆڵابی منداڵان"],
  tr: ["Mobilya ve Dekorasyon", "Salon ve oturma grupları", "Çalışma masaları ve çalışma alanı", "Masalar ve yemek alanı", "Sandalyeler ve oturaklar", "Yatak odası ve yatak takımları", "Dolaplar ve giyinme alanı", "Şifonyerler ve depolama", "Kitaplıklar ve raflar", "TV ve medya mobilyaları", "Mutfak mobilyaları", "Banyo mobilyaları ve depolama", "Dış mekân mobilyaları", "Çocuk oturma mobilyaları", "Çocuk çalışma masaları", "Çocuk masaları", "Çocuk sandalyeleri", "Çocuk yatakları", "Çocuk dolapları"],
  de: ["Möbel & Einrichtung", "Wohnzimmer & Sitzmöbel", "Schreibtische & Arbeitsbereich", "Tische & Essbereich", "Stühle & Sitzgelegenheiten", "Schlafzimmer & Bettwaren", "Schränke & Ankleide", "Kommoden & Aufbewahrung", "Bücherregale & Regale", "TV- & Medienmöbel", "Küchenmöbel & Einrichtung", "Badmöbel & Aufbewahrung", "Gartenmöbel", "Kindersitzmöbel", "Kinderschreibtische", "Kindertische", "Kinderstühle", "Kinderbetten", "Kinderschränke"],
  es: ["Muebles y decoración", "Salón y asientos", "Escritorios y espacio de trabajo", "Mesas y comedor", "Sillas y asientos", "Dormitorio y ropa de cama", "Armarios y vestidores", "Cómodas y almacenaje", "Librerías y estanterías", "Muebles de TV y multimedia", "Muebles de cocina", "Muebles de baño y almacenaje", "Muebles de exterior", "Asientos infantiles", "Escritorios infantiles", "Mesas infantiles", "Sillas infantiles", "Camas infantiles", "Armarios infantiles"],
  it: ["Mobili e arredamento", "Soggiorno e sedute", "Scrivanie e spazio di lavoro", "Tavoli e zona pranzo", "Sedie e sedute", "Camera da letto e biancheria", "Armadi e guardaroba", "Cassettiere e contenitori", "Librerie e scaffali", "Mobili TV e multimediali", "Mobili e arredi da cucina", "Mobili da bagno e contenitori", "Mobili da esterno", "Sedute per bambini", "Scrivanie per bambini", "Tavoli per bambini", "Sedie per bambini", "Letti per bambini", "Armadi per bambini"],
  nl: ["Meubels & inrichting", "Woonkamer & zitmeubels", "Bureaus & werkruimte", "Tafels & eetruimte", "Stoelen & zitplaatsen", "Slaapkamer & beddengoed", "Kasten & kledingruimte", "Ladekasten & opbergen", "Boekenkasten & planken", "TV- & mediameubels", "Keukenmeubels & inrichting", "Badkamermeubels & opbergen", "Buitenmeubels", "Kinderzitmeubels", "Kinderbureaus", "Kindertafels", "Kinderstoelen", "Kinderbedden", "Kinderkasten"],
  zh: ["家具与家居布置", "客厅与坐具", "书桌与工作空间", "桌子与用餐空间", "椅子与座椅", "卧室与床品", "衣柜与衣帽间", "斗柜与收纳", "书柜与置物架", "电视柜与影音家具", "厨房家具与布置", "浴室家具与收纳", "户外家具", "儿童坐具", "儿童书桌", "儿童桌子", "儿童椅子", "儿童床", "儿童衣柜"],
  fa: ["مبلمان و چیدمان", "نشیمن و مبلمان راحتی", "میز تحریر و فضای کار", "میز و فضای غذاخوری", "صندلی و نشیمن", "اتاق خواب و کالای خواب", "کمد و فضای لباس", "دراور و فضای نگهداری", "کتابخانه و قفسه", "میز تلویزیون و مبلمان رسانه", "مبلمان و چیدمان آشپزخانه", "مبلمان حمام و فضای نگهداری", "مبلمان فضای باز", "نشیمن کودک", "میز تحریر کودک", "میز کودک", "صندلی کودک", "تخت کودک", "کمد کودک"],
  hi: ["फ़र्नीचर और गृह सज्जा", "बैठक और बैठने का फ़र्नीचर", "लेखन मेज़ और कार्यस्थल", "मेज़ और भोजन कक्ष", "कुर्सियाँ और आसन", "शयनकक्ष और बिस्तर", "अलमारियाँ और कपड़े रखने की जगह", "दराज़ वाली अलमारियाँ और भंडारण", "पुस्तक अलमारियाँ और शेल्फ़", "टीवी और मीडिया फ़र्नीचर", "रसोई का फ़र्नीचर और व्यवस्था", "स्नानघर का फ़र्नीचर और भंडारण", "बाहरी फ़र्नीचर", "बच्चों के बैठने का फ़र्नीचर", "बच्चों की लेखन मेज़", "बच्चों की मेज़", "बच्चों की कुर्सियाँ", "बच्चों के बिस्तर", "बच्चों की अलमारियाँ"],
  pt: ["Móveis e decoração", "Sala de estar e assentos", "Secretárias e espaço de trabalho", "Mesas e sala de jantar", "Cadeiras e assentos", "Quarto e roupa de cama", "Roupeiros e espaço de vestir", "Cómodas e arrumação", "Estantes e prateleiras", "Móveis de TV e multimédia", "Móveis e organização de cozinha", "Móveis de casa de banho e arrumação", "Móveis de exterior", "Assentos infantis", "Secretárias infantis", "Mesas infantis", "Cadeiras infantis", "Camas infantis", "Roupeiros infantis"],
  ru: ["Мебель и обустройство", "Гостиная и мягкая мебель", "Письменные столы и рабочее пространство", "Столы и обеденная зона", "Стулья и сиденья", "Спальня и постельные принадлежности", "Шкафы и гардеробные", "Комоды и хранение", "Книжные шкафы и полки", "Мебель для ТВ и мультимедиа", "Кухонная мебель и обустройство", "Мебель для ванной и хранение", "Уличная мебель", "Детская мебель для сидения", "Детские письменные столы", "Детские столы", "Детские стулья", "Детские кровати", "Детские шкафы"],
};

/** Presentation adapter for the existing three-level taxonomy, never a classifier. */
export function localizedFurnitureCategoryLabel(value: string, locale: Locale): string | null {
  if (value === "Mobilier & Aménagement") return furnitureTaxonomyLabels[locale][0];
  const leaf = canonicalLeafCategory(value);
  if (!leaf || leaf.categoryId !== "home" || leaf.groupId !== "furniture") return null;
  const index = furnitureTaxonomyLabels.fr.indexOf(leaf.label);
  return index > 0 ? furnitureTaxonomyLabels[locale][index] : null;
}
