import type{Locale}from"./config";
const en={title:"Global Dropshipping Profit Margin",label:"Target margin",description:"Applies to CJ platform products and approved dropshipping sellers. Ordinary marketplace products are unaffected.",future:"Changes apply to new and live price calculations. Historical paid orders are never repriced.",defaultValue:"Default: 20%",save:"Update margin",saving:"Updating…",success:"Global dropshipping margin updated.",invalid:"Enter a percentage from 0 to 80 with at most two decimals."};
export const globalDropshippingMarginMessages:Record<Locale,typeof en>={
 en,fr:{title:"Marge bénéficiaire globale du dropshipping",label:"Marge cible",description:"S’applique aux produits CJ de la plateforme et aux vendeurs autorisés au dropshipping. Les produits ordinaires ne sont pas concernés.",future:"Les changements s’appliquent aux nouveaux calculs et aux prix en direct. Les commandes payées restent inchangées.",defaultValue:"Valeur par défaut : 20 %",save:"Mettre à jour la marge",saving:"Mise à jour…",success:"Marge globale mise à jour.",invalid:"Saisissez un pourcentage de 0 à 80 avec deux décimales maximum."},
 ar:{title:"هامش ربح الدروبشيبينغ العام",label:"الهامش المستهدف",description:"ينطبق على منتجات CJ التابعة للمنصة وعلى البائعين المعتمدين للدروبشيبينغ، ولا يؤثر في منتجات السوق العادية.",future:"تسري التغييرات على حسابات الأسعار الجديدة والمباشرة، ولا يُعاد تسعير الطلبات المدفوعة السابقة.",defaultValue:"الافتراضي: 20٪",save:"تحديث الهامش",saving:"جارٍ التحديث…",success:"تم تحديث الهامش العام.",invalid:"أدخل نسبة من 0 إلى 80 وبحد أقصى منزلتين عشريتين."},
 ku:{title:"پەراوێزی قازانجی گشتی درۆپشیپینگ",label:"پەراوێزی ئامانج",description:"بۆ بەرهەمەکانی CJ و فرۆشیارانی پەسەندکراوی درۆپشیپینگ بەکاردێت؛ بازاڕی ئاسایی ناگرێتەوە.",future:"گۆڕانکاری بۆ حیسابە نوێ و ڕاستەوخۆکانە؛ داواکارییە پارەدراوە مێژووییەکان ناگۆڕدرێن.",defaultValue:"بنەڕەت: 20٪",save:"نوێکردنەوەی پەراوێز",saving:"نوێکردنەوە…",success:"پەراوێزی گشتی نوێکرایەوە.",invalid:"ڕێژەیەک لە 0 تا 80 بە زۆرترین دوو خانە بنووسە."},
 tr:{title:"Küresel Dropshipping Kâr Marjı",label:"Hedef marj",description:"CJ platform ürünleri ve onaylı dropshipping satıcıları için geçerlidir; normal pazar ürünlerini etkilemez.",future:"Değişiklikler yeni ve canlı fiyat hesaplarına uygulanır. Ödenmiş geçmiş siparişler yeniden fiyatlandırılmaz.",defaultValue:"Varsayılan: %20",save:"Marjı güncelle",saving:"Güncelleniyor…",success:"Küresel marj güncellendi.",invalid:"0 ile 80 arasında, en fazla iki ondalıklı bir yüzde girin."},
 de:{title:"Globale Dropshipping-Gewinnmarge",label:"Zielmarge",description:"Gilt für CJ-Plattformprodukte und freigegebene Dropshipping-Händler; normale Marktplatzprodukte bleiben unberührt.",future:"Änderungen gelten für neue und aktuelle Berechnungen. Bezahlte historische Bestellungen werden nie neu berechnet.",defaultValue:"Standard: 20 %",save:"Marge aktualisieren",saving:"Wird aktualisiert…",success:"Globale Marge aktualisiert.",invalid:"Prozentwert von 0 bis 80 mit höchstens zwei Dezimalstellen eingeben."},
 es:{title:"Margen de beneficio global de dropshipping",label:"Margen objetivo",description:"Se aplica a productos CJ y vendedores de dropshipping autorizados; no afecta a productos normales.",future:"Los cambios se aplican a cálculos nuevos y en vivo. Los pedidos pagados históricos nunca se recalculan.",defaultValue:"Predeterminado: 20 %",save:"Actualizar margen",saving:"Actualizando…",success:"Margen global actualizado.",invalid:"Introduce un porcentaje de 0 a 80 con hasta dos decimales."},
 it:{title:"Margine di profitto dropshipping globale",label:"Margine obiettivo",description:"Si applica ai prodotti CJ e ai venditori dropshipping approvati; i prodotti normali non cambiano.",future:"Le modifiche valgono per i nuovi calcoli e quelli in tempo reale. Gli ordini pagati storici non vengono ricalcolati.",defaultValue:"Predefinito: 20%",save:"Aggiorna margine",saving:"Aggiornamento…",success:"Margine globale aggiornato.",invalid:"Inserisci una percentuale da 0 a 80 con massimo due decimali."},
 nl:{title:"Wereldwijde dropshipping-winstmarge",label:"Doelmarge",description:"Geldt voor CJ-platformproducten en goedgekeurde dropshippingverkopers; gewone producten blijven ongewijzigd.",future:"Wijzigingen gelden voor nieuwe en live berekeningen. Betaalde historische bestellingen worden nooit herprijsd.",defaultValue:"Standaard: 20%",save:"Marge bijwerken",saving:"Bijwerken…",success:"Wereldwijde marge bijgewerkt.",invalid:"Voer een percentage van 0 tot 80 in met maximaal twee decimalen."},
 zh:{title:"全球代发利润率",label:"目标利润率",description:"适用于 CJ 平台商品和已批准的代发卖家；普通市场商品不受影响。",future:"更改用于新的实时价格计算；历史已付款订单绝不重新定价。",defaultValue:"默认：20%",save:"更新利润率",saving:"正在更新…",success:"全球利润率已更新。",invalid:"请输入 0 到 80 之间且最多两位小数的百分比。"},
 fa:{title:"حاشیه سود سراسری دراپ‌شیپینگ",label:"حاشیه هدف",description:"برای محصولات CJ پلتفرم و فروشندگان مجاز دراپ‌شیپینگ است؛ محصولات عادی بازار تغییر نمی‌کنند.",future:"تغییرات بر محاسبات جدید و زنده اعمال می‌شود؛ سفارش‌های پرداخت‌شده گذشته هرگز بازقیمت‌گذاری نمی‌شوند.",defaultValue:"پیش‌فرض: ۲۰٪",save:"به‌روزرسانی حاشیه",saving:"در حال به‌روزرسانی…",success:"حاشیه سراسری به‌روزرسانی شد.",invalid:"درصدی بین ۰ تا ۸۰ با حداکثر دو رقم اعشار وارد کنید."},
 hi:{title:"वैश्विक ड्रॉपशिपिंग लाभ मार्जिन",label:"लक्षित मार्जिन",description:"CJ प्लेटफ़ॉर्म उत्पादों और स्वीकृत ड्रॉपशिपिंग विक्रेताओं पर लागू; सामान्य मार्केटप्लेस उत्पाद अप्रभावित हैं।",future:"बदलाव नई और लाइव गणनाओं पर लागू होते हैं। पुराने भुगतान किए गए ऑर्डर दोबारा मूल्यांकित नहीं होते।",defaultValue:"डिफ़ॉल्ट: 20%",save:"मार्जिन अपडेट करें",saving:"अपडेट हो रहा है…",success:"वैश्विक मार्जिन अपडेट हुआ।",invalid:"0 से 80 तक अधिकतम दो दशमलव वाला प्रतिशत दर्ज करें।"},
 pt:{title:"Margem de lucro global do dropshipping",label:"Margem alvo",description:"Aplica-se a produtos CJ e vendedores de dropshipping aprovados; produtos normais não são afetados.",future:"As alterações aplicam-se a cálculos novos e em tempo real. Encomendas pagas históricas nunca são recalculadas.",defaultValue:"Predefinição: 20%",save:"Atualizar margem",saving:"A atualizar…",success:"Margem global atualizada.",invalid:"Introduza uma percentagem de 0 a 80 com até duas casas decimais."},
 ru:{title:"Глобальная маржа дропшиппинга",label:"Целевая маржа",description:"Применяется к товарам CJ и одобренным дропшиппинг-продавцам; обычные товары не затрагиваются.",future:"Изменения действуют для новых и текущих расчётов. Оплаченные исторические заказы не пересчитываются.",defaultValue:"По умолчанию: 20%",save:"Обновить маржу",saving:"Обновление…",success:"Глобальная маржа обновлена.",invalid:"Введите процент от 0 до 80, не более двух знаков после запятой."}
};
