import type { Locale } from "./config";

const en = {
  eyebrow: "Todijo Help Center", title: "How can we help?", intro: "Send a secure request through Todijo. Your request is stored for authorized support review; no response time is promised.",
  category: "Reason for contact", replyEmail: "Reply email", subject: "Subject", message: "Message", orderReference: "Order reference (optional)", orderReferenceHelp: "Only an order belonging to your signed-in account can be attached.", signInForOrder: "Sign in before attaching an order reference.", productContext: "The verified public product context from the reporting link will be attached.",
  securityWarning: "Never send passwords, authentication codes, OAuth/provider tokens or full payment-card numbers.", attachmentDeferred: "Attachments are not accepted here yet. This avoids unsafe public uploads until dedicated private support storage is available.", submit: "Send request", submitting: "Sending…", failed: "The request could not be sent. Check the fields and verification, then try again.", rateLimited: "Too many requests. Please wait before trying again.", successTitle: "Request received", successText: "Todijo has securely received your request. Keep the reference below; no exact response time is promised.", referenceLabel: "Request reference", contactCta: "Contact the Todijo Help Center",
  categories: { TECHNICAL_ISSUE: "Technical problem", PRODUCT_REPORT: "Report a product", ORDER_OR_PAYMENT: "Order or payment", ACCOUNT_OR_SECURITY: "Account or security", PRIVACY_OR_DATA: "Privacy, personal data or deletion", SELLER_SUPPORT: "Seller or shop", RETURNS_OR_REFUNDS: "Return or refund", GENERAL_QUESTION: "General question", OTHER: "Other" },
  adminTitle: "Support requests", adminIntro: "Database-authorized review queue for requests submitted through Todijo.", empty: "No requests in this status.", save: "Save status", note: "Internal resolution note", backAdmin: "Back to administration",
};
const fr: typeof en = {
  eyebrow: "Centre d'aide Todijo", title: "Comment pouvons-nous vous aider ?", intro: "Envoyez une demande sécurisée via Todijo. Elle est conservée pour examen par les personnes autorisées ; aucun délai de réponse précis n'est promis.",
  category: "Motif du contact", replyEmail: "Adresse e-mail de réponse", subject: "Objet", message: "Message", orderReference: "Référence de commande (facultatif)", orderReferenceHelp: "Seule une commande appartenant à votre compte connecté peut être associée.", signInForOrder: "Connectez-vous avant d'associer une commande.", productContext: "Le contexte public vérifié du produit provenant du lien de signalement sera associé.",
  securityWarning: "N'envoyez jamais de mot de passe, code d'authentification, jeton OAuth/fournisseur ni numéro complet de carte bancaire.", attachmentDeferred: "Les pièces jointes ne sont pas encore acceptées ici. Cela évite les téléversements publics non sûrs jusqu'à la disponibilité d'un stockage privé dédié au support.", submit: "Envoyer la demande", submitting: "Envoi…", failed: "La demande n'a pas pu être envoyée. Vérifiez les champs et la validation, puis réessayez.", rateLimited: "Trop de demandes. Attendez avant de réessayer.", successTitle: "Demande reçue", successText: "Todijo a reçu votre demande en toute sécurité. Conservez la référence ci-dessous ; aucun délai précis n'est promis.", referenceLabel: "Référence de la demande", contactCta: "Contacter le Centre d'aide Todijo",
  categories: { TECHNICAL_ISSUE: "Problème technique", PRODUCT_REPORT: "Signaler un produit", ORDER_OR_PAYMENT: "Commande ou paiement", ACCOUNT_OR_SECURITY: "Compte ou sécurité", PRIVACY_OR_DATA: "Vie privée, données ou suppression", SELLER_SUPPORT: "Vendeur ou boutique", RETURNS_OR_REFUNDS: "Retour ou remboursement", GENERAL_QUESTION: "Question générale", OTHER: "Autre" },
  adminTitle: "Demandes d'assistance", adminIntro: "File d'examen autorisée par la base de données pour les demandes envoyées via Todijo.", empty: "Aucune demande avec ce statut.", save: "Enregistrer le statut", note: "Note de résolution interne", backAdmin: "Retour à l'administration",
};
const ku: typeof en = {
  ...en, eyebrow: "ناوەندی یارمەتی Todijo", title: "چۆن یارمەتیت بدەین؟", intro: "داواکارییەکی پارێزراو لە ڕێگەی Todijo بنێرە. داواکارییەکەت بۆ پشکنینی تیمی مۆڵەتپێدراو هەڵدەگیرێت.", category: "هۆکاری پەیوەندی", replyEmail: "ئیمەیڵی وەڵام", subject: "بابەت", message: "نامە", orderReference: "ژمارەی داواکاری (ئارەزوومەندانە)", orderReferenceHelp: "تەنها داواکارییەکی سەر بە هەژماری خۆت دەتوانرێت پەیوەست بکرێت.", signInForOrder: "پێش پەیوەستکردنی داواکاری بچۆ ژوورەوە.", productContext: "زانیاریی پشتڕاستکراوی کاڵاکە پەیوەست دەکرێت.", securityWarning: "هەرگیز وشەی نهێنی، کۆدی دڵنیایی، تۆکنی OAuth یان ژمارەی تەواوی کارتی پارەدان مەنێرە.", attachmentDeferred: "هاوپێچ لێرە هێشتا وەرناگیرێت تا storage ـی تایبەت و پارێزراو ئامادە بێت.", submit: "ناردنی داواکاری", submitting: "دەنێردرێت…", failed: "داواکارییەکە نەنێردرا. خانەکان و پشتڕاستکردنەوە بپشکنە.", rateLimited: "داواکاری زۆرە؛ تکایە چاوەڕێ بکە.", successTitle: "داواکاری وەرگیرا", successText: "Todijo داواکارییەکەت بە پارێزراوی وەرگرت. ژمارەکە هەڵبگرە.", referenceLabel: "ژمارەی داواکاری", contactCta: "پەیوەندی بە ناوەندی یارمەتی Todijo", categories: { TECHNICAL_ISSUE: "کێشەی تەکنیکی", PRODUCT_REPORT: "ڕاپۆرتکردنی کاڵا", ORDER_OR_PAYMENT: "داواکاری یان پارەدان", ACCOUNT_OR_SECURITY: "هەژمار یان ئاسایش", PRIVACY_OR_DATA: "تایبەتمەندی، داتا یان سڕینەوە", SELLER_SUPPORT: "فرۆشیار یان دووکان", RETURNS_OR_REFUNDS: "گەڕاندنەوە یان پارەدانەوە", GENERAL_QUESTION: "پرسیاری گشتی", OTHER: "هیتر" }, adminTitle: "داواکارییەکانی یارمەتی", adminIntro: "ڕیزی پشکنینی مۆڵەتپێدراو.", empty: "هیچ داواکارییەک نییە.", save: "هەڵگرتنی دۆخ", note: "تێبینی ناوخۆیی", backAdmin: "گەڕانەوە بۆ بەڕێوەبەرایەتی",
};

export const helpCenterMessages = Object.fromEntries((["en","fr","ar","ku","tr","de","es","it","nl","zh","fa","hi","pt","ru"] satisfies Locale[]).map((locale) => [locale, locale === "fr" ? fr : locale === "ku" ? ku : en])) as Record<Locale, typeof en>;
