import type { Locale } from "./config";

const en = {
  eyebrow: "Todijo Help Center", title: "How can we help?", intro: "Send a secure request through Todijo. Your request is stored for authorized support review; no response time is promised.",
  category: "Reason for contact", replyEmail: "Reply email", subject: "Subject", message: "Message", orderReference: "Order reference (optional)", orderReferenceHelp: "Only an order belonging to your signed-in account can be attached.", signInForOrder: "Sign in before attaching an order reference.", productContext: "The verified public product context from the reporting link will be attached.",
  securityWarning: "Never send passwords, authentication codes, OAuth/provider tokens or full payment-card numbers.", attachmentDeferred: "Attachments are not accepted here yet. This avoids unsafe public uploads until dedicated private support storage is available.", submit: "Send request", submitting: "Sendingâ€¦", failed: "The request could not be sent. Check the fields and verification, then try again.", rateLimited: "Too many requests. Please wait before trying again.", successTitle: "Request received", successText: "Todijo has securely received your request. Keep the reference below; no exact response time is promised.", referenceLabel: "Request reference", contactCta: "Contact the Todijo Help Center",
  categories: { TECHNICAL_ISSUE: "Technical problem", PRODUCT_REPORT: "Report a product", ORDER_OR_PAYMENT: "Order or payment", ACCOUNT_OR_SECURITY: "Account or security", PRIVACY_OR_DATA: "Privacy, personal data or deletion", SELLER_SUPPORT: "Seller or shop", RETURNS_OR_REFUNDS: "Return or refund", GENERAL_QUESTION: "General question", OTHER: "Other" },
  adminTitle: "Support requests", adminIntro: "Database-authorized review queue for requests submitted through Todijo.", empty: "No requests in this status.", save: "Save status", note: "Internal resolution note", backAdmin: "Back to administration",
};
const fr: typeof en = {
  eyebrow: "Centre d'aide Todijo", title: "Comment pouvons-nous vous aiderÂ ?", intro: "Envoyez une demande sÃ©curisÃ©e via Todijo. Elle est conservÃ©e pour examen par les personnes autorisÃ©esÂ ; aucun dÃ©lai de rÃ©ponse prÃ©cis n'est promis.",
  category: "Motif du contact", replyEmail: "Adresse e-mail de rÃ©ponse", subject: "Objet", message: "Message", orderReference: "RÃ©fÃ©rence de commande (facultatif)", orderReferenceHelp: "Seule une commande appartenant Ã  votre compte connectÃ© peut Ãªtre associÃ©e.", signInForOrder: "Connectez-vous avant d'associer une commande.", productContext: "Le contexte public vÃ©rifiÃ© du produit provenant du lien de signalement sera associÃ©.",
  securityWarning: "N'envoyez jamais de mot de passe, code d'authentification, jeton OAuth/fournisseur ni numÃ©ro complet de carte bancaire.", attachmentDeferred: "Les piÃ¨ces jointes ne sont pas encore acceptÃ©es ici. Cela Ã©vite les tÃ©lÃ©versements publics non sÃ»rs jusqu'Ã  la disponibilitÃ© d'un stockage privÃ© dÃ©diÃ© au support.", submit: "Envoyer la demande", submitting: "Envoiâ€¦", failed: "La demande n'a pas pu Ãªtre envoyÃ©e. VÃ©rifiez les champs et la validation, puis rÃ©essayez.", rateLimited: "Trop de demandes. Attendez avant de rÃ©essayer.", successTitle: "Demande reÃ§ue", successText: "Todijo a reÃ§u votre demande en toute sÃ©curitÃ©. Conservez la rÃ©fÃ©rence ci-dessousÂ ; aucun dÃ©lai prÃ©cis n'est promis.", referenceLabel: "RÃ©fÃ©rence de la demande", contactCta: "Contacter le Centre d'aide Todijo",
  categories: { TECHNICAL_ISSUE: "ProblÃ¨me technique", PRODUCT_REPORT: "Signaler un produit", ORDER_OR_PAYMENT: "Commande ou paiement", ACCOUNT_OR_SECURITY: "Compte ou sÃ©curitÃ©", PRIVACY_OR_DATA: "Vie privÃ©e, donnÃ©es ou suppression", SELLER_SUPPORT: "Vendeur ou boutique", RETURNS_OR_REFUNDS: "Retour ou remboursement", GENERAL_QUESTION: "Question gÃ©nÃ©rale", OTHER: "Autre" },
  adminTitle: "Demandes d'assistance", adminIntro: "File d'examen autorisÃ©e par la base de donnÃ©es pour les demandes envoyÃ©es via Todijo.", empty: "Aucune demande avec ce statut.", save: "Enregistrer le statut", note: "Note de rÃ©solution interne", backAdmin: "Retour Ã  l'administration",
};
const ku: typeof en = {
  ...en, eyebrow: "ناوەندی یارمەتی Todijo", title: "چۆن یارمەتیت بدەین؟", intro: "داواکارییەکی پارێزراو لە ڕێگەی Todijo بنێرە. داواکارییەکەت بۆ پشکنینی تیمی مۆڵەتپێدراو هەڵدەگیرێت.", category: "هۆکاری پەیوەندی", replyEmail: "ئیمەیڵی وەڵام", subject: "بابەت", message: "نامە", orderReference: "ژمارەی داواکاری (ئارەزوومەندانە)", orderReferenceHelp: "تەنها داواکارییەکی سەر بە هەژماری خۆت دەتوانرێت پەیوەست بکرێت.", signInForOrder: "پێش پەیوەستکردنی داواکاری بچۆ ژوورەوە.", productContext: "زانیاریی پشتڕاستکراوی کاڵاکە پەیوەست دەکرێت.", securityWarning: "هەرگیز وشەی نهێنی، کۆدی دڵنیایی، تۆکنی OAuth یان ژمارەی تەواوی کارتی پارەدان مەنێرە.", attachmentDeferred: "هاوپێچ لێرە هێشتا وەرناگیرێت تا storage ـی تایبەت و پارێزراو ئامادە بێت.", submit: "ناردنی داواکاری", submitting: "دەنێردرێتâ€¦", failed: "داواکارییەکە نەنێردرا. خانەکان و پشتڕاستکردنەوە بپشکنە.", rateLimited: "داواکاری زۆرە؛ تکایە چاوەڕێ بکە.", successTitle: "داواکاری وەرگیرا", successText: "Todijo داواکارییەکەت بە پارێزراوی وەرگرت. ژمارەکە هەڵبگرە.", referenceLabel: "ژمارەی داواکاری", contactCta: "پەیوەندی بە ناوەندی یارمەتی Todijo", categories: { TECHNICAL_ISSUE: "کێشەی تەکنیکی", PRODUCT_REPORT: "ڕاپۆرتکردنی کاڵا", ORDER_OR_PAYMENT: "داواکاری یان پارەدان", ACCOUNT_OR_SECURITY: "هەژمار یان ئاسایش", PRIVACY_OR_DATA: "تایبەتمەندی، داتا یان سڕینەوە", SELLER_SUPPORT: "فرۆشیار یان دووکان", RETURNS_OR_REFUNDS: "گەڕاندنەوە یان پارەدانەوە", GENERAL_QUESTION: "پرسیاری گشتی", OTHER: "هیتر" }, adminTitle: "داواکارییەکانی یارمەتی", adminIntro: "ڕیزی پشکنینی مۆڵەتپێدراو.", empty: "هیچ داواکارییەک نییە.", save: "هەڵگرتنی دۆخ", note: "تێبینی ناوخۆیی", backAdmin: "گەڕانەوە بۆ بەڕێوەبەرایەتی",
};

export const helpCenterMessages = Object.fromEntries((["en","fr","ar","ku","tr","de","es","it","nl","zh","fa","hi","pt","ru"] satisfies Locale[]).map((locale) => [locale, locale === "fr" ? fr : locale === "ku" ? ku : en])) as Record<Locale, typeof en>;
