import type { Locale } from "./config";

export const loyaltyKeys = ["title", "intro", "available", "pending", "expiringSoon",
  "store", "history", "emptyHistory", "earnedPending", "earnedAvailable",
  "redeemed", "restored", "reversed", "expired", "adjusted", "owed",
  "participation", "enabled", "disabled", "globalRate", "reserve",
  "eligibleProducts", "save", "blocked", "unavailable"] as const;
export type LoyaltyKey = typeof loyaltyKeys[number];
type LoyaltyCopy = Record<LoyaltyKey, string>;

const labels: Record<Locale, readonly string[]> = {
  en: ["Loyalty credit", "Your credit is in euros and can be used only at the issuing store.", "Available credit", "Pending credit", "Expiring soon", "Store", "History", "No loyalty activity yet.", "Credit pending", "Credit available", "Credit used", "Credit restored", "Credit reversed", "Credit expired", "Adjustment", "Amount owed", "Loyalty program", "On", "Off", "Current rate", "Loyalty reserve", "Eligible products", "Save", "Participation blocked", "Loyalty is unavailable right now."],
  fr: ["Crédit fidélité", "Votre crédit est en euros et ne peut être utilisé que dans la boutique qui l’a émis.", "Crédit disponible", "Crédit en attente", "Expire bientôt", "Boutique", "Historique", "Aucune activité fidélité pour le moment.", "Crédit en attente", "Crédit disponible", "Crédit utilisé", "Crédit restauré", "Crédit annulé", "Crédit expiré", "Ajustement", "Montant dû", "Programme fidélité", "Activé", "Désactivé", "Taux actuel", "Réserve fidélité", "Produits éligibles", "Enregistrer", "Participation bloquée", "Le crédit fidélité est momentanément indisponible."],
  ar: ["رصيد الولاء", "رصيدك باليورو ولا يُستخدم إلا في المتجر الذي أصدره.", "الرصيد المتاح", "الرصيد المعلّق", "ينتهي قريبًا", "المتجر", "السجل", "لا توجد معاملات ولاء بعد.", "رصيد معلّق", "رصيد متاح", "رصيد مستخدم", "رصيد مستعاد", "رصيد معكوس", "رصيد منتهي", "تعديل", "مبلغ مستحق", "برنامج الولاء", "مفعّل", "معطّل", "النسبة الحالية", "احتياطي الولاء", "المنتجات المؤهلة", "حفظ", "المشاركة محظورة", "رصيد الولاء غير متاح الآن."],
  ku: ["کرێدیتی دڵسۆزی", "کرێدیتەکەت بە یۆرۆیە و تەنها لەو فرۆشگایە بەکاردێت کە دایەتی.", "کرێدیتی بەردەست", "کرێدیتی چاوەڕوان", "بەم زووانە بەسەردەچێت", "فرۆشگا", "مێژوو", "هێشتا چاڵاکی دڵسۆزی نییە.", "کرێدیتی چاوەڕوان", "کرێدیتی بەردەست", "کرێدیتی بەکارهاتوو", "کرێدیتی گەڕاوە", "کرێدیتی پاشگەزکراو", "کرێدیتی بەسەرچوو", "ڕاستکردنەوە", "بڕی قەرز", "بەرنامەی دڵسۆزی", "چالاک", "ناچالاک", "ڕێژەی ئێستا", "یەدەگی دڵسۆزی", "کاڵای شیاو", "پاشەکەوتکردن", "بەشداری ڕاگیراوە", "کرێدیتی دڵسۆزی ئێستا بەردەست نییە."],
  tr: ["Sadakat kredisi", "Krediniz avro cinsindedir ve yalnızca krediyi veren mağazada kullanılabilir.", "Kullanılabilir kredi", "Bekleyen kredi", "Yakında sona erecek", "Mağaza", "Geçmiş", "Henüz sadakat işlemi yok.", "Bekleyen kredi", "Kullanılabilir kredi", "Kullanılan kredi", "Geri yüklenen kredi", "Geri alınan kredi", "Süresi dolan kredi", "Düzeltme", "Borç tutarı", "Sadakat programı", "Açık", "Kapalı", "Geçerli oran", "Sadakat karşılığı", "Uygun ürünler", "Kaydet", "Katılım engellendi", "Sadakat kredisi şu anda kullanılamıyor."],
  de: ["Treueguthaben", "Ihr Guthaben lautet auf Euro und gilt nur im ausstellenden Shop.", "Verfügbares Guthaben", "Ausstehendes Guthaben", "Läuft bald ab", "Shop", "Verlauf", "Noch keine Treueaktivität.", "Guthaben ausstehend", "Guthaben verfügbar", "Guthaben eingelöst", "Guthaben wiederhergestellt", "Guthaben rückgängig gemacht", "Guthaben abgelaufen", "Anpassung", "Geschuldeter Betrag", "Treueprogramm", "Ein", "Aus", "Aktueller Satz", "Treuerücklage", "Berechtigte Produkte", "Speichern", "Teilnahme gesperrt", "Treueguthaben ist derzeit nicht verfügbar."],
  es: ["Crédito de fidelidad", "Tu crédito está en euros y solo puede usarse en la tienda que lo emitió.", "Crédito disponible", "Crédito pendiente", "Caduca pronto", "Tienda", "Historial", "Aún no hay actividad de fidelidad.", "Crédito pendiente", "Crédito disponible", "Crédito utilizado", "Crédito restablecido", "Crédito revertido", "Crédito caducado", "Ajuste", "Importe adeudado", "Programa de fidelidad", "Activado", "Desactivado", "Tasa actual", "Reserva de fidelidad", "Productos aptos", "Guardar", "Participación bloqueada", "El crédito de fidelidad no está disponible ahora."],
  it: ["Credito fedeltà", "Il credito è in euro e si può usare solo nel negozio che lo ha emesso.", "Credito disponibile", "Credito in attesa", "In scadenza", "Negozio", "Cronologia", "Nessuna attività fedeltà per ora.", "Credito in attesa", "Credito disponibile", "Credito utilizzato", "Credito ripristinato", "Credito stornato", "Credito scaduto", "Rettifica", "Importo dovuto", "Programma fedeltà", "Attivo", "Disattivo", "Tasso attuale", "Riserva fedeltà", "Prodotti idonei", "Salva", "Partecipazione bloccata", "Il credito fedeltà non è disponibile ora."],
  nl: ["Trouwtegoed", "Je tegoed is in euro en kan alleen worden gebruikt bij de winkel die het heeft uitgegeven.", "Beschikbaar tegoed", "Tegoed in behandeling", "Verloopt binnenkort", "Winkel", "Geschiedenis", "Nog geen trouwactiviteiten.", "Tegoed in behandeling", "Tegoed beschikbaar", "Tegoed gebruikt", "Tegoed hersteld", "Tegoed teruggedraaid", "Tegoed verlopen", "Correctie", "Verschuldigd bedrag", "Trouwprogramma", "Aan", "Uit", "Huidig percentage", "Trouwreserve", "Geschikte producten", "Opslaan", "Deelname geblokkeerd", "Trouwtegoed is momenteel niet beschikbaar."],
  zh: ["忠诚抵用金", "抵用金以欧元计，仅可在发放该抵用金的店铺使用。", "可用抵用金", "待生效抵用金", "即将到期", "店铺", "记录", "暂无忠诚抵用金记录。", "待生效抵用金", "可用抵用金", "已使用抵用金", "已恢复抵用金", "已撤销抵用金", "已到期抵用金", "调整", "欠款金额", "忠诚计划", "开启", "关闭", "当前比例", "忠诚金准备金", "符合条件的商品", "保存", "参与已被禁止", "忠诚抵用金暂不可用。"],
  fa: ["اعتبار وفاداری", "اعتبار شما به یورو است و فقط در فروشگاه صادرکننده قابل استفاده است.", "اعتبار موجود", "اعتبار در انتظار", "به‌زودی منقضی می‌شود", "فروشگاه", "سابقه", "هنوز فعالیت وفاداری وجود ندارد.", "اعتبار در انتظار", "اعتبار موجود", "اعتبار مصرف‌شده", "اعتبار بازگردانده‌شده", "اعتبار برگشت‌خورده", "اعتبار منقضی‌شده", "تعدیل", "مبلغ بدهی", "برنامه وفاداری", "روشن", "خاموش", "نرخ کنونی", "ذخیره وفاداری", "محصولات واجد شرایط", "ذخیره", "مشارکت مسدود است", "اعتبار وفاداری اکنون در دسترس نیست."],
  hi: ["लॉयल्टी क्रेडिट", "आपका क्रेडिट यूरो में है और केवल जारी करने वाले स्टोर में उपयोग किया जा सकता है।", "उपलब्ध क्रेडिट", "लंबित क्रेडिट", "जल्द समाप्त होगा", "स्टोर", "इतिहास", "अभी कोई लॉयल्टी गतिविधि नहीं है।", "लंबित क्रेडिट", "उपलब्ध क्रेडिट", "उपयोग किया गया क्रेडिट", "बहाल किया गया क्रेडिट", "वापस लिया गया क्रेडिट", "समाप्त क्रेडिट", "समायोजन", "बकाया राशि", "लॉयल्टी कार्यक्रम", "चालू", "बंद", "वर्तमान दर", "लॉयल्टी आरक्षित राशि", "पात्र उत्पाद", "सहेजें", "भागीदारी रोकी गई", "लॉयल्टी क्रेडिट अभी उपलब्ध नहीं है।"],
  pt: ["Crédito de fidelidade", "O seu crédito é em euros e só pode ser usado na loja que o emitiu.", "Crédito disponível", "Crédito pendente", "A expirar em breve", "Loja", "Histórico", "Ainda não há atividade de fidelidade.", "Crédito pendente", "Crédito disponível", "Crédito utilizado", "Crédito reposto", "Crédito revertido", "Crédito expirado", "Ajuste", "Montante devido", "Programa de fidelidade", "Ativo", "Inativo", "Taxa atual", "Reserva de fidelidade", "Produtos elegíveis", "Guardar", "Participação bloqueada", "O crédito de fidelidade não está disponível agora."],
  ru: ["Бонусный кредит", "Ваш кредит в евро и действует только в магазине, который его выдал.", "Доступный кредит", "Ожидаемый кредит", "Скоро истечёт", "Магазин", "История", "Пока нет операций по программе лояльности.", "Кредит ожидается", "Кредит доступен", "Кредит использован", "Кредит восстановлен", "Кредит отменён", "Кредит истёк", "Корректировка", "Сумма долга", "Программа лояльности", "Включена", "Выключена", "Текущая ставка", "Резерв лояльности", "Подходящие товары", "Сохранить", "Участие заблокировано", "Бонусный кредит сейчас недоступен."],
};

export const loyaltyMessages = Object.fromEntries(Object.entries(labels).map(([locale, values]) => {
  if (values.length !== loyaltyKeys.length || values.some(value => !value.trim())) throw new Error(`Incomplete loyalty copy: ${locale}`);
  return [locale, Object.fromEntries(loyaltyKeys.map((key, index) => [key, values[index]]))];
})) as Record<Locale, LoyaltyCopy>;
