const en = {
  title: "Your store can start for free", intro: "Buying on Todijo never requires a seller subscription. FREE lets you sell up to 5 products after the normal seller, verification and payment setup requirements are met.",
  compare: "Which plan suits me?", free: "No seller subscription", oneStore: "One store", setup: "Complete seller information and required verification", payments: "Configure payments with Stripe", add: "Add products and publish when eligible", reach: "Grow your presence beyond your town, across France and in markets served by available shipping options.",
  freeHelp: "Start free with up to 5 products. Your products remain searchable and browsable normally.", plusHelp: "Grow your catalog to 50 products and create more opportunities for buyers to discover your items.", proHelp: "Grow your catalog without limits, access advanced tools and resurface up to 5 eligible products each day.", proImport: "Import products",
  dashboardUpgradeTitle: "Grow your catalog and increase visibility opportunities", dashboardUpgradeBody: "Upgrade to PLUS or PRO to publish more products and create more opportunities to present your items to buyers.", dashboardProVisibility: "With PRO, up to 5 eligible products can be resurfaced each day.", dashboardUpgradeCta: "Discover PLUS and PRO",
  readinessTitle: "Complete your seller setup", readinessHelp: "Finish the required seller information and store checks before publishing.", readinessAction: "Review store setup", storeReviewTitle: "Your store is under review", storeReviewHelp: "Your store must be approved before you can publish products. Contact Todijo support if you need help.", storeUnavailableTitle: "Your store is not currently available for publishing", storeUnavailableHelp: "Contact Todijo support for information about your store status.",
  importProducts: "Import products", importTitle: "PRO product import", importBack: "Back to your products", importSource: "Source", importFile: "Catalog file", importFormats: "Accepted formats: CSV, Excel, XML and JSON.", importVerify: "Review file", importAsDrafts: "Import as drafts", importReady: "{count} products are ready to be imported as drafts.",
  resurfacing: "Up to 5 eligible products resurfaced each day", discovery: "Discover independent PRO stores", supplies: "Todijo shipping supplies", suppliesHelp: "Access to Todijo shipping supplies, subject to availability and conditions.", suppliesRequest: "Request shipping supplies", suppliesSubject: "Todijo shipping supplies request",
  continue: "Continue to secure payment", modify: "Change my plan", canceled: "Payment was canceled. Your selection is preserved; you can retry or change it.", recommended: "Recommended for your catalog", quota: "FREE allows up to 5 products. Upgrade to PLUS or PRO for more capacity. On expiry, the five oldest published products stay visible; excess products remain stored. Unpublish a product to choose another within your limit. Demoted products require manual reactivation.",
};
const fr: typeof en = {
  title: "Votre boutique peut commencer gratuitement", intro: "Acheter sur Todijo ne nécessite jamais d’abonnement vendeur. FREE vous permet de vendre jusqu’à 5 produits après les vérifications et la configuration des paiements requises.",
  compare: "Découvrir les formules", free: "Sans abonnement vendeur", oneStore: "Une boutique", setup: "Compléter les informations vendeur et la vérification requise", payments: "Configurer les paiements avec Stripe", add: "Ajouter des produits et publier lorsque vous êtes éligible", reach: "Développez votre présence au-delà de votre ville, en France et dans les marchés desservis par les options de livraison disponibles.",
  freeHelp: "Commencez gratuitement avec jusqu’à 5 produits. Vos produits restent accessibles dans la recherche et le catalogue.", plusHelp: "Développez votre catalogue jusqu’à 50 produits et multipliez les opportunités de présenter vos articles aux acheteurs.", proHelp: "Développez votre catalogue sans limite, accédez aux outils avancés et remettez jusqu’à 5 produits éligibles en avant chaque jour.", proImport: "Importer vos produits",
  dashboardUpgradeTitle: "Développez votre catalogue et gagnez en visibilité", dashboardUpgradeBody: "Passez à PLUS ou PRO pour publier davantage de produits et multiplier les opportunités de présenter vos articles aux acheteurs.", dashboardProVisibility: "Avec PRO, jusqu’à 5 produits éligibles peuvent être remis en avant chaque jour.", dashboardUpgradeCta: "Découvrir PLUS et PRO",
  readinessTitle: "Terminez la configuration de votre compte vendeur", readinessHelp: "Complétez les informations vendeur et les vérifications requises avant de publier.", readinessAction: "Vérifier la configuration de la boutique", storeReviewTitle: "Votre boutique est en cours d’examen", storeReviewHelp: "Votre boutique doit être approuvée avant de publier des produits. Contactez l’assistance Todijo si vous avez besoin d’aide.", storeUnavailableTitle: "La publication est indisponible pour votre boutique", storeUnavailableHelp: "Contactez l’assistance Todijo pour obtenir des informations sur le statut de votre boutique.",
  importProducts: "Importer vos produits", importTitle: "Importer vos produits", importBack: "Retour à vos produits", importSource: "Source d’importation", importFile: "Fichier catalogue", importFormats: "Formats acceptés : CSV, Excel, XML et JSON.", importVerify: "Vérifier le fichier", importAsDrafts: "Importer comme brouillons", importReady: "{count} produits prêts à être importés comme brouillons.",
  resurfacing: "Jusqu’à 5 produits éligibles remis en avant chaque jour", discovery: "Découvrez les boutiques PRO indépendantes", supplies: "Fournitures d’expédition Todijo", suppliesHelp: "Accès aux fournitures d’expédition Todijo, selon disponibilité et conditions.", suppliesRequest: "Demander des fournitures d’expédition", suppliesSubject: "Demande de fournitures d’expédition Todijo",
  continue: "Continuer vers le paiement sécurisé", modify: "Modifier ma formule", canceled: "Le paiement a été annulé. Votre sélection est conservée : réessayez ou modifiez votre formule.", recommended: "Recommandé pour votre catalogue", quota: "Votre formule FREE permet jusqu’à 5 produits. Passez à PLUS ou PRO pour plus de capacité. À l’expiration, les cinq produits publiés les plus anciens restent visibles ; les autres restent enregistrés. Dépubliez un produit pour en choisir un autre dans votre limite. Les produits dépubliés nécessitent une réactivation manuelle.",
};
/** New copy uses the established English fallback for locales not yet translated. */
export function sellerFreeModelCopy(locale: string) { return locale === "fr" ? fr : en; }
