import { defaultLocale, isLocale, type Locale } from "./config";

const messages = {
  en: { downloadReport: "Download report", downloadStock: "Download stock", paymentDate: "Payment date", order: "Order", currency: "Currency", merchandiseSales: "Merchandise sales", shipping: "Shipping", commission: "Todijo commission", refunds: "Refunds", sellerAmount: "Seller amount", transferStatus: "Transfer status", transferDate: "Transfer date", product: "Product", variant: "Variant", sku: "SKU", stock: "Stock", price: "Price", status: "Status" },
  fr: { downloadReport: "Télécharger le rapport", downloadStock: "Télécharger le stock", paymentDate: "Date de paiement", order: "Commande", currency: "Devise", merchandiseSales: "Ventes d’articles", shipping: "Livraison", commission: "Commission Todijo", refunds: "Remboursements", sellerAmount: "Montant vendeur", transferStatus: "État du versement", transferDate: "Date du versement", product: "Produit", variant: "Variante", sku: "Référence SKU", stock: "Stock", price: "Prix", status: "Statut" },
  ar: { downloadReport: "تنزيل التقرير", downloadStock: "تنزيل المخزون", paymentDate: "تاريخ الدفع", order: "الطلب", currency: "العملة", merchandiseSales: "مبيعات المنتجات", shipping: "الشحن", commission: "عمولة توديجو", refunds: "المبالغ المستردة", sellerAmount: "مبلغ البائع", transferStatus: "حالة التحويل", transferDate: "تاريخ التحويل", product: "المنتج", variant: "النوع", sku: "رمز SKU", stock: "المخزون", price: "السعر", status: "الحالة" },
  ku: { downloadReport: "داگرتنی ڕاپۆرت", downloadStock: "داگرتنی کۆگا", paymentDate: "بەرواری پارەدان", order: "داواکاری", currency: "دراو", merchandiseSales: "فرۆشی بەرهەم", shipping: "گەیاندن", commission: "کۆمیسیۆنی تۆدیجۆ", refunds: "پارە گەڕاوەکان", sellerAmount: "بڕی فرۆشیار", transferStatus: "دۆخی گواستنەوە", transferDate: "بەرواری گواستنەوە", product: "بەرهەم", variant: "جۆر", sku: "کۆدی SKU", stock: "کۆگا", price: "نرخ", status: "دۆخ" },
  tr: { downloadReport: "Raporu indir", downloadStock: "Stoğu indir", paymentDate: "Ödeme tarihi", order: "Sipariş", currency: "Para birimi", merchandiseSales: "Ürün satışları", shipping: "Kargo", commission: "Todijo komisyonu", refunds: "İadeler", sellerAmount: "Satıcı tutarı", transferStatus: "Aktarım durumu", transferDate: "Aktarım tarihi", product: "Ürün", variant: "Varyant", sku: "SKU", stock: "Stok", price: "Fiyat", status: "Durum" },
  de: { downloadReport: "Bericht herunterladen", downloadStock: "Bestand herunterladen", paymentDate: "Zahlungsdatum", order: "Bestellung", currency: "Währung", merchandiseSales: "Warenverkäufe", shipping: "Versand", commission: "Todijo-Provision", refunds: "Erstattungen", sellerAmount: "Verkäuferbetrag", transferStatus: "Auszahlungsstatus", transferDate: "Auszahlungsdatum", product: "Produkt", variant: "Variante", sku: "SKU-Referenz", stock: "Bestand", price: "Preis", status: "Status" },
  es: { downloadReport: "Descargar informe", downloadStock: "Descargar existencias", paymentDate: "Fecha de pago", order: "Pedido", currency: "Moneda", merchandiseSales: "Ventas de productos", shipping: "Envío", commission: "Comisión de Todijo", refunds: "Reembolsos", sellerAmount: "Importe del vendedor", transferStatus: "Estado de la transferencia", transferDate: "Fecha de transferencia", product: "Producto", variant: "Variante", sku: "Referencia SKU", stock: "Existencias", price: "Precio", status: "Estado" },
  it: { downloadReport: "Scarica il rapporto", downloadStock: "Scarica le scorte", paymentDate: "Data di pagamento", order: "Ordine", currency: "Valuta", merchandiseSales: "Vendite dei prodotti", shipping: "Spedizione", commission: "Commissione Todijo", refunds: "Rimborsi", sellerAmount: "Importo del venditore", transferStatus: "Stato del trasferimento", transferDate: "Data del trasferimento", product: "Prodotto", variant: "Variante", sku: "Riferimento SKU", stock: "Scorte", price: "Prezzo", status: "Stato" },
  nl: { downloadReport: "Rapport downloaden", downloadStock: "Voorraad downloaden", paymentDate: "Betaaldatum", order: "Bestelling", currency: "Valuta", merchandiseSales: "Productverkopen", shipping: "Verzending", commission: "Todijo-commissie", refunds: "Terugbetalingen", sellerAmount: "Bedrag voor verkoper", transferStatus: "Overboekingsstatus", transferDate: "Overboekingsdatum", product: "Product", variant: "Variant", sku: "SKU-referentie", stock: "Voorraad", price: "Prijs", status: "Status" },
  zh: { downloadReport: "下载报告", downloadStock: "下载库存", paymentDate: "付款日期", order: "订单", currency: "货币", merchandiseSales: "商品销售额", shipping: "配送", commission: "Todijo 佣金", refunds: "退款", sellerAmount: "卖家金额", transferStatus: "转账状态", transferDate: "转账日期", product: "商品", variant: "规格", sku: "SKU 编号", stock: "库存", price: "价格", status: "状态" },
  fa: { downloadReport: "دانلود گزارش", downloadStock: "دانلود موجودی", paymentDate: "تاریخ پرداخت", order: "سفارش", currency: "ارز", merchandiseSales: "فروش کالا", shipping: "ارسال", commission: "کارمزد تودیجو", refunds: "بازپرداخت‌ها", sellerAmount: "مبلغ فروشنده", transferStatus: "وضعیت انتقال", transferDate: "تاریخ انتقال", product: "محصول", variant: "مدل", sku: "شناسه SKU", stock: "موجودی", price: "قیمت", status: "وضعیت" },
  hi: { downloadReport: "रिपोर्ट डाउनलोड करें", downloadStock: "स्टॉक डाउनलोड करें", paymentDate: "भुगतान की तारीख", order: "ऑर्डर", currency: "मुद्रा", merchandiseSales: "उत्पाद बिक्री", shipping: "शिपिंग", commission: "Todijo कमीशन", refunds: "रिफंड", sellerAmount: "विक्रेता राशि", transferStatus: "हस्तांतरण स्थिति", transferDate: "हस्तांतरण की तारीख", product: "उत्पाद", variant: "वेरिएंट", sku: "SKU संदर्भ", stock: "स्टॉक", price: "कीमत", status: "स्थिति" },
  pt: { downloadReport: "Descarregar relatório", downloadStock: "Descarregar stock", paymentDate: "Data do pagamento", order: "Encomenda", currency: "Moeda", merchandiseSales: "Vendas de produtos", shipping: "Envio", commission: "Comissão Todijo", refunds: "Reembolsos", sellerAmount: "Valor do vendedor", transferStatus: "Estado da transferência", transferDate: "Data da transferência", product: "Produto", variant: "Variante", sku: "Referência SKU", stock: "Stock", price: "Preço", status: "Estado" },
  ru: { downloadReport: "Скачать отчет", downloadStock: "Скачать остатки", paymentDate: "Дата оплаты", order: "Заказ", currency: "Валюта", merchandiseSales: "Продажи товаров", shipping: "Доставка", commission: "Комиссия Todijo", refunds: "Возвраты", sellerAmount: "Сумма продавца", transferStatus: "Статус перевода", transferDate: "Дата перевода", product: "Товар", variant: "Вариант", sku: "Артикул SKU", stock: "Остаток", price: "Цена", status: "Статус" },
} satisfies Record<Locale, Record<string, string>>;

export type SellerReportCopy = typeof messages.en;
export function sellerReportCopy(locale: string): SellerReportCopy {
  const key = (isLocale(locale) ? locale : defaultLocale) as Locale;
  return messages[key];
}
