const en = {
  title: "Your store can start for free", intro: "Buying on Todijo never requires a seller subscription. FREE lets you sell up to 5 products after the normal seller, verification and payment setup requirements are met. PLUS and PRO are optional upgrades.",
  compare: "Which plan suits me?", proNeeds: "I need dropshipping, Team, multiple stores or daily homepage resurfacing", free: "No seller subscription", oneStore: "One store", setup: "Complete seller information and required verification", payments: "Configure payments with Stripe", add: "Add products and publish when eligible", reach: "Reach customers beyond your town, across France and supported shipping markets. Visibility does not guarantee sales.",
  freeHelp: "Start with up to 5 products. Your products remain searchable and browsable normally.", plusHelp: "Grow your catalog to 50 products.", proHelp: "Unlimited products, dropshipping, Team and up to 3 stores.",
  resurfacing: "Up to 5 products resurfaced each day", discovery: "Discover independent PRO stores", supplies: "Todijo shipping supplies", suppliesHelp: "Access to Todijo shipping supplies, subject to availability and conditions. No unlimited free supplies are promised.", suppliesRequest: "Request shipping supplies", suppliesSubject: "Todijo shipping supplies request",
  continue: "Continue to secure payment", modify: "Change my plan", canceled: "Payment was canceled. Your selection is preserved; you can retry or change it.", recommended: "Recommended for your catalog", quota: "FREE allows up to 5 products. Upgrade to PLUS or PRO for more capacity. On expiry, the five oldest published products stay visible; excess products remain stored. Unpublish a product to choose another within your limit. Demoted products require manual reactivation.",
};
const fr: typeof en = {
  title: "Votre boutique peut commencer gratuitement", intro: "Acheter sur Todijo ne nécessite jamais d’abonnement vendeur. FREE permet de vendre jusqu’à 5 produits une fois les conditions normales vendeur, de vérification et de paiement remplies. PLUS et PRO sont des améliorations facultatives.",
  compare: "Quel plan me convient ?", proNeeds: "J’ai besoin du dropshipping, d’une équipe, de plusieurs boutiques ou de la mise en avant quotidienne", free: "Sans abonnement vendeur", oneStore: "Une boutique", setup: "Compléter les informations vendeur et la vérification requise", payments: "Configurer les paiements avec Stripe", add: "Ajouter des produits et publier lorsque vous êtes éligible", reach: "Touchez des clients au-delà de votre ville, en France et dans les marchés desservis par les livraisons. La visibilité ne garantit pas de ventes.",
  freeHelp: "Commencez avec jusqu’à 5 produits. Vos produits restent accessibles dans la recherche et le catalogue.", plusHelp: "Développez votre catalogue jusqu’à 50 produits.", proHelp: "Produits illimités, dropshipping, équipe et jusqu’à 3 boutiques.",
  resurfacing: "Jusqu’à 5 produits remis en avant chaque jour", discovery: "Découvrez les boutiques PRO indépendantes", supplies: "Fournitures d’expédition Todijo", suppliesHelp: "Accès aux fournitures d’expédition Todijo, selon disponibilité et conditions. Aucune fourniture gratuite illimitée n’est promise.", suppliesRequest: "Demander des fournitures d’expédition", suppliesSubject: "Demande de fournitures d’expédition Todijo",
  continue: "Continuer vers le paiement sécurisé", modify: "Modifier ma formule", canceled: "Le paiement a été annulé. Votre sélection est conservée : réessayez ou modifiez votre formule.", recommended: "Recommandé pour votre catalogue", quota: "Votre formule FREE permet jusqu’à 5 produits. Passez à PLUS ou PRO pour plus de capacité. À l’expiration, les cinq produits publiés les plus anciens restent visibles ; les autres restent enregistrés. Dépubliez un produit pour en choisir un autre dans votre limite. Les produits dépubliés nécessitent une réactivation manuelle.",
};
/** New copy uses the established English fallback for locales not yet translated. */
export function sellerFreeModelCopy(locale: string) { return locale === "fr" ? fr : en; }
