import { defaultLocale, isLocale, type Locale } from "./config";

export type SellerTeamCopy = {
  title: string; intro: string; invite: string; email: string; stores: string; role: string; permissions: string;
  invitationHelp: string; storeHelp: string; roleHelp: string; ownerOnly: string; active: string; pending: string; suspended: string; removed: string;
  save: string; suspend: string; reactivate: string; remove: string; revoke: string; resend: string; audit: string; empty: string;
  invitationSubject: string; invitationHeading: string; invitationBody: string; invitationCta: string;
  edit: string; cancel: string; firstName: string; lastName: string; password: string; expires: string; confirmRemove: string; confirmSuspend: string;
  createStore: string; createStoreHelp: string; allStores: string; selectStoreHelp: string;
  dashboard: string; security: string; all: string; category: string; filter: string; when: string; who: string; where: string; action: string; target: string; previous: string; next: string;
};

const en: SellerTeamCopy = { title:"Team",intro:"Give trusted people access to selected stores without sharing your password.",invite:"Invite a team member",email:"Email",stores:"Store access",role:"Role template",permissions:"Permissions",invitationHelp:"This person receives their own secure Todijo login. Your password is never shared.",storeHelp:"Choose the stores this person can access. Other stores and private data stay hidden.",roleHelp:"Choose a starting role, then customize individual permissions.",ownerOnly:"Only the business owner can manage team access.",active:"Active",pending:"Pending",suspended:"Suspended",removed:"Removed",save:"Save access",suspend:"Suspend",reactivate:"Reactivate",remove:"Remove",revoke:"Revoke",resend:"Resend",audit:"Audit history",empty:"No team members yet.",invitationSubject:"You’re invited to a Todijo team",invitationHeading:"Join a Todijo seller team",invitationBody:"A Todijo business owner invited you to securely manage selected stores. The private link expires in 7 days.",invitationCta:"Review invitation",edit:"Edit access",cancel:"Cancel",firstName:"First name",lastName:"Last name",password:"Password",expires:"Expires",confirmRemove:"Remove this member and revoke access immediately?",confirmSuspend:"Suspend this member and revoke current sessions?",createStore:"Create another store",createStoreHelp:"Your PRO subscription covers this business. Each store keeps separate products, orders and team assignments.",allStores:"All stores",selectStoreHelp:"Select a store to manage its products, orders and settings.",dashboard:"Dashboard",security:"Security",all:"All",category:"Category",filter:"Filter",when:"When",who:"Who",where:"Where",action:"Action",target:"Target",previous:"Previous",next:"Next" };
const fr: SellerTeamCopy = { ...en,title:"Équipe",intro:"Donnez à des personnes de confiance accès aux boutiques choisies sans partager votre mot de passe.",invite:"Inviter un membre",email:"E-mail",stores:"Accès aux boutiques",role:"Modèle de rôle",permissions:"Autorisations",invitationHelp:"Cette personne reçoit son propre accès Todijo sécurisé. Votre mot de passe n’est jamais partagé.",storeHelp:"Choisissez les boutiques accessibles. Les autres boutiques et leurs données privées restent masquées.",roleHelp:"Choisissez un rôle de départ, puis personnalisez les autorisations.",ownerOnly:"Seul le propriétaire de l’entreprise peut gérer l’équipe.",active:"Actif",pending:"En attente",suspended:"Suspendu",removed:"Supprimé",save:"Enregistrer",suspend:"Suspendre",reactivate:"Réactiver",remove:"Supprimer",revoke:"Révoquer",resend:"Renvoyer",audit:"Historique d’audit",empty:"Aucun membre pour le moment.",invitationSubject:"Invitation à rejoindre une équipe Todijo",invitationHeading:"Rejoignez une équipe vendeur Todijo",invitationBody:"Un propriétaire Todijo vous invite à gérer des boutiques sélectionnées en toute sécurité. Ce lien privé expire dans 7 jours.",invitationCta:"Voir l’invitation",edit:"Modifier l’accès",cancel:"Annuler",firstName:"Prénom",lastName:"Nom",password:"Mot de passe",expires:"Expire",confirmRemove:"Supprimer ce membre et révoquer immédiatement son accès ?",confirmSuspend:"Suspendre ce membre et révoquer ses sessions actuelles ?",dashboard:"Tableau de bord",security:"Sécurité",all:"Toutes",category:"Catégorie",filter:"Filtrer",when:"Date",who:"Auteur",where:"Emplacement",action:"Action",target:"Cible",previous:"Précédent",next:"Suivant" };
const translations: Record<Locale, SellerTeamCopy> = {
  en, fr,
  ar:{...en,title:"الفريق",intro:"امنح أشخاصًا موثوقين وصولًا إلى متاجر محددة دون مشاركة كلمة المرور.",invite:"دعوة عضو",email:"البريد الإلكتروني",stores:"الوصول إلى المتاجر",role:"قالب الدور",permissions:"الأذونات",invitationHelp:"سيحصل هذا الشخص على تسجيل دخول آمن خاص به في Todijo. لن تتم مشاركة كلمة مرورك.",storeHelp:"اختر المتاجر التي يمكن لهذا الشخص الوصول إليها. تبقى المتاجر والبيانات الأخرى مخفية.",roleHelp:"اختر دورًا مبدئيًا ثم خصص الأذونات.",ownerOnly:"يمكن لمالك النشاط فقط إدارة الفريق.",active:"نشط",pending:"قيد الانتظار",suspended:"موقوف",removed:"تمت إزالته",save:"حفظ الوصول",suspend:"إيقاف",reactivate:"إعادة التفعيل",remove:"إزالة",revoke:"إلغاء",resend:"إعادة الإرسال",audit:"سجل التدقيق",empty:"لا يوجد أعضاء بعد.",invitationSubject:"دعوة للانضمام إلى فريق Todijo",invitationHeading:"انضم إلى فريق بائع Todijo",invitationBody:"دعاك مالك نشاط Todijo لإدارة متاجر محددة بأمان. تنتهي صلاحية الرابط الخاص خلال 7 أيام.",invitationCta:"عرض الدعوة"},
  ku:{...en,title:"تیم",intro:"بێ هاوبەشکردنی وشەی نهێنی، دەسەڵاتی فرۆشگای دیاریکراو بە کەسانی متمانەپێکراو بدە.",invite:"بانگهێشتکردنی ئەندام",email:"ئیمەیڵ",stores:"دەسەڵاتی فرۆشگا",role:"نموونەی ڕۆڵ",permissions:"دەسەڵاتەکان",invitationHelp:"ئەم کەسە چوونەژوورەوەی پارێزراوی تایبەت بە خۆی وەردەگرێت.",storeHelp:"فرۆشگاکانی ڕێگەپێدراو هەڵبژێرە؛ زانیاریی فرۆشگاکانی تر شاراوە دەمێنێتەوە.",roleHelp:"ڕۆڵێکی سەرەتایی هەڵبژێرە و پاشان دەسەڵاتەکان بگۆڕە.",ownerOnly:"تەنها خاوەنی بازرگانی دەتوانێت تیم بەڕێوە ببات.",active:"چالاک",pending:"چاوەڕوان",suspended:"ڕاگیراو",removed:"لابراو",save:"پاشەکەوتکردن",suspend:"ڕاگرتن",reactivate:"چالاککردنەوە",remove:"لابردن",revoke:"هەڵوەشاندنەوە",resend:"ناردنەوە",audit:"مێژووی پشکنین",empty:"هێشتا ئەندام نییە.",invitationSubject:"بانگهێشت بۆ تیمی Todijo",invitationHeading:"بە تیمی فرۆشیاری Todijo پەیوەست بە",invitationBody:"خاوەن بازرگانییەک بانگهێشتی کردوویت بۆ بەڕێوەبردنی پارێزراوی فرۆشگا هەڵبژێردراوەکان. لینکەکە لە ٧ ڕۆژدا بەسەر دەچێت.",invitationCta:"بینینی بانگهێشت"},
  fa:{...en,title:"تیم",intro:"بدون اشتراک گذرواژه، دسترسی فروشگاه‌های منتخب را به افراد مورد اعتماد بدهید.",invite:"دعوت عضو",email:"ایمیل",stores:"دسترسی فروشگاه",role:"الگوی نقش",permissions:"مجوزها",invitationHelp:"این شخص ورود امن Todijo مخصوص خود را دریافت می‌کند. گذرواژه شما هرگز به اشتراک گذاشته نمی‌شود.",storeHelp:"فروشگاه‌های قابل دسترسی را انتخاب کنید؛ داده‌های خصوصی سایر فروشگاه‌ها پنهان می‌ماند.",roleHelp:"یک نقش اولیه انتخاب و سپس مجوزها را شخصی‌سازی کنید.",ownerOnly:"فقط مالک کسب‌وکار می‌تواند تیم را مدیریت کند.",active:"فعال",pending:"در انتظار",suspended:"تعلیق‌شده",removed:"حذف‌شده",save:"ذخیره دسترسی",suspend:"تعلیق",reactivate:"فعال‌سازی",remove:"حذف",revoke:"لغو",resend:"ارسال مجدد",audit:"سابقه حسابرسی",empty:"هنوز عضوی نیست.",invitationSubject:"دعوت به تیم Todijo",invitationHeading:"به تیم فروشنده Todijo بپیوندید",invitationBody:"مالک یک کسب‌وکار Todijo شما را برای مدیریت امن فروشگاه‌های منتخب دعوت کرده است. پیوند خصوصی ۷ روز اعتبار دارد.",invitationCta:"مشاهده دعوت"},
  de:{...en,title:"Team",invite:"Teammitglied einladen",stores:"Shop-Zugriff",role:"Rollenvorlage",permissions:"Berechtigungen",active:"Aktiv",pending:"Ausstehend",suspended:"Gesperrt",removed:"Entfernt",save:"Zugriff speichern",suspend:"Sperren",reactivate:"Reaktivieren",remove:"Entfernen",revoke:"Widerrufen",resend:"Erneut senden",audit:"Auditverlauf",empty:"Noch keine Teammitglieder."},
  es:{...en,title:"Equipo",invite:"Invitar a un miembro",stores:"Acceso a tiendas",role:"Plantilla de rol",permissions:"Permisos",active:"Activo",pending:"Pendiente",suspended:"Suspendido",removed:"Eliminado",save:"Guardar acceso",suspend:"Suspender",reactivate:"Reactivar",remove:"Eliminar",revoke:"Revocar",resend:"Reenviar",audit:"Historial de auditoría",empty:"Aún no hay miembros."},
  it:{...en,title:"Team",invite:"Invita un membro",stores:"Accesso ai negozi",role:"Modello di ruolo",permissions:"Autorizzazioni",active:"Attivo",pending:"In attesa",suspended:"Sospeso",removed:"Rimosso",save:"Salva accesso",suspend:"Sospendi",reactivate:"Riattiva",remove:"Rimuovi",revoke:"Revoca",resend:"Invia di nuovo",audit:"Registro attività",empty:"Nessun membro."},
  nl:{...en,title:"Team",invite:"Teamlid uitnodigen",stores:"Winkeltoegang",role:"Rolsjabloon",permissions:"Rechten",active:"Actief",pending:"In afwachting",suspended:"Geschorst",removed:"Verwijderd",save:"Toegang opslaan",suspend:"Schorsen",reactivate:"Heractiveren",remove:"Verwijderen",revoke:"Intrekken",resend:"Opnieuw sturen",audit:"Auditgeschiedenis",empty:"Nog geen teamleden."},
  tr:{...en,title:"Ekip",invite:"Ekip üyesi davet et",stores:"Mağaza erişimi",role:"Rol şablonu",permissions:"İzinler",active:"Etkin",pending:"Bekliyor",suspended:"Askıya alındı",removed:"Kaldırıldı",save:"Erişimi kaydet",suspend:"Askıya al",reactivate:"Yeniden etkinleştir",remove:"Kaldır",revoke:"İptal et",resend:"Yeniden gönder",audit:"Denetim geçmişi",empty:"Henüz ekip üyesi yok."},
  zh:{...en,title:"团队",invite:"邀请团队成员",email:"电子邮件",stores:"店铺访问权限",role:"角色模板",permissions:"权限",active:"活跃",pending:"待接受",suspended:"已暂停",removed:"已移除",save:"保存权限",suspend:"暂停",reactivate:"重新启用",remove:"移除",revoke:"撤销",resend:"重新发送",audit:"审计记录",empty:"暂无团队成员。"},
  hi:{...en,title:"टीम",invite:"टीम सदस्य को आमंत्रित करें",email:"ईमेल",stores:"स्टोर एक्सेस",role:"भूमिका टेम्पलेट",permissions:"अनुमतियाँ",active:"सक्रिय",pending:"लंबित",suspended:"निलंबित",removed:"हटाया गया",save:"एक्सेस सहेजें",suspend:"निलंबित करें",reactivate:"फिर सक्रिय करें",remove:"हटाएँ",revoke:"रद्द करें",resend:"फिर भेजें",audit:"ऑडिट इतिहास",empty:"अभी कोई टीम सदस्य नहीं।"},
  pt:{...en,title:"Equipa",invite:"Convidar membro",stores:"Acesso às lojas",role:"Modelo de função",permissions:"Permissões",active:"Ativo",pending:"Pendente",suspended:"Suspenso",removed:"Removido",save:"Guardar acesso",suspend:"Suspender",reactivate:"Reativar",remove:"Remover",revoke:"Revogar",resend:"Reenviar",audit:"Histórico de auditoria",empty:"Ainda não existem membros."},
  ru:{...en,title:"Команда",invite:"Пригласить участника",email:"Эл. почта",stores:"Доступ к магазинам",role:"Шаблон роли",permissions:"Разрешения",active:"Активен",pending:"Ожидает",suspended:"Приостановлен",removed:"Удалён",save:"Сохранить доступ",suspend:"Приостановить",reactivate:"Возобновить",remove:"Удалить",revoke:"Отозвать",resend:"Отправить снова",audit:"Журнал аудита",empty:"Участников пока нет."},
};

const auditCopy:Record<Locale,Pick<SellerTeamCopy,"dashboard"|"security"|"all"|"category"|"filter"|"when"|"who"|"where"|"action"|"target"|"previous"|"next">>={
  en:{dashboard:"Dashboard",security:"Security",all:"All",category:"Category",filter:"Filter",when:"When",who:"Who",where:"Where",action:"Action",target:"Target",previous:"Previous",next:"Next"},
  fr:{dashboard:"Tableau de bord",security:"Sécurité",all:"Toutes",category:"Catégorie",filter:"Filtrer",when:"Date",who:"Auteur",where:"Emplacement",action:"Action",target:"Cible",previous:"Précédent",next:"Suivant"},
  de:{dashboard:"Übersicht",security:"Sicherheit",all:"Alle",category:"Kategorie",filter:"Filtern",when:"Zeitpunkt",who:"Person",where:"Ort",action:"Aktion",target:"Ziel",previous:"Zurück",next:"Weiter"},
  es:{dashboard:"Panel",security:"Seguridad",all:"Todas",category:"Categoría",filter:"Filtrar",when:"Fecha",who:"Persona",where:"Lugar",action:"Acción",target:"Objetivo",previous:"Anterior",next:"Siguiente"},
  it:{dashboard:"Dashboard",security:"Sicurezza",all:"Tutti",category:"Categoria",filter:"Filtra",when:"Data",who:"Persona",where:"Luogo",action:"Azione",target:"Destinazione",previous:"Precedente",next:"Successivo"},
  nl:{dashboard:"Dashboard",security:"Beveiliging",all:"Alle",category:"Categorie",filter:"Filteren",when:"Wanneer",who:"Wie",where:"Waar",action:"Actie",target:"Doel",previous:"Vorige",next:"Volgende"},
  pt:{dashboard:"Painel",security:"Segurança",all:"Todas",category:"Categoria",filter:"Filtrar",when:"Quando",who:"Quem",where:"Onde",action:"Ação",target:"Destino",previous:"Anterior",next:"Seguinte"},
  tr:{dashboard:"Panel",security:"Güvenlik",all:"Tümü",category:"Kategori",filter:"Filtrele",when:"Zaman",who:"Kişi",where:"Yer",action:"İşlem",target:"Hedef",previous:"Önceki",next:"Sonraki"},
  ru:{dashboard:"Панель",security:"Безопасность",all:"Все",category:"Категория",filter:"Фильтр",when:"Когда",who:"Кто",where:"Где",action:"Действие",target:"Цель",previous:"Назад",next:"Далее"},
  ar:{dashboard:"لوحة التحكم",security:"الأمان",all:"الكل",category:"الفئة",filter:"تصفية",when:"الوقت",who:"المستخدم",where:"المكان",action:"الإجراء",target:"الهدف",previous:"السابق",next:"التالي"},
  fa:{dashboard:"داشبورد",security:"امنیت",all:"همه",category:"دسته‌بندی",filter:"فیلتر",when:"زمان",who:"کاربر",where:"مکان",action:"اقدام",target:"هدف",previous:"قبلی",next:"بعدی"},
  hi:{dashboard:"डैशबोर्ड",security:"सुरक्षा",all:"सभी",category:"श्रेणी",filter:"फ़िल्टर",when:"समय",who:"व्यक्ति",where:"स्थान",action:"कार्रवाई",target:"लक्ष्य",previous:"पिछला",next:"अगला"},
  zh:{dashboard:"控制面板",security:"安全",all:"全部",category:"类别",filter:"筛选",when:"时间",who:"操作人",where:"位置",action:"操作",target:"目标",previous:"上一页",next:"下一页"},
  ku:{dashboard:"داشبۆرد",security:"پاراستن",all:"هەموو",category:"پۆل",filter:"پاڵاوتن",when:"کات",who:"کەس",where:"شوێن",action:"کردار",target:"ئامانج",previous:"پێشوو",next:"دواتر"},
};

const workflowCopy:Record<Locale,Pick<SellerTeamCopy,"edit"|"cancel"|"firstName"|"lastName"|"password"|"expires"|"confirmRemove"|"confirmSuspend"|"createStore"|"createStoreHelp"|"allStores"|"selectStoreHelp"|"invitationSubject"|"invitationHeading"|"invitationBody"|"invitationCta">>={
  en:{edit:"Edit access",cancel:"Cancel",firstName:"First name",lastName:"Last name",password:"Password",expires:"Expires",confirmRemove:"Remove this member and revoke access immediately?",confirmSuspend:"Suspend this member and revoke current sessions?",createStore:"Create another store",createStoreHelp:"Your PRO subscription covers this business. Each store keeps separate products, orders and team assignments.",allStores:"All stores",selectStoreHelp:"Select a store to manage its products, orders and settings.",invitationSubject:"You’re invited to a Todijo team",invitationHeading:"Join a Todijo seller team",invitationBody:"A Todijo business owner invited you to securely manage selected stores. The private link expires in 7 days.",invitationCta:"Review invitation"},
  fr:{edit:"Modifier l’accès",cancel:"Annuler",firstName:"Prénom",lastName:"Nom",password:"Mot de passe",expires:"Expire",confirmRemove:"Supprimer ce membre et révoquer immédiatement son accès ?",confirmSuspend:"Suspendre ce membre et révoquer ses sessions actuelles ?",createStore:"Créer une autre boutique",createStoreHelp:"Votre abonnement PRO couvre cette entreprise. Chaque boutique conserve ses produits, commandes et affectations d’équipe.",allStores:"Toutes les boutiques",selectStoreHelp:"Sélectionnez une boutique pour gérer ses produits, commandes et paramètres.",invitationSubject:"Invitation à rejoindre une équipe Todijo",invitationHeading:"Rejoignez une équipe vendeur Todijo",invitationBody:"Un propriétaire Todijo vous invite à gérer des boutiques sélectionnées en toute sécurité. Ce lien privé expire dans 7 jours.",invitationCta:"Voir l’invitation"},
  de:{edit:"Zugriff bearbeiten",cancel:"Abbrechen",firstName:"Vorname",lastName:"Nachname",password:"Passwort",expires:"Läuft ab",confirmRemove:"Dieses Mitglied entfernen und den Zugriff sofort entziehen?",confirmSuspend:"Dieses Mitglied sperren und aktuelle Sitzungen widerrufen?",createStore:"Weiteren Shop erstellen",createStoreHelp:"Ihr PRO-Abonnement gilt für dieses Unternehmen. Produkte, Bestellungen und Teamzuweisungen bleiben je Shop getrennt.",allStores:"Alle Shops",selectStoreHelp:"Wählen Sie einen Shop, um Produkte, Bestellungen und Einstellungen zu verwalten.",invitationSubject:"Einladung in ein Todijo-Team",invitationHeading:"Todijo-Verkäuferteam beitreten",invitationBody:"Ein Todijo-Unternehmen lädt Sie zur sicheren Verwaltung ausgewählter Shops ein. Der private Link läuft in 7 Tagen ab.",invitationCta:"Einladung ansehen"},
  es:{edit:"Editar acceso",cancel:"Cancelar",firstName:"Nombre",lastName:"Apellidos",password:"Contraseña",expires:"Caduca",confirmRemove:"¿Eliminar a este miembro y revocar su acceso ahora?",confirmSuspend:"¿Suspender a este miembro y revocar sus sesiones actuales?",createStore:"Crear otra tienda",createStoreHelp:"Tu suscripción PRO cubre este negocio. Cada tienda mantiene separados sus productos, pedidos y asignaciones.",allStores:"Todas las tiendas",selectStoreHelp:"Selecciona una tienda para gestionar productos, pedidos y ajustes.",invitationSubject:"Invitación a un equipo de Todijo",invitationHeading:"Únete a un equipo vendedor de Todijo",invitationBody:"Un propietario de Todijo te invitó a gestionar tiendas seleccionadas de forma segura. El enlace privado caduca en 7 días.",invitationCta:"Ver invitación"},
  it:{edit:"Modifica accesso",cancel:"Annulla",firstName:"Nome",lastName:"Cognome",password:"Password",expires:"Scade",confirmRemove:"Rimuovere il membro e revocare subito l’accesso?",confirmSuspend:"Sospendere il membro e revocare le sessioni attuali?",createStore:"Crea un altro negozio",createStoreHelp:"L’abbonamento PRO copre questa attività. Prodotti, ordini e assegnazioni restano separati per negozio.",allStores:"Tutti i negozi",selectStoreHelp:"Seleziona un negozio per gestire prodotti, ordini e impostazioni.",invitationSubject:"Invito a un team Todijo",invitationHeading:"Unisciti a un team venditore Todijo",invitationBody:"Un titolare Todijo ti ha invitato a gestire in sicurezza negozi selezionati. Il link privato scade tra 7 giorni.",invitationCta:"Vedi invito"},
  nl:{edit:"Toegang bewerken",cancel:"Annuleren",firstName:"Voornaam",lastName:"Achternaam",password:"Wachtwoord",expires:"Verloopt",confirmRemove:"Dit lid verwijderen en de toegang direct intrekken?",confirmSuspend:"Dit lid schorsen en huidige sessies intrekken?",createStore:"Nog een winkel maken",createStoreHelp:"Uw PRO-abonnement geldt voor dit bedrijf. Producten, bestellingen en teamtoewijzingen blijven per winkel gescheiden.",allStores:"Alle winkels",selectStoreHelp:"Selecteer een winkel om producten, bestellingen en instellingen te beheren.",invitationSubject:"Uitnodiging voor een Todijo-team",invitationHeading:"Word lid van een Todijo-verkoopteam",invitationBody:"Een Todijo-eigenaar nodigt u uit om geselecteerde winkels veilig te beheren. De privékoppeling verloopt over 7 dagen.",invitationCta:"Uitnodiging bekijken"},
  pt:{edit:"Editar acesso",cancel:"Cancelar",firstName:"Nome",lastName:"Apelido",password:"Palavra-passe",expires:"Expira",confirmRemove:"Remover este membro e revogar já o acesso?",confirmSuspend:"Suspender este membro e revogar as sessões atuais?",createStore:"Criar outra loja",createStoreHelp:"A subscrição PRO cobre esta empresa. Produtos, encomendas e atribuições ficam separados por loja.",allStores:"Todas as lojas",selectStoreHelp:"Selecione uma loja para gerir produtos, encomendas e definições.",invitationSubject:"Convite para uma equipa Todijo",invitationHeading:"Junte-se a uma equipa de vendedores Todijo",invitationBody:"Um proprietário Todijo convidou-o a gerir lojas selecionadas com segurança. A ligação privada expira em 7 dias.",invitationCta:"Ver convite"},
  tr:{edit:"Erişimi düzenle",cancel:"İptal",firstName:"Ad",lastName:"Soyad",password:"Parola",expires:"Son kullanma",confirmRemove:"Bu üye kaldırılsın ve erişimi hemen iptal edilsin mi?",confirmSuspend:"Bu üye askıya alınıp mevcut oturumları iptal edilsin mi?",createStore:"Başka mağaza oluştur",createStoreHelp:"PRO aboneliğiniz bu işletmeyi kapsar. Ürünler, siparişler ve ekip atamaları mağazalara göre ayrı tutulur.",allStores:"Tüm mağazalar",selectStoreHelp:"Ürünleri, siparişleri ve ayarları yönetmek için bir mağaza seçin.",invitationSubject:"Todijo ekibine davet",invitationHeading:"Todijo satıcı ekibine katılın",invitationBody:"Bir Todijo işletme sahibi sizi seçili mağazaları güvenle yönetmeye davet etti. Özel bağlantı 7 gün içinde sona erer.",invitationCta:"Daveti görüntüle"},
  ru:{edit:"Изменить доступ",cancel:"Отмена",firstName:"Имя",lastName:"Фамилия",password:"Пароль",expires:"Истекает",confirmRemove:"Удалить участника и немедленно отозвать доступ?",confirmSuspend:"Приостановить участника и отозвать текущие сеансы?",createStore:"Создать ещё один магазин",createStoreHelp:"Подписка PRO действует на весь бизнес. Товары, заказы и назначения команды разделены по магазинам.",allStores:"Все магазины",selectStoreHelp:"Выберите магазин для управления товарами, заказами и настройками.",invitationSubject:"Приглашение в команду Todijo",invitationHeading:"Присоединиться к команде продавца Todijo",invitationBody:"Владелец бизнеса Todijo приглашает вас безопасно управлять выбранными магазинами. Ссылка истекает через 7 дней.",invitationCta:"Открыть приглашение"},
  ar:{edit:"تعديل الوصول",cancel:"إلغاء",firstName:"الاسم الأول",lastName:"اسم العائلة",password:"كلمة المرور",expires:"تنتهي",confirmRemove:"إزالة هذا العضو وإلغاء وصوله فورًا؟",confirmSuspend:"إيقاف هذا العضو وإلغاء جلساته الحالية؟",createStore:"إنشاء متجر آخر",createStoreHelp:"يغطي اشتراك PRO هذا النشاط. تبقى المنتجات والطلبات وتعيينات الفريق منفصلة لكل متجر.",allStores:"كل المتاجر",selectStoreHelp:"اختر متجرًا لإدارة منتجاته وطلباته وإعداداته.",invitationSubject:"دعوة إلى فريق Todijo",invitationHeading:"انضم إلى فريق بائع Todijo",invitationBody:"دعاك مالك نشاط Todijo لإدارة متاجر محددة بأمان. تنتهي صلاحية الرابط الخاص خلال 7 أيام.",invitationCta:"عرض الدعوة"},
  fa:{edit:"ویرایش دسترسی",cancel:"لغو",firstName:"نام",lastName:"نام خانوادگی",password:"گذرواژه",expires:"انقضا",confirmRemove:"این عضو حذف و دسترسی او فوراً لغو شود؟",confirmSuspend:"این عضو تعلیق و نشست‌های فعلی او لغو شود؟",createStore:"ایجاد فروشگاه دیگر",createStoreHelp:"اشتراک PRO این کسب‌وکار را پوشش می‌دهد. محصولات، سفارش‌ها و تخصیص‌های تیم برای هر فروشگاه جدا می‌مانند.",allStores:"همه فروشگاه‌ها",selectStoreHelp:"برای مدیریت محصولات، سفارش‌ها و تنظیمات یک فروشگاه را انتخاب کنید.",invitationSubject:"دعوت به تیم Todijo",invitationHeading:"به تیم فروشنده Todijo بپیوندید",invitationBody:"مالک یک کسب‌وکار Todijo شما را برای مدیریت امن فروشگاه‌های منتخب دعوت کرده است. پیوند خصوصی ۷ روز اعتبار دارد.",invitationCta:"مشاهده دعوت"},
  hi:{edit:"एक्सेस संपादित करें",cancel:"रद्द करें",firstName:"पहला नाम",lastName:"उपनाम",password:"पासवर्ड",expires:"समाप्ति",confirmRemove:"इस सदस्य को हटाकर एक्सेस तुरंत रद्द करें?",confirmSuspend:"इस सदस्य को निलंबित कर मौजूदा सत्र रद्द करें?",createStore:"एक और स्टोर बनाएँ",createStoreHelp:"आपकी PRO सदस्यता इस व्यवसाय को कवर करती है। हर स्टोर के उत्पाद, ऑर्डर और टीम असाइनमेंट अलग रहते हैं।",allStores:"सभी स्टोर",selectStoreHelp:"उत्पाद, ऑर्डर और सेटिंग प्रबंधित करने के लिए स्टोर चुनें।",invitationSubject:"Todijo टीम का निमंत्रण",invitationHeading:"Todijo विक्रेता टीम से जुड़ें",invitationBody:"Todijo व्यवसाय स्वामी ने आपको चुने गए स्टोर सुरक्षित रूप से प्रबंधित करने के लिए आमंत्रित किया है। निजी लिंक 7 दिनों में समाप्त होगा।",invitationCta:"निमंत्रण देखें"},
  zh:{edit:"编辑访问权限",cancel:"取消",firstName:"名字",lastName:"姓氏",password:"密码",expires:"到期",confirmRemove:"移除此成员并立即撤销访问权限？",confirmSuspend:"暂停此成员并撤销当前会话？",createStore:"创建另一家店铺",createStoreHelp:"您的 PRO 订阅覆盖此企业。每家店铺的商品、订单和团队分配相互独立。",allStores:"全部店铺",selectStoreHelp:"选择一家店铺以管理商品、订单和设置。",invitationSubject:"Todijo 团队邀请",invitationHeading:"加入 Todijo 卖家团队",invitationBody:"Todijo 企业所有者邀请您安全管理指定店铺。私人链接将在 7 天后失效。",invitationCta:"查看邀请"},
  ku:{edit:"دەستکاری دەسەڵات",cancel:"هەڵوەشاندنەوە",firstName:"ناوی یەکەم",lastName:"ناوی خێزان",password:"وشەی نهێنی",expires:"بەسەرچوون",confirmRemove:"ئەم ئەندامە لاببرێت و دەسەڵاتەکەی دەستبەجێ هەڵبوەشێتەوە؟",confirmSuspend:"ئەم ئەندامە ڕابگیرێت و دانیشتنەکانی ئێستا هەڵبوەشێنەوە؟",createStore:"دروستکردنی فرۆشگایەکی تر",createStoreHelp:"بەشداری PRO ئەم بازرگانییە دەگرێتەوە. بەرهەم و داواکاری و دیاریکردنی تیم بۆ هەر فرۆشگایەک جیا دەمێننەوە.",allStores:"هەموو فرۆشگاکان",selectStoreHelp:"فرۆشگایەک هەڵبژێرە بۆ بەڕێوەبردنی بەرهەم و داواکاری و ڕێکخستنەکانی.",invitationSubject:"بانگهێشت بۆ تیمی Todijo",invitationHeading:"بە تیمی فرۆشیاری Todijo پەیوەست بە",invitationBody:"خاوەن بازرگانییەکی Todijo بانگهێشتی کردوویت بۆ بەڕێوەبردنی پارێزراوی فرۆشگا هەڵبژێردراوەکان. لینکە تایبەتەکە لە ٧ ڕۆژدا بەسەر دەچێت.",invitationCta:"بینینی بانگهێشت"},
};

export function sellerTeamCopy(locale: string) { const resolved=isLocale(locale)?locale:defaultLocale;return {...translations[resolved],...workflowCopy[resolved],...auditCopy[resolved]}; }
