import type { Locale } from "./config";

type Copy = {
  adminUnlimitedUsage: (count: number) => string;
  dashboard: string; title: string; intro: string; currentStatus: string; cancels: string; adminAccess: string;
  perMonth: string; upTo: (limit: number) => string; unlimited: string; sellerDashboard: string; ordersRevenue: string;
  opening: string; active: string; anotherActive: string; subscribe: string; unavailable: string; checkoutError: string;
};

export const sellerEntitlementSubscriptionMessages: Record<Locale, Copy> = {
  en:{adminUnlimitedUsage:c=>`${c} products · Admin — unlimited`,dashboard:"Dashboard",title:"Seller subscription",intro:"Choose a monthly plan to publish products. Stripe securely manages billing.",currentStatus:"Current status:",cancels:"Cancels at period end",adminAccess:"Administrator access: unlimited product quota (separate from billing)",perMonth:"/ month",upTo:l=>`Up to ${l} products`,unlimited:"Unlimited products",sellerDashboard:"Seller dashboard",ordersRevenue:"Orders and revenue",opening:"Opening Stripe…",active:"Subscription active",anotherActive:"Another plan is active",subscribe:"Subscribe",unavailable:"Unavailable",checkoutError:"Unable to start checkout."},
  fr:{adminUnlimitedUsage:c=>`${c} produits · Admin — illimité`,dashboard:"Tableau de bord",title:"Abonnement vendeur",intro:"Choisissez un forfait mensuel pour publier des produits. Stripe gère la facturation en toute sécurité.",currentStatus:"Statut actuel :",cancels:"Résiliation à la fin de la période",adminAccess:"Accès administrateur : quota de produits illimité (indépendant de l’abonnement)",perMonth:"/ mois",upTo:l=>`Jusqu’à ${l} produits`,unlimited:"Produits illimités",sellerDashboard:"Tableau de bord vendeur",ordersRevenue:"Commandes et revenus",opening:"Ouverture de Stripe…",active:"Abonnement actif",anotherActive:"Un autre forfait est actif",subscribe:"S’abonner",unavailable:"Indisponible",checkoutError:"Impossible de démarrer le paiement."},
  ar:{adminUnlimitedUsage:c=>`${c} منتج · مسؤول — غير محدود`,dashboard:"لوحة التحكم",title:"اشتراك البائع",intro:"اختر خطة شهرية لنشر المنتجات. يدير Stripe الفوترة بأمان.",currentStatus:"الحالة الحالية:",cancels:"يُلغى في نهاية الفترة",adminAccess:"صلاحية المسؤول: عدد غير محدود من المنتجات (منفصل عن الاشتراك)",perMonth:"/ شهر",upTo:l=>`حتى ${l} منتجًا`,unlimited:"منتجات غير محدودة",sellerDashboard:"لوحة تحكم البائع",ordersRevenue:"الطلبات والإيرادات",opening:"جارٍ فتح Stripe…",active:"الاشتراك نشط",anotherActive:"هناك خطة أخرى نشطة",subscribe:"اشترك",unavailable:"غير متاح",checkoutError:"تعذر بدء عملية الدفع."},
  ku:{adminUnlimitedUsage:c=>`${c} بەرهەم · بەڕێوەبەر — بێ سنوور`,dashboard:"داشبۆرد",title:"بەشداری فرۆشیار",intro:"پلانێکی مانگانە هەڵبژێرە بۆ بڵاوکردنەوەی بەرهەمەکان. Stripe پارەدان بە پارێزراوی بەڕێوە دەبات.",currentStatus:"دۆخی ئێستا:",cancels:"لە کۆتایی ماوەکەدا هەڵدەوەشێتەوە",adminAccess:"دەسەڵاتی بەڕێوەبەر: ژمارەی بەرهەم بێ سنوورە (جیاوازە لە بەشداری)",perMonth:"/ مانگ",upTo:l=>`تا ${l} بەرهەم`,unlimited:"بەرهەمی بێ سنوور",sellerDashboard:"داشبۆردی فرۆشیار",ordersRevenue:"داواکاری و داهات",opening:"Stripe دەکرێتەوە…",active:"بەشداری چالاکە",anotherActive:"پلانێکی تر چالاکە",subscribe:"بەشداربە",unavailable:"بەردەست نییە",checkoutError:"دەستپێکردنی پارەدان سەرکەوتوو نەبوو."},
  tr:{adminUnlimitedUsage:c=>`${c} ürün · Yönetici — sınırsız`,dashboard:"Kontrol paneli",title:"Satıcı aboneliği",intro:"Ürün yayınlamak için aylık bir plan seçin. Ödemeler Stripe tarafından güvenle yönetilir.",currentStatus:"Mevcut durum:",cancels:"Dönem sonunda iptal edilir",adminAccess:"Yönetici erişimi: sınırsız ürün kotası (abonelikten bağımsız)",perMonth:"/ ay",upTo:l=>`${l} ürüne kadar`,unlimited:"Sınırsız ürün",sellerDashboard:"Satıcı paneli",ordersRevenue:"Siparişler ve gelir",opening:"Stripe açılıyor…",active:"Abonelik aktif",anotherActive:"Başka bir plan aktif",subscribe:"Abone ol",unavailable:"Kullanılamıyor",checkoutError:"Ödeme başlatılamadı."},
  de:{adminUnlimitedUsage:c=>`${c} Produkte · Admin — unbegrenzt`,dashboard:"Dashboard",title:"Verkäufer-Abonnement",intro:"Wählen Sie einen Monatsplan, um Produkte zu veröffentlichen. Stripe verwaltet die Abrechnung sicher.",currentStatus:"Aktueller Status:",cancels:"Kündigung zum Periodenende",adminAccess:"Administratorzugriff: unbegrenztes Produktkontingent (unabhängig vom Abonnement)",perMonth:"/ Monat",upTo:l=>`Bis zu ${l} Produkte`,unlimited:"Unbegrenzte Produkte",sellerDashboard:"Verkäufer-Dashboard",ordersRevenue:"Bestellungen und Umsatz",opening:"Stripe wird geöffnet…",active:"Abonnement aktiv",anotherActive:"Ein anderer Plan ist aktiv",subscribe:"Abonnieren",unavailable:"Nicht verfügbar",checkoutError:"Der Bezahlvorgang konnte nicht gestartet werden."},
  es:{adminUnlimitedUsage:c=>`${c} productos · Administrador — ilimitado`,dashboard:"Panel",title:"Suscripción de vendedor",intro:"Elige un plan mensual para publicar productos. Stripe gestiona la facturación de forma segura.",currentStatus:"Estado actual:",cancels:"Se cancela al final del período",adminAccess:"Acceso de administrador: límite de productos ilimitado (independiente de la suscripción)",perMonth:"/ mes",upTo:l=>`Hasta ${l} productos`,unlimited:"Productos ilimitados",sellerDashboard:"Panel del vendedor",ordersRevenue:"Pedidos e ingresos",opening:"Abriendo Stripe…",active:"Suscripción activa",anotherActive:"Hay otro plan activo",subscribe:"Suscribirse",unavailable:"No disponible",checkoutError:"No se pudo iniciar el pago."},
  it:{adminUnlimitedUsage:c=>`${c} prodotti · Amministratore — illimitato`,dashboard:"Dashboard",title:"Abbonamento venditore",intro:"Scegli un piano mensile per pubblicare prodotti. Stripe gestisce la fatturazione in modo sicuro.",currentStatus:"Stato attuale:",cancels:"Annullamento al termine del periodo",adminAccess:"Accesso amministratore: limite prodotti illimitato (separato dall’abbonamento)",perMonth:"/ mese",upTo:l=>`Fino a ${l} prodotti`,unlimited:"Prodotti illimitati",sellerDashboard:"Dashboard venditore",ordersRevenue:"Ordini e ricavi",opening:"Apertura di Stripe…",active:"Abbonamento attivo",anotherActive:"È attivo un altro piano",subscribe:"Abbonati",unavailable:"Non disponibile",checkoutError:"Impossibile avviare il pagamento."},
  nl:{adminUnlimitedUsage:c=>`${c} producten · Beheerder — onbeperkt`,dashboard:"Dashboard",title:"Verkopersabonnement",intro:"Kies een maandabonnement om producten te publiceren. Stripe beheert de facturering veilig.",currentStatus:"Huidige status:",cancels:"Wordt aan het einde van de periode opgezegd",adminAccess:"Beheerderstoegang: onbeperkt productquotum (los van het abonnement)",perMonth:"/ maand",upTo:l=>`Tot ${l} producten`,unlimited:"Onbeperkt aantal producten",sellerDashboard:"Verkopersdashboard",ordersRevenue:"Bestellingen en omzet",opening:"Stripe openen…",active:"Abonnement actief",anotherActive:"Er is een ander abonnement actief",subscribe:"Abonneren",unavailable:"Niet beschikbaar",checkoutError:"Betaling kon niet worden gestart."},
  zh:{adminUnlimitedUsage:c=>`${c} 个商品 · 管理员 — 不限数量`,dashboard:"控制面板",title:"卖家订阅",intro:"选择月度方案以发布商品。Stripe 将安全管理账单。",currentStatus:"当前状态：",cancels:"将在周期结束时取消",adminAccess:"管理员权限：商品数量不限（独立于订阅）",perMonth:"/ 月",upTo:l=>`最多 ${l} 个商品`,unlimited:"商品数量不限",sellerDashboard:"卖家控制面板",ordersRevenue:"订单和收入",opening:"正在打开 Stripe…",active:"订阅有效",anotherActive:"另一个方案已生效",subscribe:"订阅",unavailable:"不可用",checkoutError:"无法开始付款。"},
  fa:{adminUnlimitedUsage:c=>`${c} محصول · مدیر — نامحدود`,dashboard:"داشبورد",title:"اشتراک فروشنده",intro:"برای انتشار محصولات یک طرح ماهانه انتخاب کنید. Stripe صورتحساب را به‌صورت امن مدیریت می‌کند.",currentStatus:"وضعیت فعلی:",cancels:"در پایان دوره لغو می‌شود",adminAccess:"دسترسی مدیر: سهمیه نامحدود محصول (مستقل از اشتراک)",perMonth:"/ ماه",upTo:l=>`تا ${l} محصول`,unlimited:"محصولات نامحدود",sellerDashboard:"داشبورد فروشنده",ordersRevenue:"سفارش‌ها و درآمد",opening:"در حال باز کردن Stripe…",active:"اشتراک فعال",anotherActive:"طرح دیگری فعال است",subscribe:"اشتراک",unavailable:"در دسترس نیست",checkoutError:"شروع پرداخت ممکن نشد."},
  hi:{adminUnlimitedUsage:c=>`${c} उत्पाद · एडमिन — असीमित`,dashboard:"डैशबोर्ड",title:"विक्रेता सदस्यता",intro:"उत्पाद प्रकाशित करने के लिए मासिक योजना चुनें। Stripe बिलिंग को सुरक्षित रूप से प्रबंधित करता है।",currentStatus:"वर्तमान स्थिति:",cancels:"अवधि के अंत में रद्द होगा",adminAccess:"एडमिन पहुँच: असीमित उत्पाद कोटा (सदस्यता से अलग)",perMonth:"/ माह",upTo:l=>`${l} उत्पादों तक`,unlimited:"असीमित उत्पाद",sellerDashboard:"विक्रेता डैशबोर्ड",ordersRevenue:"ऑर्डर और आय",opening:"Stripe खुल रहा है…",active:"सदस्यता सक्रिय",anotherActive:"दूसरी योजना सक्रिय है",subscribe:"सदस्यता लें",unavailable:"उपलब्ध नहीं",checkoutError:"भुगतान शुरू नहीं हो सका।"},
  pt:{adminUnlimitedUsage:c=>`${c} produtos · Admin — ilimitado`,dashboard:"Painel",title:"Assinatura do vendedor",intro:"Escolha um plano mensal para publicar produtos. A Stripe gere a faturação com segurança.",currentStatus:"Estado atual:",cancels:"Cancela no fim do período",adminAccess:"Acesso de administrador: limite de produtos ilimitado (separado da assinatura)",perMonth:"/ mês",upTo:l=>`Até ${l} produtos`,unlimited:"Produtos ilimitados",sellerDashboard:"Painel do vendedor",ordersRevenue:"Encomendas e receitas",opening:"A abrir a Stripe…",active:"Assinatura ativa",anotherActive:"Outro plano está ativo",subscribe:"Assinar",unavailable:"Indisponível",checkoutError:"Não foi possível iniciar o pagamento."},
  ru:{adminUnlimitedUsage:c=>`${c} товаров · Администратор — без ограничений`,dashboard:"Панель управления",title:"Подписка продавца",intro:"Выберите ежемесячный план для публикации товаров. Stripe безопасно управляет оплатой.",currentStatus:"Текущий статус:",cancels:"Отмена в конце периода",adminAccess:"Доступ администратора: неограниченное число товаров (отдельно от подписки)",perMonth:"/ месяц",upTo:l=>`До ${l} товаров`,unlimited:"Неограниченное число товаров",sellerDashboard:"Панель продавца",ordersRevenue:"Заказы и выручка",opening:"Открываем Stripe…",active:"Подписка активна",anotherActive:"Активен другой план",subscribe:"Подписаться",unavailable:"Недоступно",checkoutError:"Не удалось начать оплату."},
};
