const en={country:"Country",chooseCountry:"Choose a country",available:"Shipping available.",postalRuleCountry:"Country",postalAllCountries:"All selected countries",postalRuleType:"Rule type",postalPrefix:"Postal prefix",postalExact:"Exact postal code",postalValue:"Value",postalRemove:"Remove postal rule",postalEmpty:"No postal restrictions. Country-level shipping applies.",postalAdd:"Add postal rule",postalRuleHelp:"Choose Prefix for a department or area such as 59. Buyers enter their normal postal code."};
export const shippingHotfixMessages:Record<string,typeof en>={
en,
fr:{country:"Pays",chooseCountry:"Choisissez un pays",available:"Livraison disponible.",postalRuleCountry:"Pays",postalAllCountries:"Tous les pays sélectionnés",postalRuleType:"Type de règle",postalPrefix:"Préfixe postal",postalExact:"Code postal exact",postalValue:"Valeur",postalRemove:"Supprimer la règle postale",postalEmpty:"Aucune restriction postale. La livraison par pays s’applique.",postalAdd:"Ajouter une règle postale",postalRuleHelp:"Choisissez Préfixe pour un département ou une zone comme 59. L’acheteur saisit son code postal normal."},
de:{country:"Land",chooseCountry:"Land auswählen",available:"Versand verfügbar.",postalRuleCountry:"Land",postalAllCountries:"Alle ausgewählten Länder",postalRuleType:"Regeltyp",postalPrefix:"Postleitzahlpräfix",postalExact:"Genaue Postleitzahl",postalValue:"Wert",postalRemove:"Postregel entfernen",postalEmpty:"Keine Postleitzahlbeschränkung. Der Versand nach Land gilt.",postalAdd:"Postregel hinzufügen",postalRuleHelp:"Wählen Sie Präfix für ein Gebiet wie 59. Käufer geben ihre normale Postleitzahl ein."},
es:{country:"País",chooseCountry:"Elige un país",available:"Envío disponible.",postalRuleCountry:"País",postalAllCountries:"Todos los países seleccionados",postalRuleType:"Tipo de regla",postalPrefix:"Prefijo postal",postalExact:"Código postal exacto",postalValue:"Valor",postalRemove:"Eliminar regla postal",postalEmpty:"Sin restricciones postales. Se aplica el envío por país.",postalAdd:"Añadir regla postal",postalRuleHelp:"Elige Prefijo para una zona como 59. El comprador introduce su código postal normal."},
it:{country:"Paese",chooseCountry:"Scegli un paese",available:"Spedizione disponibile.",postalRuleCountry:"Paese",postalAllCountries:"Tutti i paesi selezionati",postalRuleType:"Tipo di regola",postalPrefix:"Prefisso postale",postalExact:"Codice postale esatto",postalValue:"Valore",postalRemove:"Rimuovi regola postale",postalEmpty:"Nessuna restrizione postale. Si applica la spedizione per paese.",postalAdd:"Aggiungi regola postale",postalRuleHelp:"Scegli Prefisso per una zona come 59. L’acquirente inserisce il normale codice postale."},
nl:{country:"Land",chooseCountry:"Kies een land",available:"Verzending beschikbaar.",postalRuleCountry:"Land",postalAllCountries:"Alle geselecteerde landen",postalRuleType:"Regeltype",postalPrefix:"Postcodeprefix",postalExact:"Exacte postcode",postalValue:"Waarde",postalRemove:"Postcoderegel verwijderen",postalEmpty:"Geen postcodebeperkingen. Verzending per land geldt.",postalAdd:"Postcoderegel toevoegen",postalRuleHelp:"Kies Prefix voor een gebied zoals 59. De koper voert de normale postcode in."},
pt:{country:"País",chooseCountry:"Escolha um país",available:"Envio disponível.",postalRuleCountry:"País",postalAllCountries:"Todos os países selecionados",postalRuleType:"Tipo de regra",postalPrefix:"Prefixo postal",postalExact:"Código postal exato",postalValue:"Valor",postalRemove:"Remover regra postal",postalEmpty:"Sem restrições postais. Aplica-se o envio por país.",postalAdd:"Adicionar regra postal",postalRuleHelp:"Escolha Prefixo para uma zona como 59. O comprador introduz o código postal normal."},
tr:{country:"Ülke",chooseCountry:"Ülke seçin",available:"Kargo mevcut.",postalRuleCountry:"Ülke",postalAllCountries:"Seçili tüm ülkeler",postalRuleType:"Kural türü",postalPrefix:"Posta kodu öneki",postalExact:"Tam posta kodu",postalValue:"Değer",postalRemove:"Posta kuralını kaldır",postalEmpty:"Posta kodu kısıtlaması yok. Ülke düzeyinde kargo uygulanır.",postalAdd:"Posta kuralı ekle",postalRuleHelp:"59 gibi bir bölge için Önek seçin. Alıcı normal posta kodunu girer."},
ru:{country:"Страна",chooseCountry:"Выберите страну",available:"Доставка доступна.",postalRuleCountry:"Страна",postalAllCountries:"Все выбранные страны",postalRuleType:"Тип правила",postalPrefix:"Префикс индекса",postalExact:"Точный почтовый индекс",postalValue:"Значение",postalRemove:"Удалить почтовое правило",postalEmpty:"Почтовых ограничений нет. Действует доставка по стране.",postalAdd:"Добавить почтовое правило",postalRuleHelp:"Выберите Префикс для региона, например 59. Покупатель вводит обычный индекс."},
ar:{country:"البلد",chooseCountry:"اختر بلدًا",available:"الشحن متاح.",postalRuleCountry:"البلد",postalAllCountries:"جميع البلدان المحددة",postalRuleType:"نوع القاعدة",postalPrefix:"بادئة الرمز البريدي",postalExact:"الرمز البريدي الدقيق",postalValue:"القيمة",postalRemove:"إزالة القاعدة البريدية",postalEmpty:"لا توجد قيود بريدية. ينطبق الشحن حسب البلد.",postalAdd:"إضافة قاعدة بريدية",postalRuleHelp:"اختر البادئة لمنطقة مثل 59. يُدخل المشتري رمزه البريدي المعتاد."},
fa:{country:"کشور",chooseCountry:"یک کشور انتخاب کنید",available:"ارسال ممکن است.",postalRuleCountry:"کشور",postalAllCountries:"همه کشورهای انتخاب‌شده",postalRuleType:"نوع قانون",postalPrefix:"پیشوند کد پستی",postalExact:"کد پستی دقیق",postalValue:"مقدار",postalRemove:"حذف قانون پستی",postalEmpty:"محدودیت پستی وجود ندارد. ارسال در سطح کشور اعمال می‌شود.",postalAdd:"افزودن قانون پستی",postalRuleHelp:"برای منطقه‌ای مانند 59 پیشوند را انتخاب کنید. خریدار کد پستی عادی را وارد می‌کند."},
hi:{country:"देश",chooseCountry:"देश चुनें",available:"शिपिंग उपलब्ध है।",postalRuleCountry:"देश",postalAllCountries:"सभी चुने हुए देश",postalRuleType:"नियम का प्रकार",postalPrefix:"पिन कोड उपसर्ग",postalExact:"सटीक पिन कोड",postalValue:"मान",postalRemove:"पिन कोड नियम हटाएँ",postalEmpty:"कोई पिन कोड प्रतिबंध नहीं। देश-स्तरीय शिपिंग लागू है।",postalAdd:"पिन कोड नियम जोड़ें",postalRuleHelp:"59 जैसे क्षेत्र के लिए उपसर्ग चुनें। खरीदार अपना सामान्य पिन कोड दर्ज करता है।"},
ku:{country:"وڵات",chooseCountry:"وڵاتێک هەڵبژێرە",available:"گەیاندن بەردەستە.",postalRuleCountry:"وڵات",postalAllCountries:"هەموو وڵاتە هەڵبژێردراوەکان",postalRuleType:"جۆری یاسا",postalPrefix:"پێشگری کۆدی پۆستە",postalExact:"کۆدی پۆستەی تەواو",postalValue:"بەها",postalRemove:"لابردنی یاسای پۆستە",postalEmpty:"هیچ سنووردارییەکی پۆستە نییە. گەیاندنی ئاستی وڵات کاردەکات.",postalAdd:"زیادکردنی یاسای پۆستە",postalRuleHelp:"بۆ ناوچەیەک وەک 59 پێشگر هەڵبژێرە. کڕیار کۆدی پۆستەی ئاسایی دەنووسێت."},
zh:{country:"国家或地区",chooseCountry:"选择国家或地区",available:"可以配送。",postalRuleCountry:"国家或地区",postalAllCountries:"所有已选国家或地区",postalRuleType:"规则类型",postalPrefix:"邮政编码前缀",postalExact:"完整邮政编码",postalValue:"值",postalRemove:"删除邮政规则",postalEmpty:"没有邮政编码限制，按国家或地区配送。",postalAdd:"添加邮政规则",postalRuleHelp:"对于 59 之类的区域请选择前缀。买家输入正常邮政编码。"}
};
