const en={title:"CJ Dropshipping",help:"Import a selected CJ product as a private draft for review. Supplier costs are never shown to buyers.",productId:"CJ product ID",sellingPrice:"Todijo selling price",category:"Todijo category",importAction:"Import as draft",working:"Working…",imported:"Product imported as a draft.",sync:"Refresh supplier data",supplierCost:"Supplier cost",supplierStock:"Supplier stock",lastSynced:"Last synchronized",notConfigured:"CJ is not configured.",status:"Supplier status"};
export const supplierMessages:Record<string,typeof en>={
en,
fr:{title:"CJ Dropshipping",help:"Importez un produit CJ sélectionné comme brouillon privé à vérifier. Le coût fournisseur n’est jamais montré aux acheteurs.",productId:"Identifiant produit CJ",sellingPrice:"Prix de vente Todijo",category:"Catégorie Todijo",importAction:"Importer comme brouillon",working:"Traitement…",imported:"Produit importé comme brouillon.",sync:"Actualiser les données fournisseur",supplierCost:"Coût fournisseur",supplierStock:"Stock fournisseur",lastSynced:"Dernière synchronisation",notConfigured:"CJ n’est pas configuré.",status:"État fournisseur"},
de:{title:"CJ Dropshipping",help:"Ausgewähltes CJ-Produkt als privaten Entwurf zur Prüfung importieren. Lieferantenkosten sind für Käufer nie sichtbar.",productId:"CJ-Produkt-ID",sellingPrice:"Todijo-Verkaufspreis",category:"Todijo-Kategorie",importAction:"Als Entwurf importieren",working:"Wird verarbeitet…",imported:"Produkt als Entwurf importiert.",sync:"Lieferantendaten aktualisieren",supplierCost:"Lieferantenkosten",supplierStock:"Lieferantenbestand",lastSynced:"Zuletzt synchronisiert",notConfigured:"CJ ist nicht konfiguriert.",status:"Lieferantenstatus"},
es:{title:"CJ Dropshipping",help:"Importa un producto CJ seleccionado como borrador privado para revisarlo. El coste del proveedor nunca se muestra a compradores.",productId:"ID de producto CJ",sellingPrice:"Precio de venta Todijo",category:"Categoría Todijo",importAction:"Importar como borrador",working:"Procesando…",imported:"Producto importado como borrador.",sync:"Actualizar datos del proveedor",supplierCost:"Coste del proveedor",supplierStock:"Stock del proveedor",lastSynced:"Última sincronización",notConfigured:"CJ no está configurado.",status:"Estado del proveedor"},
it:{title:"CJ Dropshipping",help:"Importa un prodotto CJ selezionato come bozza privata da verificare. Il costo fornitore non viene mai mostrato agli acquirenti.",productId:"ID prodotto CJ",sellingPrice:"Prezzo di vendita Todijo",category:"Categoria Todijo",importAction:"Importa come bozza",working:"Elaborazione…",imported:"Prodotto importato come bozza.",sync:"Aggiorna dati fornitore",supplierCost:"Costo fornitore",supplierStock:"Scorte fornitore",lastSynced:"Ultima sincronizzazione",notConfigured:"CJ non è configurato.",status:"Stato fornitore"},
nl:{title:"CJ Dropshipping",help:"Importeer een gekozen CJ-product als privéconcept ter controle. Leverancierskosten zijn nooit zichtbaar voor kopers.",productId:"CJ-product-ID",sellingPrice:"Todijo-verkoopprijs",category:"Todijo-categorie",importAction:"Als concept importeren",working:"Bezig…",imported:"Product als concept geïmporteerd.",sync:"Leveranciersgegevens vernieuwen",supplierCost:"Leverancierskosten",supplierStock:"Leveranciersvoorraad",lastSynced:"Laatst gesynchroniseerd",notConfigured:"CJ is niet geconfigureerd.",status:"Leveranciersstatus"},
pt:{title:"CJ Dropshipping",help:"Importe um produto CJ selecionado como rascunho privado para revisão. O custo do fornecedor nunca é mostrado aos compradores.",productId:"ID do produto CJ",sellingPrice:"Preço de venda Todijo",category:"Categoria Todijo",importAction:"Importar como rascunho",working:"A processar…",imported:"Produto importado como rascunho.",sync:"Atualizar dados do fornecedor",supplierCost:"Custo do fornecedor",supplierStock:"Stock do fornecedor",lastSynced:"Última sincronização",notConfigured:"CJ não está configurado.",status:"Estado do fornecedor"},
tr:{title:"CJ Dropshipping",help:"Seçilen CJ ürününü inceleme için özel taslak olarak içe aktarın. Tedarikçi maliyeti alıcılara gösterilmez.",productId:"CJ ürün kimliği",sellingPrice:"Todijo satış fiyatı",category:"Todijo kategorisi",importAction:"Taslak olarak içe aktar",working:"İşleniyor…",imported:"Ürün taslak olarak içe aktarıldı.",sync:"Tedarikçi verisini yenile",supplierCost:"Tedarikçi maliyeti",supplierStock:"Tedarikçi stoğu",lastSynced:"Son eşitleme",notConfigured:"CJ yapılandırılmamış.",status:"Tedarikçi durumu"},
ru:{title:"CJ Dropshipping",help:"Импортируйте выбранный товар CJ как закрытый черновик для проверки. Закупочная цена не видна покупателям.",productId:"ID товара CJ",sellingPrice:"Цена продажи Todijo",category:"Категория Todijo",importAction:"Импортировать в черновик",working:"Обработка…",imported:"Товар импортирован как черновик.",sync:"Обновить данные поставщика",supplierCost:"Стоимость поставщика",supplierStock:"Запас поставщика",lastSynced:"Последняя синхронизация",notConfigured:"CJ не настроен.",status:"Статус поставщика"},
ar:{title:"CJ Dropshipping",help:"استورد منتج CJ محدداً كمسودة خاصة للمراجعة. لا تظهر تكلفة المورد للمشترين أبداً.",productId:"معرّف منتج CJ",sellingPrice:"سعر البيع في Todijo",category:"فئة Todijo",importAction:"استيراد كمسودة",working:"جارٍ التنفيذ…",imported:"تم استيراد المنتج كمسودة.",sync:"تحديث بيانات المورد",supplierCost:"تكلفة المورد",supplierStock:"مخزون المورد",lastSynced:"آخر مزامنة",notConfigured:"لم يتم إعداد CJ.",status:"حالة المورد"},
fa:{title:"CJ Dropshipping",help:"محصول انتخابی CJ را برای بررسی به‌صورت پیش‌نویس خصوصی وارد کنید. هزینه تأمین‌کننده هرگز به خریدار نشان داده نمی‌شود.",productId:"شناسه محصول CJ",sellingPrice:"قیمت فروش Todijo",category:"دسته Todijo",importAction:"ورود به‌صورت پیش‌نویس",working:"در حال انجام…",imported:"محصول به‌صورت پیش‌نویس وارد شد.",sync:"به‌روزرسانی داده تأمین‌کننده",supplierCost:"هزینه تأمین‌کننده",supplierStock:"موجودی تأمین‌کننده",lastSynced:"آخرین همگام‌سازی",notConfigured:"CJ پیکربندی نشده است.",status:"وضعیت تأمین‌کننده"},
hi:{title:"CJ Dropshipping",help:"चुने हुए CJ उत्पाद को समीक्षा के लिए निजी ड्राफ़्ट के रूप में आयात करें। आपूर्तिकर्ता लागत खरीदारों को नहीं दिखाई जाती।",productId:"CJ उत्पाद आईडी",sellingPrice:"Todijo बिक्री मूल्य",category:"Todijo श्रेणी",importAction:"ड्राफ़्ट के रूप में आयात",working:"प्रक्रिया जारी…",imported:"उत्पाद ड्राफ़्ट के रूप में आयात हुआ।",sync:"आपूर्तिकर्ता डेटा रीफ़्रेश करें",supplierCost:"आपूर्तिकर्ता लागत",supplierStock:"आपूर्तिकर्ता स्टॉक",lastSynced:"अंतिम सिंक",notConfigured:"CJ कॉन्फ़िगर नहीं है।",status:"आपूर्तिकर्ता स्थिति"},
ku:{title:"CJ Dropshipping",help:"بەرهەمی هەڵبژێردراوی CJ وەک ڕەشنووسی تایبەت بۆ پشکنین هاوردە بکە. تێچووی دابینکەر نیشانی کڕیار نادرێت.",productId:"ناسنامەی بەرهەمی CJ",sellingPrice:"نرخی فرۆشتنی Todijo",category:"پۆلی Todijo",importAction:"هاوردەکردن وەک ڕەشنووس",working:"لە جێبەجێکردندایە…",imported:"بەرهەم وەک ڕەشنووس هاوردە کرا.",sync:"نوێکردنەوەی زانیاری دابینکەر",supplierCost:"تێچووی دابینکەر",supplierStock:"کۆگای دابینکەر",lastSynced:"دوا هاوکاتکردن",notConfigured:"CJ ڕێکنەخراوە.",status:"دۆخی دابینکەر"},
zh:{title:"CJ Dropshipping",help:"将选定的 CJ 商品作为私密草稿导入以供审核。供应商成本绝不会向买家显示。",productId:"CJ 商品 ID",sellingPrice:"Todijo 销售价",category:"Todijo 分类",importAction:"导入为草稿",working:"处理中…",imported:"商品已导入为草稿。",sync:"刷新供应商数据",supplierCost:"供应商成本",supplierStock:"供应商库存",lastSynced:"上次同步",notConfigured:"CJ 尚未配置。",status:"供应商状态"}
};
