const en={bulkTitle:"CJ catalog import",bulkHelp:"Search CJ or submit up to 500 exact product IDs/SKUs. Work is saved as a resumable job and every imported product remains a private draft.",bulkProductIds:"CJ product IDs / SKUs",bulkPlaceholder:"One exact ID per line, or select products from search",bulkImportAction:"Create import job",bulkSafety:"Products are processed in controlled batches with bounded concurrency to respect CJ limits. Nothing is published automatically; review products before publication.",bulkComplete:"Catalog job updated",bulkImported:"Imported",bulkSkipped:"Already imported",bulkFailed:"Technical failures",syncAll:"Sync stale CJ products",syncComplete:"Sync complete",synced:"synced",catalogSearch:"Search CJ catalog",searchPlaceholder:"Product name, PID, SKU or SPU",searchAction:"Search",selectedCount:"Selected products",destinationCountry:"Pricing destination country",batchLimit:"Items processed per request",resume:"Resume next batch",retryReview:"Retry failed/review items",quarantined:"Requires review",pending:"pending",pricingStatus:"Pricing",stockStatus:"Stock",categoryStatus:"Category",complianceStatus:"Compliance",openDraft:"Edit draft",previewDraft:"Buyer preview",loadMore:"Load more",jobStatus:"Job status",noResults:"No products found",reviewRequired:"Admin review required",classification:"Classification",needsReview:"Needs review / quarantine",bulkStatusGood:"Classification accepted",override:"Override canonical category",quarantine:"Low-confidence quarantine",bulkStatus:"Status",processedCount:"Processed",remainingCount:"Remaining",elapsed:"Elapsed",durationUnavailable:"In progress",resumeBusy:"Batch in progress…",jobStatusPending:"Waiting to start",jobStatusRunning:"Import in progress",jobStatusReady:"Ready for next batch",jobStatusCompleted:"Completed",jobStatusReview:"Completed — review required"};
export const supplierBulkMessages:Record<string,Partial<typeof en>>={
 en,
 fr:{bulkTitle:"Import CJ en lot",bulkHelp:"Recherchez dans CJ ou soumettez jusqu’à 500 identifiants/SKU exacts. Le travail est enregistré comme tâche reprenable et chaque produit importé reste un brouillon privé.",bulkProductIds:"Identifiants / SKU CJ",bulkPlaceholder:"Un identifiant par ligne, ou séparés par des virgules",bulkImportAction:"Importer les brouillons",bulkSafety:"Les produits sont traités par lots avec une concurrence contrôlée afin de respecter les limites de CJ. Aucun produit n’est publié automatiquement : vérifiez-les avant publication.",bulkComplete:"Import en lot mis à jour",bulkImported:"Importés",bulkSkipped:"Déjà importés",bulkFailed:"Échecs techniques",syncAll:"Synchroniser les produits CJ",syncComplete:"Synchronisation terminée",synced:"synchronisés",catalogSearch:"Chercher CJ",searchPlaceholder:"Nom du produit, PID, SKU ou SPU",searchAction:"Rechercher",selectedCount:"Produits sélectionnés",destinationCountry:"Pays de destination des prix",batchLimit:"Articles traités par demande",resume:"Reprendre le lot suivant",retryReview:"Réessayer les articles en révision",quarantined:"À vérifier",pending:"en attente",pricingStatus:"Tarification",stockStatus:"Stock",categoryStatus:"Catégorie",complianceStatus:"Conformité",openDraft:"Modifier brouillon",previewDraft:"Aperçu acheteur",loadMore:"Voir plus",jobStatus:"État de la tâche",noResults:"Aucun produit trouvé",reviewRequired:"Revue admin requise",classification:"Classification",needsReview:"Revue requise / quarantaine",bulkStatusGood:"Classification acceptée",override:"Remplacer la catégorie canonique",quarantine:"Quarantaine faible confiance",bulkStatus:"État",processedCount:"Traités",remainingCount:"Restants",elapsed:"Temps écoulé",durationUnavailable:"En cours",resumeBusy:"Lot en cours…",jobStatusPending:"En attente de démarrage",jobStatusRunning:"Import en cours",jobStatusReady:"Prêt pour le lot suivant",jobStatusCompleted:"Terminé",jobStatusReview:"Terminé — vérification requise"},
 ku:{bulkTitle:"هاوردەکردنی کۆمەڵەیی CJ",bulkHelp:"لە CJ بگەڕێ یان تا 500 ناسنامە/SKU ـی ورد بنێرە. کارەکە وەک ئەرکێکی بەردەوامبوو هەڵدەگیرێت و هەموو بەرهەمێک وەک ڕەشنووسی تایبەت دەمێنێتەوە.",bulkProductIds:"ناسنامە / SKU ـەکانی CJ",bulkPlaceholder:"هەر ناسنامەیەک لە هێڵێک، یان بە کۆما جیا بکەرەوە",bulkImportAction:"هاوردەکردنی draft ـەکان",bulkSafety:"بەرهەمەکان بە کۆمەڵەی کۆنترۆڵکراو پرۆسە دەکرێن بۆ ڕێزگرتن لە سنوورەکانی CJ. هیچ بەرهەمێک خۆکارانە بڵاوناکرێتەوە.",bulkComplete:"هاوردەکردنی کۆمەڵەیی نوێکرایەوە",bulkImported:"هاوردەکراو",bulkSkipped:"پێشتر هاوردەکراو",bulkFailed:"هەڵە تەکنیکییەکان",syncAll:"هاوکاتکردنی کاڵا کۆنەکانی CJ",syncComplete:"هاوکاتکردن تەواو بوو",synced:"هاوکاتکرا",catalogSearch:"بگەڕێ بە CJ",searchPlaceholder:"ناوی کاڵا، PID یا SKU یان SPU",searchAction:"گەڕان",selectedCount:"کاڵە دیاریکراوەکان",destinationCountry:"وڵاتی مەبەستی نرخدان",batchLimit:"ئایتمە بۆ هەربار",resume:"بەردەوامبوون بە کۆمەڵەی داهاتوو",retryReview:"هەوڵەی دووبارەکردنەوەی بابەتەکانی بازدان",quarantined:"پێویستی بە پشکنینە",pending:"چاوەڕێی",pricingStatus:"نرخ",stockStatus:"کۆلۆنی خەزن",categoryStatus:"بەش",complianceStatus:"ڕێکخستن",openDraft:"دەستکاری ئەمڕۆ",previewDraft:"پێشبینی کڕیار",loadMore:"زیاتر بینین",jobStatus:"دۆخی کار",noResults:"هیچ کاڵایەک نەدۆزرایەوە",reviewRequired:"پێویستە پشتڕاست بکەیت",classification:"پێشبینی",needsReview:"پێویستە چارەسەرەیەکی بازدان",bulkStatusGood:"پێشنیاریەکی وەرگرتوو",override:"لەگەل بڕوانەی دەستکرد",quarantine:"قارەنتینی ئامادەی نزم",bulkStatus:"دۆخ"},
};

const jobPolishMessages:Record<string,Pick<typeof en,"bulkSafety"|"processedCount"|"remainingCount"|"elapsed"|"durationUnavailable"|"resumeBusy"|"jobStatusPending"|"jobStatusRunning"|"jobStatusReady"|"jobStatusCompleted"|"jobStatusReview"|"bulkImported"|"bulkSkipped"|"quarantined"|"bulkFailed">>={
  en,
  fr:supplierBulkMessages.fr as typeof en,
  ar:{bulkSafety:"تُعالَج المنتجات على دفعات مضبوطة وبتزامن محدود لاحترام حدود CJ. لا يُنشر أي منتج تلقائيًا؛ راجع المنتجات قبل النشر.",processedCount:"تمت المعالجة",remainingCount:"المتبقي",elapsed:"الوقت المنقضي",durationUnavailable:"قيد التنفيذ",resumeBusy:"الدفعة قيد التنفيذ…",jobStatusPending:"بانتظار البدء",jobStatusRunning:"الاستيراد قيد التنفيذ",jobStatusReady:"جاهز للدفعة التالية",jobStatusCompleted:"مكتمل",jobStatusReview:"مكتمل — يتطلب المراجعة",bulkImported:"تم استيرادها",bulkSkipped:"مستوردة مسبقًا",quarantined:"تتطلب المراجعة",bulkFailed:"أخطاء تقنية"},
  ku:{bulkSafety:"بەرهەمەکان بە کۆمەڵەی کۆنترۆڵکراو پرۆسە دەکرێن بۆ ڕێزگرتن لە سنوورەکانی CJ. هیچ بەرهەمێک خۆکارانە بڵاوناکرێتەوە.",processedCount:"پرۆسەکراو",remainingCount:"ماوە",elapsed:"کاتی تێپەڕیو",durationUnavailable:"لە کاردایە",resumeBusy:"کۆمەڵەکە لە کاردایە…",jobStatusPending:"چاوەڕێی دەستپێکردن",jobStatusRunning:"هاوردەکردن لە کاردایە",jobStatusReady:"ئامادەی کۆمەڵەی داهاتووە",jobStatusCompleted:"تەواوبوو",jobStatusReview:"تەواوبوو — پشکنین پێویستە",bulkImported:"هاوردەکراو",bulkSkipped:"پێشتر هاوردەکراو",quarantined:"پشکنین پێویستە",bulkFailed:"هەڵە تەکنیکییەکان"},
  tr:{bulkSafety:"Ürünler, CJ sınırlarına uymak için kontrollü ve sınırlı eşzamanlı gruplar halinde işlenir. Hiçbir ürün otomatik yayımlanmaz; yayımlamadan önce inceleyin.",processedCount:"İşlenen",remainingCount:"Kalan",elapsed:"Geçen süre",durationUnavailable:"İşlem sürüyor",resumeBusy:"Grup işleniyor…",jobStatusPending:"Başlamayı bekliyor",jobStatusRunning:"İçe aktarma sürüyor",jobStatusReady:"Sonraki grup için hazır",jobStatusCompleted:"Tamamlandı",jobStatusReview:"Tamamlandı — inceleme gerekli",bulkImported:"İçe aktarıldı",bulkSkipped:"Önceden içe aktarıldı",quarantined:"İnceleme gerekli",bulkFailed:"Teknik hata"},
  de:{bulkSafety:"Produkte werden in kontrollierten Stapeln mit begrenzter Parallelität verarbeitet, um die CJ-Limits einzuhalten. Nichts wird automatisch veröffentlicht; prüfen Sie Produkte vor der Veröffentlichung.",processedCount:"Verarbeitet",remainingCount:"Verbleibend",elapsed:"Vergangene Zeit",durationUnavailable:"In Bearbeitung",resumeBusy:"Stapel wird verarbeitet…",jobStatusPending:"Wartet auf Start",jobStatusRunning:"Import läuft",jobStatusReady:"Bereit für den nächsten Stapel",jobStatusCompleted:"Abgeschlossen",jobStatusReview:"Abgeschlossen — Prüfung erforderlich",bulkImported:"Importiert",bulkSkipped:"Bereits importiert",quarantined:"Prüfung erforderlich",bulkFailed:"Technische Fehler"},
  es:{bulkSafety:"Los productos se procesan en lotes controlados con concurrencia limitada para respetar los límites de CJ. Nada se publica automáticamente; revise los productos antes de publicarlos.",processedCount:"Procesados",remainingCount:"Restantes",elapsed:"Tiempo transcurrido",durationUnavailable:"En curso",resumeBusy:"Lote en curso…",jobStatusPending:"Esperando inicio",jobStatusRunning:"Importación en curso",jobStatusReady:"Listo para el siguiente lote",jobStatusCompleted:"Completado",jobStatusReview:"Completado — requiere revisión",bulkImported:"Importados",bulkSkipped:"Ya importados",quarantined:"Requieren revisión",bulkFailed:"Errores técnicos"},
  it:{bulkSafety:"I prodotti vengono elaborati in lotti controllati con concorrenza limitata per rispettare i limiti CJ. Nulla viene pubblicato automaticamente; controlla i prodotti prima della pubblicazione.",processedCount:"Elaborati",remainingCount:"Rimanenti",elapsed:"Tempo trascorso",durationUnavailable:"In corso",resumeBusy:"Lotto in corso…",jobStatusPending:"In attesa di avvio",jobStatusRunning:"Importazione in corso",jobStatusReady:"Pronto per il lotto successivo",jobStatusCompleted:"Completato",jobStatusReview:"Completato — revisione necessaria",bulkImported:"Importati",bulkSkipped:"Già importati",quarantined:"Da revisionare",bulkFailed:"Errori tecnici"},
  nl:{bulkSafety:"Producten worden in gecontroleerde batches met begrensde gelijktijdigheid verwerkt om de CJ-limieten te respecteren. Niets wordt automatisch gepubliceerd; controleer producten vóór publicatie.",processedCount:"Verwerkt",remainingCount:"Resterend",elapsed:"Verstreken tijd",durationUnavailable:"Bezig",resumeBusy:"Batch wordt verwerkt…",jobStatusPending:"Wacht op start",jobStatusRunning:"Import bezig",jobStatusReady:"Klaar voor volgende batch",jobStatusCompleted:"Voltooid",jobStatusReview:"Voltooid — controle vereist",bulkImported:"Geïmporteerd",bulkSkipped:"Al geïmporteerd",quarantined:"Controle vereist",bulkFailed:"Technische fouten"},
  zh:{bulkSafety:"产品以受控批次和有限并发处理，以遵守 CJ 限制。任何产品都不会自动发布；请在发布前审核。",processedCount:"已处理",remainingCount:"剩余",elapsed:"已用时间",durationUnavailable:"进行中",resumeBusy:"批次处理中…",jobStatusPending:"等待开始",jobStatusRunning:"正在导入",jobStatusReady:"可处理下一批",jobStatusCompleted:"已完成",jobStatusReview:"已完成 — 需要审核",bulkImported:"已导入",bulkSkipped:"已导入过",quarantined:"需要审核",bulkFailed:"技术失败"},
  fa:{bulkSafety:"محصولات در دسته‌های کنترل‌شده و با هم‌زمانی محدود پردازش می‌شوند تا محدودیت‌های CJ رعایت شود. هیچ محصولی خودکار منتشر نمی‌شود؛ پیش از انتشار بررسی کنید.",processedCount:"پردازش‌شده",remainingCount:"باقی‌مانده",elapsed:"زمان سپری‌شده",durationUnavailable:"در حال انجام",resumeBusy:"دسته در حال پردازش…",jobStatusPending:"در انتظار شروع",jobStatusRunning:"واردسازی در حال انجام",jobStatusReady:"آماده دسته بعدی",jobStatusCompleted:"تکمیل شد",jobStatusReview:"تکمیل شد — نیازمند بررسی",bulkImported:"واردشده",bulkSkipped:"قبلاً واردشده",quarantined:"نیازمند بررسی",bulkFailed:"خطاهای فنی"},
  hi:{bulkSafety:"CJ सीमाओं का पालन करने के लिए उत्पाद नियंत्रित बैच और सीमित समवर्ती प्रसंस्करण से संसाधित होते हैं। कोई उत्पाद स्वतः प्रकाशित नहीं होता; प्रकाशन से पहले समीक्षा करें।",processedCount:"संसाधित",remainingCount:"शेष",elapsed:"बीता समय",durationUnavailable:"प्रगति पर",resumeBusy:"बैच प्रगति पर…",jobStatusPending:"आरंभ की प्रतीक्षा",jobStatusRunning:"आयात प्रगति पर",jobStatusReady:"अगले बैच के लिए तैयार",jobStatusCompleted:"पूर्ण",jobStatusReview:"पूर्ण — समीक्षा आवश्यक",bulkImported:"आयातित",bulkSkipped:"पहले से आयातित",quarantined:"समीक्षा आवश्यक",bulkFailed:"तकनीकी विफलताएँ"},
  pt:{bulkSafety:"Os produtos são processados em lotes controlados com concorrência limitada para respeitar os limites da CJ. Nada é publicado automaticamente; reveja os produtos antes da publicação.",processedCount:"Processados",remainingCount:"Restantes",elapsed:"Tempo decorrido",durationUnavailable:"Em curso",resumeBusy:"Lote em curso…",jobStatusPending:"Aguardando início",jobStatusRunning:"Importação em curso",jobStatusReady:"Pronto para o próximo lote",jobStatusCompleted:"Concluído",jobStatusReview:"Concluído — revisão necessária",bulkImported:"Importados",bulkSkipped:"Já importados",quarantined:"Requerem revisão",bulkFailed:"Falhas técnicas"},
  ru:{bulkSafety:"Товары обрабатываются контролируемыми пакетами с ограниченным параллелизмом, чтобы соблюдать лимиты CJ. Ничего не публикуется автоматически; проверяйте товары перед публикацией.",processedCount:"Обработано",remainingCount:"Осталось",elapsed:"Прошло времени",durationUnavailable:"В процессе",resumeBusy:"Пакет обрабатывается…",jobStatusPending:"Ожидает запуска",jobStatusRunning:"Импорт выполняется",jobStatusReady:"Готово к следующему пакету",jobStatusCompleted:"Завершено",jobStatusReview:"Завершено — требуется проверка",bulkImported:"Импортировано",bulkSkipped:"Уже импортировано",quarantined:"Требует проверки",bulkFailed:"Технические ошибки"},
};
for(const [locale,messages] of Object.entries(jobPolishMessages))Object.assign(supplierBulkMessages[locale]??(supplierBulkMessages[locale]={}),messages);
Object.assign(supplierBulkMessages.en,{importInProgress:"Import in progress… please wait.",importFailed:"The import could not be started. Please review the selection and try again."});
Object.assign(supplierBulkMessages.fr,{importInProgress:"Importation en cours… veuillez patienter.",importFailed:"L’importation n’a pas pu démarrer. Vérifiez la sélection et réessayez."});
Object.assign(supplierBulkMessages.ar??(supplierBulkMessages.ar={}), {importInProgress:"الاستيراد جارٍ… يُرجى الانتظار.",importFailed:"تعذر بدء الاستيراد. راجع التحديد وحاول مرة أخرى."});
