import type{Locale}from"./config";
type Copy={title:string;delivery:string;carrier:string;number:string;copy:string;copied:string;open:string;shippedAt:string;deliveredAt:string;updatedAt:string;noTracking:string;status:Record<"preparing"|"shipped"|"in_transit"|"out_for_delivery"|"delivered"|"exception"|"unknown",string>};
const en:Copy={title:"Shipment tracking",delivery:"Delivery shipment",carrier:"Carrier",number:"Tracking number",copy:"Copy tracking number",copied:"Copied",open:"Open carrier tracking",shippedAt:"Shipped",deliveredAt:"Delivered",updatedAt:"Latest update",noTracking:"Tracking details are not available yet.",status:{preparing:"Preparing",shipped:"Shipped",in_transit:"In transit",out_for_delivery:"Out for delivery",delivered:"Delivered",exception:"Delivery exception",unknown:"Status unavailable"}};
export const trackingUi:Record<Locale,Copy>={
 en,
 fr:{title:"Suivi de l’envoi",delivery:"Envoi de livraison",carrier:"Transporteur",number:"Numéro de suivi",copy:"Copier le numéro de suivi",copied:"Copié",open:"Ouvrir le suivi du transporteur",shippedAt:"Expédié",deliveredAt:"Livré",updatedAt:"Dernière mise à jour",noTracking:"Les informations de suivi ne sont pas encore disponibles.",status:{preparing:"En préparation",shipped:"Expédié",in_transit:"En transit",out_for_delivery:"En cours de livraison",delivered:"Livré",exception:"Incident de livraison",unknown:"Statut indisponible"}},
 ar:{title:"تتبع الشحنة",delivery:"شحنة التسليم",carrier:"شركة الشحن",number:"رقم التتبع",copy:"نسخ رقم التتبع",copied:"تم النسخ",open:"فتح تتبع شركة الشحن",shippedAt:"تاريخ الشحن",deliveredAt:"تاريخ التسليم",updatedAt:"آخر تحديث",noTracking:"تفاصيل التتبع غير متاحة بعد.",status:{preparing:"قيد التجهيز",shipped:"تم الشحن",in_transit:"قيد النقل",out_for_delivery:"خرج للتسليم",delivered:"تم التسليم",exception:"مشكلة في التسليم",unknown:"الحالة غير متاحة"}},
 ku:{title:"بەدواداچوونی بار",delivery:"باری گەیاندن",carrier:"گواستنەوەکار",number:"ژمارەی بەدواداچوون",copy:"کۆپیکردنی ژمارە",copied:"کۆپی کرا",open:"کردنەوەی بەدواداچوونی گواستنەوەکار",shippedAt:"نێردرا",deliveredAt:"گەیەندرا",updatedAt:"نوێترین نوێکردنەوە",noTracking:"زانیاری بەدواداچوون هێشتا بەردەست نییە.",status:{preparing:"ئامادە دەکرێت",shipped:"نێردرا",in_transit:"لە ڕێگادایە",out_for_delivery:"بۆ گەیاندن دەرچووە",delivered:"گەیەندرا",exception:"کێشەی گەیاندن",unknown:"دۆخ بەردەست نییە"}},
 de:{...en,title:"Sendungsverfolgung",delivery:"Liefersendung",carrier:"Transportdienst",number:"Sendungsnummer",copy:"Sendungsnummer kopieren",copied:"Kopiert",open:"Sendungsverfolgung öffnen",shippedAt:"Versandt",deliveredAt:"Zugestellt",updatedAt:"Letzte Aktualisierung",noTracking:"Trackingdetails sind noch nicht verfügbar."},
 es:{...en,title:"Seguimiento del envío",delivery:"Envío de entrega",carrier:"Transportista",number:"Número de seguimiento",copy:"Copiar número de seguimiento",copied:"Copiado",open:"Abrir seguimiento",shippedAt:"Enviado",deliveredAt:"Entregado",updatedAt:"Última actualización",noTracking:"Los datos de seguimiento aún no están disponibles."},
 it:{...en,title:"Tracciamento spedizione",delivery:"Spedizione di consegna",carrier:"Corriere",number:"Numero di tracciamento",copy:"Copia numero",copied:"Copiato",open:"Apri tracciamento",shippedAt:"Spedito",deliveredAt:"Consegnato",updatedAt:"Ultimo aggiornamento",noTracking:"I dettagli di tracciamento non sono ancora disponibili."},
 nl:{...en,title:"Zending volgen",delivery:"Bezorgzending",carrier:"Vervoerder",number:"Trackingnummer",copy:"Trackingnummer kopiëren",copied:"Gekopieerd",open:"Tracking openen",shippedAt:"Verzonden",deliveredAt:"Bezorgd",updatedAt:"Laatste update",noTracking:"Trackinggegevens zijn nog niet beschikbaar."},
 tr:{...en,title:"Gönderi takibi",delivery:"Teslimat gönderisi",carrier:"Taşıyıcı",number:"Takip numarası",copy:"Takip numarasını kopyala",copied:"Kopyalandı",open:"Taşıyıcı takibini aç",shippedAt:"Gönderildi",deliveredAt:"Teslim edildi",updatedAt:"Son güncelleme",noTracking:"Takip ayrıntıları henüz mevcut değil."},
 zh:{...en,title:"物流跟踪",delivery:"配送包裹",carrier:"承运商",number:"跟踪号码",copy:"复制跟踪号码",copied:"已复制",open:"打开承运商跟踪",shippedAt:"已发货",deliveredAt:"已送达",updatedAt:"最新更新",noTracking:"跟踪详情尚不可用。"},
 fa:{...en,title:"رهگیری مرسوله",delivery:"مرسوله تحویل",carrier:"حمل‌کننده",number:"شماره رهگیری",copy:"کپی شماره رهگیری",copied:"کپی شد",open:"بازکردن رهگیری",shippedAt:"ارسال شد",deliveredAt:"تحویل شد",updatedAt:"آخرین به‌روزرسانی",noTracking:"جزئیات رهگیری هنوز در دسترس نیست."},
 hi:{...en,title:"शिपमेंट ट्रैकिंग",delivery:"डिलीवरी शिपमेंट",carrier:"कैरियर",number:"ट्रैकिंग नंबर",copy:"ट्रैकिंग नंबर कॉपी करें",copied:"कॉपी किया गया",open:"कैरियर ट्रैकिंग खोलें",shippedAt:"भेजा गया",deliveredAt:"डिलीवर किया गया",updatedAt:"नवीनतम अपडेट",noTracking:"ट्रैकिंग विवरण अभी उपलब्ध नहीं हैं।"},
 pt:{...en,title:"Rastreio da remessa",delivery:"Remessa de entrega",carrier:"Transportadora",number:"Número de rastreio",copy:"Copiar número",copied:"Copiado",open:"Abrir rastreio",shippedAt:"Enviado",deliveredAt:"Entregue",updatedAt:"Última atualização",noTracking:"Os dados de rastreio ainda não estão disponíveis."},
 ru:{...en,title:"Отслеживание отправления",delivery:"Доставка",carrier:"Перевозчик",number:"Трек-номер",copy:"Копировать трек-номер",copied:"Скопировано",open:"Открыть отслеживание",shippedAt:"Отправлено",deliveredAt:"Доставлено",updatedAt:"Последнее обновление",noTracking:"Данные отслеживания пока недоступны."},
};
