import Link from "next/link";
import { redirect } from "next/navigation";
import { getLocale } from "next-intl/server";
import { prisma } from "@/lib/prisma";
import { readSession } from "@/lib/session";
import { requireBusinessOwner } from "@/lib/seller-business-access";
import { sellerTeamCopy } from "@/i18n/seller-team";
export const dynamic="force-dynamic";
export default async function SellerAuditPage({searchParams}:{searchParams:Promise<{page?:string;store?:string;category?:string}>}){const[session,locale,query]=await Promise.all([readSession(),getLocale(),searchParams]);if(!session)redirect(`/${locale}/login`);let principal;try{principal=await requireBusinessOwner(prisma,session.userId)}catch{redirect(`/${locale}/dashboard`)}const page=Math.max(1,Number(query.page)||1),take=30,where={businessId:principal.businessId,...(query.store?{storeId:query.store}:{}),...(query.category?{category:query.category}:{})};const[events,total,stores]=await Promise.all([prisma.sellerBusinessAuditEvent.findMany({where,orderBy:[{createdAt:"desc"},{id:"desc"}],skip:(page-1)*take,take,select:{id:true,category:true,action:true,targetType:true,targetId:true,metadata:true,createdAt:true,store:{select:{name:true}},actor:{select:{firstName:true,lastName:true,email:true}}}}),prisma.sellerBusinessAuditEvent.count({where}),prisma.store.findMany({where:{businessId:principal.businessId},select:{id:true,name:true}})]),copy=sellerTeamCopy(locale);return <main className="sellerStandalonePage"><header className="sellerTeamHero"><div><span>{copy.security}</span><h1>{copy.audit}</h1><p>{copy.ownerOnly}</p></div><Link href={`/${locale}/seller/team`}>← {copy.title}</Link></header><section className="sellerTeamCard"><form className="adminForm"><label>{copy.stores}<select name="store" defaultValue={query.store??""}><option value="">{copy.all}</option>{stores.map(store=><option key={store.id} value={store.id}>{store.name}</option>)}</select></label><label>{copy.category}<input name="category" defaultValue={query.category??""} maxLength={40}/></label><button>{copy.filter}</button></form><div className="adminTableWrap"><table><thead><tr><th>{copy.when}</th><th>{copy.who}</th><th>{copy.where}</th><th>{copy.action}</th><th>{copy.target}</th></tr></thead><tbody>{events.map(event=><tr key={event.id}><td>{new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short"}).format(event.createdAt)}</td><td>{event.actor.firstName} {event.actor.lastName}<small>{event.actor.email}</small></td><td>{event.store?.name??copy.allStores}</td><td>{event.category} · {event.action}</td><td>{event.targetType??"—"}<small>{event.targetId??""}</small></td></tr>)}</tbody></table></div><nav className="buyerOrdersBack">{page>1&&<Link href={`?page=${page-1}`}>{copy.previous}</Link>}<span>{page} / {Math.max(1,Math.ceil(total/take))}</span>{page*take<total&&<Link href={`?page=${page+1}`}>{copy.next}</Link>}</nav></section></main>}
