import { CANONICAL_LEAF_CATEGORIES, DESKTOP_CATEGORY_TAXONOMY, canonicalLeafCategory, subcategoryId } from "../desktop-category-taxonomy";
import type { SupplierProductSnapshot } from "./types";

export const CJ_CLASSIFICATION_THRESHOLDS={high:0.82,accepted:0.62} as const;
export type CjClassificationStatus="SUGGESTED"|"NEEDS_REVIEW"|"UNRESOLVED"|"CONFLICT";
export type CjClassification={canonicalCategoryId:string|null;categoryId:string|null;categoryLabel:string|null;subcategoryLabel:string|null;confidence:number;status:CjClassificationStatus;evidence:string[]};
function normalized(value:string){return value.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();}
function contextualText(value:string){return normalized(value).replace(/\b(short|long) sleeved?\b/g," ").replace(/\b(short|long) sleeve\b/g," ").replace(/\bhigh waisted?\b/g," ").replace(/\bwide legged?\b/g," ").replace(/\s+/g," ").trim();}
function tokens(value:string){return new Set(contextualText(value).split(/\s+/).filter(item=>item.length>2));}
function overlap(source:Set<string>,label:string){const target=tokens(label);if(!target.size)return 0;let matches=0;for(const item of target)if(source.has(item))matches++;return matches/target.size;}
function metadataText(snapshot:SupplierProductSnapshot){return [snapshot.categoryReference,snapshot.rawMetadata.categoryId,snapshot.rawMetadata.productType].filter((v):v is string=>typeof v==="string").join(" ");}
function leafResult(categoryId:string,groupId:string,label:string,confidence:number,evidence:string[]):CjClassification{const category=DESKTOP_CATEGORY_TAXONOMY.find(c=>c.id===categoryId),group=category?.groups.find(g=>g.id===groupId);if(!category||!group||!group.items.includes(label))return{canonicalCategoryId:null,categoryId:null,categoryLabel:null,subcategoryLabel:null,confidence:0,status:"UNRESOLVED",evidence:["EXPLICIT_RULE_TARGET_MISSING"]};return{canonicalCategoryId:subcategoryId(categoryId,groupId,label),categoryId,categoryLabel:category.label,subcategoryLabel:label,confidence,status:"SUGGESTED",evidence};}
function reviewResult(evidence:string[],confidence=0.45):CjClassification{return{canonicalCategoryId:null,categoryId:null,categoryLabel:null,subcategoryLabel:null,confidence,status:"NEEDS_REVIEW",evidence};}
function explicitClassification(snapshot:SupplierProductSnapshot):CjClassification|null{
 const title=contextualText(snapshot.title),description=contextualText(snapshot.description.slice(0,1200)),combined=`${title} ${description}`,has=(p:RegExp)=>p.test(title),hasCombined=(p:RegExp)=>p.test(combined),words=tokens(combined);
 const baby=hasCombined(/\b(baby|babies|infant|infants|newborn|toddler|toddlers)\b/),child=hasCombined(/\b(child|children|childrens|kid|kids|youth|junior)\b/),girl=hasCombined(/\b(girl|girls)\b/),boy=hasCombined(/\b(boy|boys)\b/),women=has(/\b(women|womens|woman|female|ladies|lady)\b/),men=has(/\b(men|mens|man|male)\b/);
 if(baby){if(hasCombined(/\b(romper|rompers|onesie|onesies|overall|overalls|jumpsuit|jumpsuits)\b/))return leafResult("kids","baby","Barboteuses de bébé",.94,["EXPLICIT_AGE:BABY","EXPLICIT_PRODUCT_TYPE:ROMPER_OR_OVERALL"]);if(hasCombined(/\b(dress|dresses)\b/))return leafResult("kids","baby","Robes de bébé",.94,["EXPLICIT_AGE:BABY","EXPLICIT_PRODUCT_TYPE:DRESS"]);if(hasCombined(/\b(pant|pants|trouser|trousers)\b/))return leafResult("kids","baby","Pantalon de bébé",.93,["EXPLICIT_AGE:BABY","EXPLICIT_PRODUCT_TYPE:PANTS"]);if(hasCombined(/\b(set|sets|outfit|outfits|clothing set|clothes set)\b/))return leafResult("kids","baby","Ensembles de vêtements pour bébé",.92,["EXPLICIT_AGE:BABY","EXPLICIT_PRODUCT_TYPE:CLOTHING_SET"]);return reviewResult(["EXPLICIT_AGE:BABY","BABY_PRODUCT_TYPE_UNRESOLVED"],.5);}
 if(child||girl||boy){if(girl){if(hasCombined(/\b(dress|dresses)\b/))return leafResult("kids","girls","Robes de Fille",.94,["EXPLICIT_AGE:CHILD","AUDIENCE:GIRL","EXPLICIT_PRODUCT_TYPE:DRESS"]);if(hasCombined(/\b(t shirt|tshirt|tee shirt|top|tops)\b/))return leafResult("kids","girls","Hauts et T-shirts",.93,["EXPLICIT_AGE:CHILD","AUDIENCE:GIRL","EXPLICIT_PRODUCT_TYPE:TOP"]);if(hasCombined(/\b(pant|pants|trouser|trousers|jean|jeans|denim)\b/))return leafResult("kids","girls","Girls' Pants",.92,["EXPLICIT_AGE:CHILD","AUDIENCE:GIRL","EXPLICIT_PRODUCT_TYPE:PANTS"]);if(hasCombined(/\b(set|sets|outfit|outfits)\b/))return leafResult("kids","girls","Ensembles de vêtements pour fille",.91,["EXPLICIT_AGE:CHILD","AUDIENCE:GIRL","EXPLICIT_PRODUCT_TYPE:CLOTHING_SET"]);}if(boy){if(hasCombined(/\bjeans?\b|\bdenim\b/))return leafResult("kids","boys","Jeans pour garçon",.94,["EXPLICIT_AGE:CHILD","AUDIENCE:BOY","EXPLICIT_PRODUCT_TYPE:JEANS"]);if(hasCombined(/\b(t shirt|tshirt|tee shirt)\b/))return leafResult("kids","boys","T-shirts pour garçon",.94,["EXPLICIT_AGE:CHILD","AUDIENCE:BOY","EXPLICIT_PRODUCT_TYPE:T_SHIRT"]);if(hasCombined(/\b(set|sets|outfit|outfits)\b/))return leafResult("kids","boys","Ensembles de vêtements pour garçon",.91,["EXPLICIT_AGE:CHILD","AUDIENCE:BOY","EXPLICIT_PRODUCT_TYPE:CLOTHING_SET"]);}return reviewResult(["EXPLICIT_AGE:CHILD","CHILD_PRODUCT_TYPE_OR_GENDER_UNRESOLVED"],.48);}
 if(has(/\b(t shirt|tshirt|tee shirt|graphic tee)\b/)){if(women&&!men)return leafResult("women","tops","Ladies Short Sleeve",.96,["EXPLICIT_PRODUCT_TYPE:T_SHIRT","AUDIENCE:WOMEN"]);if(men&&!women)return leafResult("men","tshirts",has(/\b(print|printed|graphic|dragon|cartoon|pattern)\b/)?"Impression":"Solide",.96,["EXPLICIT_PRODUCT_TYPE:T_SHIRT","AUDIENCE:MEN"]);return reviewResult(["EXPLICIT_PRODUCT_TYPE:T_SHIRT","ADULT_AUDIENCE_AMBIGUOUS"],.52);}
 if((words.has("digital")&&(words.has("watch")||words.has("wristwatch")))||hasCombined(/\b(smart watch|smartwatch)\b/))return leafResult("jewelry","men-watches","Montres numériques",.98,["EXPLICIT_PRODUCT_TYPE:DIGITAL_WATCH","ALIAS:digital watch"]);
 if(hasCombined(/\bquartz watch\b/))return leafResult("jewelry","men-watches","Montres à quartz",.98,["EXPLICIT_PRODUCT_TYPE:QUARTZ_WATCH","ALIAS:quartz watch"]);if(hasCombined(/\bmechanical watch\b/))return leafResult("jewelry","men-watches","Montres mécaniques",.98,["EXPLICIT_PRODUCT_TYPE:MECHANICAL_WATCH","ALIAS:mechanical watch"]);if(hasCombined(/\b(sports watch|sport watch)\b/)&&men)return leafResult("jewelry","men-watches","Montres de sport pour homme",.96,["EXPLICIT_PRODUCT_TYPE:SPORTS_WATCH","AUDIENCE:MEN","ALIAS:sports watch"]);if(hasCombined(/\b(sports watch|sport watch)\b/)&&women)return leafResult("jewelry","women-watches","Montres de sport pour femmes",.96,["EXPLICIT_PRODUCT_TYPE:SPORTS_WATCH","AUDIENCE:WOMEN","ALIAS:sports watch"]);
 // Shoe subtype guard: generic "shoe(s)" can establish the product family, never a specific leaf. A specific leaf requires explicit subtype evidence.
 const shoes=hasCombined(/\b(shoe|shoes|footwear)\b/);
 if(shoes&&men){if(hasCombined(/\b(formal|business|wedding|dress shoe|dress shoes|oxford|oxfords)\b/))return leafResult("bags-shoes","men-shoes","Chaussures formelles",.96,["EXPLICIT_PRODUCT_TYPE:FORMAL_SHOES","AUDIENCE:MEN"]);if(hasCombined(/\b(boot|boots)\b/))return leafResult("bags-shoes","men-shoes","Bottes pour Homme",.96,["EXPLICIT_PRODUCT_TYPE:BOOTS","AUDIENCE:MEN"]);if(hasCombined(/\b(sandal|sandals)\b/))return leafResult("bags-shoes","men-shoes","Sandales Pour Homme",.96,["EXPLICIT_PRODUCT_TYPE:SANDALS","AUDIENCE:MEN"]);if(hasCombined(/\b(slipper|slippers)\b/))return leafResult("bags-shoes","men-shoes","Pantoufles pour Homme",.95,["EXPLICIT_PRODUCT_TYPE:SLIPPERS","AUDIENCE:MEN"]);if(hasCombined(/\b(vulcanized|vulcanised|vulcanization|vulcanisation)\b/))return leafResult("bags-shoes","men-shoes","Chaussure de vulcanisation",.95,["EXPLICIT_PRODUCT_TYPE:VULCANIZED_SHOES","AUDIENCE:MEN"]);if(hasCombined(/\b(casual|leisure|everyday)\b/))return leafResult("bags-shoes","men-shoes","Chaussures décontractées",.92,["EXPLICIT_PRODUCT_TYPE:CASUAL_SHOES","AUDIENCE:MEN"]);return reviewResult(["EXPLICIT_PRODUCT_FAMILY:SHOES","AUDIENCE:MEN","SHOE_SUBTYPE_UNRESOLVED"],.56);}
 if(shoes&&women){if(hasCombined(/\b(high heel|high heels|heels|stiletto|stilettos)\b/))return leafResult("bags-shoes","women-shoes","Talons hauts",.96,["EXPLICIT_PRODUCT_TYPE:HIGH_HEELS","AUDIENCE:WOMEN"]);if(hasCombined(/\b(boot|boots)\b/))return leafResult("bags-shoes","women-shoes","Bottes pour femme",.96,["EXPLICIT_PRODUCT_TYPE:BOOTS","AUDIENCE:WOMEN"]);if(hasCombined(/\b(sandal|sandals)\b/))return leafResult("bags-shoes","women-shoes","Sandales pour femme",.96,["EXPLICIT_PRODUCT_TYPE:SANDALS","AUDIENCE:WOMEN"]);if(hasCombined(/\b(slipper|slippers)\b/))return leafResult("bags-shoes","women-shoes","Chaussons pour femme",.95,["EXPLICIT_PRODUCT_TYPE:SLIPPERS","AUDIENCE:WOMEN"]);if(hasCombined(/\b(flat|flats|ballet flat|ballet flats)\b/))return leafResult("bags-shoes","women-shoes","Chaussures plates",.94,["EXPLICIT_PRODUCT_TYPE:FLAT_SHOES","AUDIENCE:WOMEN"]);if(hasCombined(/\b(vulcanized|vulcanised|vulcanization|vulcanisation)\b/))return leafResult("bags-shoes","women-shoes","Les chaussures Vulcanises",.95,["EXPLICIT_PRODUCT_TYPE:VULCANIZED_SHOES","AUDIENCE:WOMEN"]);return reviewResult(["EXPLICIT_PRODUCT_FAMILY:SHOES","AUDIENCE:WOMEN","SHOE_SUBTYPE_UNRESOLVED"],.56);}
 if(has(/\b(backpack|rucksack)\b/)&&men)return leafResult("bags-shoes","men-bags","Sacs à dos pour hommes",.96,["EXPLICIT_PRODUCT_TYPE:BACKPACK","AUDIENCE:MEN"]);if(has(/\b(handbag|hand bag|purse)\b/))return leafResult("bags-shoes","women-bags","Sac à main",.95,["EXPLICIT_PRODUCT_TYPE:HANDBAG"]);if(women&&has(/\bjeans?\b|\bdenim\b/))return leafResult("women","pants","Jeans pour femmes",.97,["EXPLICIT_PRODUCT_TYPE:JEANS","AUDIENCE:WOMEN"]);if(men&&has(/\bjeans?\b|\bdenim\b/))return leafResult("men","pants","Jeans pour hommes",.97,["EXPLICIT_PRODUCT_TYPE:JEANS","AUDIENCE:MEN"]);if(women&&has(/\bshorts\b/))return leafResult("women","pants","Short pour femmes",.96,["EXPLICIT_PRODUCT_TYPE:SHORTS","AUDIENCE:WOMEN"]);if(men&&has(/\bshorts\b/))return leafResult("men","pants","Short pour hommes",.96,["EXPLICIT_PRODUCT_TYPE:SHORTS","AUDIENCE:MEN"]);if(women&&has(/\b(dress|dresses)\b/))return leafResult("women","tops","Robes pour femmes",.96,["EXPLICIT_PRODUCT_TYPE:DRESS","AUDIENCE:WOMEN"]);return null;
}
const ENGLISH_ALIASES:Record<string,readonly string[]>={"Talons hauts":["high heels","heel shoes","womens heels"],"Chargeurs":["charger","charging adapter"],"Câbles":["usb cable","charging cable"],"Écouteurs":["earbuds","headphones","earphones"],"Sacs à dos pour hommes":["mens backpack","men backpack","backpack"],"Sacs à bandoulière pour femme":["women shoulder bag","crossbody bag"],"Sac à main":["handbag","purse"],"Robes pour femmes":["womens dress","women dress","dress"],"Montres numériques":["digital watch","smart watch","smartwatch"],"Montres à quartz":["quartz watch"],"Montres mécaniques":["mechanical watch"],"Montres de sport pour homme":["sports watch men","mens sports watch","men sports watch"],"Montres de sport pour femmes":["womens sports watch","women sports watch"],"Chaussures de course":["running shoes","athletic shoes"],"Sandales Pour Homme":["men sandals"],"Sandales pour femme":["women sandals"],"Bottes pour femme":["women boots"],"Bottes pour Homme":["men boots"],"Jeans pour femmes":["women jeans","womens denim"],"Jeans pour hommes":["men jeans","mens denim"]};
function aliasScore(source:Set<string>,label:string){const aliases=ENGLISH_ALIASES[label]??[];const exact=aliases.filter(a=>overlap(source,a)===1);return{score:exact.length?Math.max(...exact.map(a=>tokens(a).size>=2?1:.75)):0,hits:exact};}
function boostSignals(source:Set<string>){const out=new Set(source),has=(...v:string[])=>v.some(x=>source.has(x));if(has("watch","watches","smartwatch")){out.add("montre");out.add("montres");}if(has("backpack","handbag","purse","bag")){out.add("sac");out.add("sacs");}if(has("shoe","shoes","sneaker","sneakers","boot","boots","sandal","sandals")){out.add("chaussure");out.add("chaussures");}if(has("jean","jeans","denim")){out.add("jean");out.add("jeans");}if(has("men","mens","man","male")){out.add("homme");out.add("hommes");}if(has("women","womens","woman","female")){out.add("femme");out.add("femmes");}return out;}
export function classify