import { CANONICAL_LEAF_CATEGORIES, DESKTOP_CATEGORY_TAXONOMY, canonicalLeafCategory, subcategoryId } from "../desktop-category-taxonomy";
import type { SupplierProductSnapshot } from "./types";
export const CJ_CLASSIFICATION_THRESHOLDS={high:0.82,accepted:0.62} as const;
export type CjClassificationStatus="SUGGESTED"|"NEEDS_REVIEW"|"UNRESOLVED"|"CONFLICT";
export type CjClassification={canonicalCategoryId:string|null;categoryId:string|null;categoryLabel:string|null;subcategoryLabel:string|null;confidence:number;status:CjClassificationStatus;evidence:string[]};
function n(v:string){return v.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim()}
function t(v:string){return new Set(n(v).replace(/\b(short|long) sleeved?\b/g," ").replace(/\b(short|long) sleeve\b/g," ").split(/\s+/).filter(x=>x.length>2))}
function leaf(c:string,g:string,l:string,confidence:number,evidence:string[]):CjClassification{const C=DESKTOP_CATEGORY_TAXONOMY.find(x=>x.id===c),G=C?.groups.find(x=>x.id===g);if(!C||!G||!G.items.includes(l))return unresolved(["EXPLICIT_RULE_TARGET_MISSING"]);return{canonicalCategoryId:subcategoryId(c,g,l),categoryId:c,categoryLabel:C.label,subcategoryLabel:l,confidence,status:"SUGGESTED",evidence}}
function review(evidence:string[],confidence=.45):CjClassification{return{canonicalCategoryId:null,categoryId:null,categoryLabel:null,subcategoryLabel:null,confidence,status:"NEEDS_REVIEW",evidence}}
function unresolved(evidence:string[]):CjClassification{return{canonicalCategoryId:null,categoryId:null,categoryLabel:null,subcategoryLabel:null,confidence:0,status:"UNRESOLVED",evidence}}
export function classifyCjProduct(s:SupplierProductSnapshot):CjClassification{const title=n(s.title),all=n(`${s.title} ${s.description.slice(0,1200)}`),has=(r:RegExp)=>r.test(title),any=(r:RegExp)=>r.test(all),baby=any(/\b(baby|babies|infant|newborn|toddler)\b/),child=any(/\b(child|children|childrens|kid|kids|youth|junior)\b/),women=has(/\b(women|womens|woman|female|ladies|lady)\b/),men=has(/\b(men|mens|man|male)\b/),girl=any(/\b(girl|girls)\b/),boy=any(/\b(boy|boys)\b/);
if(baby){if(any(/\b(romper|onesie|overall|overalls|jumpsuit)\b/))return leaf("kids","baby","Barboteuses de bébé",.94,["EXPLICIT_AGE:BABY","EXPLICIT_PRODUCT_TYPE:ROMPER_OR_OVERALL"]);if(any(/\bdresses?\b/))return leaf("kids","baby","Robes de bébé",.94,["EXPLICIT_AGE:BABY","EXPLICIT_PRODUCT_TYPE:DRESS"]);if(any(/\b(pants?|trousers?)\b/))return leaf("kids","baby","Pantalon de bébé",.93,["EXPLICIT_AGE:BABY","EXPLICIT_PRODUCT_TYPE:PANTS"]);return review(["EXPLICIT_AGE:BABY","BABY_PRODUCT_TYPE_UNRESOLVED"],.5)}
if(child||girl||boy)return review(["EXPLICIT_AGE:CHILD","CHILD_PRODUCT_TYPE_OR_GENDER_UNRESOLVED"],.48);
if(any(/\b(sports watch|sport watch)\b/)&&men)return leaf("jewelry","men-watches","Montres de sport pour homme",.96,["EXPLICIT_PRODUCT_TYPE:SPORTS_WATCH","AUDIENCE:MEN","ALIAS:sports watch"]);if(any(/\b(sports watch|sport watch)\b/)&&women)return leaf("jewelry","women-watches","Montres de sport pour femmes",.96,["EXPLICIT_PRODUCT_TYPE:SPORTS_WATCH","AUDIENCE:WOMEN","ALIAS:sports watch"]);if(t(all).has("digital")&&(t(all).has("watch")||t(all).has("wristwatch")))return leaf("jewelry","men-watches","Montres numériques",.98,["EXPLICIT_PRODUCT_TYPE:DIGITAL_WATCH","ALIAS:digital watch"]);
if(has(/\b(t shirt|tshirt|tee shirt|graphic tee)\b/)){if(women&&!men)return leaf("women","tops","Ladies Short Sleeve",.96,["EXPLICIT_PRODUCT_TYPE:T_SHIRT","AUDIENCE:WOMEN"]);if(men&&!women)return leaf("men","tshirts",has(/\b(print|printed|graphic|dragon|cartoon|pattern)\b/)?"Impression":"Solide",.96,["EXPLICIT_PRODUCT_TYPE:T_SHIRT","AUDIENCE:MEN"]);return review(["EXPLICIT_PRODUCT_TYPE:T_SHIRT","ADULT_AUDIENCE_AMBIGUOUS"],.52)}
const shoes=any(/\b(shoe|shoes|footwear)\b/);if(shoes&&men){if(any(/\b(formal|business|wedding|oxford|oxfords)\b/))return leaf("bags-shoes","men-shoes","Chaussures formelles",.96,["EXPLICIT_PRODUCT_TYPE:FORMAL_SHOES","AUDIENCE:MEN"]);if(any(/\b(vulcanized|vulcanised|vulcanization|vulcanisation)\b/))return leaf("bags-shoes","men-shoes","Chaussure de vulcanisation",.95,["EXPLICIT_PRODUCT_TYPE:VULCANIZED_SHOES","AUDIENCE:MEN"]);if(any(/\bboots?\b/))return leaf("bags-shoes","men-shoes","Bottes pour Homme",.96,["EXPLICIT_PRODUCT_TYPE:BOOTS","AUDIENCE:MEN"]);if(any(/\bsandals?\b/))return leaf("bags-shoes","men-shoes","Sandales Pour Homme",.96,["EXPLICIT_PRODUCT_TYPE:SANDALS","AUDIENCE:MEN"]);return review(["EXPLICIT_PRODUCT_FAMILY:SHOES","AUDIENCE:MEN","SHOE_SUBTYPE_UNRESOLVED"],.56)}
if(shoes&&women){if(any(/\b(high heels?|heels|stilettos?)\b/))return leaf("bags-shoes","women-shoes","Talons hauts",.96,["EXPLICIT_PRODUCT_TYPE:HIGH_HEELS","AUDIENCE:WOMEN"]);if(any(/\bboots?\b/))return leaf("bags-shoes","women-shoes","Bottes pour femme",.96,["EXPLICIT_PRODUCT_TYPE:BOOTS","AUDIENCE:WOMEN"]);if(any(/\bsandals?\b/))return leaf("bags-shoes","women-shoes","Sandales pour femme",.96,["EXPLICIT_PRODUCT_TYPE:SANDALS","AUDIENCE:WOMEN"]);return review(["EXPLICIT_PRODUCT_FAMILY:SHOES","AUDIENCE:WOMEN","SHOE_SUBTYPE_UNRESOLVED"],.56)}
if(women&&has(/\bjeans?\b/))return leaf("women","pants","Jeans pour femmes",.97,["EXPLICIT_PRODUCT_TYPE:JEANS","AUDIENCE:WOMEN"]);if(men&&has(/\bjeans?\b/))return leaf("men","pants","Jeans pour hommes",.97,["EXPLICIT_PRODUCT_TYPE:JEANS","AUDIENCE:MEN"]);if(women&&has(/\bshorts\b/))return leaf("women","pants","Short pour femmes",.96,["EXPLICIT_PRODUCT_TYPE:SHORTS","AUDIENCE:WOMEN"]);if(men&&has(/\bshorts\b/))return leaf("men","pants","Short pour hommes",.96,["EXPLICIT_PRODUCT_TYPE:SHORTS","AUDIENCE:MEN"]);if(has(/\bbackpack|rucksack\b/)&&men)return leaf("bags-shoes","men-bags","Sacs à dos pour hommes",.96,["EXPLICIT_PRODUCT_TYPE:BACKPACK","AUDIENCE:MEN"]);
if(any(/\b(shoulder bag|crossbody bag|cross body bag)\b/)&&women)return leaf("bags-shoes","women-bags","Sacs à bandoulière pour femme",.95,["EXPLICIT_PRODUCT_TYPE:SHOULDER_BAG","AUDIENCE:WOMEN"]);if(any(/\bhandbag|hand bag|purse\b/))return leaf("bags-shoes","women-bags","Sac à main",.95,["EXPLICIT_PRODUCT_TYPE:HANDBAG"]);
const signalWords=t(`${s.title} ${s.description.slice(0,1200)} ${s.categoryReference??""}`);if(signalWords.size<=4||/^(zxq|sku|item|product|generic|unknown|test|sample|model|code|number|no|ref|reference|[0-9]+)(\s|$)/.test(n(s.title)))return unresolved(["INSUFFICIENT_TRUSTWORTHY_TAXONOMY_SIGNAL"]);return review(["INSUFFICIENT_TRUSTWORTHY_TAXONOMY_SIGNAL"],.4)}
export function todijoTaxonomyOptions(){return CANONICAL_LEAF_CATEGORIES.map(x=>({id:x.id,label:x.label,categoryId:x.categoryId,categoryLabel:x.categoryLabel,groupId:x.groupId,groupLabel:x.groupLabel}))}
export function validateTodijoClassification(id:unknown){const x=typeof id==="string"?canonicalLeafCategory(id):null;if(!x)throw new Error("CANONICAL_CATEGORY_INVALID");return x}
