import { CANONICAL_LEAF_CATEGORIES, DESKTOP_CATEGORY_TAXONOMY, canonicalLeafCategory, subcategoryId } from "../desktop-category-taxonomy";
import type { SupplierProductSnapshot } from "./types";
export const CJ_CLASSIFICATION_THRESHOLDS={high:0.82,accepted:0.62} as const;
export type CjClassificationStatus="SUGGESTED"|"NEEDS_REVIEW"|"UNRESOLVED"|"CONFLICT";
export type CjClassification={canonicalCategoryId:string|null;categoryId:string|null;categoryLabel:string|null;subcategoryLabel:string|null;confidence:number;status:CjClassificationStatus;evidence:string[]};
function normalized(v:string){return v.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim()}
function contextualText(v:string){return normalized(v).replace(/\b(short|long) sleeved?\b/g," ").replace(/\b(short|long) sleeve\b/g," ").replace(/\bhigh waisted?\b/g," ").replace(/\bwide legged?\b/g," ").replace(/\s+/g," ").trim()}
function tokens(v:string){return new Set(contextualText(v).split(/\s+/).filter(x=>x.length>2))}
function overlap(s:Set<string>,label:string){const t=tokens(label);if(!t.size)return 0;let n=0;for(const x of t)if(s.has(x))n++;return n/t.size}
function metadataText(s:SupplierProductSnapshot){return[s.categoryReference,s.rawMetadata.categoryId,s.rawMetadata.productType].filter((v):v is string=>typeof v==="string").join(" ")}
function leafResult(categoryId:string,groupId:string,label:string,confidence:number,evidence:string[]):CjClassification{const c=DESKTOP_CATEGORY_TAXONOMY.find(x=>x.id===categoryId),g=c?.groups.find(x=>x.id===groupId);if(!c||!g||!g.items.includes(label))return{canonicalCategoryId:null,categoryId:null,categoryLabel:null,subcategoryLabel:null,confidence:0,status:"UNRESOLVED",evidence:["EXPLICIT_RULE_TARGET_MISSING"]};return{canonicalCategoryId:subcategoryId(categoryId,groupId,label),categoryId,categoryLabel:c.label,subcategoryLabel:label,confidence,status:"SUGGESTED",evidence}}
function reviewResult(evidence:string[],confidence=.45):CjClassification{return{canonicalCategoryId:null,categoryId:null,categoryLabel:null,subcategoryLabel:null,confidence,status:"NEEDS_REVIEW",evidence}}
function explicitClassification(s:SupplierProductSnapshot):CjClassification|null{const title=contextualText(s.title),desc=contextualText(s.description.slice(0,1200)),all=`${title} ${desc}`,has=(r:RegExp)=>r.test(title),hasAll=(r:RegExp)=>r.test(all),w=tokens(all),baby=hasAll(/\b(baby|babies|infant|infants|newborn|toddler|toddlers)\b/),child=hasAll(/\b(child|children|childrens|kid|kids|youth|junior)\b/),girl=hasAll(/\b(girl|girls)\b/),boy=hasAll(/\b(boy|boys)\b/),women=has(/\b(women|womens|woman|female|ladies|lady)\b/),men=has(/\b(men|mens|man|male)\b/);
if(baby){if(hasAll(/\b(romper|rompers|onesie|onesies|overall|overalls|jumpsuit|jumpsuits)\b/))return leafResult("kids","baby","Barboteuses de bébé",.94,["EXPLICIT_AGE:BABY","EXPLICIT_PRODUCT_TYPE:ROMPER_OR_OVERALL"]);if(hasAll(/\b(dress|dresses)\b/))return leafResult("kids","baby","Robes de bébé",.94,["EXPLICIT_AGE:BABY","EXPLICIT_PRODUCT_TYPE:DRESS"]);if(hasAll(/\b(pant|pants|trouser|trousers)\b/))return leafResult("kids","baby","Pantalon de bébé",.93,["EXPLICIT_AGE:BABY","EXPLICIT_PRODUCT_TYPE:PANTS"]);if(hasAll(/\b(set|sets|outfit|outfits|clothing set|clothes set)\b/))return leafResult("kids","baby","Ensembles de vêtements pour bébé",.92,["EXPLICIT_AGE:BABY","EXPLICIT_PRODUCT_TYPE:CLOTHING_SET"]);return reviewResult(["EXPLICIT_AGE:BABY","BABY_PRODUCT_TYPE_UNRESOLVED"],.5)}
if(child||girl||boy){if(girl&&hasAll(/\b(dress|dresses)\b/))return leafResult("kids","girls","Robes de Fille",.94,["EXPLICIT_AGE:CHILD","AUDIENCE:GIRL","EXPLICIT_PRODUCT_TYPE:DRESS"]);if(girl&&hasAll(/\b(t shirt|tshirt|tee shirt|top|tops)\b/))return leafResult("kids","girls","Hauts et T-shirts",.93,["EXPLICIT_AGE:CHILD","AUDIENCE:GIRL","EXPLICIT_PRODUCT_TYPE:TOP"]);if(girl&&hasAll(/\b(pant|pants|trouser|trousers|jean|jeans|denim)\b/))return leafResult("kids","girls","Girls' Pants",.92,["EXPLICIT_AGE:CHILD","AUDIENCE:GIRL","EXPLICIT_PRODUCT_TYPE:PANTS"]);if(boy&&hasAll(/\bjeans?\b|\bdenim\b/))return leafResult("kids","boys","Jeans pour garçon",.94,["EXPLICIT_AGE:CHILD","AUDIENCE:BOY","EXPLICIT_PRODUCT_TYPE:JEANS"]);if(boy&&hasAll(/\b(t shirt|tshirt|tee shirt)\b/))return leafResult("kids","boys","T-shirts pour garçon",.94,["EXPLICIT_AGE:CHILD","AUDIENCE:BOY","EXPLICIT_PRODUCT_TYPE:T_SHIRT"]);return reviewResult(["EXPLICIT_AGE:CHILD","CHILD_PRODUCT_TYPE_OR_GENDER_UNRESOLVED"],.48)}
if(has(/\b(t shirt|tshirt|tee shirt|graphic tee)\b/)){if(women&&!men)return leafResult("women","tops","Ladies Short Sleeve",.96,["EXPLICIT_PRODUCT_TYPE:T_SHIRT","AUDIENCE:WOMEN"]);if(men&&!women)return leafResult("men","tshirts",has(/\b(print|printed|graphic|dragon|cartoon|pattern)\b/)?"Impression":"Solide",.96,["EXPLICIT_PRODUCT_TYPE:T_SHIRT","AUDIENCE:MEN"]);return reviewResult(["EXPLICIT_PRODUCT_TYPE:T_SHIRT","ADULT_AUDIENCE_AMBIGUOUS"],.52)}
if((w.has("digital")&&(w.has("watch")||w.has("wristwatch")))||hasAll(/\b(smart watch|smartwatch)\b/))return leafResult("jewelry","men-watches","Montres numériques",.98,["EXPLICIT_PRODUCT_TYPE:DIGITAL_WATCH","ALIAS:digital watch"]);if(hasAll(/\bquartz watch\b/))return leafResult("jewelry","men-watches","Montres à quartz",.98,["EXPLICIT_PRODUCT_TYPE:QUARTZ_WATCH","ALIAS:quartz watch"]);if(hasAll(/\bmechanical watch\b/))return leafResult("jewelry","men-watches","Montres mécaniques",.98,["EXPLICIT_PRODUCT_TYPE:MECHANICAL_WATCH","ALIAS:mechanical watch"]);if(hasAll(/\b(sports watch|sport watch)\b/)&&men)return leafResult("jewelry","men-watches","Montres de sport pour homme",.96,["EXPLICIT_PRODUCT_TYPE:SPORTS_WATCH","AUDIENCE:MEN","ALIAS:sports watch"]);if(hasAll(/\b(sports watch|sport watch)\b/)&&women)return leafResult("jewelry","women-watches","Montres de sport pour femmes",.96,["EXPLICIT_PRODUCT_TYPE:SPORTS_WATCH","AUDIENCE:WOMEN","ALIAS:sports watch"]);
const shoes=hasAll(/\b(shoe|shoes|footwear)\b/);if(shoes&&men){if(hasAll(/\b(formal|business|wedding|dress shoe|dress shoes|oxford|oxfords)\b/))return leafResult("bags-shoes","men-shoes","Chaussures formelles",.96,["EXPLICIT_PRODUCT_TYPE:FORMAL_SHOES","AUDIENCE:MEN"]);if(hasAll(/\b(boot|boots)\b/))return leafResult("bags-shoes","men-shoes","Bottes pour Homme",.96,["EXPLICIT_PRODUCT_TYPE:BOOTS","AUDIENCE:MEN"]);if(hasAll(/\b(sandal|sandals)\b/))return leafResult("bags-shoes","men-shoes","Sandales Pour Homme",.96,["EXPLICIT_PRODUCT_TYPE:SANDALS","AUDIENCE:MEN"]);if(hasAll(/\b(slipper|slippers)\b/))return leafResult("bags-shoes","men-shoes","Pantoufles pour Homme",.95,["EXPLICIT_PRODUCT_TYPE:SLIPPERS","AUDIENCE:MEN"]);if(hasAll(/\b(vulcanized|vulcanised|vulcanization|vulcanisation)\b/))return leafResult("bags-shoes","men-shoes","Chaussure de vulcanisation",.95,["EXPLICIT_PRODUCT_TYPE:VULCANIZED_SHOES","AUDIENCE:MEN"]);if(hasAll(/\b(casual|leisure|everyday)\b/))return leafResult("bags-shoes","men-shoes","Chaussures décontractées",.92,["EXPLICIT_PRODUCT_TYPE:CASUAL_SHOES","AUDIENCE:MEN"]);return reviewResult(["EXPLICIT_PRODUCT_FAMILY:SHOES","AUDIENCE:MEN","SHOE_SUBTYPE_UNRESOLVED"],.56)}
if(shoes&&women){if(hasAll(/\b(high heel|high heels|heels|stiletto|stilettos)\b/))return leafResult("bags-shoes","women-shoes","Talons hauts",.96,["EXPLICIT_PRODUCT_TYPE:HIGH_HEELS","AUDIENCE:WOMEN"]);if(hasAll(/\b(boot|boots)\b/))return leafResult("bags-shoes","women-shoes","Bottes pour femme",.96,["EXPLICIT_PRODUCT_TYPE:BOOTS","AUDIENCE:WOMEN"]);if(hasAll(/\b(sandal|sandals)\b/))return leafResult("bags-shoes","women-shoes","Sandales pour femme",.96,["EXPLICIT_PRODUCT_TYPE:SANDALS","AUDIENCE:WOMEN"]);if(hasAll(/\b(slipper|slippers)\b/))return leafResult("bags-shoes","women-shoes","Chaussons pour femme",.95,["EXPLICIT_PRODUCT_TYPE:SLIPPERS","AUDIENCE:WOMEN"]);if(hasAll(/\b(flat|flats)\b/))return leafResult("bags-shoes","women-shoes","Chaussures plates",.94,["EXPLICIT_PRODUCT_TYPE:FLAT_SHOES","AUDIENCE:WOMEN"]);return reviewResult(["EXPLICIT_PRODUCT_FAMILY:SHOES","AUDIENCE:WOMEN","SHOE_SUBTYPE_UNRESOLVED"],.56)}
if(has(/\b(backpack|rucksack)\b/)&&men)return leafResult("bags-shoes","men-bags","Sacs à dos pour hommes",.96,["EXPLICIT_PRODUCT_TYPE:BACKPACK","AUDIENCE:MEN"]);if(has(/\b(handbag|hand bag|purse)\b/))return leafResult("bags-shoes","women-bags","Sac à main",.95,["EXPLICIT_PRODUCT_TYPE:HANDBAG"]);if(women&&has(/\bjeans?\b|\bdenim\b/))return leafResult("women","pants","Jeans pour femmes",.97,["EXPLICIT_PRODUCT_TYPE:JEANS","AUDIENCE:WOMEN"]);if(men&&has(/\bjeans?\b|\bdenim\b/))return leafResult("men","pants","Jeans pour hommes",.97,["EXPLICIT_PRODUCT_TYPE:JEANS","AUDIENCE:MEN"]);if(women&&has(/\bshorts\b/))return leafResult("women","pants","Short pour femmes",.96,["EXPLICIT_PRODUCT_TYPE:SHORTS","AUDIENCE:WOMEN"]);if(men&&has(/\bshorts\b/))return leafResult("men","pants","Short pour hommes",.96,["EXPLICIT_PRODUCT_TYPE:SHORTS","AUDIENCE:MEN"]);if(women&&has(/\b(dress|dresses)\b/))return leafResult("women","tops","Robes pour femmes",.96,["EXPLICIT_PRODUCT_TYPE:DRESS","AUDIENCE:WOMEN"]);return null}
const ALIASES:Record<string,readonly string[]>={"Talons hauts":["high heels","heel shoes","womens heels"],"Chargeurs":["charger","charging adapter"],"Câbles":["usb cable","charging cable"],"Écouteurs":["earbuds","headphones","earphones"],"Sacs à dos pour hommes":["mens backpack","men backpack","backpack"],"Sac à main":["handbag","purse"],"Robes pour femmes":["womens dress","women dress","dress"],"Montres numériques":["digital watch","smart watch","smartwatch"],"Montres à quartz":["quartz watch"],"Montres mécaniques":["mechanical watch"],"Chaussures de course":["running shoes","athletic shoes"],"Jeans pour femmes":["women jeans","womens denim"],"Jeans pour hommes":["men jeans","mens denim"]};
function aliasScore(s:Set<string>,label:string){const a=ALIASES[label]??[],hits=a.filter(x=>overlap(s,x)===1);return{score:hits.length?Math.max(...hits.map(x=>tokens(x).size>=2?1:.75)):0,hits}}
function boost(s:Set<string>){const o=new Set(s),has=(...v:string[])=>v.some(x=>s.has(x));if(has("watch","watches","smartwatch")){o.add("montre");o.add("montres")}if(has("backpack","handbag","purse","bag")){o.add("sac");o.add("sacs")}if(has("shoe","shoes","sneaker","sneakers","boot","boots","sandal","sandals")){o.add("chaussure");o.add("chaussures")}if(has("jean","jeans","denim")){o.add("jean");o.add("jeans")}if(has("men","mens","man","male")){o.add("homme");o.add("hommes")}if(has("women","womens","woman","female")){o.add("femme");o.add("femmes")}return o}
export function classifyCjProduct(s:SupplierProductSnapshot):CjClassification{const explicit=explicitClassification(s);if(explicit)return explicit;const hierarchy=metadataText(s),strong=boost(tokens(`${s.title} ${hierarchy}`)),broad=boost(tokens(`${s.title} ${s.description.slice(0,1200)} ${hierarchy}`)),candidates=DESKTOP_CATEGORY_TAXONOMY.flatMap(c=>c.groups.flatMap(g=>g.items.map(label=>{const sa=aliasScore(strong,label),ba=aliasScore(broad,label),ss=Math.max(overlap(strong,label),sa.score),sb=Math.max(overlap(broad,label),ba.score),cs=Math.max(overlap(strong,c.label),...c.legacyValues.map(v=>overlap(strong,v)),overlap(strong,g.label)),score=Math.min(1,ss*.55+sb*.2+cs*.25+(ss===1?.1:0));return{c,g,label,score,evidence:[...new Set([...sa.hits,...ba.hits])]}})));candidates.sort((a,b)=>b.score-a.score||a.label.localeCompare(b.label));const best=candidates[0],second=candidates[1];if(!best||best.score<.2)return{canonicalCategoryId:null,categoryId:null,categoryLabel:null,subcategoryLabel:null,confidence:0,status:"UNRESOLVED",evidence:["INSUFFICIENT_TAXONOMY_SIGNAL"]};const conflict=Boolean(second&&second.c.id!==best.c.id&&second.score>=best.score-.08&&second.score>=CJ_CLASSIFICATION_THRESHOLDS.accepted),confidence=Number(Math.max(0,Math.min(.74,best.score-(conflict?.2:0))).toFixed(2