import { subcategoryId } from "../desktop-category-taxonomy";

export type CjLivePathAlias={path:string;canonicalCategoryId:string};
export const CJ_LIVE_PATH_ALIASES:readonly CjLivePathAlias[]=[
  {path:"Automobiles & Motorcycles > Auto Replacement Parts > Automobiles Sensors",canonicalCategoryId:subcategoryId("auto","parts","Capteurs automobiles")},
  {path:"Automobiles & Motorcycles > Auto Replacement Parts > Car Brake System",canonicalCategoryId:subcategoryId("auto","parts","Système de freinage de voiture")},
  {path:"Automobiles & Motorcycles > Auto Replacement Parts > Exterior Parts",canonicalCategoryId:subcategoryId("auto","parts","Pièces extérieures")},
  {path:"Automobiles & Motorcycles > Auto Replacement Parts > Interior Parts",canonicalCategoryId:subcategoryId("auto","parts","Pièces intérieures")},
  {path:"Automobiles & Motorcycles > Auto Replacement Parts > Spark Plugs & Ignition System",canonicalCategoryId:subcategoryId("auto","parts","Bougies d'allumage et système d'allumage")},
  {path:"Automobiles & Motorcycles > Car Electronics > Car Mirror Video",canonicalCategoryId:subcategoryId("auto","electronics","Caméra de véhicule")},
  {path:"Automobiles & Motorcycles > Car Electronics > Car Monitors",canonicalCategoryId:subcategoryId("auto","electronics","Moniteurs de voiture")},
  {path:"Automobiles & Motorcycles > Car Electronics > Car Multimedia Player",canonicalCategoryId:subcategoryId("auto","electronics","Autoradios")},
  {path:"Automobiles & Motorcycles > Car Electronics > GPS Trackers",canonicalCategoryId:subcategoryId("auto","electronics","Trackers GPS")},
  {path:"Automobiles & Motorcycles > Car Electronics > Jump Starter",canonicalCategoryId:subcategoryId("auto","electronics","Jump Starters")},
  {path:"Automobiles & Motorcycles > Interior Accessories > Automobiles Seat Covers",canonicalCategoryId:subcategoryId("auto","interior","Housses de siège d'automobile")},
  {path:"Automobiles & Motorcycles > Interior Accessories > Car Aromatherapy",canonicalCategoryId:subcategoryId("auto","interior","Car Aromatherapy")},
  {path:"Automobiles & Motorcycles > Interior Accessories > Car Perfume",canonicalCategoryId:subcategoryId("auto","interior","Car Perfume")},
  {path:"Automobiles & Motorcycles > Interior Accessories > Floor Mats",canonicalCategoryId:subcategoryId("auto","interior","Floor Mats")},
  {path:"Automobiles & Motorcycles > Interior Accessories > Key Case for Car",canonicalCategoryId:subcategoryId("auto","interior","Porte-clés pour voiture")},
  {path:"Automobiles & Motorcycles > Interior Accessories > Steering Covers",canonicalCategoryId:subcategoryId("auto","interior","Housses de direction")},
  {path:"Automobiles & Motorcycles > Interior Accessories > Stowing Tidying",canonicalCategoryId:subcategoryId("auto","interior","Rangement")},
  {path:"Automobiles & Motorcycles > Motorcycle Accessories & Parts > Body & Frame",canonicalCategoryId:subcategoryId("auto","motorcycle","Corps et cadre")},
  {path:"Automobiles & Motorcycles > Motorcycle Accessories & Parts > Exhaust & Exhaust Systems",canonicalCategoryId:subcategoryId("auto","motorcycle","Échappement et systèmes d'échappement")},
  {path:"Automobiles & Motorcycles > Motorcycle Accessories & Parts > Helmet Headset",canonicalCategoryId:subcategoryId("auto","motorcycle","Casque")},
  {path:"Automobiles & Motorcycles > Motorcycle Accessories & Parts > Motor Brake System",canonicalCategoryId:subcategoryId("auto","motorcycle","Système de freinage moteur")},
  {path:"Automobiles & Motorcycles > Motorcycle Accessories & Parts > Motorcycle Seat Covers",canonicalCategoryId:subcategoryId("auto","motorcycle","Housses de siège de moto")},
  {path:"Bags & Shoes > Men's Luggage & Bags > Briefcases",canonicalCategoryId:subcategoryId("bags-shoes","men-bags","Porte-documents")},
  {path:"Bags & Shoes > Men's Luggage & Bags > Crossbody Bags",canonicalCategoryId:subcategoryId("bags-shoes","men-bags","Sacs bandoulière")},
  {path:"Bags & Shoes > Men's Luggage & Bags > Girls Bags",canonicalCategoryId:subcategoryId("bags-shoes","men-bags","Sacs pour fille")},
  {path:"Bags & Shoes > Men's Luggage & Bags > Luggage & Travel Bags",canonicalCategoryId:subcategoryId("bags-shoes","men-bags","Bagages et Sacs de Voyage")},
  {path:"Bags & Shoes > Men's Luggage & Bags > Man Wallets",canonicalCategoryId:subcategoryId("bags-shoes","men-bags","Portefeuilles pour Homme")},
  {path:"Bags & Shoes > Men's Luggage & Bags > Waist Bags",canonicalCategoryId:subcategoryId("bags-shoes","men-bags","Sacs à la taille")},
  {path:"Bags & Shoes > Men's Shoes > Casual Shoes",canonicalCategoryId:subcategoryId("bags-shoes","men-shoes","Chaussures décontractées")},
  {path:"Bags & Shoes > Men's Shoes > Man Slippers",canonicalCategoryId:subcategoryId("bags-shoes","men-shoes","Pantoufles pour Homme")},
  {path:"Bags & Shoes > Men's Shoes > Men's Insoles",canonicalCategoryId:subcategoryId("bags-shoes","men-shoes","Semelles pour hommes")},
  {path:"Bags & Shoes > Men's Shoes > Vulcanize Shoe",canonicalCategoryId:subcategoryId("bags-shoes","men-shoes","Chaussure de vulcanisation")},
  {path:"Bags & Shoes > Women's Luggage & Bags > Bag Accessories",canonicalCategoryId:subcategoryId("bags-shoes","women-bags","Accessoires de sac")},
  {path:"Bags & Shoes > Women's Luggage & Bags > Boys Bags",canonicalCategoryId:subcategoryId("bags-shoes","women-bags","Sacs pour garçons")},
  {path:"Bags & Shoes > Women's Luggage & Bags > Clutches",canonicalCategoryId:subcategoryId("bags-shoes","women-bags","Embrayages")},
  {path:"Bags & Shoes > Women's Luggage & Bags > Evening Bags",canonicalCategoryId:subcategoryId("bags-shoes","women-bags","Sacs de soirée")},
  {path:"Bags & Shoes > Women's Luggage & Bags > Fashion Backpacks",canonicalCategoryId:subcategoryId("bags-shoes","women-bags","Sacs à dos à la mode")},
  {path:"Bags & Shoes > Women's Luggage & Bags > Shoulder Bags",canonicalCategoryId:subcategoryId("bags-shoes","women-bags","Sacs à bandoulière")},
  {path:"Bags & Shoes > Women's Luggage & Bags > Woman Wallets",canonicalCategoryId:subcategoryId("bags-shoes","women-bags","Portefeuilles pour Femme")},
  {path:"Bags & Shoes > Women's Luggage & Bags > Women's Crossbody Bags",canonicalCategoryId:subcategoryId("bags-shoes","women-bags","Sacs à bandoulière pour femme")},
  {path:"Bags & Shoes > Women's Shoes > Flats",canonicalCategoryId:subcategoryId("bags-shoes","women-shoes","Chaussures plates")},
  {path:"Bags & Shoes > Women's Shoes > Vulcanize Shoes",canonicalCategoryId:subcategoryId("bags-shoes","women-shoes","Les chaussures Vulcanises")},
  {path:"Bags & Shoes > Women's Shoes > Woman Slippers",canonicalCategoryId:subcategoryId("bags-shoes","women-shoes","Chaussons pour femme")},
  {path:"Bags & Shoes > Women's Shoes > Women's Insoles",canonicalCategoryId:subcategoryId("bags-shoes","women-shoes","Semelles pour femmes")},
  {path:"Computer & Office > Laptop & Tablets > 2 in 1 Tablets",canonicalCategoryId:subcategoryId("computers","devices","Comprimés 2 en 1")},
  {path:"Computer & Office > Laptop & Tablets > Gaming Laptops",canonicalCategoryId:subcategoryId("computers","devices","Ordinateurs portables de jeu")},
  {path:"Computer & Office > Laptop & Tablets > Laptops",canonicalCategoryId:subcategoryId("computers","devices","Portables")},
  {path:"Computer & Office > Laptop & Tablets > Phone Call Tablets",canonicalCategoryId:subcategoryId("computers","devices","Tablettes d'appel téléphonique")},
  {path:"Computer & Office > Laptop & Tablets > Tablets",canonicalCategoryId:subcategoryId("computers","devices","Tablettes")},
  {path:"Computer & Office > Networking > 3G Modems",canonicalCategoryId:subcategoryId("computers","network","Modems 3G")},
  {path:"Computer & Office > Networking > Modem-Router Combos",canonicalCategoryId:subcategoryId("computers","network","Combos modem-routeur")},
  {path:"Computer & Office > Networking > Network Cards",canonicalCategoryId:subcategoryId("computers","network","Carte réseau")},
  {path:"Computer & Office > Networking > Networking Tools",canonicalCategoryId:subcategoryId("computers","network","Outils de réseautage")},
  {path:"Computer & Office > Networking > Wireless Routers",canonicalCategoryId:subcategoryId("computers","network","Routeurs sans fil")},
  {path:"Computer & Office > Office Electronics > 3D Pens",canonicalCategoryId:subcategoryId("computers","office","Stylos 3D")},
  {path:"Computer & Office > Office Electronics > 3D Printers",canonicalCategoryId:subcategoryId("computers","office","Imprimante 3D")},
  {path:"Computer & Office > Office Electronics > Office & School Supplies",canonicalCategoryId:subcategoryId("computers","office","Fournitures de bureau et scolaires")},
  {path:"Computer & Office > Office Electronics > Printer Supplies",canonicalCategoryId:subcategoryId("computers","office","Fournitures d'imprimante")},
  {path:"Computer & Office > Office Electronics > Printers",canonicalCategoryId:subcategoryId("computers","office","Imprimante")},
  {path:"Computer & Office > Office Electronics > Scanners",canonicalCategoryId:subcategoryId("computers","office","Scanner")},
  {path:"Computer & Office > Security & Protection > Alarm & Sensor",canonicalCategoryId:subcategoryId("computers","security","Alarme et Capteur")},
  {path:"Computer & Office > Security & Protection > Door Intercom",canonicalCategoryId:subcategoryId("computers","security","Interphone de porte")},
  {path:"Computer & Office > Security & Protection > Fire Protection",canonicalCategoryId:subcategoryId("computers","security","Protection incendie")},
  {path:"Computer & Office > Security & Protection > Surveillance Products",canonicalCategoryId:subcategoryId("computers","security","Produits de surveillance")},
  {path:"Computer & Office > Security & Protection > Workplace Safety Supplies",canonicalCategoryId:subcategoryId("computers","security","Fournitures de sécurité au travail")},
  {path:"Computer & Office > Storage Devices > External Hard Drives",canonicalCategoryId:subcategoryId("computers","storage","Disque dur externe")},
  {path:"Computer & Office > Storage Devices > HDD Enclosures",canonicalCategoryId:subcategoryId("computers","storage","Boîtiers de disque dur")},
  {path:"Computer & Office > Storage Devices > Memory Cards",canonicalCategoryId:subcategoryId("computers","storage","Cartes mémoire")},
  {path:"Computer & Office > Storage Devices > SSD",canonicalCategoryId:subcategoryId("computers","storage","SSD")},
  {path:"Computer & Office > Storage Devices > USB Flash Drives",canonicalCategoryId:subcategoryId("computers","storage","Clés USB à mémoire flash")},
  {path:"Computer & Office > Tablet & Laptop Accessories > Laptop Bags & Cases",canonicalCategoryId:subcategoryId("computers","tablet","Sacs et étuis pour ordinateur portable")},
  {path:"Computer & Office > Tablet & Laptop Accessories > Laptop Batteries",canonicalCategoryId:subcategoryId("computers","tablet","Batteries pour ordinateur portable")},
  {path:"Computer & Office > Tablet & Laptop Accessories > Tablet Accessories",canonicalCategoryId:subcategoryId("computers","tablet","Accessoires pour tablettes")},
  {path:"Computer & Office > Tablet & Laptop Accessories > Tablet Cases",canonicalCategoryId:subcategoryId("computers","tablet","Étuis pour tablette")},
  {path:"Computer & Office > Tablet & Laptop Accessories > Tablet LCD Screens",canonicalCategoryId:subcategoryId("computers","tablet","Écrans LCD pour tablettes")},
  {path:"Consumer Electronics > Camera & Photo > Action Cameras",canonicalCategoryId:subcategoryId("electronics","camera","Caméras d'action")},
  {path:"Consumer Electronics > Camera & Photo > Camcorders",canonicalCategoryId:subcategoryId("electronics","camera","Caméscopes")},
  {path:"Consumer Electronics > Camera & Photo > Camera & Photo Accessories",canonicalCategoryId:subcategoryId("electronics","camera","Accessoires pour Appareils photo et Photo")},
  {path:"Consumer Electronics > Camera & Photo > Camera Drones",canonicalCategoryId:subcategoryId("electronics","camera","Drones de caméra")},
  {path:"Consumer Electronics > Camera & Photo > Digital Cameras",canonicalCategoryId:subcategoryId("electronics","camera","Caméras digitales")},
  {path:"Consumer Electronics > Camera & Photo > Photo Studio",canonicalCategoryId:subcategoryId("electronics","camera","Studio de photographie")},
  {path:"Consumer Electronics > Home Audio & Video > Audio Amplifiers",canonicalCategoryId:subcategoryId("electronics","home-av","Amplificateurs audio")},
  {path:"Consumer Electronics > Home Audio & Video > Projectors",canonicalCategoryId:subcategoryId("electronics","home-av","Projecteurs")},
  {path:"Consumer Electronics > Home Audio & Video > Projectors & Acessories",canonicalCategoryId:subcategoryId("electronics","home-av","Projecteurs et accessoires")},
  {path:"Consumer Electronics > Home Audio & Video > Television",canonicalCategoryId:subcategoryId("electronics","home-av","Télévision")},
  {path:"Consumer Electronics > Home Audio & Video > TV Receivers",canonicalCategoryId:subcategoryId("electronics","home-av","Récepteurs TV")},
  {path:"Consumer Electronics > Portable Audio & Video > Earphones & Headphones",canonicalCategoryId:subcategoryId("electronics","portable-av","Écouteurs")},
  {path:"Consumer Electronics > Portable Audio & Video > Microphones",canonicalCategoryId:subcategoryId("electronics","portable-av","Microphones")},
  {path:"Consumer Electronics > Portable Audio & Video > MP3 Players",canonicalCategoryId:subcategoryId("electronics","portable-av","Lecteur MP3")},
  {path:"Consumer Electronics > Portable Audio & Video > Speakers",canonicalCategoryId:subcategoryId("electronics","portable-av","Haut-parleurs")},
  {path:"Consumer Electronics > Portable Audio & Video > VR & AR Devices",canonicalCategoryId:subcategoryId("electronics","portable-av","VR & AR Devices")},
  {path:"Consumer Electronics > Smart Electronics > Smart Home Appliances",canonicalCategoryId:subcategoryId("electronics","smart","Appareils électroménagers intelligents")},
  {path:"Consumer Electronics > Smart Electronics > Smart Remote Controls",canonicalCategoryId:subcategoryId("electronics","smart","Télécommandes intelligentes")},
  {path:"Consumer Electronics > Smart Electronics > Smart Watches",canonicalCategoryId:subcategoryId("electronics","smart","Montres")},
  {path:"Consumer Electronics > Smart Electronics > Smart Wearable Accessories",canonicalCategoryId:subcategoryId("electronics","smart","Accessoires portables")},
  {path:"Consumer Electronics > Smart Electronics > Smart Wristbands",canonicalCategoryId:subcategoryId("electronics","smart","Bracelets")},
  {path:"Consumer Electronics > Smart Electronics > Wearable Devices",canonicalCategoryId:subcategoryId("electronics","smart","Appareils portables")},
  {path:"Consumer Electronics > Video Games > Gamepads",canonicalCategoryId:subcategoryId("electronics","games","Manettes de jeu")},
  {path:"Consumer Electronics > Video Games > Handheld Game Players",canonicalCategoryId:subcategoryId("electronics","games","Joueurs de jeux portables")},
  {path:"Consumer Electronics > Video Games > Joysticks",canonicalCategoryId:subcategoryId("electronics","games","Joysticks")},
  {path:"Consumer Electronics > Video Games > Stickers",canonicalCategoryId:subcategoryId("electronics","games","Autocollants")},
  {path:"Consumer Electronics > Video Games > Video Game Consoles",canonicalCategoryId:subcategoryId("electronics","games","Consoles de jeu vidéo")},
  {path:"Health, Beauty & Hair > Beauty Tools > Curling Iron",canonicalCategoryId:subcategoryId("beauty","tools","Fer à friser")},
  {path:"Health, Beauty & Hair > Beauty Tools > Electric Face Cleanser",canonicalCategoryId:subcategoryId("beauty","tools","Nettoyant visage électrique")},
  {path:"Health, Beauty & Hair > Beauty Tools > Facial Steamer",canonicalCategoryId:subcategoryId("beauty","tools","Facial Steamer")},
  {path:"Health, Beauty & Hair > Beauty Tools > Mirrors",canonicalCategoryId:subcategoryId("beauty","tools","Miroirs")},
  {path:"Health, Beauty & Hair > Beauty Tools > Straightening Irons",canonicalCategoryId:subcategoryId("beauty","tools","Fers à lisser")},
  {path:"Health, Beauty & Hair > Hair & Accessories > Headband & Hair Band & Hairpin",canonicalCategoryId:subcategoryId("beauty","hair","Headband & Hair Band & Hairpin")},
  {path:"Health, Beauty & Hair > Hair & Accessories > Human Hair",canonicalCategoryId:subcategoryId("beauty","hair","Cheveux humains")},
  {path:"Health, Beauty & Hair > Makeup > Eyebrow Pencil",canonicalCategoryId:subcategoryId("beauty","makeup","Crayon à sourcils")},
  {path:"Health, Beauty & Hair > Makeup > Eyeshadow",canonicalCategoryId:subcategoryId("beauty","makeup","Le fard à paupières")},
  {path:"Health, Beauty & Hair > Makeup > False Eyelashes",canonicalCategoryId:subcategoryId("beauty","makeup","Faux cils")},
  {path:"Health, Beauty & Hair > Makeup > Lipstick",canonicalCategoryId:subcategoryId("beauty","makeup","Rouge à lèvres")},
  {path:"Health, Beauty & Hair > Makeup > Makeup Brushes",canonicalCategoryId:subcategoryId("beauty","makeup","Pinceaux à maquillage")},
  {path:"Health, Beauty & Hair > Makeup > Makeup Set",canonicalCategoryId:subcategoryId("beauty","makeup","Set de maquillage")},
  {path:"Health, Beauty & Hair > Nail Art & Tools > Nail Art Kits",canonicalCategoryId:subcategoryId("beauty","nails","Kit de manucure")},
  {path:"Health, Beauty & Hair > Nail Art & Tools > Nail Decorations",canonicalCategoryId:subcategoryId("beauty","nails","Décorations pour ongles")},
  {path:"Health, Beauty & Hair > Nail Art & Tools > Nail Dryers",canonicalCategoryId:subcategoryId("beauty","nails","Sèche-ongles")},
  {path:"Health, Beauty & Hair > Nail Art & Tools > Nail Gel",canonicalCategoryId:subcategoryId("beauty","nails","Gel pour les ongles")},
  {path:"Health, Beauty & Hair > Nail Art & Tools > Nail Glitters",canonicalCategoryId:subcategoryId("beauty","nails","Paillettes à ongles")},
  {path:"Health, Beauty & Hair > Nail Art & Tools > Stickers & Decals",canonicalCategoryId:subcategoryId("beauty","nails","Autocollants et décalcomanies")},
  {path:"Health, Beauty & Hair > Skin Care > Body Care",canonicalCategoryId:subcategoryId("beauty","skin","Soin du corps")},
  {path:"Health, Beauty & Hair > Skin Care > Essential Oil",canonicalCategoryId:subcategoryId("beauty","skin","Huile essentielle")},
  {path:"Health, Beauty & Hair > Skin Care > Face Masks",canonicalCategoryId:subcategoryId("beauty","skin","Masque")},
  {path:"Health, Beauty & Hair > Skin Care > Facial Care",canonicalCategoryId:subcategoryId("beauty","skin","Soins du visage")},
  {path:"Health, Beauty & Hair > Skin Care > Razor",canonicalCategoryId:subcategoryId("beauty","skin","Rasoir")},
  {path:"Health, Beauty & Hair > Skin Care > Sun Care",canonicalCategoryId:subcategoryId("beauty","skin","Protection solaire")},
  {path:"Health, Beauty & Hair > Wigs & Extensions > Hair Braids",canonicalCategoryId:subcategoryId("beauty","wigs","Tresses De Cheveux")},
  {path:"Health, Beauty & Hair > Wigs & Extensions > Human Hair Wigs",canonicalCategoryId:subcategoryId("beauty","wigs","Perruques de cheveux humains")},
  {path:"Health, Beauty & Hair > Wigs & Extensions > Synthetic Hair Pieces",canonicalCategoryId:subcategoryId("beauty","wigs","Morceaux de cheveux synthétiques")},
  {path:"Health, Beauty & Hair > Wigs & Extensions > Synthetic Lace Wigs",canonicalCategoryId:subcategoryId("beauty","wigs","Perruques en dentelle synthétique")},
  {path:"Health, Beauty & Hair > Wigs & Extensions > Synthetic Wigs",canonicalCategoryId:subcategoryId("beauty","wigs","Perruques synthétiques")},
  {path:"Home Improvement > Home Appliances > Air Conditioning Appliances",canonicalCategoryId:subcategoryId("improvement","appliances","Appareils de climatisation")},
  {path:"Home Improvement > Home Appliances > Cleaning Appliances",canonicalCategoryId:subcategoryId("improvement","appliances","Appareils de nettoyage")},
  {path:"Home Improvement > Home Appliances > Home Appliance Parts",canonicalCategoryId:subcategoryId("improvement","appliances","Pièces d'appareils ménagers")},
  {path:"Home Improvement > Home Appliances > Kitchen Appliances",canonicalCategoryId:subcategoryId("improvement","appliances","Appareils de cuisine")},
  {path:"Home Improvement > Home Appliances > Personal Care Appliances",canonicalCategoryId:subcategoryId("improvement","appliances","Appareils de soins personnels")},
  {path:"Home Improvement > Indoor Lighting > Ceiling Lights",canonicalCategoryId:subcategoryId("improvement","indoor","Plafonniers")},
  {path:"Home Improvement > Indoor Lighting > Chandeliers",canonicalCategoryId:subcategoryId("improvement","indoor","Lustres")},
  {path:"Home Improvement > Indoor Lighting > Downlights",canonicalCategoryId:subcategoryId("improvement","indoor","Downlight")},
  {path:"Home Improvement > Indoor Lighting > Night Lights",canonicalCategoryId:subcategoryId("improvement","indoor","Lumières de la nuit")},
  {path:"Home Improvement > Indoor Lighting > Pendant Lights",canonicalCategoryId:subcategoryId("improvement","indoor","Lampes suspendues")},
  {path:"Home Improvement > Indoor Lighting > Wall Lamps",canonicalCategoryId:subcategoryId("improvement","indoor","Appliques")},
  {path:"Home Improvement > Outdoor Lighting > Flashlights & Torches",canonicalCategoryId:subcategoryId("improvement","outdoor","Lampes de poche et torches")},
  {path:"Home Improvement > Outdoor Lighting > Floodlights",canonicalCategoryId:subcategoryId("improvement","outdoor","Projecteurs")},
  {path:"Home Improvement > Outdoor Lighting > Solar Lamps",canonicalCategoryId:subcategoryId("improvement","outdoor","Lampes solaires")},
  {path:"Home Improvement > Outdoor Lighting > String Lights",canonicalCategoryId:subcategoryId("improvement","outdoor","Guirlandes lumineuses")},
  {path:"Home Improvement > Outdoor Lighting > Underwater Lights",canonicalCategoryId:subcategoryId("improvement","outdoor","Underwater Lights")},
  {path:"Home Improvement > Tools > Garden Tools",canonicalCategoryId:subcategoryId("improvement","tools","Outils de jardin")},
  {path:"Home Improvement > Tools > Hand Tools",canonicalCategoryId:subcategoryId("improvement","tools","Outils manuels")},
  {path:"Home Improvement > Tools > Home Improvement Materials",canonicalCategoryId:subcategoryId("improvement","tools","Home Improvement Materials")},
  {path:"Home Improvement > Tools > Measurement & Analysis",canonicalCategoryId:subcategoryId("improvement","tools","Mesure et analyse")},
  {path:"Home Improvement > Tools > Power Tools",canonicalCategoryId:subcategoryId("improvement","tools","Outils électroportatifs")},
  {path:"Home Improvement > Tools > Tool Sets",canonicalCategoryId:subcategoryId("improvement","tools","Ensembles d'outils")},
  {path:"Home Improvement > Tools > Welding & Soldering Supplies",canonicalCategoryId:subcategoryId("improvement","tools","Fournitures de soudage et brasage")},
  {path:"Home, Garden & Furniture > Arts, Crafts & Sewing > Apparel Sewing & Fabric",canonicalCategoryId:subcategoryId("home","crafts","Couture et Tissu pour vêtements")},
  {path:"Home, Garden & Furniture > Arts, Crafts & Sewing > Cross-Stitch",canonicalCategoryId:subcategoryId("home","crafts","Point de croix")},
  {path:"Home, Garden & Furniture > Arts, Crafts & Sewing > Decor Paintings",canonicalCategoryId:subcategoryId("home","crafts","Tableaux Décoratifs")},
  {path:"Home, Garden & Furniture > Arts, Crafts & Sewing > Diamond Painting Cross Stitch",canonicalCategoryId:subcategoryId("home","crafts","Diamant peinture point de croix")},
  {path:"Home, Garden & Furniture > Arts, Crafts & Sewing > Fabric",canonicalCategoryId:subcategoryId("home","crafts","En tissu")},
  {path:"Home, Garden & Furniture > Arts, Crafts & Sewing > Lace",canonicalCategoryId:subcategoryId("home","crafts","Dentelle")},
  {path:"Home, Garden & Furniture > Arts, Crafts & Sewing > Ribbons",canonicalCategoryId:subcategoryId("home","crafts","Rubans")},
  {path:"Home, Garden & Furniture > Festive & Party Supplies > Cake Decorating Supplies",canonicalCategoryId:subcategoryId("home","party","Fournitures de décoration de gâteaux")},
  {path:"Home, Garden & Furniture > Festive & Party Supplies > Christmas Decoration Supplies",canonicalCategoryId:subcategoryId("home","party","Fournitures de décoration de Noël")},
  {path:"Home, Garden & Furniture > Festive & Party Supplies > Decorative Flowers & Wreaths",canonicalCategoryId:subcategoryId("home","party","Fleurs et Couronnes décoratives")},
  {path:"Home, Garden & Furniture > Festive & Party Supplies > Event & Party Supplies",canonicalCategoryId:subcategoryId("home","party","Fournitures pour événements et fêtes")},
  {path:"Home, Garden & Furniture > Festive & Party Supplies > Invitation Cards",canonicalCategoryId:subcategoryId("home","party","Cartes d'invitation")},
  {path:"Home, Garden & Furniture > Festive & Party Supplies > Party Masks",canonicalCategoryId:subcategoryId("home","party","Masques de fête")},
  {path:"Home, Garden & Furniture > Home Storage > Bathroom Storage",canonicalCategoryId:subcategoryId("home","storage","Rangement de salle de bain")},
  {path:"Home, Garden & Furniture > Home Storage > Clothing & Wardrobe Storage",canonicalCategoryId:subcategoryId("home","storage","Rangement pour vêtements et garde-robes")},
  {path:"Home, Garden & Furniture > Home Storage > Furniture",canonicalCategoryId:subcategoryId("home","storage","Meubles")},
  {path:"Home, Garden & Furniture > Home Storage > Home Office Storage",canonicalCategoryId:subcategoryId("home","storage","Stockage de bureau à domicile")},
  {path:"Home, Garden & Furniture > Home Storage > Kitchen Storage",canonicalCategoryId:subcategoryId("home","storage","Rangement de cuisine")},
  {path:"Home, Garden & Furniture > Home Storage > Stationeries",canonicalCategoryId:subcategoryId("home","storage","Papeterie")},
  {path:"Home, Garden & Furniture > Home Storage > Storage Bags & Cases & Boxes",canonicalCategoryId:subcategoryId("home","storage","Sacs de rangement, étuis et boîtes")},
  {path:"Home, Garden & Furniture > Home Textiles > Bedding Sets",canonicalCategoryId:subcategoryId("home","textiles","Ensembles de literie")},
  {path:"Home, Garden & Furniture > Home Textiles > Comforters",canonicalCategoryId:subcategoryId("home","textiles","Courtepointe")},
  {path:"Home, Garden & Furniture > Home Textiles > Curtains",canonicalCategoryId:subcategoryId("home","textiles","Rideaux")},
  {path:"Home, Garden & Furniture > Home Textiles > Cushion Covers",canonicalCategoryId:subcategoryId("home","textiles","Housses de coussin")},
  {path:"Home, Garden & Furniture > Home Textiles > Floor Mats",canonicalCategoryId:subcategoryId("home","textiles","Floor Mats")},
  {path:"Home, Garden & Furniture > Home Textiles > Pillows",canonicalCategoryId:subcategoryId("home","textiles","Oreillers")},
  {path:"Home, Garden & Furniture > Home Textiles > Towels",canonicalCategoryId:subcategoryId("home","textiles","Serviettes")},
  {path:"Home, Garden & Furniture > Kitchen, Dining & Bar > Bakeware",canonicalCategoryId:subcategoryId("home","kitchen","Ustensiles de cuisson")},
  {path:"Home, Garden & Furniture > Kitchen, Dining & Bar > Barware",canonicalCategoryId:subcategoryId("home","kitchen","Barware")},
  {path:"Home, Garden & Furniture > Kitchen, Dining & Bar > Cooking Tools",canonicalCategoryId:subcategoryId("home","kitchen","Outils de cuisson")},
  {path:"Home, Garden & Furniture > Kitchen, Dining & Bar > Dinnerware",canonicalCategoryId:subcategoryId("home","kitchen","Vaisselle")},
  {path:"Home, Garden & Furniture > Kitchen, Dining & Bar > Drinkware",canonicalCategoryId:subcategoryId("home","kitchen","Verres")},
  {path:"Home, Garden & Furniture > Kitchen, Dining & Bar > Kitchen Knives & Accessories",canonicalCategoryId:subcategoryId("home","kitchen","Couteaux de cuisine et accessoires")},
  {path:"Home, Garden & Furniture > Musical Instruments > Guitars",canonicalCategoryId:subcategoryId("home","music","Guitares")},
  {path:"Home, Garden & Furniture > Musical Instruments > Steel Tongue Drum",canonicalCategoryId:subcategoryId("home","music","Steel Tongue Drum")},
  {path:"Home, Garden & Furniture > Musical Instruments > Violins",canonicalCategoryId:subcategoryId("home","music","Violons")},
  {path:"Jewelry & Watches > Fashion Jewelry > Anklets",canonicalCategoryId:subcategoryId("jewelry","fashion","Anklets")},
  {path:"Jewelry & Watches > Fashion Jewelry > Body Jewelry",canonicalCategoryId:subcategoryId("jewelry","fashion","Bijoux de corps")},
  {path:"Jewelry & Watches > Fashion Jewelry > Bracelets & Bangles",canonicalCategoryId:subcategoryId("jewelry","fashion","Bracelets et Bracelets")},
  {path:"Jewelry & Watches > Fashion Jewelry > Brooches",canonicalCategoryId:subcategoryId("jewelry","fashion","Broche")},
  {path:"Jewelry & Watches > Fashion Jewelry > Charms",canonicalCategoryId:subcategoryId("jewelry","fashion","Charmes")},
  {path:"Jewelry & Watches > Fashion Jewelry > Earrings",canonicalCategoryId:subcategoryId("jewelry","fashion","Boucles d'oreilles")},
  {path:"Jewelry & Watches > Fashion Jewelry > Keychains",canonicalCategoryId:subcategoryId("jewelry","fashion","Porte-clés")},
  {path:"Jewelry & Watches > Fashion Jewelry > Necklace & Pendants",canonicalCategoryId:subcategoryId("jewelry","fashion","Collier et Pendentifs")},
  {path:"Jewelry & Watches > Fashion Jewelry > Rings",canonicalCategoryId:subcategoryId("jewelry","fashion","Anneaux")},
  {path:"Jewelry & Watches > Fine Jewelry > 925 Silver Jewelry",canonicalCategoryId:subcategoryId("jewelry","fine","Bijoux en argent 925")},
  {path:"Jewelry & Watches > Fine Jewelry > Fine Earrings",canonicalCategoryId:subcategoryId("jewelry","fine","Boucles d'oreilles fines")},
  {path:"Jewelry & Watches > Fine Jewelry > K-Gold",canonicalCategoryId:subcategoryId("jewelry","fine","K-Or")},
  {path:"Jewelry & Watches > Fine Jewelry > Men's Fine Jewelry",canonicalCategoryId:subcategoryId("jewelry","fine","Bijoux fins pour hommes")},
  {path:"Jewelry & Watches > Fine Jewelry > Pearls Jewelry",canonicalCategoryId:subcategoryId("jewelry","fine","Bijoux en perles")},
  {path:"Jewelry & Watches > Fine Jewelry > Various Gemstones",canonicalCategoryId:subcategoryId("jewelry","fine","Diverses pierres précieuses")},
  {path:"Jewelry & Watches > Men's Watches > Dual Display Watches",canonicalCategoryId:subcategoryId("jewelry","men-watches","Montres à double affichage")},
  {path:"Jewelry & Watches > Wedding & Engagement > Bridal Jewelry Sets",canonicalCategoryId:subcategoryId("jewelry","wedding","Ensembles de bijoux de mariée")},
  {path:"Jewelry & Watches > Wedding & Engagement > Engagement Rings",canonicalCategoryId:subcategoryId("jewelry","wedding","Bagues de fiançailles")},
  {path:"Jewelry & Watches > Wedding & Engagement > Wedding Hair Jewelry",canonicalCategoryId:subcategoryId("jewelry","wedding","Bijoux de cheveux de mariage")},
  {path:"Jewelry & Watches > Women's Watches > Children's Watches",canonicalCategoryId:subcategoryId("jewelry","women-watches","Montres pour enfants")},
  {path:"Jewelry & Watches > Women's Watches > Creative Watches",canonicalCategoryId:subcategoryId("jewelry","women-watches","Montres créatives")},
  {path:"Jewelry & Watches > Women's Watches > Dress Watches",canonicalCategoryId:subcategoryId("jewelry","women-watches","Montres habillées")},
  {path:"Jewelry & Watches > Women's Watches > Lovers' Watches",canonicalCategoryId:subcategoryId("jewelry","women-watches","Montres d'amoureux")},
  {path:"Jewelry & Watches > Women's Watches > Watch Accessories",canonicalCategoryId:subcategoryId("jewelry","women-watches","Watch Accessories")},
  {path:"Jewelry & Watches > Women's Watches > Women's Bracelet Watches",canonicalCategoryId:subcategoryId("jewelry","women-watches","Montres-bracelets pour femmes")},
  {path:"Men's Clothing > Accessories > Belts",canonicalCategoryId:subcategoryId("men","accessories","Ceintures")},
  {path:"Men's Clothing > Accessories > Man Gloves & Mittens",canonicalCategoryId:subcategoryId("men","accessories","Gants et Mitaines homme")},
  {path:"Men's Clothing > Accessories > Men's Ties",canonicalCategoryId:subcategoryId("men","accessories","Cravates pour hommes")},
  {path:"Men's Clothing > Accessories > Scarves",canonicalCategoryId:subcategoryId("men","accessories","Écharpes")},
  {path:"Men's Clothing > Accessories > Skullies & Beanies",canonicalCategoryId:subcategoryId("men","accessories","Skullies & Bonnets")},
  {path:"Men's Clothing > Accessories > Socks",canonicalCategoryId:subcategoryId("men","accessories","Chaussettes")},
  {path:"Men's Clothing > Bottoms > Cargo Pants",canonicalCategoryId:subcategoryId("men","pants","Pantalon cargo")},
  {path:"Men's Clothing > Bottoms > Casual Pants",canonicalCategoryId:subcategoryId("men","pants","Pantalons décontractés")},
  {path:"Men's Clothing > Bottoms > Harem Pants",canonicalCategoryId:subcategoryId("men","pants","Sarouel")},
  {path:"Men's Clothing > Bottoms > Man Jeans",canonicalCategoryId:subcategoryId("men","pants","Jeans pour hommes")},
  {path:"Men's Clothing > Bottoms > Man Shorts",canonicalCategoryId:subcategoryId("men","pants","Short pour hommes")},
  {path:"Men's Clothing > Bottoms > Pajama Sets",canonicalCategoryId:subcategoryId("men","pants","Ensembles de pyjama")},
  {path:"Men's Clothing > Bottoms > Sweatpants",canonicalCategoryId:subcategoryId("men","pants","Les pantalons de survêtement")},
  {path:"Men's Clothing > Hats & Caps > Baseball Caps",canonicalCategoryId:subcategoryId("men","hats","Casquettes de baseball")},
  {path:"Men's Clothing > Hats & Caps > Berets",canonicalCategoryId:subcategoryId("men","hats","Bérets")},
  {path:"Men's Clothing > Hats & Caps > Bomber Hats",canonicalCategoryId:subcategoryId("men","hats","Chapeaux Bomber")},
  {path:"Men's Clothing > Hats & Caps > Fedoras",canonicalCategoryId:subcategoryId("men","hats","Feutre")},
  {path:"Men's Clothing > Outerwear & Jackets > Genuine Leather",canonicalCategoryId:subcategoryId("men","outerwear","Cuir véritable")},
  {path:"Men's Clothing > Outerwear & Jackets > Man Hoodies & Sweatshirts",canonicalCategoryId:subcategoryId("men","outerwear","Sweats à capuche et Sweat-shirts pour hommes")},
  {path:"Men's Clothing > Outerwear & Jackets > Man Trench",canonicalCategoryId:subcategoryId("men","outerwear","Trench pour hommes")},
  {path:"Men's Clothing > Outerwear & Jackets > Men's Jackets",canonicalCategoryId:subcategoryId("men","outerwear","Vestes pour hommes")},
  {path:"Men's Clothing > Outerwear & Jackets > Men's Shirts",canonicalCategoryId:subcategoryId("men","outerwear","Chemises pour hommes")},
  {path:"Men's Clothing > Outerwear & Jackets > Men's Suits",canonicalCategoryId:subcategoryId("men","outerwear","Costumes pour hommes")},
  {path:"Men's Clothing > Outerwear & Jackets > Men's Sweaters",canonicalCategoryId:subcategoryId("men","outerwear","Pull masculin")},
  {path:"Men's Clothing > Outerwear & Jackets > Parkas",canonicalCategoryId:subcategoryId("men","outerwear","Parkas")},
  {path:"Men's Clothing > Outerwear & Jackets > Suits & Blazer",canonicalCategoryId:subcategoryId("men","outerwear","Costumes & Blazer")},
  {path:"Men's Clothing > Outerwear & Jackets > Wool & Blends",canonicalCategoryId:subcategoryId("men","outerwear","Laine et Mélanges")},
  {path:"Men's Clothing > T-Shirts > 3D",canonicalCategoryId:subcategoryId("men","tshirts","3D")},
  {path:"Men's Clothing > T-Shirts > Geometric",canonicalCategoryId:subcategoryId("men","tshirts","Géométrique")},
  {path:"Men's Clothing > T-Shirts > Men's Long-Sleeved",canonicalCategoryId:subcategoryId("men","tshirts","T-shirts à manches longues pour hommes")},
  {path:"Men's Clothing > T-Shirts > Print",canonicalCategoryId:subcategoryId("men","tshirts","Impression")},
  {path:"Men's Clothing > T-Shirts > Solid",canonicalCategoryId:subcategoryId("men","tshirts","Solide")},
  {path:"Men's Clothing > T-Shirts > Striped",canonicalCategoryId:subcategoryId("men","tshirts","Rayé")},
  {path:"Men's Clothing > Underwear & Loungewear > Boxers",canonicalCategoryId:subcategoryId("men","underwear","Boxeurs")},
  {path:"Men's Clothing > Underwear & Loungewear > Briefs",canonicalCategoryId:subcategoryId("men","underwear","Slips")},
  {path:"Men's Clothing > Underwear & Loungewear > Long Johns",canonicalCategoryId:subcategoryId("men","underwear","Caleçon")},
  {path:"Men's Clothing > Underwear & Loungewear > Man Pajama Sets",canonicalCategoryId:subcategoryId("men","underwear","Ensembles de pyjama pour hommes")},
  {path:"Men's Clothing > Underwear & Loungewear > Men's Sleep & Lounge",canonicalCategoryId:subcategoryId("men","underwear","Sleep & Lounge pour hommes")},
  {path:"Men's Clothing > Underwear & Loungewear > Robes",canonicalCategoryId:subcategoryId("men","underwear","Peignoirs")},
  {path:"Men's Clothing > Underwear & Loungewear > Shorts",canonicalCategoryId:subcategoryId("men","underwear","Short")},
  {path:"Pet Supplies > Fish & Aquatic Pets > Fish Tank Cleaning Supplies",canonicalCategoryId:subcategoryId("pets","aquatic","Fournitures de nettoyage pour aquariums")},
  {path:"Pet Supplies > Fish & Aquatic Pets > Fish Tank Decorations",canonicalCategoryId:subcategoryId("pets","aquatic","Décorations pour aquariums")},
  {path:"Pet Supplies > Fish & Aquatic Pets > Fish Tanks",canonicalCategoryId:subcategoryId("pets","aquatic","Aquariums")},
  {path:"Pet Supplies > Pet Apparels > Pet Clothings",canonicalCategoryId:subcategoryId("pets","clothes","Hauts")},
  {path:"Pet Supplies > Pet Apparels > Pet Coats & Jackets",canonicalCategoryId:subcategoryId("pets","clothes","Manteaux et vestes")},
  {path:"Pet Supplies > Pet Apparels > Pet Dresses",canonicalCategoryId:subcategoryId("pets","clothes","Robes")},
  {path:"Pet Supplies > Pet Apparels > Pet Pajamas",canonicalCategoryId:subcategoryId("pets","clothes","Pyjamas")},
  {path:"Pet Supplies > Pet Apparels > Pet Shoes & Socks",canonicalCategoryId:subcategoryId("pets","clothes","Chaussures & Chaussettes")},
  {path:"Pet Supplies > Pet Apparels > Pet Sweaters",canonicalCategoryId:subcategoryId("pets","clothes","Chandails")},
  {path:"Pet Supplies > Pet Apparels > Pet Tops",canonicalCategoryId:subcategoryId("pets","clothes","Hauts")},
  {path:"Pet Supplies > Pet Bedding > Pet Beds",canonicalCategoryId:subcategoryId("pets","bedding","Lits")},
  {path:"Pet Supplies > Pet Bedding > Pet Blankets & Quilts",canonicalCategoryId:subcategoryId("pets","bedding","Couvertures et couettes")},
  {path:"Pet Supplies > Pet Bedding > Pet Mats",canonicalCategoryId:subcategoryId("pets","bedding","Tapis")},
  {path:"Pet Supplies > Pet Bedding > Pet Nests",canonicalCategoryId:subcategoryId("pets","bedding","Nids")},
  {path:"Pet Supplies > Pet Collars, Harnesses & Accessories > Pet Collars",canonicalCategoryId:subcategoryId("pets","collars","Colliers pour animaux de compagnie")},
  {path:"Pet Supplies > Pet Collars, Harnesses & Accessories > Pet Glasses",canonicalCategoryId:subcategoryId("pets","collars","Lunettes pour animaux de compagnie")},
  {path:"Pet Supplies > Pet Collars, Harnesses & Accessories > Pet Harnesses",canonicalCategoryId:subcategoryId("pets","collars","Harnais pour animaux de compagnie")},
  {path:"Pet Supplies > Pet Collars, Harnesses & Accessories > Pet Leashes",canonicalCategoryId:subcategoryId("pets","collars","Laisses pour animaux de compagnie")},
  {path:"Pet Supplies > Pet Collars, Harnesses & Accessories > Pet Muzzles",canonicalCategoryId:subcategoryId("pets","collars","Muselières pour animaux de compagnie")},
  {path:"Pet Supplies > Pet Drinking & Feeding > Pet Bowls",canonicalCategoryId:subcategoryId("pets","care","Gamelles")},
  {path:"Pet Supplies > Pet Drinking & Feeding > Pet Drinking Tools",canonicalCategoryId:subcategoryId("pets","care","Outils pour boire")},
  {path:"Pet Supplies > Pet Drinking & Feeding > Pet Feeding Tools",canonicalCategoryId:subcategoryId("pets","care","Outils d'alimentation")},
  {path:"Pet Supplies > Pet Furnitures > Cat Scratching Posts",canonicalCategoryId:subcategoryId("pets","furniture","Griffoirs pour chats")},
  {path:"Pet Supplies > Pet Furnitures > Cat Trees & Condos",canonicalCategoryId:subcategoryId("pets","furniture","Arbres et condos pour chats")},
  {path:"Pet Supplies > Pet Furnitures > Dog Stairs & Steps",canonicalCategoryId:subcategoryId("pets","furniture","Escaliers et marches pour chiens")},
  {path:"Pet Supplies > Pet Furnitures > Pet Furniture Protectors",canonicalCategoryId:subcategoryId("pets","furniture","Protecteurs de meubles pour animaux de compagnie")},
  {path:"Pet Supplies > Pet Furnitures > Pet Hammocks",canonicalCategoryId:subcategoryId("pets","furniture","Hamacs pour animaux de compagnie")},
  {path:"Pet Supplies > Pet Furnitures > Pet Houses & Cages",canonicalCategoryId:subcategoryId("pets","furniture","Maisons et cages pour animaux de compagnie")},
  {path:"Pet Supplies > Pet Furnitures > Pet Tents",canonicalCategoryId:subcategoryId("pets","furniture","Tentes pour animaux de compagnie")},
  {path:"Pet Supplies > Pet Groomings > Pet Hair Removers & Combs",canonicalCategoryId:subcategoryId("pets","care","Épilateurs et peignes")},
  {path:"Pet Supplies > Pet Groomings > Pet Shower Products",canonicalCategoryId:subcategoryId("pets","care","Produits de douche")},
  {path:"Pet Supplies > Pet Groomings > Pet Towels",canonicalCategoryId:subcategoryId("pets","care","Serviettes")},
  {path:"Pet Supplies > Pet Outdoor Supplies > Barking Control Equipments",canonicalCategoryId:subcategoryId("pets","outdoor","Équipements de contrôle des aboiements")},
  {path:"Pet Supplies > Pet Outdoor Supplies > Dog Training Pads & Diapers",canonicalCategoryId:subcategoryId("pets","outdoor","Coussins et couches de dressage pour chiens")},
  {path:"Pet Supplies > Pet Outdoor Supplies > Pet Bags",canonicalCategoryId:subcategoryId("pets","outdoor","Sacs pour animaux de compagnie")},
  {path:"Pet Supplies > Pet Outdoor Supplies > Pet Car Mats",canonicalCategoryId:subcategoryId("pets","outdoor","Tapis de voiture pour animaux de compagnie")},
  {path:"Pet Supplies > Pet Outdoor Supplies > Pet Guardrails",canonicalCategoryId:subcategoryId("pets","outdoor","Barrières de sécurité pour animaux de compagnie")},
  {path:"Pet Supplies > Pet Outdoor Supplies > Pet Seat Belts",canonicalCategoryId:subcategoryId("pets","outdoor","Ceintures de sécurité pour animaux de compagnie")},
  {path:"Pet Supplies > Pet Outdoor Supplies > Pet Snacks",canonicalCategoryId:subcategoryId("pets","outdoor","Snacks pour animaux de compagnie")},
  {path:"Pet Supplies > Pet Outdoor Supplies > Trainers",canonicalCategoryId:subcategoryId("pets","outdoor","Trainers")},
  {path:"Pet Supplies > Pet Toys > Pet Chase Toys",canonicalCategoryId:subcategoryId("pets","toys","Jouets de chasse")},
  {path:"Pet Supplies > Pet Toys > Pet Chew Toys",canonicalCategoryId:subcategoryId("pets","toys","Jouets à mâcher")},
  {path:"Pet Supplies > Pet Toys > Pet Plush Toys",canonicalCategoryId:subcategoryId("pets","toys","Jouets en peluche")},
  {path:"Pet Supplies > Pet Toys > Pet Sound Toys",canonicalCategoryId:subcategoryId("pets","toys","Jouets sonores")},
  {path:"Pet Supplies > Pet Toys > Pet Training and Educational Toys",canonicalCategoryId:subcategoryId("pets","toys","Jouets éducatifs et de dressage")},
  {path:"Pet Supplies > Pet Toys > Pet Tunnel Toys",canonicalCategoryId:subcategoryId("pets","toys","Jouets tunnel")},
  {path:"Phones & Accessories > Cases & Covers > Flip Cases",canonicalCategoryId:subcategoryId("phones","cases","Étuis à rabat")},
  {path:"Phones & Accessories > Cases & Covers > Huawei Cases",canonicalCategoryId:subcategoryId("phones","cases","Étuis Huawei")},
  {path:"Phones & Accessories > Cases & Covers > IPhone X Cases",canonicalCategoryId:subcategoryId("phones","cases","Étuis iPhone X")},
  {path:"Phones & Accessories > Cases & Covers > Leather Cases",canonicalCategoryId:subcategoryId("phones","cases","Étuis en cuir")},
  {path:"Phones & Accessories > Cases & Covers > Patterned Cases",canonicalCategoryId:subcategoryId("phones","cases","Étuis à motifs")},
  {path:"Phones & Accessories > Cases & Covers > Silicone Cases",canonicalCategoryId:subcategoryId("phones","cases","Étuis en silicone")},
  {path:"Phones & Accessories > Cases & Covers > Wallet Cases",canonicalCategoryId:subcategoryId("phones","cases","Étuis portefeuille")},
  {path:"Phones & Accessories > Cases & Covers > Waterptoof Cases",canonicalCategoryId:subcategoryId("phones","cases","Boîtiers étanches")},
  {path:"Phones & Accessories > Cases & Covers > Xiaomi Cases",canonicalCategoryId:subcategoryId("phones","cases","Étuis Xiaomi")},
  {path:"Phones & Accessories > Mobile Phone Accessories > Cables",canonicalCategoryId:subcategoryId("phones","accessories","Câbles")},
  {path:"Phones & Accessories > Mobile Phone Accessories > Chargers",canonicalCategoryId:subcategoryId("phones","accessories","Chargeurs")},
  {path:"Phones & Accessories > Mobile Phone Accessories > Holders & Stands",canonicalCategoryId:subcategoryId("phones","accessories","Supports")},
  {path:"Phones & Accessories > Mobile Phone Accessories > Lenses",canonicalCategoryId:subcategoryId("phones","accessories","Verres")},
  {path:"Phones & Accessories > Mobile Phone Accessories > Power Bank",canonicalCategoryId:subcategoryId("phones","accessories","Banque de puissance")},
  {path:"Phones & Accessories > Mobile Phone Accessories > Screen Protectors",canonicalCategoryId:subcategoryId("phones","accessories","Protecteurs d'écran")},
  {path:"Phones & Accessories > Mobile Phone Parts > Flex Cables",canonicalCategoryId:subcategoryId("phones","parts","Câbles flexibles")},
  {path:"Phones & Accessories > Mobile Phone Parts > Housings",canonicalCategoryId:subcategoryId("phones","parts","Boîtiers")},
  {path:"Phones & Accessories > Mobile Phone Parts > LCDs",canonicalCategoryId:subcategoryId("phones","parts","LCD")},
  {path:"Phones & Accessories > Mobile Phone Parts > Mobile Batteries",canonicalCategoryId:subcategoryId("phones","parts","Batteries mobiles")},
  {path:"Phones & Accessories > Mobile Phone Parts > SIM Card & Tools",canonicalCategoryId:subcategoryId("phones","parts","SIM Card & Tools")},
  {path:"Phones & Accessories > Mobile Phone Parts > Touch Panel",canonicalCategoryId:subcategoryId("phones","parts","Ecran tactile")},
  {path:"Phones & Accessories > Mobile Phones > 3GB RAM",canonicalCategoryId:subcategoryId("phones","phones","3 Go de RAM")},
  {path:"Phones & Accessories > Mobile Phones > 5-inch Display",canonicalCategoryId:subcategoryId("phones","phones","Écran de 5 pouces")},
  {path:"Phones & Accessories > Mobile Phones > Dual SIM Card",canonicalCategoryId:subcategoryId("phones","phones","Double carte SIM")},
  {path:"Phones & Accessories > Mobile Phones > Octa Core",canonicalCategoryId:subcategoryId("phones","phones","Octa Core")},
  {path:"Phones & Accessories > Mobile Phones > Quad Core",canonicalCategoryId:subcategoryId("phones","phones","Quad-core")},
  {path:"Phones & Accessories > Mobile Phones > Single SIM Card",canonicalCategoryId:subcategoryId("phones","phones","Une seule Carte SIM")},
  {path:"Sports & Outdoors > Cycling > Bicycle Helmets",canonicalCategoryId:subcategoryId("sports","cycling","Casques de vélo")},
  {path:"Sports & Outdoors > Cycling > Bicycle Lights",canonicalCategoryId:subcategoryId("sports","cycling","Lumières de vélo")},
  {path:"Sports & Outdoors > Cycling > Bicycles",canonicalCategoryId:subcategoryId("sports","cycling","Vélos")},
  {path:"Sports & Outdoors > Cycling > Cycling Gloves",canonicalCategoryId:subcategoryId("sports","cycling","Gants de cyclisme")},
  {path:"Sports & Outdoors > Cycling > Cycling Jerseys",canonicalCategoryId:subcategoryId("sports","cycling","Maillots de cyclisme")},
  {path:"Sports & Outdoors > Cycling > Scooters",canonicalCategoryId:subcategoryId("sports","cycling","Trottinettes")},
  {path:"Sports & Outdoors > Fishing > Fishing Lines",canonicalCategoryId:subcategoryId("sports","fishing","Lignes de pêche")},
  {path:"Sports & Outdoors > Fishing > Fishing Lures",canonicalCategoryId:subcategoryId("sports","fishing","Leurres de pêche")},
  {path:"Sports & Outdoors > Fishing > Fishing Reels",canonicalCategoryId:subcategoryId("sports","fishing","Moulinets de pêche")},
  {path:"Sports & Outdoors > Fishing > Fishing Rods",canonicalCategoryId:subcategoryId("sports","fishing","Cannes à pêche")},
  {path:"Sports & Outdoors > Fishing > Fishing Tackle Boxes",canonicalCategoryId:subcategoryId("sports","fishing","Boîtes de pêche")},
  {path:"Sports & Outdoors > Fishing > Rod Combos",canonicalCategoryId:subcategoryId("sports","fishing","Rod Combos")},
  {path:"Sports & Outdoors > Other Sports Equipment > Camping & Hiking",canonicalCategoryId:subcategoryId("sports","equipment","Camping et randonnée")},
  {path:"Sports & Outdoors > Other Sports Equipment > Fitness & Bodybuilding",canonicalCategoryId:subcategoryId("sports","equipment","Fitness et musculation")},
  {path:"Sports & Outdoors > Other Sports Equipment > Golf",canonicalCategoryId:subcategoryId("sports","equipment","Golf")},
  {path:"Sports & Outdoors > Other Sports Equipment > Hunting",canonicalCategoryId:subcategoryId("sports","equipment","Chasse")},
  {path:"Sports & Outdoors > Other Sports Equipment > Skiing & Snowboarding",canonicalCategoryId:subcategoryId("sports","equipment","Ski et Snowboard")},
  {path:"Sports & Outdoors > Sneakers > Basketball Shoes",canonicalCategoryId:subcategoryId("sports","shoes","Chaussure de basket-ball")},
  {path:"Sports & Outdoors > Sneakers > Dance Shoes",canonicalCategoryId:subcategoryId("sports","shoes","Chaussures de danse")},
  {path:"Sports & Outdoors > Sneakers > Hiking Shoes",canonicalCategoryId:subcategoryId("sports","shoes","Chaussures de randonnée")},
  {path:"Sports & Outdoors > Sneakers > Running Shoes",canonicalCategoryId:subcategoryId("sports","shoes","Chaussures de course")},
  {path:"Sports & Outdoors > Sneakers > Skateboarding Shoes",canonicalCategoryId:subcategoryId("sports","shoes","Chaussures de skateboard")},
  {path:"Sports & Outdoors > Sneakers > Soccer Shoes",canonicalCategoryId:subcategoryId("sports","shoes","Chaussures de foot")},
  {path:"Sports & Outdoors > Swimming > Bikini Sets",canonicalCategoryId:subcategoryId("sports","swim","Ensembles de bikini")},
  {path:"Sports & Outdoors > Swimming > Children's Swimwear",canonicalCategoryId:subcategoryId("sports","swim","Maillots de bain pour enfants")},
  {path:"Sports & Outdoors > Swimming > Men's Swimwear",canonicalCategoryId:subcategoryId("sports","swim","Maillots de bain pour hommes")},
  {path:"Sports & Outdoors > Swimming > One-Piece Suits",canonicalCategoryId:subcategoryId("sports","swim","Costumes une pièce")},
  {path:"Sports & Outdoors > Swimming > Swimming Goggles",canonicalCategoryId:subcategoryId("sports","swim","Swimming Goggles")},
  {path:"Toys, Kids & Babies > Baby & Mother > Activity & Gear",canonicalCategoryId:subcategoryId("kids","mother","Activité et Equipment")},
  {path:"Toys, Kids & Babies > Baby & Mother > Baby Care",canonicalCategoryId:subcategoryId("kids","mother","Soins bébé")},
  {path:"Toys, Kids & Babies > Baby & Mother > Backpacks & Carriers",canonicalCategoryId:subcategoryId("kids","mother","Sacs à dos et Porte-bagages")},
  {path:"Toys, Kids & Babies > Baby & Mother > Maternity",canonicalCategoryId:subcategoryId("kids","mother","Maternité")},
  {path:"Toys, Kids & Babies > Baby & Mother > Nappy Changing",canonicalCategoryId:subcategoryId("kids","mother","Changement de couche")},
  {path:"Toys, Kids & Babies > Baby Clothing > Baby Accessories",canonicalCategoryId:subcategoryId("kids","baby","Accessoires bébé")},
  {path:"Toys, Kids & Babies > Baby Clothing > Baby Dresses",canonicalCategoryId:subcategoryId("kids","baby","Robes de bébé")},
  {path:"Toys, Kids & Babies > Baby Clothing > Baby Pants",canonicalCategoryId:subcategoryId("kids","baby","Pantalon de bébé")},
  {path:"Toys, Kids & Babies > Boys Clothing > Boy Clothing Sets",canonicalCategoryId:subcategoryId("kids","boys","Ensembles de vêtements pour garçon")},
  {path:"Toys, Kids & Babies > Boys Clothing > Boy Hoodies & Sweatshirts",canonicalCategoryId:subcategoryId("kids","boys","Sweats à capuche et Sweat-shirts pour garçon")},
  {path:"Toys, Kids & Babies > Boys Clothing > Boy Jeans",canonicalCategoryId:subcategoryId("kids","boys","Jeans pour garçon")},
  {path:"Toys, Kids & Babies > Boys Clothing > Boy T-Shirts",canonicalCategoryId:subcategoryId("kids","boys","T-shirts pour garçon")},
  {path:"Toys, Kids & Babies > Boys Clothing > Outerwear & Coats",canonicalCategoryId:subcategoryId("kids","boys","Vêtements d'extérieur et Manteaux")},
  {path:"Toys, Kids & Babies > Girls Clothing > Girl Clothing Sets",canonicalCategoryId:subcategoryId("kids","girls","Ensembles de vêtements pour fille")},
  {path:"Toys, Kids & Babies > Girls Clothing > Girl Dresses",canonicalCategoryId:subcategoryId("kids","girls","Robes de Fille")},
  {path:"Toys, Kids & Babies > Girls Clothing > Girls Underwear",canonicalCategoryId:subcategoryId("kids","girls","Sous-vêtements fille")},
  {path:"Toys, Kids & Babies > Girls Clothing > Girls' Pants",canonicalCategoryId:subcategoryId("kids","girls","Girls' Pants")},
  {path:"Toys, Kids & Babies > Girls Clothing > Tops & Tees",canonicalCategoryId:subcategoryId("kids","girls","Hauts et T-shirts")},
  {path:"Toys, Kids & Babies > Shoes & Bags > Boys Shoes",canonicalCategoryId:subcategoryId("kids","shoes","Chaussures de bébé garçons")},
  {path:"Toys, Kids & Babies > Shoes & Bags > Children's Shoes",canonicalCategoryId:subcategoryId("kids","shoes","Chaussures pour enfants")},
  {path:"Toys, Kids & Babies > Shoes & Bags > Girls Shoes",canonicalCategoryId:subcategoryId("kids","shoes","Chaussures pour fille")},
  {path:"Toys, Kids & Babies > Shoes & Bags > Kids Wallets",canonicalCategoryId:subcategoryId("kids","shoes","Portefeuilles pour enfants")},
  {path:"Toys, Kids & Babies > Shoes & Bags > School Bags",canonicalCategoryId:subcategoryId("kids","shoes","Sacs d'école")},
  {path:"Toys, Kids & Babies > Toys & Hobbies > Action & Toy Figures",canonicalCategoryId:subcategoryId("kids","toys","Figurines d'action et de jouets")},
  {path:"Toys, Kids & Babies > Toys & Hobbies > Blocks",canonicalCategoryId:subcategoryId("kids","toys","Blocs")},
  {path:"Toys, Kids & Babies > Toys & Hobbies > Electronic Pets",canonicalCategoryId:subcategoryId("kids","toys","Animaux électroniques")},
  {path:"Toys, Kids & Babies > Toys & Hobbies > RC Helicopters",canonicalCategoryId:subcategoryId("kids","toys","Hélicoptères RC")},
  {path:"Toys, Kids & Babies > Toys & Hobbies > Stuffed & Plush Animals",canonicalCategoryId:subcategoryId("kids","toys","Animaux en peluche")},
  {path:"Women's Clothing > Accessories > Belts & Cummerbunds",canonicalCategoryId:subcategoryId("women","accessories","Ceintures")},
  {path:"Women's Clothing > Accessories > Face Masks",canonicalCategoryId:subcategoryId("women","accessories","Masque")},
  {path:"Women's Clothing > Accessories > Scarves & Wraps",canonicalCategoryId:subcategoryId("women","accessories","Écharpes et Foulards")},
  {path:"Women's Clothing > Accessories > Woman Gloves & Mittens",canonicalCategoryId:subcategoryId("women","accessories","Gants et Mitaines pour femmes")},
  {path:"Women's Clothing > Accessories > Woman Hats & Caps",canonicalCategoryId:subcategoryId("women","accessories","Chapeaux et Casquettes pour femmes")},
  {path:"Women's Clothing > Accessories > Woman Socks",canonicalCategoryId:subcategoryId("women","accessories","Chaussettes pour femmes")},
  {path:"Women's Clothing > Bottoms > Leggings",canonicalCategoryId:subcategoryId("women","pants","Leggings")},
  {path:"Women's Clothing > Bottoms > Pants & Capris",canonicalCategoryId:subcategoryId("women","pants","Pantalons & Capris")},
  {path:"Women's Clothing > Bottoms > Skirts",canonicalCategoryId:subcategoryId("women","pants","Jupes")},
  {path:"Women's Clothing > Bottoms > Wide Leg Pants",canonicalCategoryId:subcategoryId("women","pants","Pantalon large")},
  {path:"Women's Clothing > Bottoms > Woman Jeans",canonicalCategoryId:subcategoryId("women","pants","Jeans pour femmes")},
  {path:"Women's Clothing > Bottoms > Woman Shorts",canonicalCategoryId:subcategoryId("women","pants","Short pour femmes")},
  {path:"Women's Clothing > Couple&Parent-Child Clothing > Couple&Parent -Child Jackets",canonicalCategoryId:subcategoryId("women","family","Couple & Parent-Enfant Vestes")},
  {path:"Women's Clothing > Couple&Parent-Child Clothing > Couple&Parent-Child Pants",canonicalCategoryId:subcategoryId("women","family","Couple & Parent-Enfant Pantalon")},
  {path:"Women's Clothing > Couple&Parent-Child Clothing > Couple&Parent-Child Short-Sleeves",canonicalCategoryId:subcategoryId("women","family","Couple & Parent-Enfant Manches Courtes")},
  {path:"Women's Clothing > Couple&Parent-Child Clothing > Couple&Parent-Child Suits",canonicalCategoryId:subcategoryId("women","family","Couple & Parent-Enfant Costumes")},
  {path:"Women's Clothing > Couple&Parent-Child Clothing > Couple&Parent-Child Sweatshirts·",canonicalCategoryId:subcategoryId("women","family","Couple&Parent-Child Sweatshirts")},
  {path:"Women's Clothing > Couple&Parent-Child Clothing > Couple&Parent-Child Tops",canonicalCategoryId:subcategoryId("women","family","Couple & Parent-Enfant Tops")},
  {path:"Women's Clothing > Outerwear & Jackets > Basic Jacket",canonicalCategoryId:subcategoryId("women","outerwear","Veste basique")},
  {path:"Women's Clothing > Outerwear & Jackets > Blazers",canonicalCategoryId:subcategoryId("women","outerwear","Blazers")},
  {path:"Women's Clothing > Outerwear & Jackets > Leather & Suede",canonicalCategoryId:subcategoryId("women","outerwear","Cuir et Suède")},
  {path:"Women's Clothing > Outerwear & Jackets > Real Fur",canonicalCategoryId:subcategoryId("women","outerwear","Vraie fourrure")},
  {path:"Women's Clothing > Outerwear & Jackets > Woman Trench",canonicalCategoryId:subcategoryId("women","outerwear","Trench pour femmes")},
  {path:"Women's Clothing > Outerwear & Jackets > Women's Padded Jackets",canonicalCategoryId:subcategoryId("women","outerwear","Vestes matelassées pour femmes")},
  {path:"Women's Clothing > Outerwear & Jackets > Wool & Blend",canonicalCategoryId:subcategoryId("women","outerwear","Laine mélangée")},
  {path:"Women's Clothing > Tops & Sets > Blouses & Shirts",canonicalCategoryId:subcategoryId("women","tops","Blouses et Chemises")},
  {path:"Women's Clothing > Tops & Sets > Jumpsuits",canonicalCategoryId:subcategoryId("women","tops","Pantalon une pièce")},
  {path:"Women's Clothing > Tops & Sets > Ladies Short Sleeve",canonicalCategoryId:subcategoryId("women","tops","Ladies Short Sleeve")},
  {path:"Women's Clothing > Tops & Sets > Lady Dresses",canonicalCategoryId:subcategoryId("women","tops","Robes pour femmes")},
  {path:"Women's Clothing > Tops & Sets > Rompers",canonicalCategoryId:subcategoryId("women","tops","Barboteuse")},
  {path:"Women's Clothing > Tops & Sets > Suits & Sets",canonicalCategoryId:subcategoryId("women","tops","Costumes et Ensembles")},
  {path:"Women's Clothing > Tops & Sets > Sweaters",canonicalCategoryId:subcategoryId("women","tops","Chandails")},
  {path:"Women's Clothing > Tops & Sets > Woman Hoodies & Sweatshirts",canonicalCategoryId:subcategoryId("women","tops","Sweats à capuche et sweat-shirts pour femmes")},
  {path:"Women's Clothing > Tops & Sets > Women's Camis",canonicalCategoryId:subcategoryId("women","tops","Camisoles pour femmes")},
  {path:"Women's Clothing > Tops & Sets > Women's Long-Sleeved Shirts",canonicalCategoryId:subcategoryId("women","tops","Chemises à manches longues pour femmes")},
  {path:"Women's Clothing > Tops & Sets > Women's Short-Sleeved Shirts",canonicalCategoryId:subcategoryId("women","tops","Chemises à manches courtes pour femmes")},
  {path:"Women's Clothing > Tops & Sets > Women's Vests",canonicalCategoryId:subcategoryId("women","tops","Gilets pour femmes")},
  {path:"Women's Clothing > Weddings & Events > Bridesmaid Dresses",canonicalCategoryId:subcategoryId("women","weddings","Robes de demoiselle d'honneur")},
  {path:"Women's Clothing > Weddings & Events > Cocktail Dresses",canonicalCategoryId:subcategoryId("women","weddings","Robes de cocktail")},
  {path:"Women's Clothing > Weddings & Events > Evening Dresses",canonicalCategoryId:subcategoryId("women","weddings","Robes de soirée")},
  {path:"Women's Clothing > Weddings & Events > Flower Girl Dresses",canonicalCategoryId:subcategoryId("women","weddings","Robes fleur pour filles")},
  {path:"Women's Clothing > Weddings & Events > Prom Dresses",canonicalCategoryId:subcategoryId("women","weddings","Robes de bal")},
  {path:"Women's Clothing > Weddings & Events > Wedding Dresses",canonicalCategoryId:subcategoryId("women","weddings","Robes de mariée")},
] as const;

const byPath=new Map(CJ_LIVE_PATH_ALIASES.map(row=>[row.path,row.canonicalCategoryId]));
export function resolveCjLivePathAlias(path:string){return byPath.get(path)??null;}
