import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { publicProductAccessWhere } from "@/lib/admin-access";
import { MobileSessionError, readMobileSession } from "@/lib/mobile-session";

const failure=(error:unknown)=>error instanceof MobileSessionError?NextResponse.json({error:error.code},{status:error.status}):NextResponse.json({error:"FAVORITES_UNAVAILABLE"},{status:500});
export async function GET(request:Request){try{const session=await readMobileSession(request),items=await prisma.mobileFavorite.findMany({where:{userId:session.userId,product:{status:"PUBLISHED",...publicProductAccessWhere()}},orderBy:{createdAt:"desc"},select:{productId:true,createdAt:true}});return NextResponse.json({favorites:items.map(item=>({productId:item.productId,createdAt:item.createdAt.toISOString()}))},{headers:{"Cache-Control":"private, no-store"}})}catch(error){return failure(error)}}
export async function POST(request:Request){try{const session=await readMobileSession(request),body=await request.json().catch(()=>null),productId=typeof body?.productId==="string"?body.productId:"";if(!productId)return NextResponse.json({error:"INVALID_INPUT"},{status:400});const product=await prisma.product.findFirst({where:{id:productId,status:"PUBLISHED",...publicProductAccessWhere()},select:{id:true}});if(!product)return NextResponse.json({error:"PRODUCT_NOT_FOUND"},{status:404});await prisma.mobileFavorite.upsert({where:{userId_productId:{userId:session.userId,productId}},create:{userId:session.userId,productId},update:{}});return NextResponse.json({ok:true},{status:201})}catch(error){return failure(error)}}
export async function DELETE(request:Request){try{const session=await readMobileSession(request),body=await request.json().catch(()=>null),productId=typeof body?.productId==="string"?body.productId:"";if(!productId)return NextResponse.json({error:"INVALID_INPUT"},{status:400});await prisma.mobileFavorite.deleteMany({where:{userId:session.userId,productId}});return NextResponse.json({ok:true})}catch(error){return failure(error)}}
