"use client";
import { FormEvent,useState } from "react";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
import { Boxes,FileText,ImagePlus,Shapes,Tag,Trash2 } from "lucide-react";
import { SellerActionBar,SellerFormField,SellerSection } from "@/components/SellerControlPanel";
import ProductImageManager from "@/components/ProductImageManager";
import { MAX_PRODUCT_IMAGES } from "@/lib/product-images";
import { productStockForForm } from "@/lib/product-variant-form";
import VariantImageManager,{type VariantImageAssignment} from "@/components/VariantImageManager";
const categories=[["Mode","fashion"],["Électronique","electronics"],["Maison","home"],["Beauté","beauty"],["Sports","sports"],["Livres","books"],["Enfants","children"],["Auto","auto"],["Artisanat","crafts"],["Autre","other"]] as const;
type ProductData={id:string;name:string;description:string;price:string;compareAtPrice:string|null;stock:number;category:string;condition:string;status:"DRAFT"|"PUBLISHED";colors:string[];sizes:string[];images:string[];currency:string;hasVariants:boolean;options:Array<{id:string;name:string;values:Array<{id:string;value:string}>}>;variantImages:VariantImageAssignment[]};
export default function EditProductForm({product}:{product:ProductData}){
 const router=useRouter(),t=useTranslations("SellerControl"); const [images,setImages]=useState(product.images),[variantImages,setVariantImages]=useState(product.variantImages),[message,setMessage]=useState(""),[submitting,setSubmitting]=useState(false),[uploading,setUploading]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setMessage("");if(uploading)return setMessage(t("waitUpload"));setSubmitting(true);const form=new FormData(event.currentTarget);const response=await fetch(`/api/products/${product.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.get("name"),description:form.get("description"),price:form.get("price"),compareAtPrice:form.get("compareAtPrice"),stock:productStockForForm(product.hasVariants,form.get("stock"),product.stock),category:form.get("category"),condition:form.get("condition"),status:product.status,images,variantImages,colors:product.colors,sizes:product.sizes})});const data=await response.json() as {error?:string};if(!response.ok){setMessage(data.error??t("errorGeneric"));setSubmitting(false);return}router.push("/seller/products");router.refresh()}
 async function removeProduct(){if(!window.confirm(t("deleteConfirm")))return;setSubmitting(true);const response=await fetch(`/api/products/${product.id}`,{method:"DELETE"});if(!response.ok){const data=await response.json() as {error?:string};setMessage(data.error??t("deleteError"));setSubmitting(false);return}router.push("/seller/products");router.refresh()}
 return <form className="sellerControlForm sellerEditProductForm" onSubmit={submit}><div className="sellerControlFormGrid"><div className="sellerControlFormMain">
  <SellerSection icon={FileText} title={t("basicInfo")} description={t("basicInfoHelp")}><SellerFormField label={t("productName")} htmlFor="name" hint={t("productNameHint")} required><input id="name" name="name" defaultValue={product.name} minLength={2} maxLength={120} required/></SellerFormField><SellerFormField label={t("description")} htmlFor="description" hint={t("descriptionHint")} required><textarea id="description" name="description" defaultValue={product.description} rows={7} minLength={10} maxLength={5000} required/></SellerFormField></SellerSection>
  <SellerSection icon={Tag} title={t("pricing")} description={t("pricingHelp")}><div className="sellerControlFieldGrid"><SellerFormField label={t("price",{currency:product.currency})} htmlFor="price" required><input id="price" name="price" type="number" defaultValue={product.price} min=".01" max="1000000" step=".01" required/></SellerFormField><SellerFormField label={t("comparePrice",{currency:product.currency})} htmlFor="compareAtPrice" hint={t("comparePriceHint")}><input id="compareAtPrice" name="compareAtPrice" type="number" defaultValue={product.compareAtPrice??""} min=".01" max="1000000" step=".01"/></SellerFormField></div></SellerSection>
  <SellerSection icon={ImagePlus} title={t("images")} description={t("imagesHelp",{max:MAX_PRODUCT_IMAGES})}><ProductImageManager initialImages={product.images} onChange={setImages} onUploadingChange={setUploading} disabled={submitting}/></SellerSection>
  {product.hasVariants&&<SellerSection icon={ImagePlus} title={t("variantImages")} description={t("variantImagesHelp")}><VariantImageManager images={images} options={product.options} initialAssignments={product.variantImages} onChange={setVariantImages}/></SellerSection>}
  <SellerSection icon={Shapes} title={t("details")} description={t("detailsHelp")}><div className="sellerControlFieldGrid"><SellerFormField label={t("category")} htmlFor="category" required><select id="category" name="category" defaultValue={product.category} required>{categories.map(([value,key])=><option key={value} value={value}>{t(`categories.${key}`)}</option>)}</select></SellerFormField><SellerFormField label={t("condition")} htmlFor="condition"><select id="condition" name="condition" defaultValue={product.condition}><option value="NEUF">{t("conditions.new")}</option><option value="COMME_NEUF">{t("conditions.likeNew")}</option><option value="BON_ETAT">{t("conditions.good")}</option><option value="OCCASION">{t("conditions.used")}</option></select></SellerFormField></div></SellerSection>
 </div><aside className="sellerControlFormAside">{!product.hasVariants&&<SellerSection icon={Boxes} title={t("inventory")} description={t("inventoryHelp")}><SellerFormField label={t("stock")} htmlFor="stock" hint={t("stockHint")} required><input id="stock" name="stock" type="number" defaultValue={product.stock} min="0" max="1000000" required/></SellerFormField></SellerSection>}<SellerSection icon={Trash2} title={t("dangerZone")} description={t("dangerZoneHelp")}><button className="sellerControlButton danger sellerDeleteProduct" type="button" onClick={removeProduct} disabled={submitting||uploading}><Trash2 size={17}/>{t("deleteProduct")}</button></SellerSection></aside></div>
 <SellerActionBar status={message&&<p className="sellerControlFeedback" role="alert">{message}</p>}><a className="sellerControlButton secondary" href="/seller/products">{t("cancel")}</a><button className="sellerControlButton primary" type="submit" disabled={submitting||uploading}>{submitting?t("saving"):t("saveChanges")}</button></SellerActionBar></form>
}
