"use client";
import { FormEvent,type ReactNode,useRef,useState } from "react";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
import { Boxes,FileText,ImagePlus,Shapes,Tag,Trash2,Truck } from "lucide-react";
import { SellerActionBar,SellerFormField,SellerSection } from "@/components/SellerControlPanel";
import ProductImageManager from "@/components/ProductImageManager";
import { MAX_PRODUCT_IMAGES } from "@/lib/product-images";
import { productStockForForm } from "@/lib/product-variant-form";
import VariantImageManager,{type VariantImageAssignment} from "@/components/VariantImageManager";
import SellerCategorySelector from "@/components/SellerCategorySelector";
import ProductComplianceFields,{type ProductComplianceValues} from "@/components/ProductComplianceFields";
import ShippingRuleFields,{shippingDraftPayload,type ShippingDraft} from "@/components/ShippingRuleFields";
import ProductVideoManager from "@/components/ProductVideoManager";
import type { ProductVideoInput } from "@/lib/product-media";
type ProductData={id:string;name:string;description:string;price:string;compareAtPrice:string|null;stock:number;category:string;condition:string;status:"DRAFT"|"PUBLISHED";colors:string[];sizes:string[];images:string[];currency:string;allowPrepurchaseQuestions:boolean;hasVariants:boolean;options:Array<{id:string;name:string;values:Array<{id:string;value:string}>}>;variantImages:VariantImageAssignment[];shippingOverrideEnabled:boolean;shippingEnabled:boolean|null;shippingMethodName:string|null;shippingPrice:string|null;shippingFree:boolean|null;shippingFreeThreshold:string|null;shippingMinDays:number|null;shippingMaxDays:number|null;shippingCountries:string[];shippingWorldwide:boolean|null;shippingPostalCodes:string[];shippingCarrier:string|null;storeShippingSummary:string}&ProductComplianceValues;
export default function EditProductForm({product,variantEditor}:{product:ProductData&{video?:ProductVideoInput|null};variantEditor:ReactNode}){
 const videoRef=useRef<ProductVideoInput|null>(product.video??null);
 const router=useRouter(),t=useTranslations("SellerControl"),ux=useTranslations("Ux"),compliance=useTranslations("Compliance"),shipping=useTranslations("Shipping"); const [images,setImages]=useState(product.images),[variantImages,setVariantImages]=useState(product.variantImages),[message,setMessage]=useState(""),[submitting,setSubmitting]=useState(false),[uploading,setUploading]=useState(false),[shippingOverrideEnabled,setShippingOverrideEnabled]=useState(product.shippingOverrideEnabled),[shippingRule,setShippingRule]=useState<ShippingDraft>({enabled:product.shippingEnabled??true,method:product.shippingMethodName??"",price:product.shippingPrice??"",free:product.shippingFree??false,freeThreshold:product.shippingFreeThreshold??"",minDays:String(product.shippingMinDays??""),maxDays:String(product.shippingMaxDays??""),countries:product.shippingCountries,worldwide:product.shippingWorldwide??false,postalCodes:product.shippingPostalCodes.join("\n"),carrier:product.shippingCarrier??""});
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setMessage("");if(uploading)return setMessage(t("waitUpload"));setSubmitting(true);const form=new FormData(event.currentTarget);const submitter=(event.nativeEvent as SubmitEvent).submitter as HTMLButtonElement|null;const status=submitter?.value==="PUBLISHED"?"PUBLISHED":product.status;const response=await fetch(`/api/products/${product.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.get("name"),description:form.get("description"),price:form.get("price"),compareAtPrice:form.get("compareAtPrice"),stock:productStockForForm(product.hasVariants,form.get("stock"),product.stock),category:form.get("category"),condition:form.get("condition"),status,images,video:videoRef.current,variantImages,colors:product.colors,sizes:product.sizes,allowPrepurchaseQuestions:form.get("allowPrepurchaseQuestions")==="on",productIdentifier:form.get("productIdentifier"),manufacturerName:form.get("manufacturerName"),manufacturerContact:form.get("manufacturerContact"),responsiblePerson:form.get("responsiblePerson"),safetyInformation:form.get("safetyInformation"),complianceInformation:form.get("complianceInformation"),complianceDeclaration:form.get("complianceDeclaration")==="on",shippingOverrideEnabled,...(shippingOverrideEnabled?shippingDraftPayload(shippingRule):{})})});const data=await response.json() as {error?:string};if(!response.ok){setMessage(data.error??t("errorGeneric"));setSubmitting(false);return}router.push("/seller/products");router.refresh()}
 async function removeProduct(){if(!window.confirm(t("deleteConfirm")))return;setSubmitting(true);const response=await fetch(`/api/products/${product.id}`,{method:"DELETE"});if(!response.ok){const data=await response.json() as {error?:string};setMessage(data.error??t("deleteError"));setSubmitting(false);return}router.push("/seller/products");router.refresh()}
 return <form className="sellerControlForm sellerEditProductForm" onSubmit={submit}><div className="sellerControlFormGrid isSingleColumn"><div className="sellerControlFormMain">
  <SellerSection icon={FileText} title={t("basicInfo")} description={t("basicInfoHelp")}><SellerFormField label={t("productName")} htmlFor="name" hint={t("productNameHint")} required><input id="name" name="name" defaultValue={product.name} minLength={2} maxLength={120} required/></SellerFormField><SellerFormField label={t("description")} htmlFor="description" hint={t("descriptionHint")} required><textarea id="description" name="description" defaultValue={product.description} rows={7} minLength={10} maxLength={5000} required/></SellerFormField></SellerSection>
  <SellerSection icon={Tag} title={t("pricing")} description={t("pricingHelp")}><div className="sellerControlFieldGrid"><SellerFormField label={t("price",{currency:product.currency})} htmlFor="price" required><input id="price" name="price" type="number" defaultValue={product.price} min=".01" max="1000000" step=".01" required/></SellerFormField><SellerFormField label={t("comparePrice",{currency:product.currency})} htmlFor="compareAtPrice" hint={t("comparePriceHint")}><input id="compareAtPrice" name="compareAtPrice" type="number" defaultValue={product.compareAtPrice??""} min=".01" max="1000000" step=".01"/></SellerFormField></div></SellerSection>
  <SellerSection icon={ImagePlus} title={t("images")} description={t("imagesHelp",{max:MAX_PRODUCT_IMAGES})}><ProductImageManager initialImages={product.images} onChange={setImages} onUploadingChange={setUploading} disabled={submitting}/><ProductVideoManager productId={product.id} initialVideo={product.video??null} onChange={(value)=>{videoRef.current=value}} onUploadingChange={setUploading}/></SellerSection>
  {variantEditor}
  {product.hasVariants&&<SellerSection icon={ImagePlus} title={t("variantImages")} description={t("variantImagesHelp")}><VariantImageManager images={images} options={product.options} initialAssignments={product.variantImages} onChange={setVariantImages}/></SellerSection>}
  <SellerSection icon={Shapes} title={t("details")} description={t("detailsHelp")}><div className="sellerControlFieldGrid"><SellerFormField label={t("category")} htmlFor="category" required><SellerCategorySelector initialValue={product.category} labels={{main:t("mainCategory"),group:t("categoryGroup"),leaf:t("leafCategory"),chooseMain:t("chooseMainCategory"),chooseGroup:t("chooseCategoryGroup"),chooseLeaf:t("chooseLeafCategory"),legacyInvalid:t("legacyCategoryInvalid")}}/></SellerFormField><SellerFormField label={t("condition")} htmlFor="condition"><select id="condition" name="condition" defaultValue={product.condition}><option value="NEUF">{t("conditions.new")}</option><option value="COMME_NEUF">{t("conditions.likeNew")}</option><option value="BON_ETAT">{t("conditions.good")}</option><option value="OCCASION">{t("conditions.used")}</option></select></SellerFormField></div><label className="sellerQuestionPreference"><input name="allowPrepurchaseQuestions" type="checkbox" defaultChecked={product.allowPrepurchaseQuestions}/><span><strong>{ux("questionLabel")}</strong><small>{ux("questionHelp")}</small></span></label></SellerSection>
  <SellerSection icon={Shapes} title={compliance("productComplianceTitle")} description={compliance("productComplianceHelp")}><ProductComplianceFields initial={product}/></SellerSection>
  <SellerSection icon={Truck} title={shipping("productSettingsTitle")} description={shipping("productSettingsHelp")}><label className="shippingToggle"><input type="checkbox" checked={shippingOverrideEnabled} onChange={e=>setShippingOverrideEnabled(e.target.checked)}/><span><strong>{shippingOverrideEnabled?shipping("customProductShipping"):shipping("inheritStoreShipping")}</strong><small>{product.storeShippingSummary||shipping("storeShippingUnconfigured")}</small></span></label>{shippingOverrideEnabled&&<ShippingRuleFields value={shippingRule} onChange={setShippingRule} currency={product.currency}/>}</SellerSection>
  {!product.hasVariants&&<SellerSection icon={Boxes} title={t("inventory")} description={t("inventoryHelp")}><SellerFormField label={t("stock")} htmlFor="stock" hint={t("stockHint")} required><input id="stock" name="stock" type="number" defaultValue={product.stock} min="0" max="1000000" required/></SellerFormField></SellerSection>}
  <SellerSection icon={Trash2} title={t("dangerZone")} description={t("dangerZoneHelp")}><button className="sellerControlButton danger sellerDeleteProduct" type="button" onClick={removeProduct} disabled={submitting||uploading}><Trash2 size={17}/>{t("deleteProduct")}</button></SellerSection>
 </div></div>
 <SellerActionBar status={message&&<p className="sellerControlFeedback" role="alert">{message}</p>}><a className="sellerControlButton secondary" href="/seller/products">{t("cancel")}</a><button className="sellerControlButton primary" type="submit" disabled={submitting||uploading}>{submitting?t("saving"):t("saveChanges")}</button>{product.status==="DRAFT"&&<button className="sellerControlButton primary" type="submit" name="intent" value="PUBLISHED" disabled={submitting||uploading}>{submitting?t("saving"):t("publishNow")}</button>}</SellerActionBar></form>
}
